### ISSUE TITLE
Visualize the PDF document border

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#100]
When setting a slice using the mouse (`s m`) it would be useful to be able to actually see the PDF document's borders.  Right now, you can't distinguish the margins of a document from free space in the emacs window which makes it hard to set a slice properly (always assuming both PDF and Emacs are black-on-white).

**Comment by politza** [comment]
This command should be changed to act on the region, whose selection
I've improved a couple commits ago, i.e. try M-drag-mouse-1 .

**Comment by tsdh** [comment]
`M-drag-mouse-1` is nice but I don't see how I can use it with `s m`.  There, `M-drag-mouse-1` has neither its visual effect nor does it work for setting the slice.

Apart from that, the nice region marking doesn't help in my original scenario.  Consider you have a page displayed which is a chapter beginning.  The text doesn't start at the top of the page but somewhere in the first third of the page.  In order to set a proper slice which will also fit the next full page, it would be good to see the page borders.

Well, actually this issue is already solved by auto-slicing (your answer in #101).

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> M-drag-mouse-1 is nice but I don't see how I can use it with s m.
> There, M-drag-mouse-1 has neither its visual effect nor does it work
> for setting the slice.

> Apart from that, the nice region marking doesn't help in my original
> scenario. 

That's why I said ''This command should be changed...', but yes it
won't help in this scenario.  Having a slightly different frame
background would be the normal solution to this, I guess.

**Comment by tsdh** [comment]
Yes, temporarily changing the frame background color would work although that would affect other windows, too, and you have to ensure that you revert it also in the case of an error.

What also works is using the `:relief` image descriptor.  I've just tested, and that looks nice and is what "normal" pdf viewers also do.  The relief also disappears when a slice is set, so that seems like a good thing to do.

```diff
diff -u --label /home/horn/.emacs.d/elpa/pdf-tools-20150613.414/pdf-view.el --label \#\<buffer\ pdf-view.el\> /home/horn/.emacs.d/elpa/pdf-tools-20150613.414/pdf-view.el /tmp/buffer-content-11626jHE
--- /home/horn/.emacs.d/elpa/pdf-tools-20150613.414/pdf-view.el
+++ #<buffer pdf-view.el>
@@ -752,7 +752,8 @@
     (pdf-view-create-image data 
       :width (car size)
       :map hotspots
-      :pointer 'arrow)))
+      :pointer 'arrow
+      :relief 3)))
 
 (defun pdf-view-image-size (&optional displayed-p window)
   "Return the size in pixel of the current image.

Diff finished.  Wed Jun 17 09:19:34 2015
```

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> What also works is using the :relief image descriptor.

Sounds good.

**Comment by politza** [comment]
The slightly annoying thing is, that the relief is not accounted for in the `image-size` function.

**Comment by politza** [comment]
Seems, I was mistaken about `image-size`.  Though, it's never that easy: When rapidly displaying different images (isearch, region) the drawing of the relief creates an effect which is called `tearing', I believe.
