### ISSUE TITLE
Improve setting slice by bounding box

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#101]
When reading documents, the first thing I usually do is setting the slice by the bounding box in order to get rid of margins.  However, that doesn't work for documents which are meant to be printed as books and thus the margins of left pages are different (inverse) to the margins of right pages.  The result of slicing using the bounding box of a left page is that there's a margin on the one side of right pages and text cut off at the other side of right pages.

So it would be awesome if I could still slice per bounding box.  I can think of at least two possibilities.

1. Get the bounding boxes of two or more consecutive pages and combine them to a larger slice which is able to fit either one.
2. Have some "slice-to-bounding-box" minor mode which automatically slices to the BB as soon as a page is displayed.

Option 1 could still get something wrong in case the considered pages aren't "typical", e.g., just contain a figure with lots of margins around.

**Comment by tsdh** [comment]
FWIW, I've just tried option 2 using an advice, and it works very well.

```elisp
(advice-add #'pdf-view-display-page :after
	    (lambda (&rest _ignore)
	      (pdf-view-set-slice-from-bounding-box)))
```

**Comment by politza** [comment]
pdf-view-auto-slice-minor-mode ?

**Comment by tsdh** [comment]
Oh, yes, that's it.
