### ISSUE TITLE
pdf-view-midnight-minor-mode breaks when saving or reverting the buffer

### ISSUE THREAD

**Issue by duud** [politza/pdf-tools#102]
Using pdf-tools with pdf-view-midnight-minor-mode works great for reading, but as I'm starting to mark and/or add markup annotation the page is rendered 'bright' again. I have to disable and then enable pdf-view-midnight-minor-mode again in order to get a dark rendering again.

**Comment by politza** [comment]
This shouldn't happen in the latest version.

**Comment by politza** [comment]
By `version' I meant revision.

**Comment by duud** [comment]
I've upgraded to the last revision on melpa, it seems to be in sync with the version on github, but it still has the same issue.

**Comment by politza** [comment]
Please try with `emacs -Q`.

**Comment by duud** [comment]
You're right, it's my configuration. The problem doesn't occur with -q.
It's not related to pdf-tools, but do you have some hints how to debug this?

**Comment by oscarfv** [comment]
@duud This is usually (and quickly) done by bisectting your `.emacs` file:

http://stackoverflow.com/questions/23772890/how-to-find-a-bug-in-emacs-or-init-el

**Comment by politza** [comment]
duud <notifications@github.com> writes:

> It's not related to pdf-tools, [...]

It still might.  Did you customize pdf-tools in some way ?

**Comment by duud** [comment]
No, I didn't

**Comment by duud** [comment]
OK, it seems to happen after saving 'C-x C-s' the file.
Try this sequence:
enable midnight-mode
highlight
save

**Comment by politza** [comment]
Yes, that doesn't work right at the moment.

**Comment by duud** [comment]
Btw. I'm using prelude and it does auto-saving.
This is why it happens right after highlighting for me.

**Comment by politza** [comment]
Should work now.
