### ISSUE TITLE
Declare dependency on tablist in Cask

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#103]
The MELPA version of pdf-tools depend on tablist (in pdf-occur.el) so that should be defined as a dependency in Cask.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> The MELPA version of pdf-tools depend on tablist (in pdf-occur.el) so
> that should be defined as a dependency in Cask.

When is this a problem ?

tablist belongs to the same repository and I'm not sure if and how cask
is able to deal with two packages in the same directory.

**Comment by politza** [comment]
Forget what I said, I just added tablist as dependency.

**Comment by tsdh** [comment]
Just to be clear (to other interested readers), the repo contains tablist.el but the pdf-tools MELPA package does not (which is correct).  Thus it must declare tablist as a dependency.
