### ISSUE TITLE
Marking a region in lower half of scrolled page scrolls up instead of marking

### ISSUE THREAD

**Issue by andersjohansson** [politza/pdf-tools#105]
Hi,
When trying to mark a region with the mouse in the lower half of a page that has been scrolled down the page is scrolled up and another region is marked (to mouse position after scrolling)

Something since 0.60 seem to introduce this behaviour. Reverting to 0.60 (melpa-stable) I don't encounter the problem. I think it's more recent though since I experienced it first in some update a few days ago. I think it might have been introduced between the 20150603 and 20150613 melpa-builds which are the two I had installed in the last few weeks.
It doesn't seem to be a configuration issue at least, I tried with `emacs -q` and saw the problem then too. I could try to bisect this if needed, but probably not today.

Thanks for a brilliant package otherwise!

**Comment by politza** [comment]
Fixed. Thanks.
