### ISSUE TITLE
Isearch only searches one page

### ISSUE THREAD

**Issue by marion06** [politza/pdf-tools#106]
Hello !

Pdf-tools seems really great, and i would love to use only emacs as my pdf viewer. However,  i have a small problem :

When i I-search, only the current page i am viewing is searched. For instance, if i search for "the", and i press C-s to go trough all results, i can go trough all of them, but only on the current page. When the last result on the current page is marked, and i C-s again, i see [(void-function alist-get)] and red-highlighted text in I-search bar, as if there are no more results. 

'M-s o' (isearch-occur) works just fine, it displays all the lines of pdf containing "the". But can i just search entire document by hitting repeatedly 'C-s', as i could in any text file in emacs ?

Thanks in advance !

**Comment by politza** [comment]
marion06 <notifications@github.com> writes:

> [...] i see [(void-function alist-get)] [...]

Yep, that function was introduced in Emacs 25.1 . I'll fix it later.

**Comment by kaushalmodi** [comment]
I came here to report an issue with `C-s` in emacs 25+. For me `C-s` does not return any results at all, but `M-s o` works just fine.

**Comment by politza** [comment]
This is an unrelated issue.

Try to uninstall, restart Emacs and reinstall pdf-tools; otherwise `emacs -Q`.

**Comment by kaushalmodi** [comment]
@politza OK, I've opened a separate issue for that (https://github.com/politza/pdf-tools/issues/110). I'll verify if this issue repeats on `emacs -Q` when I get back to my computer next week. Thanks!
