### ISSUE TITLE
Opening eshell while reading a PDF crashes Emacs

### ISSUE THREAD

**Issue by manuel-uberti** [politza/pdf-tools#107]
I am using latest ```pdf-tools``` from MELPA.
Whenever I issue ```M-x eshell``` while reading a PDF with ```pdf-tools```, Emacs crashes.
It's hard for me to debug this crash, but if there is something I could do to help fixing the issue please ask.

**Comment by politza** [comment]
If Emacs crashes, it's a bug in Emacs, not pdf-tools.

`M-x report-emacs-bug ret`

**Comment by manuel-uberti** [comment]
Ok, thanks for the tip. I'll report the bug.

**Comment by phikal** [comment]
@manuel-uberti Did you manage to find out anything? Could you solve the issue?

**Comment by manuel-uberti** [comment]
Completely forgot about it. Don't even use EShell that much these days, sorry.

**Comment by politza** [comment]
I'm able to reproduce this with Emacs 26.1, but it seems to be fixed in
the master branch.

**Comment by phikal** [comment]
That's wierd, because I just built Emacs 26.1 from source (I have this issue when using Emacs 25.1) and I couldn't reproduce it...

**Comment by oantolin** [comment]
I'm seeing this bug on Emacs 26.1 with pdf-tools 20190129.1822, but only if I load eshell for the first time from a pdf-view-mode buffer. If I have the eshell library already loaded, running `M-x eshell` from a pdf-view-mode buffer does *not* crash. So there is a very simple workaround: if the very first time you want to run eshell you are reading a PDF, first switch to another non-pdf buffer and run eshell from there. After that, run eshell from wherever you want.
