### ISSUE TITLE
C-s search does not work in emacs 25+

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#110]
In emacs 25+, `C-s` does not return any result at all, but `M-s o` works just fine.

But `C-s` search works fine with the latest version of `pdf-tools` and emacs 24.5 using the exact same emacs config.

**Comment by kaushalmodi** [comment]
@politza Are you unable to recreate this problem on the latest build from master branch of emacs git?

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> @politza Are you unable to recreate this problem on the latest build
> from master branch of emacs git?

Does setting character-fold-search to nil fix this for you ?

**Comment by kaushalmodi** [comment]
It does! I doubted that could be a problem but didn't try it thinking that as it is folding all character variants, it should not matter.

**Comment by kaushalmodi** [comment]
I am making it work this way for now:

```el
    ;; The default value `t' of `character-fold-search' in emacs 25+ breaks
    ;; the isearch in `pdf-isearch-minor-mode'; fix it
    (defun modi/pdf-isearch-no-char-fold (orig-fun &rest args)
      (let* ((character-fold-search-orig character-fold-search)
             (character-fold-search character-fold-search-orig))
        (when pdf-isearch-minor-mode
          (setq character-fold-search nil))
        (apply orig-fun args)))
    (advice-add 'isearch-mode :around #'modi/pdf-isearch-no-char-fold)
```

**Comment by politza** [comment]
https://github.com/politza/pdf-tools/commit/f0bf677438985de9de23a7df0ea9539e92c407a3

**Comment by kaushalmodi** [comment]
Thanks! That fixes this problem.
