### ISSUE TITLE
Redisplaying first page  after opening helm window

### ISSUE THREAD

**Issue by Enrico68** [politza/pdf-tools#111]
I dont know if it's correlated to helm or pdf-tools. Whenever I open an helm window pdf-tools redisplays the first page of the file. I put a screen of what is happening.  http://i.imgur.com/CThwo7v.gif

**Comment by politza** [comment]
Enrico Pirani <notifications@github.com> writes:

> I dont know if it's correlated to helm or pdf-tools.

My guess is that helm reverts the buffer for some reason.

**Comment by Enrico68** [comment]
I saw now even with guide-key .... 

Inviato da iPad

> Il giorno 04/lug/2015, alle ore 23:24, politza <notifications@github.com> ha scritto:
>

**Comment by rekado** [comment]
I see this too, but I'm not using Helm.  I've been trying to figure out what may cause this, but so far it looks as if it happens even if I do nothing at all and just wait.  Each time this happened the buffer was buried and I had just switched to the PDF buffer.

**Comment by Enrico68** [comment]
Confirm it is not correlated using Helm, but it  happens whenever the buffer is buried (even partially, e.g. by spell-check). It is little bit annoying as I am translating a pdf-book..

**Comment by politza** [comment]
Enrico Pirani <notifications@github.com> writes:

> Confirm it is not correlated using Helm, but it happens whenever the
> buffer is buried (even partially, e.g. by spell-check) [...]

What does burying a partially mean ?

Anyway, I can't confirm this, i.e.

M-x bury-buffer RET
C-x b pdf-buffer RET

does not change the displayed page.

It may be depending on the Emacs version.

**Comment by rekado** [comment]
I would like to add that (in my case) burying the buffer is not what triggers the issue.  It is just that I haven't ever seen this happen while the buffer was being displayed.

I can switch back and forth between the PDF buffer and something else and nothing bad will happen.  But whenever it happened the PDF buffer had been buried before.  (I realise that this may not be the most helpful indicator as many things might have happened while the buffer was buried.)

**Comment by politza** [comment]
rekado <notifications@github.com> writes:

> I would like to add that (in my case) burying the buffer is not what
> triggers the issue. It is just that I haven't ever seen this happen
> while the buffer was being displayed.

Misunderstanding: What you call `buried buffer' is simply an undisplayed
buffer.  Burying a buffer means to undsiplay it and put it at the end of
the buffer-list (via bury-buffer).

Emacs version ?

**Comment by cmccloud** [comment]
This issue comes up for me both with pdf-tools and doc-view-mode - in my case, the root cause is popwin which deletes all windows but the current window as part of the popup creation process. The code in question, for anyone who is interested, is here:

```
(defun* popwin:create-popup-window (&optional (size 15) (position 'bottom) (adjust t))
  "Create a popup window with SIZE on the frame.  If SIZE
is integer, the size of the popup window will be SIZE. If SIZE is
float, the size of popup window will be a multiplier of SIZE and
frame-size. can be an integer and a float. If ADJUST is t, all of
windows will be adjusted to fit the frame. POSITION must be one
of (left top right bottom). The return value is a pair of a
master window and the popup window. To close the popup window
properly, get `current-window-configuration' before calling this
function, and call `set-window-configuration' with the
window-configuration."
  (let* ((root (car (popwin:window-config-tree)))
         (root-win (popwin:last-selected-window))
         (hfactor 1)
         (vfactor 1))
    (popwin:save-selected-window
     (delete-other-windows root-win)) ;; => The pdf is closed here, if it isn't the selected window
    (let ((root-width (window-width root-win))
          (root-height (window-height root-win)))
      (when adjust
        (if (floatp size)
            (if (popwin:position-horizontal-p position)
                (setq hfactor (- 1.0 size)
                      size (round (* root-width size)))
              (setq vfactor (- 1.0 size)
                    size (round (* root-height size))))
          (if (popwin:position-horizontal-p position)
              (setq hfactor (/ (float (- root-width size)) root-width))
            (setq vfactor (/ (float (- root-height size)) root-height)))))
      (destructuring-bind (master-win popup-win)
          (popwin:create-popup-window-1 root-win size position)
        ;; Mark popup-win being a popup window.
        (with-selected-window popup-win
          (popwin:switch-to-buffer (popwin:dummy-buffer) t))
        (let ((win-map (popwin:replicate-window-config master-win root hfactor vfactor)))
;; => popwins restoration process doesn't correctly handle the current page of a pdf
          (list master-win popup-win win-map))))))
```

I wrote a quick fix which works for me - I was in the process of doing a little more digging into whether it was possible to integrate a fix into doc-view-mode directly, but I have a couple of other projects which are a higher priority at the moment. 

I'm still learning the emacs API, so for anyone with a bit more experience, I would appreciate any tips or suggestions they might have on the code below - I would really like to be able to get it to work without the call to with-selected-window.

Fix code:
```
(defun mcc-pdf-view-save ()
  (cl-loop for win in (window-list)
           do (with-selected-window win
                (when (eql major-mode 'pdf-view-mode)
                  (setq-local pdf-view-last-visited-page
                              (pdf-view-current-page))))))

(defun mcc-pdf-view-restore ()
  (cl-loop for win in (window-list)
           do (with-selected-window win
                (when (eql major-mode 'pdf-view-mode)
                  (pdf-view-goto-page pdf-view-last-visited-page)))))

  (add-hook 'popwin:before-popup-hook #'mcc-pdf-view-save)
  (add-hook 'popwin:after-popup-hook #'mcc-pdf-view-restore)
```

**Comment by cmccloud** [comment]
@Enrico68 and guide-key delegates to popwin if i'm not mistaken - the fix handles guide-key on my system.

**Comment by rekado** [comment]
> Emacs version ?

24.5.1

And yes, you are right.  I was mistaken about the meaning of "buried buffer".

**Comment by politza** [comment]
Christopher McCloud <notifications@github.com> writes:

> This issue comes up for me both with pdf-tools and doc-view-mode - in
> my case, the root cause is popwin which deletes all windows but the
> current window as part of the popup creation process. The code in
> question, for anyone who is interested, is here:

Both packages use image-mode to attach various properties with different
windows (i.e. the page number).  Of course this won't work if the window
is deleted and replaced with a new window.  In this case image-mode does
not recognize the window and falls back to default values for
undisplayed buffers (i.e. page 1).

Additionally both packages use the `window' overlay property, which
determines the image displayed.  These also would have to be restored
for every window.

I suppose that popwin is an older package, when it was not possible to
split the frame's root-window to create a side-window.  Not deleting all
windows on the frame is probably the easiest way out of this.

**Comment by cmccloud** [comment]
@politza thanks for the explanation - much appreciated.

**Comment by Enrico68** [comment]
@cmccloud  Thanks for your fix. Now the problem with `guide-key` is fixed.  
@politza sorry for not correctly describe the problem. 
The main issue for me still remain with helm.

**Comment by cmccloud** [comment]
@Enrico68 helm-default-display-buffer will also run delete-other-windows if certain conditions are met - you might try setting helm-split-window-in-side to t if you haven't already. 

```
(defun helm-default-display-buffer (buffer)
  "Default function to display `helm-buffer' BUFFER.
It uses `switch-to-buffer' or `pop-to-buffer' depending of value of
`helm-full-frame' and/or `helm-split-window-default-side'."
  (if (or (buffer-local-value 'helm-full-frame (get-buffer buffer))
          (and (eq helm-split-window-default-side 'same)
               (one-window-p t)))
      (progn (delete-other-windows) (switch-to-buffer buffer))
    (when (and (or helm-always-two-windows helm-autoresize-mode
                   (and (not helm-split-window-in-side-p)
                        (eq (save-selected-window
                              (funcall helm-split-window-preferred-function
                                       (selected-window)))
                            (get-buffer-window helm-current-buffer))))
               (not (eq helm-split-window-default-side 'same))
               (not (minibufferp helm-current-buffer))
               (not helm-split-window-in-side-p))
      (delete-other-windows))
    (pop-to-buffer buffer)))
```

**Comment by Enrico68** [comment]
@cmccloud thanks for your suggestion but  problem still remains.

**Comment by politza** [comment]
Upgrading Emacs would also help somewhat, I think.  Various improvements were made to image-mode last year.

**Comment by rekado** [comment]
In my case this is triggered by magit-status (magit version: 20150608.1139).

**Comment by politza** [comment]
Does this problem persist ?

**Comment by Enrico68** [comment]
Now it seems ok for me. Helm does not interferes the redisplaying of buffer.

**Comment by Andre0991** [comment]
@politza, I'm getting this problem here.

I'm using Spacemacs, which uses `popwin`, but it could also be caused by `persp.el` or another thing.

It gets back to the first page when the same window is used to display another buffer, provided that this other buffer is located in another `perspective` and the active window after switching the perspective is the one that was being used by `pdf-tools`.

The snippet of code suggested by cmccloud didn't work for me, unfortunately.

Can this property of `image-mode` be considered a bug? 

I wonder if it's possible to change its implementation in regard to setting the property to the window.

**Comment by braham-snyder** [comment]
is it correct that #18 is blocked by this issue? if so, could it be reopened?

**Comment by politza** [comment]
No. The other issue has nothing to do with this.  This issue is about
retstoring windows using window-state-put, which has some inherent
problems regarding window identity.

I probablly closed it because there is at least one other realting to
the same problem, namely #232.
