### ISSUE TITLE
PDF view mode, the image auto enlarge when I use mouse (left button) to select text with region.

### ISSUE THREAD

**Issue by stardiviner** [politza/pdf-tools#112]
Here is a video screencast to show how it looks like.

https://www.dropbox.com/s/nr23n3wnafd3rwz/out.ogv?dl=0

**Comment by politza** [comment]
What's the value of pdf-view-image-relief ?

**Comment by stardiviner** [comment]
It's `5`. I saw it's description, not as what I image.

**Comment by stardiviner** [comment]
@politza setting it to original `0` solved issue.
