### ISSUE TITLE
Provide seperate customization options for different annotation types

### ISSUE THREAD

**Issue by mandarm** [politza/pdf-tools#113]
For me, it makes sense to distinguish between text and markup annotations for the customisable variable pdf-annot-activate-created-annotations, i.e., I want text annotations to be opened by default so that I can write a note right away, while I do not want markup annotations to be activated.

I have accordingly modified my local pdf-annot.el file as follows. Just a suggestion, in case it's useful.

--- pdf-annot-mm.el     2015-07-05 19:52:47.767491503 +0530
+++ pdf-annot.el        2015-07-03 13:38:43.023931149 +0530
@@ -995,8 +995,7 @@
     (setq a (pdf-annot-create a))
     (set-buffer-modified-p t)
     (pdf-annot-run-modified-hooks :insert a)
-    (when (or pdf-annot-activate-created-annotations
-              (eq type 'text))
-    (when pdf-annot-activate-created-annotations
     (pdf-annot-activate-annotation a))
   a))

**Comment by mandarm** [comment]
Sorry, the patch got messed up.

```
--- pdf-annot-mm.el     2015-07-05 19:52:47.767491503 +0530
+++ pdf-annot.el        2015-07-03 13:38:43.023931149 +0530
@@ -995,8 +995,7 @@
     (setq a (pdf-annot-create a))
     (set-buffer-modified-p t)
     (pdf-annot-run-modified-hooks :insert a)
-    (when (or pdf-annot-activate-created-annotations
-              (eq type 'text))
+    (when pdf-annot-activate-created-annotations
       (pdf-annot-activate-annotation a))
     a))
 ```

**Comment by politza** [comment]
The variable could alternatively be a alist mapping types to a boolean.

**Comment by Xunius** [comment]
> Sorry, the patch got messed up.
> 
> ```
> --- pdf-annot-mm.el     2015-07-05 19:52:47.767491503 +0530
> +++ pdf-annot.el        2015-07-03 13:38:43.023931149 +0530
> @@ -995,8 +995,7 @@
>      (setq a (pdf-annot-create a))
>      (set-buffer-modified-p t)
>      (pdf-annot-run-modified-hooks :insert a)
> -    (when (or pdf-annot-activate-created-annotations
> -              (eq type 'text))
> +    (when pdf-annot-activate-created-annotations
>        (pdf-annot-activate-annotation a))
>      a))
> ```

I was about to suggest the same.
I also found your fix a bit confusing. Shouldn't it be

```
     (setq a (pdf-annot-create a))
     (set-buffer-modified-p t)
     (pdf-annot-run-modified-hooks :insert a)
-    (when (and pdf-annot-activate-created-annotations
-              (eq type 'text))
+    (when pdf-annot-activate-created-annotations
       (pdf-annot-activate-annotation a))
     a))
```
i.e. `and` instead of `or`?
