### ISSUE TITLE
Highlight (not the annotation highlight) text across the whole pdf (like `hi-lock`) [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#114]
It would be very useful to be able to highlight a user specified text across the whole pdf. It would be something along the lines of `highlight-symbol`.

pdf isearch and occur help but having an ability to put persistent highlights for a session would be nice to have.

_I am not talking about the highlight annotations that get saved to the pdf._

**Comment by politza** [comment]
Yes, that sounds nice.  Would require some sense of state when rendering a page.
