### ISSUE TITLE
pdf-tools occur API

### ISSUE THREAD

**Issue by cmccloud** [politza/pdf-tools#115]
I wanted to write a helm extension to replace pdf-occur - looking briefly at the pdf-occur library, it looks like the main entry point is pdf-info-local-batch-query, is that right? 

If I understand correctly - it is the function bound to pdf-info-asynchronous that receives the result of the server side operation?

If you have any suggestions or tips on how to go about querying the server I would really appreciate it.

**Comment by cmccloud** [comment]
Answered my own question - thanks.

**Comment by politza** [comment]
Christopher McCloud <notifications@github.com> writes:

> I wanted to write a helm extension to replace pdf-occur - looking
> briefly at the pdf-occur library, it looks like the main entry point
> is pdf-info-local-batch-query, is that right? 

This function solves the problem of chaining a bunch of asynchronous
calls, in this case calls to pdf-info-search-string on different
documents/pages.

> If I understand correctly - it is the function bound to
> pdf-info-asynchronous that receives the result of the server side
> operation?

Yes, look at it's documentation.  Ordinarily all functions in the `High
Level' section of pdf-info are synchronous, unless this variable is
bound.

> If you have any suggestions or tips on how to go about querying the
> server I would really appreciate it.

First you maybe want to create a dedicated server instance for the
search task.  This will avoid blocking ordinary viewing of PDFs.

(pdf-info-make-local-server nil t)

This starts a new process, which is bound to the current buffer.  That
means all queries invoked in this buffer are answered by this new
instance.

Next you probably want to split the search across various queries, even
if there is only one document.  This makes results appear more quickly.

A simple asynchronous search would look like

(let ((pdf-info-asynchronous
       (lambda (status result)
         (unless status
           (do-something result)))))
  (pdf-info-search-regexp "(foo|bar)"))

This would search all pages of the current buffer and then do
something.

Maybe you can adapt pdf-occur-start-search.
