### ISSUE TITLE
Weird copying / conflict with CUA-mode

### ISSUE THREAD

**Issue by pseudomyne** [politza/pdf-tools#117]
Hi, 
i use CUA-mode, which seems to conflict with pdf-tools. Indeed, striking M-w has no effect after some pdf text selection and attempt to copy it in some org document (with C-v or either with C-y). Weird thing is copying still works when clicking 'Copy Region' in the right-click mouse menu. 

Been trying to "hook out" CUA-mode in pdf-view-mode with no effect with 
(add-hook 'pdf-view-mode-hook (lambda () (cua-mode 0)))

**Comment by pseudomyne** [comment]
May it come from my copying setup ? 
(setq x-select-enable-clipboard t
      mouse-yank-at-point t
      x-select-enable-primary t
      select-active-regions 'only
     ; save-interprogram-paste-before-kill t )

**Comment by politza** [comment]
`cua-mode` remaps `M-w`, when the region is active, which it is, if you select something with the mouse.  This inhibits pdf-tools from doing it's thing, i.e. retrieving the text from the server.

    (add-hook 'pdf-view-mode-hook (lambda () (cua-mode 0)))

works for me, though `cua-mode` is a global minor mode.  You could also try the following.

    (add-hook 'pdf-view-mode-hook (lambda () (setq-local cua-mode nil)))

I doubt this'll get fixed anytime soon.

**Comment by ericdanan** [comment]
I'm not sure if that would suit you, but instead of turning off CUA mode, you could advise `cua-copy-region` so that `C-c` also works in `pdf-view-mode`. The following works for me:

```
(defun cua-copy-region--pdf-view-advice (&rest r)
  "If current buffer is in `pdf-view' mode, call `pdf-view-kill-ring-save'.
  (when (eq major-mode 'pdf-view-mode)
    (pdf-view-kill-ring-save)))

(advice-add 'cua-copy-region                    
            :before-until                       
            #'cua-copy-region--pdf-view-advice)
```
