### ISSUE TITLE
Slice needs to be recomputed when the pdf buffer is refreshed

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#118]
I use `pdf-view-auto-slice-minor-mode` in combination with

``` elisp
(defun th/pdf-view-revert-buffer-maybe (file)
  (when-let ((buf (find-buffer-visiting file)))
    (with-current-buffer buf
      (when (derived-mode-p 'pdf-view-mode)
        (pdf-view-revert-buffer nil t)))))

(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
          #'th/pdf-view-revert-buffer-maybe)
```

which basically works very well.  I can write my latex documents with AUCTeX and the PDF view buffer is reverted after recompiling my document.

However, `pdf-view-revert-buffer` doesn't adapt the current slice.  For example, when the current page is only one short paragraph long right now, the slice is set very small to fit exactly the contents.  Now I write another paragraph in my tex document and recompile which triggers `pdf-view-revert-buffer`.  The page is redisplayed but the slice stays as it is meaning that I can't see my newly written paragraph.

As a workaround, I simply switch to the next or previous page and then back again which triggers re-slicing.

Obviously, that happens only if there's nothing at the bottom of a page already, e.g., a line number.

**Comment by vyp** [comment]
I have been wondering about this as well. +1 if possible.

**Comment by manuel-uberti** [comment]
Yes, this would be nice.

**Comment by grauschnabel** [comment]
I would recommend a solution for that too.
