### ISSUE TITLE
Only a few annotations are shown

### ISSUE THREAD

**Issue by Paethon** [politza/pdf-tools#119]
Hi

For some reason only a small amount of annotations are shown. For example:
https://dl.dropboxusercontent.com/u/97142252/howtoreadapaper.pdf

PDFTools only shows the first two annotations.

**Comment by politza** [comment]
I see 3 `highlight` annotations on the first page.  How many should there be ?

**Comment by Paethon** [comment]
Yes that is very weird. It now also shows all three for me. When I posted that issue I am pretty sure it only showed two of the annotations. Maybe something changed in the code since then?
