### ISSUE TITLE
Unsupported annotation type

### ISSUE THREAD

**Issue by billbrod** [politza/pdf-tools#120]
I'm unable to highlight anything in a pdf document. When I select some text with my mouse and then use the command pdf-annot-add-highlight-markup-annotation, I simply receive the error message: `pdf-annot-add-annotation: Unsupported annotation type: highlight`.

I get the same results when I try the other markup annotations (squiggly, strikeout, and underline). 

Was there an option or variable I needed to set somewhere? I am able to markup the pdfs in another pdf viewer (both Mendeley and Okular) and then view the resulting annotations in pdf tools.

This is a great package. Once I've got this figured out, I'm going to start moving over all my papers from Mendeley -- thanks!

**Comment by billbrod** [comment]
Doing some research, it looks like the problem is that my `pdf-info-features` variable is defined as `(case-sensitive-search writable-annotations no-markup-annotations)`, so it excludes `markup-annotations`. However, I have pdf-info version 0.70 (installed via el-get), which should be able to create and modify markup annotations...

**Comment by politza** [comment]
Just read the README.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: "William F. Broderick" <notifications@github.com> </div><div>Datum:17.08.2015  22:28  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Betreff: Re: [pdf-tools] Unsupported annotation type (#120) </div><div>
</div>Doing some research, it looks like the problem is that my pdf-info-features variable is defined as (case-sensitive-search writable-annotations no-markup-annotations), so it excludes markup-annotations. However, I have pdf-info version 0.70 (installed via el-get), which should be able to create and modify markup annotations...

**Comment by billbrod** [comment]
Ah yup, sorry bout that. I read the README as saying I needed that version of pdf-tools, not of libpoppler. Building the newest libpoppler from source and then reinstalling pdf-tools made it work

**Comment by billbrod** [comment]
Wait no. Now I'm trying to get this working on my other computer and I can't get it working. I've got `libpoppler` 0.30, I've run `sudo ldconfig`,  checked that `locate` can find the newer version, and re-installed pdf-tools, but when I try to open up a pdf with pdf-tools, I get `The epdfinfo server quit, restart it?` over and over again.

I didn't do anything differently than on my other computer (both running same version of Ubuntu and of Emacs and of pdf-tools). The only difference that I can tell is that on this computer, libpoppler was put into /usr/bin instead of /usr/local/bin. I put symlinks to the relevant files in /usr/local/bin to see if that would help and it does nothing...

Any idea what might be going on?

**Comment by billbrod** [comment]
I also tried running epfinfo from the command line and nothing happens (no message pops up or anything), but this also happened on the computer I got it  working on, so I'm not sure what to make of that...

**Comment by politza** [comment]
This happens frequently, in case your runtime libraries are different from the compile ones. Try to run the following command in a terminal in the appropriate directory.

`echo renderpage:/absolute/path/to/some.pdf:1:100 | ./epdfinfo`

It should respond with a `OK` message.

**Comment by billbrod** [comment]
As I mentioned above, I was able to get this working without any problems on one computer, but have since given up on the other one. I'm pretty certain it's an issue with libpoppler though, not with pdf-tools.
