### ISSUE TITLE
highlighting: imprecise/incorrect regions

### ISSUE THREAD

**Issue by rdiaz02** [politza/pdf-tools#122]
(Submitted together, as I think these are related).

A. Selecting a region for highlighting can easily result in not highlighting what you think you have selected, and this is particularly common with two-column pdfs. Note that Okular, which is also poppler-based, does not display this problem, so I am not sure this is directly a poppler issue.

Reproducible example: 
    - Get, for instance, this pdf: http://advan.physiology.org/content/37/3/213.full-text.pdf+html
    - Go to page 217 (5th page), on right column, about mid page, and try to select for highlighting the  first line of the paragraph `How do we make sense of these disparate conclusions`. Even if you mark it correctly, what gets highlighted is the line below (but, interestingly, if you display the annotations ---with `C-c C-a l` and have `pdf-annot-list-follow-minor-mode` you will see that the line that pdftools shows with the ellipse on top is the correct one, even if the yellow one is the one below it).

B. Selecting a region of more that one line, where the first word to highlight on the top row is further to the right than the last word to highlight on the bottom row, is impossible (unless you mark and highlight each line independently).

For the sake of the example, in the above PDF, in the same 5th page, go for instance to the last two lines and try to highlight `t test or a permutation`. Again, I cannot reproduce this problem with Okular.

**Comment by rdiaz02** [comment]
Another manifestation of the above bug(s), specially B, is that, in multicolumn documents, you cannot easily select a region that spans multiple columns (e.g., a sentence that spans the last two lines at the bottom of the left column and continues for one or a few lines on the top of the right column).

**Comment by politza** [comment]
I think these issues are unrelated.

A: The current code reorders the beginning and end coordinates of the
region, which results in the behaviour you've described.

B: I'm pretty sure this is a bug in the glib front-end of poppler (okular uses the qt one).  The same behaviour can be examined in evince, i.e. the visual highlight and the zone where the mouse pointer reacts to the annotation differ similarly.

**Comment by rdiaz02** [comment]
Aha, I see, thanks.  It did not occure to me to try evince; I just did and, yes, I can also reproduce the problem in A.  Should I fill two separate issues since they are unrelated?

P.S. I think you reverted the A and B with respect to my A and B

**Comment by politza** [comment]
Ramon Diaz-Uriarte <notifications@github.com> writes:

> Aha, I see, thanks. It did not occure to me to try evince; I just did
> and, yes, I can also reproduce the problem in A. Should I fill two
> separate issues since they are unrelated?

I just did (#138), so let's stick to the glib-poppler bug in here.  I
believe the problem is described here:

https://bugzilla.gnome.org/show_bug.cgi?id=744220

The annotation's coordinates should undergo some transformation which
glib-poppler fails to apply. Too bad.

**Comment by rdiaz02** [comment]
Thanks. However, the link refers to cropped pdfs and I see the problem without cropping (for instance, in Evince).

**Comment by politza** [comment]
You may not notice, that the PDF is cropped.  Please see if that works for you: 0107f80dcf268d08ac075b01729820062c0fbd67

**Comment by rdiaz02** [comment]
Highlights work perfect. Annotations, however, are still placed in incorrect locations in at least some files (far from the chosen location in the files from the bug report of bugzilla, slightly off in the pdf I gave as example).  They can, though, be moved to the correct location.

**Comment by titaniumbones** [comment]
For me, highlights are placed properly, but the new edge values cannot be used by pdf-info-gettext:
``` elisp
(mapc
           (lambda (annot) ;; traverse all annotations
             (message "%s" annot)
             (message "%s" (assoc-default 'edge annot))
             (let* ((page (assoc-default 'page annot))
                    ;;(text (assoc-default 'subject annot))
                    (text (pdf-info-gettext page (assoc-default 'edges annot)))
                    (height (nth 1 (assoc-default 'edges annot)))
                    ;; use pdfview link directly to page number
                   (linktext (concat "[[pdfview:" pdfpath "::" (number-to-string page) 
                                     "++" (number-to-string height) "][" title  "]]" ))
                   )
               (setq outputstring (concat outputstring text " ("
                                          linktext ", " (number-to-string page) ")\n\n"))
               ))
           annots)
```
Throws an error:
```
Debugger entered--Lisp error: (error "epdfinfo: Expected a relative rectangle: -0.083333 -0.036796 -0.083333 -0.036796")
  signal(error ("epdfinfo: Expected a relative rectangle: -0.083333 -0.036796 -0.083333 -0.036796"))
  error("epdfinfo: %s" "Expected a relative rectangle: -0.083333 -0.036796 -0.083333 -0.036796")
  pdf-info-query(gettext "/tmp/pdf-tools-2778u5Z/ *temp*-2778jqt/ *temp*-2778w0z" 3 "-0.083333 -0.036796 -0.083333 -0.036796" 0)
  pdf-info-gettext(3 (-0.083333 -0.036796 -0.083333 -0.036796))
```

**Comment by politza** [comment]
Ramon Diaz-Uriarte <notifications@github.com> writes:

> Annotations, however, are still placed in incorrect locations

They seem to also need translation.

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> For me, highlights are placed properly, but the new edge values cannot
> be used by pdf-info-gettext

The edges attribute is set to 0 (which is properly the wrong thing
anyway) for highlight annotations. Why these values are sometimes below
0 I don't know.

Anway, you should use the markup-edges one (which is a list of edges).

**Comment by titaniumbones** [comment]
OK, trying markup-edges. I guess I don't quite understand how to do this. I tried:

```elisp
(defun pdf-annot-markups-as-org-text (pdfpath &optional title level)
  "Acquire highlight annotations as text, and return as org heading"

  (interactive "fPath to PDF: ")
  (let* ((outputstring "") ;; the text to be return
         (title (or title (replace-regexp-in-string "-" " " (file-name-base pdfpath ))))
         (level (or level (1+ (org-current-level)))) ;; I guess if we're not in an org-buffer this will fail
         (levelstring (make-string level ?*))
        )
    (with-temp-buffer ;; use temp buffer to avoid opening zillions of pdf buffers
      (insert-file-contents pdfpath)
      (pdf-view-mode)
      (pdf-annot-minor-mode t)
      (let* ((annots (sort (pdf-annot-getannots nil (list 'highlight)  nil) ;; only get highlights
                           'pdf-annot-compare-annotations)))
        (setq outputstring (concat levelstring " Quotes From " title "\n\n")) ;; create heading

        ;; extract text
        (mapc
         (lambda (annot) ;; traverse all annotations
           (message "%s" annot)
           (message "%s" (assoc-default 'edge annot))
           (let* ((page (assoc-default 'page annot))
                  (edges (car (assoc-default 'markup-edges annot)))
                  ;;(text (assoc-default 'subject annot))
                  (text (pdf-info-gettext page edges))
                  (height (nth 1 edges))
                  ;; use pdfview link directly to page number
                 (linktext (concat "[[pdfview:" pdfpath "::" (number-to-string page) 
                                   "++" (number-to-string height) "][" title  "]]" ))
                 )
             (setq outputstring (concat outputstring text " ("
                                        linktext ", " (number-to-string page) ")\n\n"))
             ))
         annots)
        ))
    outputstring ;; return the header
    ))
```

on this file: https://www.dropbox.com/s/g83leqpw7a0yphu/historical-authority-hampton.pdf?dl=0 

(pdf-annot-markups-as-org-text "/path/to/historical-authority-hampton.pdf)

---------
Now I guess I am supposed to iterate over the markup-edges object somehow? How would you do this?  

Also, it seems that the text is still not aligned perfectly with the actual highlighted region.  Tell me if you see the same phenomena? Thank you!

**Comment by politza** [comment]
Try the function below. It'll extract to much text. There seems to be
still something wrong.

(defun pdf-annot-markups-as-org-text (pdfpath)
  "Acquire highlight annotations as text, and return as org heading"

  (interactive "fPath to PDF: ")
  (let ((title (replace-regexp-in-string "-" " " (file-name-base pdfpath ))))
    (with-temp-buffer
      (mapc
       (lambda (annot)
	 (when (eq 'highlight
		   (assoc-default 'type annot))
	   (let* ((page (assoc-default 'page annot))
		  (edges (assoc-default 'markup-edges annot))
		  (text (mapconcat (lambda (e)
				     (pdf-info-gettext page e nil pdfpath))
				   edges " "))
		  (height (nth 1 (car edges)))
		  (link (format "[[pdfview:%s::%d++%.2f][%s]]"
				pdfpath
				page
				height
				title)))
	     (insert (format "%s (%s, %d)\n\n" text link page)))))
       (sort (pdf-info-getannots nil pdfpath)
	     #'pdf-annot-compare-annotations))
      (buffer-string))))

**Comment by titaniumbones** [comment]
I think the bounds of the edge objects in markup-edges overlap, so you get strange overlapping text like this:

> ent or the Crown, and so relies heav- ily on revenues generated by visitors. Among its palaces is Hampton Court ily on revenues generated by visitors. Among its palaces is Hampton Court Palace, on the banks of the Thames, twelve miles from central London. Known Palace, on the banks of the Thames, twelve miles from central London. Known for being the finest Tudor palace in England, it is actually a tale of two for being the finest Tudor palace in England, it is actually a tale of two for being the finest Tudor palace in England, it is actually a tale of two palacesthe Tudor palace built by Thomas Wolsey and Henry VIII, and a baroque palace created by William III and Mary II. To start communicating baroque palace created by William III and Mary II. To start communicating the dual nature of the palace and to mark the 500th ann 

That's in addition to grabbing too much text, I think.

**Comment by titaniumbones** [comment]
replacing mapconcat with a single call to (pdf-info-gettext real-edges nil pdfpath) with 
```
(real-edges (list (nth 0 (nth 0 edges)) (nth 1 (nth 0 edges))  (nth 2 (car  (last edges))) (nth 3 (car (last edges))) ))  
```
eliminates the overlapping text (I'm sure there's a less clumsy way to do this), but the values are still sllightly off. This is obvious when you compare the edges field (which, in repligo reader's annotations at least, seems to accurately represent the extent of the annotation) with real-edges.

**Comment by politza** [comment]
After some investigation, I believe that this is another problem of the
glib front-end.

Matt Price <notifications@github.com> writes:

>
> (real-edges (list (nth 0 (nth 0 edges)) (nth 1 (nth 0 edges))  (nth 2 (car  (last edges))) (nth 3 (car (last edges))) ))  
>

These regions do not necessarily have to be continuous.

**Comment by titaniumbones** [comment]
> After some investigation, I believe that this is another problem of the
> glib front-end.
ah, bummer.
> 
> Matt Price <notifications@github.com> writes:
> 
>  (real-edges (list (nth 0 (nth 0 edges)) (nth 1 (nth 0 edges))  (nth 2 (car  (last edges))) (nth 3 (car (last edges))) ))
> These regions do not necessarily have to be continuous.

hmm, is there a better method? with the repligo comments "edges" gives the right boundaries, but I guess that  will not be the case with annotation added via glib.

**Comment by titaniumbones** [comment]
@pinguim06 has a function for guessing the region boundaries:
22629c746878f4e554d4e530306f3433d594a654 
It works well for me in limited testing.

**Comment by dit7ya** [comment]
I am receiving this problem on a current installation of `pdf-tools`. Is there a canonical way to fix it?

**Comment by vnckppl** [comment]
I am also still experiencing this problem (i.e., the highlight shows up in the wrong place).

**Comment by omarelashkar** [comment]
Yes, this problem is on again

**Comment by tongjie-chen** [comment]
I can confirm poppler-0.84.0-1-x86_64 worked and I have downgraded poppler from Archlinux package archive without a problem.

**Comment by tongjie-chen** [comment]
A walk around without breaking other programs is to extract poppler 0.84 ang poppler-glib files and build with those. Then add libpoppler*.so and glib files to loading path. I am not familiar with the building process, maybe some experts can have a better way to integrate these library files into pdf-tools package.
