### ISSUE TITLE
Annotations (seemingly) disappear when saving

### ISSUE THREAD

**Issue by antviro** [politza/pdf-tools#125]
I have done several annotations in a pdf and afterwards most of them are destroyed while saving the pdfs, Do you know what can be the reason? Moreover, an undo option would be great for this cases.

Thanks for your efforts on this useful tool!!

**Comment by politza** [comment]
Sounds like a bug. Are you able to reproduce it ?



<div>-------- Ursprüngliche Nachricht --------</div><div>Von: antviro <notifications@github.com> </div><div>Datum:18.09.2015  12:00  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Betreff: [pdf-tools] Sometimes annotations are removed while saving the pdf
  (#125) </div><div>
</div>I have done several annotations in a pdf and afterwards they are destroyed while saving the pdfs, Do you know what can be the reason? Moreover, an undo option would be great for this cases.

Thanks for your efforts on this useful tool!!

**Comment by mickesv** [comment]
Are they really destroyed? For me, they disappear from the open document when I save, but when I revert the buffer it turns out they have indeed been saved.
