### ISSUE TITLE
Bug: should switch to pdf buffer before determining target window

### ISSUE THREAD

**Issue by qizhihere** [politza/pdf-tools#127]
When using pdf-tools with bookmarks+, i cannot to jump to pdf bookmarks unless i manually switch to the pdf buffer. 

when i try to jump to a pdf bookmark, an error message is shown as below:

> pdf-info-query: epdfinfo: Error opening /home/qizhi/.emacs.d/elpa/pdf-tools-20150716.643/pdf-view.el:PDF document is damaged

After some debugging i find out the source of the error: 
https://github.com/politza/pdf-tools/blob/master/lisp/pdf-view.el#L1333

```elisp
(or (get-buffer-window (current-buffer) 0)
    (selected-window))
```
I change it to this:

```elisp
(or (get-buffer-window (current-buffer) 0)
    (and (switch-to-buffer (current-buffer))
         (selected-window)))
```

Then everything works fine. But i am a little confused: why `(get-buffer-window (current-buffer) 0)` return `nil` :??

**Comment by politza** [comment]
I believe this is a bug in `bookmark+` (ask Drew if he agrees). AFAIK the bookmark handler (i.e. `pdf-view-bookmark-handler`) should only set up the buffer, but not display it.  `bookmark+` does not seem to do this before running the hooks (the first of which running the code you referred to).
