### ISSUE TITLE
epdfinfo: destination not found

### ISSUE THREAD

**Issue by wyousef** [politza/pdf-tools#129]
I am always using multi-file tex document (file1, file2, ...etc) with not problem. The new document I am writing gives me "epdfinfo: destination not found" error when I try to go forward and backward in places located after file 1. 

The only thing new in this document is that I am using pdfpages. I tried to comment all the contents of file1 and file2 and started removing the comments line by line it kept working until I unncommented all the pdfpages statements; by then the C-c C-g gave me the error!!

**Comment by wyousef** [comment]
In fact, I just tried even removing the pdfpages statements; still not working. All other multi-file document work !! I think it is ambiguous.

**Comment by politza** [comment]
Sounds like SyncTeX can't handle it.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Waleed Yousef <notifications@github.com> </div><div>Datum:04.10.2015  21:59  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Betreff: [pdf-tools] epdfinfo: destination not found (#129) </div><div>
</div>I am always using multi-file tex document (file1, file2, ...etc) with not problem. The new document I am writing gives me "epdfinfo: destination not found" error when I try to go forward and backward in places located after file 1.

The only thing new in this document is that I am using pdfpages. I tried to comment all the contents of file1 and file2 and started removing the comments line by line it kept working until I unncommented all the pdfpages statements; by then the C-c C-g gave me the error!!

**Comment by wyousef** [comment]
I kept tracing until I found the problem. The option "clip" in includegraphics or includepdf is the source of the problem.

Thanks for your great tool again.

Please, feel free to close the ticket.
