### ISSUE TITLE
(void-function pdf-tools-install)

### ISSUE THREAD

**Issue by gdkrmr** [politza/pdf-tools#130]
I installed ```pdf-tools``` following the instructions in the README and the installation seems to go well. But when I try to open a pdf ```docview``` is used and I get a warning when I start emacs, with the --debug-init option I get the following error:

```
Debugger entered--Lisp error: (void-function pdf-tools-install)
  (pdf-tools-install)
  eval-buffer(#<buffer  *load*> nil "/home/me/.emacs" nil t)  ; Reading at buffer position 541
  load-with-code-conversion("/home/me/.emacs" "/home/me/.emacs" t t)
  load("~/.emacs" t t)
    ... some bytecode I cannot copy and paste ...
  command-line()
  normal-top-level()
```

```emacs-version``` gives the following output: 
```GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9) of 2015-03-21 on kissel, modified by Debian```

I installed from source using the current master branch. When I run ```M-x pdf-view-install RET``` everything seems to work fine.

**Comment by politza** [comment]
Any chance you forgot to install the package ?

Try `(require 'pdf-tools)` .

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: gdkrmr <notifications@github.com> </div><div>Datum:08.10.2015  19:18  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Betreff: [pdf-tools] (void-function pdf-tools-install) (#130) </div><div>
</div>I installed pdf-tools following the instructions in the README and the installation seems to go well. But when I try to open a pdf docview is used and I get a warning when I start emacs, with the --debug-init option I get the following error:

Debugger entered--Lisp error: (void-function pdf-tools-install)
  (pdf-tools-install)
  eval-buffer(#<buffer  *load*> nil "/home/me/.emacs" nil t)  ; Reading at buffer position 541
  load-with-code-conversion("/home/me/.emacs" "/home/me/.emacs" t t)
  load("~/.emacs" t t)
    ... some bytecode I cannot copy and paste ...
  command-line()
  normal-top-level()
emacs-version gives the following output: 
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9) of 2015-03-21 on kissel, modified by Debian

I installed from source using the current master branch.

**Comment by gdkrmr** [comment]
```(require 'pdf-tools)```  give the following warning at startup:
```
Warning (initialization): An error occurred while loading `/home/me/.emacs':

File error: Cannot open load file, no such file or directory, pdf-tools
```
and yes I have it installed, I used ```M-x package-install-file``` and it appears if I call ```M-x list-packages```

**Comment by politza** [comment]
Does emacs.d/elpa/pdf-tools exist ? Tried a restart ?

This sounds strange to me.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: gdkrmr <notifications@github.com> </div><div>Datum:08.10.2015  21:44  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de> </div><div>Betreff: Re: [pdf-tools] (void-function pdf-tools-install) (#130) </div><div>
</div>(require 'pdf-tools) give the following warning at startup:

Warning (initialization): An error occurred while loading `/home/me/.emacs':

File error: Cannot open load file, no such file or directory, pdf-tools
and yes I have it installed, I used M-x package-install-file and it appears if I call M-x list-packages

**Comment by gdkrmr** [comment]
It is installed under ```~/.emacs.d/elpa/pdf-tools-0.70```, yes i tried restarting, as I said ```M-x pdf-tools-install``` from inside emacs works.

**Comment by politza** [comment]
You probably need to package-initialize before using this function. 

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: gdkrmr <notifications@github.com> </div><div>Datum:08.10.2015  23:09  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de> </div><div>Betreff: Re: [pdf-tools] (void-function pdf-tools-install) (#130) </div><div>
</div>It is installed under ~/.emacs.d/elpa/pdf-tools-0.70, yes i tried restarting, as I said M-x pdf-tools-install from inside emacs works.

**Comment by gdkrmr** [comment]
you are right, adding 
```lisp
(package-initialize)
(pdf-tools-install)
```
to ```.emacs``` solved the problem, cool Thanks a lot!!
