### ISSUE TITLE
Resolution of images taken by pdf-view-extract-region-image

### ISSUE THREAD

**Issue by wyousef** [politza/pdf-tools#131]
When I select a rectangle, then C-c tab it open a buffer with a good apparent resolution. when I save the buffer and reopen the resolution is good as well. However, when I include the saved image in LaTeX  the resolution is degraded. I tried (Setq doc-view-resolution 300) nothing happened.

**Comment by politza** [comment]
`C-c tab` creates an image with the same dimensions as the current selection (or displayed page) and displays it in some buffer.  If you need a larger picture, enlarge the PDF page first using `+`.

LaTeX may scale included pictures up or down.  This is what you describe as ,,image dgredation''.

docview is an entirely different package.

**Comment by wyousef** [comment]
Thanks so much; it works now after enlarging!

Please close the issue (I am replying from gmail not GitHub)
