### ISSUE TITLE
extract annotations?

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#134]
I'm just starting to use pdf-tools, and wondering if it might provide a way to extract highlights and other annotations from the text.  I currently use a bash script for this purpose but it often fails to recognize the highlighted text; it would be great to manage this task completely within Emacs, e.g. from an org-mode code block.  

If you think this is possible I'd appreciate some pointers! Thanks very much.

**Comment by politza** [comment]
Like #133 ?

**Comment by titaniumbones** [comment]
ha, kind of!  I had totally missed that pull request.  I want something a little different, that will capture especially highlighted text.  So I've modeified pdf-annot-export-to-org to the following:
``` elisp
(defun pdf-annot-export-as-org-heading ()
  "Acquire highlight annotations as text, and insert into existing buffer as org heading"
  (interactive)
  (let ((annots (sort (pdf-annot-getannots nil (list 'highlight)  nil) 'pdf-annot-compare-annotations))
        (filename (format "%s.org"
                          (file-name-sans-extension
                           (buffer-name))))
        (linktext (concat "[[file://" (buffer-file-name) "][" (file-name-sans-extension (buffer-name)) "]]" ))
        )
    (with-temp-buffer
      (insert (concat "#+TITLE: Notes for " (file-name-sans-extension filename)))
      (org-insert-heading-respect-content)
      (insert (file-name-sans-extension filename))
      (mapc
       (lambda (annot) ;; traverse all annotations
         (message "%s" annot)
         (let ((page (assoc-default 'page annot))
               (text (assoc-default 'subject annot))
               )
           (insert (concat "\n" text " (" linktext ", " (number-to-string page) ")\n"))
           )
         )
       annots)
      (write-file filename t))))
```
This does almost what I want -- really, I would like to call from a SRC block within org, and have the contents appear directly in my org file, like this:

* Notes about Mice
#+BEGIN_SRC elisp :results
(pdf-annot-export-as-org-heading "/home/matt/mice/bluemouse.pdf")
(pdf-annot-export-as-org-heading "/home/matt/mice/redmouse.pdf")
#+END_SRC

which would output:
``` org
** Notes from bluemouse
blue mice are sad ([[file://home/matt/mice/bluemouse.pdf][bluemouse]], p.2)
** Notes from redmouse
red mice are angry ([[file://home/matt/mice/redmouse.pdf][redmouse]], p.2)
```
I'm not so good at loading files and so forth, if you have suggestions for improvements I'd be very grateful.

Also: even better would be to have the org link jump directly to the citation location (page and position).  Can PDF Tools do that? If so, it should be possible to write a custom org link type that replicates the behaviour, shouldn't it? 

Many thanks,
Matt

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> Also: even better would be to have the org link jump directly to the
> citation location (page and position). Can PDF Tools do that? If so,
> it should be possible to write a custom org link type that replicates
> the behaviour, shouldn't it? 

Sure, it's possible, i.e. see pdf-view-bookmark-jump-handler.  Maybe you
should ask the maintainer of org-pdfview to extend the link format.

**Comment by titaniumbones** [comment]
Thanks, I will point him to this issue.  

Looking at pdf-view-bookmark-jump-handler, I see some (to me) unfamiliar attributes of bookmarks: slice,size,origin. Annotation location, at least for highlights, seems to be specified by the "edges" attribute.  I'm not quite sure I understand the bookmark code, but it looks like the height of the jump is  set in here and that it depends on a list "size":
```elisp
(when origin
                (let ((size (pdf-view-image-size t)))
                  (image-set-window-hscroll
                   (round (/ (* (car origin) (car size))
                             (frame-char-width))))
                  (image-set-window-vscroll
                   (round (/ (* (cdr origin) (cdr size))
                             (frame-char-height)))))))))
```

Can org-pdfview get access to "size"? and can I scroll approximately to the height of a highlight annotation with 

```elisp
(image-set-window-vscroll 
  (round (/ (* (HEIGHT-EXTRACTED-SOMEHOW-FROM-EDGES-ATTRIBUTE) (cdr SIZE)) 
    (frame-char-height))))
```

**Comment by titaniumbones** [comment]
Not that it matters much, but I've written about my current use of pdf-tools here: http://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/

**Comment by politza** [comment]
For highlight annotations `markup-edges' is a list of relative edges of
the marked regions. You need to multiply them with the actual image-size
(pdf-view-image-size) and finally divide by frame-char-height
(resp. width) because image-set-window-[vh]scroll scrolls by lines
(resp. columns).

**Comment by titaniumbones** [comment]
ah, that works, thx.

**Comment by AtomicNess123** [comment]
Where are the annotations stored with PDFTOOLS?

**Comment by tongjie-chen** [comment]
> Where are the annotations stored with PDFTOOLS?

@AtomicNess123 It's inside the PDF file. All functions related are in ~pdf-annot.el~.
