### ISSUE TITLE
confict with customization buttons

### ISSUE THREAD

**Issue by Jehops** [politza/pdf-tools#135]
Starting emacs with `emacsclient -nc` using an empty init file other than the line `(add-hook 'after-init-hook 'pdf-tools-install)` will cause all buttons in customization buffers to be text only.  

Starting emacs without the server and the same init file doesn't cause the problem.

Starting with `emacsclient -nc` using an empty init file and evaluating `(pdf-tools-install)` after startup doesn't cause the problem.

**Comment by politza** [comment]
Joseph Mingrone <notifications@github.com> writes:

> Starting emacs with emacsclient -nc using an empty init file other
> than the line (add-hook 'after-init-hook 'pdf-tools-install) will
> cause all buttons in customization buffers to be text only. 

How do you start emacs via emacsclient w/o starting the server in your
init file ?

This sounds like a odd problem and I don't see how pdf-tools could cause it.

**Comment by Jehops** [comment]
politza <notifications@github.com> writes:
> How do you start emacs via emacsclient w/o starting the server in your
> init file ?
I set the environment variable ALTERNATIVE_EDITOR to the empty string.  This is described in the emacsclient man page under the first option `-a, --alternate-editor=EDITOR`.

> This sounds like a odd problem and I don't see how pdf-tools could cause it.
How can I make a more clear example?  I can only suggest that you try the simple test I described.

**Comment by politza** [comment]
I see, but this sounds more like a problem with your setup or Emacs itself.  Anyway, I couldn't reproduce it, i.e. widgets look fine for me with your recipe.

**Comment by Jehops** [comment]
I went to a new system, this time GNU/Linux, without Emacs.

    % uname -orv
    3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 GNU/Linux
    git clone git://git.savannah.gnu.org/emacs.git
    cd emacs
    ./configure --disable-acl --without-dbus --without-file-notification --without-gconf --with-gif --with-gnutls --without-gsettings --with-jpeg --with-m17n-flt --with-imagemagick --with-libotf --with-png --without-toolkit-scroll-bars --with-rsvg --with-tiff --with-x --with-xft --with-xim --with-xml2 --with-xpm --prefix=${HOME}/local
    make

I started `emacsclient -nc` and visited a customization buffer and the buttons were true buttons.
Next, I did `M-x list-packages` and installed pdf-tools.  Then, the only text I added to an empty `~/.emacs` was `(package-initialize) (pdf-tools-install)`.  When I killed the server and ran `emacsclient -nc` again and visited a customization buffer, the buttons were text buttons.  When I removed the `(install-pdf-tools)` line from `~/.emacs`, did `M-x kill-emacs`, then started Emacs as before, the buttons were again true buttons.  If I add my 600-line `~/.emacs` without `(pdf-tools-install)` the buttons appear fine.

**Comment by Jehops** [comment]
I've discovered that any call to `customize-save-variable` during startup (as described above) will cause the problem.  When I remove the call to that function is `pdf-misc.el`, byte-compile the file, rebuild the server and restart Emacs, the widget buttons appear again.

**Comment by politza** [comment]
This sounds like a bug/feature in Emacs.  The function `customize-save-variable` is in there, but it's not called in the circumstances you describe.

**Comment by Jehops** [comment]
Since it's been 3 months, I don't recall the details, but I just tried commenting out the call to `customize-save-variable`, but the buttons were still text.  I test all the claims in my others comment and they are correct.

**Comment by Jehops** [comment]
politza <notifications@github.com> writes:
> I see, but this sounds more like a problem with your setup or Emacs itself.  Anyway, I couldn't reproduce it, i.e. widgets look fine for me with
> your recipe.

Hopefully this short video (1 minute) confirms that the problem exists and it's not with my Emacs configuration.

https://www.youtube.com/watch?v=GsFvedRz77g

**Comment by politza** [comment]
pdf-tools loads cus-edit.el, which defines the faces for the buttons and
may be causing this problem.  Try to replace the pdf-tools code with a
simple `(require 'cus-edit)` and see if it's still happening.

**Comment by Jehops** [comment]
Creating an init file with only the line `(require 'cus-edit)` triggers the issue.

**Comment by politza** [comment]
Clearly an Emacs feature/bug.
