### ISSUE TITLE
highlight annotations have no content

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#137]
I'm using pdf-tools from git and installed as a self-rolled package in elpa, as per the README.  

Highlight annotations created in other tools (mostly repligo reader on Android) display in the annotations list and have content (that is, subject) equivalent to the highlighted text.  In pdf-tools, I can select text and then M-x pdf-annot-add-highlight-markup-annotation.  This creates a new highlight annotation, but the annotation:
(a) is displaced in space -- usually up and to the left
(b) has an empty subject assoc cell

I'm running Arch Linux with recent versions of poppler, and I think I have the relevant dev libraries installed, though the naming conventions on arch are different from Debian and I'm not 100% sure. 

Thank you!

**Comment by titaniumbones** [comment]
hmm, this may be a duplicate of #122 -- at least (a).  I'm not sure about (b), and whether the gtk frontend to poppler cna handle this - -evince annotations are very buggy on my machine.

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> hmm, this may be a duplicate of #122 -- at least (a). 

Looks like it. Does the offending PDF have multiple columns ?

> I'm not sure about (b), and whether the gtk frontend to poppler cna
> handle this - - evince annotations are very buggy on my machine.

It's the glib front-end. )b seems to me application dependent, i.e. your
particular mentioned viewer chooses to use the selections text as the
subject value or is this behavior ubiquitous ?

Anyway, it's currently not possible to set the subject of an annotation
per poppler-glib, though I've `extended' the API before
(poppler-hacks.cc).

**Comment by titaniumbones** [comment]
>> hmm, this may be a duplicate of #122 -- at least (a).

> Looks like it. Does the offending PDF have multiple columns ?

no. Here's an example:
https://www.dropbox.com/s/g83leqpw7a0yphu/historical-authority-hampton.pdf?dl=0  
All but one of the highlights was made with the closed-source Repligo Reader app on Android; the single highlight with a creator of "Matt Price" was made within emacs using pdf-annot-add-highlight-markup-annotation.  

>>  I'm not sure about (b), and whether the gtk frontend to poppler cna
>  handle this - - evince annotations are very buggy on my machine.

> It's the glib front-end. )b seems to me application dependent, i.e. your
> particular mentioned viewer chooses to use the selections text as the
> subject value or is this behavior ubiquitous ?
> 
> Anyway, it's currently not possible to set the subject of an annotation
> per poppler-glib, though I've `extended' the API before
> (poppler-hacks.cc).

ah. so highlights made with pdf-tools will probably never have a "subject", unless poppler-glib adds this functionality?  Sorry to hear that, bummer.  Anyway, I would love to hear if highlighting in the dropbox link above works for you.

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> Here's an example:
> https://www.dropbox.com/s/g83leqpw7a0yphu/historical-authority-hampton.pdf?dl=0
>

Seems to be the same problem.  If I open this in evince (which also uses
glib-poppler) and create a highlight annotation, it is similarly offset.


> ah. so highlights made with pdf-tools will probably never have a
> "subject",

Not true, because we could extend the glib API by referring to poppler
core functions.

**Comment by titaniumbones** [comment]
> Not true, because we could extend the glib API by referring to poppler core functions.

well, if you can figure out how to do that I would be very grateful! Sounds out of my league though.

**Comment by titaniumbones** [comment]
(changed the title to reflect the fact that displacement is a dupe of #122).

**Comment by politza** [comment]
It would be nice if the subject, among other attributes, could be modified.  Though, I don't think it should default to the full-text of the annotation.

**Comment by titaniumbones** [comment]
> It would be nice if the subject, among other attributes, could be modified. Though, I don't think it should default to the full-text of the annotation.

no?  Interesting. I use highlighting as a way of taking notes -- I read, highlight, and then later extract the hihglights for potential use in writing. I think it's a fairly common practice, as exemplified by the way tablet pdf apps set the subject.  

Maybe it could be customizable?

**Comment by politza** [comment]
> I don't think it [subject] should default to the full-text of the annotation.

If every other reader does it, then ok.  But it seems to me that subject
is not the proper place for the full text. I'd go with contents (which
incidentally is also writable in pdf-tools).

**Comment by titaniumbones** [comment]
(a) how would I acquire the text that is contained in the bounds of the highlighted region?
(b) would it be better to store that text in a field of the annotation object, or just to extract it on the go at the moment I want to see it? I suppose that, if most or even some other PDF readers store the text elsewhere, it might be more reliable to identify and extract the text directly in the annotation-retrieval function. (thx to Matt Lundin on the org list for suggesting many other android readers don't store text of markup annotations).

**Comment by titaniumbones** [comment]
ok (sorry for all the messages): 

I can do something like this:

```elisp
(let ((text (pdf-info-gettext page (assoc-default 'edges annot))))
...
)
```
But in those pdf's where poppler _assigns_ markup to the wrong co-ordinates, it also _extracts text_ from the wrong co-ordinates.  So, for me atl east, this is not a more reliable method than extracting the text from the subject field.
