### ISSUE TITLE
Problem during installation on Debian 8 Jessie - gtklp not longer available

### ISSUE THREAD

**Issue by corto037** [politza/pdf-tools#140]
Hello,
Congratulations and thank you for your tool! It seems to be an useful add-on to Emacs.
However, trying to install it under Debian 8 Jessie, I met a problem. 
Following all your instructions, all was good until I entered 'make install-server-deps' where I get an error message. After some inquiries on Debian sites and forums, I understand that the package requested gtklp is not longer available for Jessie. Is it right? Despite this problem, Is it a way to install it?
Thank you in advance and best for all,
corto037

**Comment by politza** [comment]
corto037 <notifications@github.com> writes:

> I understand that the package requested gtklp is not longer available for Jessie.

gtklp is a printer-dialog program. You may ignore this error message.

**Comment by corto037** [comment]
Thank you very much for this quick reply.
Indeed, during the compilation, I ignored the 'optional' command 'make install-server-deps' and the installation completes well. Once installed in Emacs, all is fine.
Thanks again & best for all,
corto037
