### ISSUE TITLE
Unable to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by codemeleon** [politza/pdf-tools#143]
Hi, 
Commands worked without errors till "make -s" command. However, "make install-package" gives following error

emacs -Q --batch --eval \
		"(progn (package-initialize) \
			(package-install-file \
				\"pdf-tools-0.70.tar\"))"
Wrong type argument: stringp, nil
make: *** [install-package] Error 255

I am using emacs-24.3.1 on Ubuntu 14.04(x86_64).

Thanks

**Comment by politza** [comment]
I think this might be an old bug in package.el . Try to open the tar
file in Emacs and do package-install-from-buffer on it.

If that doesn't work, enable debugging (toggle-debug-on-error), do it
again and post the back-trace.

**Comment by codemeleon** [comment]
I am not good with Emacs commads. It is my first time using Emacs. I guess, I am giving installation of pdf-tools until I learn more about Emacs.

Thanks

**Comment by politza** [comment]
Anmol Kiran <notifications@github.com> writes:

> I am not good with Emacs commads.

Try this then :

(progn
  (require 'package)
  (add-to-list 'package-archives
	       '("melpa" . "https://melpa.org/packages/") t)
  (package-initialize t)
  (package-refresh-contents)
  (package-install 'pdf-tools));;C-x C-e here

**Comment by mikegilchrist** [comment]
Having the same problem installing on a 14.04 machine.  I have enabled debugging and doing the install via emacs gives:

      Debugger entered--Lisp error: (error "package.el is not yet initialized!")
      signal(error ("package.el is not yet initialized!"))
      error("package.el is not yet initialized!")
      package-installed-p(emacs (24 3))
      package-compute-transaction(nil ((emacs (24 3)) (let-alist (1 0 1))))
      package-install-from-buffer(["pdf-tools" ((emacs (24 3)) (let-alist (1 0 1))) 
      package-install-file("~/tmp/pdf-tools-master/pdf-tools-0.70.tar")
      call-interactively(package-install-file record nil)
      command-execute(package-install-file record)
      execute-extended-command(nil "package-install-file")
      call-interactively(execute-extended-command nil nil)

Any thoughts?  I am able to byte compile and load my personal.el file w/o any problems.

**Comment by politza** [comment]
mikegilchrist <notifications@github.com> writes:

> Having the same problem installing on a 14.04 machine. I have enabled debugging and doing the install via emacs gives:
>
>   Debugger entered--Lisp error: (error "package.el is not yet initialized!")

Just call package-initialize before invoking any other package function.

**Comment by mikegilchrist** [comment]
Not 100% sure how to follow your suggestion.  W/in emacs I did `<M-x package-initialize>` and saw no output.  Next I tried `<M-x package-install-file RET pdf-tools-0.70.tar RET>`.  I then got the error `<Package `let-alist-1.0.1' is unavailable>`

**Comment by mikegilchrist** [comment]
Also, per your previous instructions I opened the .tar file in emacs and then tried `<package-install-from-buffer>` and got the error `<Packages lacks a file header`>
