### ISSUE TITLE
extract embedded images

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#146]
I would love to have a way to extract an embedded image from a PDF & save as file. I do this often in evince while writing lectures (right click --> save file as).  As far as I can tell, there's no way to interact with embedded images in pdf-tools.  Am I missing something? And if not, how hard would it be to make this possible? 

For instance, the attached pdf has an image on p. 5 that' I'd like to extract.  

thanks, m

[Latour · Critique Run Out of Steam.pdf](https://github.com/politza/pdf-tools/files/41128/Latour.Critique.Run.Out.of.Steam.pdf)

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> I would love to have a way to extract an embedded image from a PDF

Not currently implemented.

**Comment by titaniumbones** [comment]
Is there access to the images already, in a way that I could try to implement some of this in elisp? Though I am a pretty clumsy coder, as you've already seen.

**Comment by politza** [comment]
Matt Price <notifications@github.com> writes:

> Is there access to the images already, 

No.

**Comment by vyp** [comment]
@titaniumbones you can do this outside of emacs by using pdfimages from [poppler-utils](https://en.wikipedia.org/wiki/Poppler_(software)#poppler-utils).
