### ISSUE TITLE
inline notes

### ISSUE THREAD

**Issue by tpapp** [politza/pdf-tools#149]
Would it be possible to add what inline notes? Ie a box with text that is just displayed, instead of an icon which needs to be clicked on. The version I am using (libpoppler 0.26.5, pdf-tools 20151111) can edit existing inline notes just fine (eg made with okular), but I could not figure out how to add them.

**Comment by politza** [comment]
I'm afraid, this is currently not possible (using poppler-glib).

**Comment by x-ji** [comment]
So that is something `poppler-glib` has to add on their side, correct?

**Comment by politza** [comment]
Xiang Ji <notifications@github.com> writes:

> So that is something poppler-glib has to add on their side, correct?

I think so, yes.
