### ISSUE TITLE
Is pdf-tools still maintained for MELPA Stable?

### ISSUE THREAD

**Issue by cilia** [politza/pdf-tools#152]
Hi, just checked [stable.melpa.org](http://stable.melpa.org) and saw `pdf-tools`'s latest stable version is 0.70 back in early June. Also saw that on the project Github page there is no indication the package is available/maintained for MELPA Stable. Just wondering if there is any plan for maintaining `pdf-tools` for MELPA Stable going forward, or the package will only be available through MELPA now.

Thanks!

**Comment by politza** [comment]
cilia <notifications@github.com> writes:

> [...] pdf-tools's latest stable version is 0.70 back in early
> June. [...]

More like early November.

**Comment by politza** [comment]
There is a button "Releases" on this site. These are automatically used by melpa-stable.  So there is nothing specifically for me to do, apart from tagging some commit as a new release.  I suppose that answers your question.
