### ISSUE TITLE
package epdfinfo separately

### ISSUE THREAD

**Issue by zabbal** [politza/pdf-tools#154]
The need to rebuild epdfinfo every time pdf-tools are updated (at least this seems to be the case with melpa install) is real headache: emacs init appears to be broken, hard to debug and so on.

I don't think epdfinfo is actually changing that often hence would be great if it could be packaged separately and shipped as part or regular distribution repo: .deb, .rpm etc and pdf-tools just depend on it being available in $PATH.

If some distro is lagging behind or users just absolutely need bleeding edge features than it still could be compiled manually and placed into ~/bin or whatever.

Such decoupling should also make emacs part of pdf-tools simpler. This would also enable for easier experimentation where one can replace epdfinfo with different binary as long as it complies to the same interface.

**Comment by politza** [comment]
That would probably be a good idea.
