### ISSUE TITLE
Add ability to change default font used for rendering

### ISSUE THREAD

**Issue by nitishch** [politza/pdf-tools#155]
How can I change the default font used by `pdf-tools`? For example, the following pdf doesn't have any font information bundled with it. 

Rendered by `pdf-tools`:

![tools](https://cloud.githubusercontent.com/assets/6604116/11651251/73125dba-9db5-11e5-9fe0-f5c15fc105fc.png)

Rendered by `mupdf`:

![mu](https://cloud.githubusercontent.com/assets/6604116/11651269/91e7ccac-9db5-11e5-9f75-0773b1c368e9.png)

I like the look of the second image. How can I change the default font used by `pdf-tools`?

**Comment by politza** [comment]
Nitish Chandra <notifications@github.com> writes:

> How can I change the default font

You can't.  Maybe from outside (environment etc.), but I don't know.
