### ISSUE TITLE
(pdf-tools-install) works after emacs is loaded but not in .emacs.

### ISSUE THREAD

**Issue by LordZorgoth** [politza/pdf-tools#158]
I installed pdf-tools using emacs' package manager and ran pdf-tools-install, which compiled something. I can now use pdf-tools, except that I have to manually run pdf-tools-install every time I start emacs.

If it's in the .emacs file, it says the function isn't defined. I don't know what to (require ) to make it work -- it certainly won't let me (require 'pdf-tools).

**Comment by politza** [comment]
Try to put this

    (package-initialize)

at the start of your init file.

**Comment by LordZorgoth** [comment]
Thanks! That worked.
