### ISSUE TITLE
wrong-type-argument inserted-chars

### ISSUE THREAD

**Issue by manuel-uberti** [politza/pdf-tools#159]
Hi,

I am on `GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.5) of 2015-12-11`, on Debian Jessie. I've built Emacs development sources (`emacs-25` branch, commit: `83114ccf77d2a5d59fccbdbda6edefacce1b979e`).

Whenever I try to open a PDF file using `pdf-tools`, I get this error:

```
Debugger entered--Lisp error: (wrong-type-argument inserted-chars 1579781)
  insert-file-contents("~/Documents/books/tech/emacs/mastering-emacs.pdf" t)
  find-file-noselect-1(#<buffer mastering-emacs.pdf> "~/Documents/books/tech/emacs/mastering-emacs.pdf" nil nil "~/Documents/books/tech/emacs/mastering-emacs.pdf" (7078315 2049))
  find-file-noselect("~/Documents/books/tech/emacs/mastering-emacs.pdf" nil nil t)
  find-file("~/Documents/books/tech/emacs/mastering-emacs.pdf" t)
  funcall-interactively(find-file "~/Documents/books/tech/emacs/mastering-emacs.pdf" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

This is a small recipe to reproduce the error:

- `emacs -Q`
- `M-x package-initialize`
- `M-x pdf-tools-install`
- `C-x C-f ~/Documents/books/tech/emacs/mastering-emacs.pdf`

Also, up until commit `d75849e937af0ecbcdc7bf621aa9bcd43aa75df4`, everything was working fine.

**Comment by politza** [comment]
Manuel Uberti <notifications@github.com> writes:

> Debugger entered--Lisp error: (wrong-type-argument inserted-chars 1579781)

Do you get the same bug without pdf-tools installed ?

**Comment by manuel-uberti** [comment]
No, I can view the same PDF just fine without pdf-tools and relying on DocView. (Again, this in `emacs -Q`).

**Comment by politza** [comment]
Manuel Uberti <notifications@github.com> writes:

> No, I can view the same PDF just fine without pdf-tools and relying on DocView. (Again, this in emacs -Q).

Try with normal invocation (i.e. without -Q), without
`pdf-tools-install` or even better pdf-tools uninstalled.

Anyway, I don't think that pdf-tools is the cause of this problem.  And
I don't understand the code signaling this error.

**Comment by politza** [comment]
Manuel Uberti <notifications@github.com> writes:

> * emacs -Q 
> * M-x package-initialize 
> * M-x pdf-tools-install 
> * C-x C-f ~/Documents/books/tech/emacs/mastering-emacspdf 

Ok, maybe I'm wrong.

**Comment by manuel-uberti** [comment]
I uninstalled pdf-tools and tried without -Q: I can view PDFs with DocView and no error.

**Comment by manuel-uberti** [comment]
I have "good" news: just upgraded my Emacs dev sources and rebuilt, and now I got the same error even when using plain old DocView. 

I'm closing this issue, apparently `pdf-tools` is innocent. :+1:

**Comment by manuel-uberti** [comment]
Just a quick note: already solved on `emacs-25` branch.
