### ISSUE TITLE
Customizable background/text colors

### ISSUE THREAD

**Issue by oscarfv** [politza/pdf-tools#16]
Other poppler-based PDF readers (Okular, qpdfview) have the capability of selectable background/text colors for the PDF content, which is a must for night reading. Is it possible to implement that feature on pdf-tools?

**Comment by politza** [comment]
> I can complete the recolor feature once we have the epdinfo customization system discussed above.

Are you still interested in this ?

**Comment by oscarfv** [comment]
Yes.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> Yes.

I started a branch for this called `options'. On it is a comment in
epdfinfo.c:

/* image_recolor (cr); */

That's where I think your function should be called. You should be able
to enable recoloring from Lisp with using something like this

(pdf-info-setoptions
 :render/usecolors t
 :render/foreground fg
 :render/background bg)

in some PDF buffer.

Have fun.

**Comment by oscarfv** [comment]
Okay, I'll have a look.

Thanks.

**Comment by vspinu** [comment]
So how is this supposed to work? I don't see any user level configuration for this. I want to render white background as grey.  How can I do that? Thanks.
