### ISSUE TITLE
capitalization after certain characters, such as ¡ ¿ do not work, unless lowercased. 

### ISSUE THREAD

**Issue by linguafalsa** [politza/pdf-tools#160]
I think the title would be the main issue I'm having. Maybe not.

Other issues include but are not limited to: 

error while processing tq callback: Lisp nesting exceeds `max-lisp-eval-depth' (this one deserves mentioning) 
![screenshot from 2015-12-11 22 14 58](https://cloud.githubusercontent.com/assets/6383794/11760020/c9b001b4-a057-11e5-9f14-d818a1b82454.png)

error in process filter: lisp nesting exceeds `max-lisp-eval-depth'

error running timer `blink-cursor-timer-function': (error "lisp nesting exceeds `max-lisp-eval-depth'") 

and emacs becomes unresponsive, after a while (minutes, well, a while really) it stabilizes. An example, running ConTeXt MKIV:

      \setuppapersize[A5][A4]
      \setuplayout[marking=on,location=middle]
      \setupbodyfont[10pt]
      \starttext 
      ¡Una prueba!

      ¡¡¡Una prueba!!!

      y esta otra ¡prueba más!

      ¿Qué prueba?

      ¡Qué prueba!
      \stoptext

emacs running auctex and pdf-tools was compiled in the system.  Not elpa nor melpa.

**Comment by linguafalsa** [comment]
Please note that after restarting emacs, some of the above issues may not be present. But as soon as new code is entered, rendering of characters is unreliable. Also, simple arithmetic rendering is not possible either, so the latter deserves its own thread. Thanks guys.

**Comment by politza** [comment]
The way LaTeX renders certain character is not under the control of pdf-tools.
