### ISSUE TITLE
Viewing annotations in Chrome

### ISSUE THREAD

**Issue by mweaverh** [politza/pdf-tools#161]
The Google Chrome PDF viewer does not display annotations that were added via pdf-tools. Is this expected?
Thanks.

**Comment by politza** [comment]
Matthew Weaver <notifications@github.com> writes:

> The Google Chrome PDF viewer does not display annotations that were added via pdf-tools Is this expected?

Well, does it display any annotations at all ?

**Comment by mweaverh** [comment]
Yes, it displays annotations created by Acrobat Reader (windows).
But now I've noticed if I open and edit my file in Acrobat then re-save, the annotations work in Chrome.

**Comment by politza** [comment]
Matthew Weaver <notifications@github.com> writes:

> Yes, it displays annotations created by Acrobat Reader (windows).
> But now I've noticed if I open and edit my file in Acrobat then re-save, the annotations work in Chrome.

I think I'm not handling some annotation property right and this *may*
be a cause of it.

I suppose text-annotations work ?  Can you confirm that annotations
created with evince/okular work ?

**Comment by mweaverh** [comment]
This may be a problem with poppler. I have the same trouble with annotations created by
- qpdfview
- evince

whereas Chrome displays annotations created by

- xournal
- Adobe Acrobat (windows)
- PDFStudio
- Okular, but only by using Print to File (PDF)

I am not seeing _any_ annotations -- highlight, underline, text (sticky note).

**Comment by politza** [comment]
I'm not familiar with Okular. What is the alternative to "Print
to File" ?

So it's like a problem in poppler, more specifically
poppler-glib.

**Comment by homerobse** [comment]
To this day, the problem with Okular persists.

**Comment by baidut** [comment]
To this day, the problem with Okular persists.
