### ISSUE TITLE
Feature request: fit content to window

### ISSUE THREAD

**Issue by LordZorgoth** [politza/pdf-tools#162]
It would be useful to have a command that sets zoom and scroll to exclude the margins, so as to capitalize on screen space without having to fiddle around (my use case is LaTeX, and I'm editing the document and running a julia shell in the same frame).

**Comment by politza** [comment]
Like `pdf-view-auto-slice-minor-mode` ?

**Comment by LordZorgoth** [comment]
Oh, thanks. It might be work a default keyboard shortcut, but that's what I was looking for.

**Comment by LordZorgoth** [comment]
I don't know if this has anything to do with you, but simply having the mode enabled automatically doesn't seem to do anything for me. It only works when I explicitly call the command as a user.

Although, it's not 100% optimal. It would be better to have a mode that would still show you how big the margins are when you zoom out, but it's not as high a priority.

**Comment by LordZorgoth** [comment]
(speaking of which, the default zoom level for the 0 key is ridiculous. My pdfs become midgets. I think that's a core emacs bug though)

**Comment by LordZorgoth** [comment]
The most logical thing to do would seem to be too make a new option for pdf-view-display-size 'fit-width-to-content that sets the zoom to the same level as the size of a document in pdf-view-auto-slice-mode, but without slicing.
