### ISSUE TITLE
Remote buffer do not revert properly

### ISSUE THREAD

**Issue by emiliotorres** [politza/pdf-tools#163]
I am at a machine A and I usually use tramp to connect to another computer B. 

I am sitting at computer A, I open a tex file from computer B, I compile it, and I open the pdf file (from computer B).  I see the pdf with pdf-tools with no problems.

Now, I edit the tex file, I compile it again, and I select the buffer pdf, press the key g, I see this messages: Revert buffer from file /scp:[...] Tramp: Inserting [...] done
but the buffer pdf does not revert.

If I kill this buffer pdf and I reopen it, I can see the new version.
Is it the expected behaviour?

Thank you very much for your excellent package!
(Using Emacs GNU Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 2.24.23), pdf-tools 0.70)

**Comment by politza** [comment]
Yes, that does not work.  Remote files are copied, since the epdfinfo
program only works with local files.  But this currently happens only
once, when pdf-view-mode is activated.

I guess reverting the buffer should also trigger the creation of a new
local copy.

**Comment by andreasleha** [comment]
I am also hit by this bug.  The work-around (kill and re-open buffer) is quite annoying especially as this also prevents auto-refresh. Has by any chance anything happened on this?

**Comment by kaz-yos** [comment]
I cooked up the following hack and assigned it to ```g``` in the ```pdf-view-mode-map```.
```lisp
  (defun kill-file-associated-buffer-and-reopen-file ()
    "Kill the buffer if its file associated, and reopen the file."
    (let ((file buffer-file-name))
      (when file
        (kill-buffer)
        (find-file file))))
  ;;
  (defun my-revert-pdf ()
    "Revert if local. Kill and reopen if remote."
    (interactive)
    (cond
     ;; If remote kill buffer and reopen.
     ((file-remote-p buffer-file-name)
      (kill-file-associated-buffer-and-reopen-file))
     ;; If not remote, just revert
     (t (revert-buffer))))
```
