### ISSUE TITLE
Image relief feature is broken

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#164]
When I select text by pressing and holding the left mouse button, it seems like the PDF was being zoomed a bit.  See the linked screencast.

As soon as I click somewhere into the PDF after selecting text, the zoom level will switch back to normal.

http://videobin.org/+azg/edg.html

**Comment by politza** [comment]
(setq pdf-view-image-relief 0)

This feature is currently broken. The :relief property increases the
image's size as per image-size, which leads to a zooming effect
everytime the page is re-rendered.

But more dramatically it causes heavy tearing issues when
e.g. isearching (at least under X11).

**Comment by tsdh** [comment]
Indeed, that's the cause.  But isearching doesn't work at all for me right now, no matter if with or without reliefs.  I get no matches no matter for what I search.  But that's a separate issue.

**Comment by parmegv** [comment]
If I change the fontsize via set-default-font, then even (setq pdf-view-image-relief 0) does not work. I have to leave the default-font untouched for that trick to work.

**Comment by politza** [comment]
I don't see how this could be related.  Are you talking about tearing or the image getting larger ?

It could be a caching issue, try `(pdf-cache-clear-images)`.

**Comment by parmegv** [comment]
(pdf-cache-clear-images) does not help. 

The image gets larger, as I move the mouse. Exactly like in the video of the first message, but more quickly.
