### ISSUE TITLE
Change default value of pdf-view-resize-factor

### ISSUE THREAD

**Issue by LordZorgoth** [politza/pdf-tools#167]
On most pdf viewers (including evince), zoom by a factor of 10%, not 25%, on a zoom in/zoom out command. They probably did this after some research. A 25% resize factor doesn't give the user fine-grained control, and I certainly found it frustrating enough to change the variable. Of course, any user can customize the variable, but it's better to have good defaults.

**Comment by politza** [comment]
Show me the research and I'll change it accordingly.
