### ISSUE TITLE
Mark activated/mark set on click makes it hard to interact with LaTeX documents

### ISSUE THREAD

**Issue by LordZorgoth** [politza/pdf-tools#168]
When viewing a document made with lualatex/pdflatex, it can be difficult to follow synctex or click on the equation links.

Double clicking to follow synctex can be difficult because if you click somewhere and activate the mark, double clicking has no effect: you would have to triple click, and if you don't do that fast enough, you may end up having to click many times.

For hyperref links, the area you have to click on is pretty small, and it's complicated by the fact that if you click in the area surrounding it, you become unable to follow the link, requiring you to press C-g or click several times in order to follow the link.

These features should be tuned so that they don't care about accidental clicks resulting in "Mark Activated".

**Comment by LordZorgoth** [comment]
I'm attaching a file and its code so you can play around and experience the issue.
[mytest.pdf](https://github.com/politza/pdf-tools/files/67982/mytest.pdf)

    \documentclass{article}
    \usepackage[hidelinks=1]{hyperref}
    \usepackage{amsmath}
    \begin{document}

    \begin{equation}
    1+1=2\label{mylabel}
    \end{equation}

    Let's go to page 2 now.

    \newpage

    By \eqref{mylabel}, we have that

    \begin{equation}
    \textrm{Pdf-tools is awesome!}
    \end{equation}

    \end{document}

**Comment by politza** [comment]
I'm sorry, but I don't understand the problem.  Why does a single click activate the mark ?  You may want to use `C-mouse1` instead of double-clicking.

**Comment by LordZorgoth** [comment]
I don't know why a single click activates the mark, but it sometimes does, though it seems to depend on where you click. I can't tell you why; the only thing I can say is that the message that's associated with double clicking being messed up is "Mark Activated."

C-mouse1 instead of double clicking solves my problem in practice.
