### ISSUE TITLE
Select texts using keyboard

### ISSUE THREAD

**Issue by dsdshcym** [politza/pdf-tools#169]
I was using Chrome with cVim earlier and thought if we can select texts using
keyboard?

In cVim, I can select texts in a web page like this:
1. search the beginning of the texts I want to select
2. using `w` to select until word's end, `$` to select til line's end, etc.
3. using `y` to copy the selected region

Can we do this in pdf-tools?

**Comment by liuzy** [comment]
An alternate method maybe: using the "Mouse Key".

**Comment by jajpater** [comment]
I'd certainly would like to see this happen. I guess @peterbecich would also like this, for he asked [this question on stackexchange](https://emacs.stackexchange.com/questions/13715/mark-text-with-keyboard-in-pdfview-pdf-tools-mode). I haven't tried out the comment @stardiviner gives to make some custom keybindings to `mouse-xx`.

**Comment by slk500** [comment]
Can I make donation to someone to make this function?

**Comment by oantolin** [comment]
Here's the UI I'd like for keyboard text selection. You'd start by using isearch until you move to the beginning of the text you want to select. Then, as in regular isearch, I'd like to be able to use C-w to add the following word to the search term. Finally, I'd like some keybinding to exit isearch and leave the current match as the text selection. That would be a dream! And I think it would be very Emacsy, and relatively simple (no need to implement cursors for example).

**Comment by dalanicolai** [comment]
[pdf-avy-highlight.el}(https://github.com/dalanicolai/dala-emacs-lisp) provides a way to highlight with the keyboard using avy. The more characters you type the faster it works.

**Comment by jloow** [comment]
> [pdf-avy-highlight.el](https://github.com/dalanicolai/dala-emacs-lisp) provides a way to highlight with the keyboard using avy. The more characters you type the faster it works.

Would it be possible to use the same method to select a region? I'm very new to Emacs and elisp but maybe setting `pdf-view-active-region` could work?
