### ISSUE TITLE
make from melpa: No rule to make target 'lisp/*.el'

### ISSUE THREAD

**Issue by mihaiolteanu** [politza/pdf-tools#171]
When calling `make -s` from `~/.emacs.d/elpa/pdf-tools-0.70/build` after the package is installed from melpa I get the following error:

```make: *** No rule to make target `lisp/*.el', needed by `pdf-tools-0.70.tar'.  Stop.```

**Possible problem**: The `build` folder only contains the `Makefile` and the `server` folder after installing from melpa, but the original project, as cloned from github, has other stuff in it.
**Possible solution**: I've manually copied the `lisp` folder with all the `*.el` files in it and the `README` and `README.org` files into the `build` folder. `make -s` didn't complain as a result.

I don't know how the melpa package is built/submitted, but it seems it doesn't have all the necessary ingredients. `epdfinfo` was not build after installing from `melpa`, that's why I've tried the manual install.

**Comment by politza** [comment]
You can't use the Makefile in the melpa archive for (almost) anything
else, but compiling the c-sources via the target melpa-package .

Either install from melpa or create a package via make from git sources
and install that.
