### ISSUE TITLE
caching not working

### ISSUE THREAD

**Issue by vapniks** [politza/pdf-tools#173]
pdf-tools has created a directory at /tmp/pdf-tools-14802XjT but it is not putting anything in there, and pdf files need to be rendered each time I revisit them. 

Also it would be nice to be able to specify the cache directory to somewhere other than /tmp so that cache files are persistent across reboots.

**Comment by politza** [comment]
Images are cached in Lisp strings. This directory holds a possible local
copy of a remote file and file attachments.  The file-name is
constructed via temporary-file-directory.

**Comment by vapniks** [comment]
feature request: persistent pdf-file caching, with configurable cache directory (as in doc-view).

**Comment by politza** [comment]
vapniks <notifications@github.com> writes:

> feature request: persistent pdf-file caching, with configurable cache
> directory (as in doc-view).

Are you talking about downloaded remote files ?

**Comment by vapniks** [comment]
No, all files. `temporary-file-directory` gets emptied on reboot. Some pdf files are slow to load, so a cached version would be nice.
