### ISSUE TITLE
OS X compile documentation up to date?

### ISSUE THREAD

**Issue by myrjola** [politza/pdf-tools#178]
I managed to compile epdfinfo on OS X using `pdf-tools-install` without setting `PKG_CONFIG_PATH`. Before I used to have this snippet in my dotfiles:

```
(when (eq system-type 'darwin)
  (setenv "PKG_CONFIG_PATH"
          "/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig"))
(pdf-tools-install))
```

I was reviewing https://github.com/syl20bnr/spacemacs/pull/4627 and noticed that a similar snippet was missing and decided to try out if it was still necessary. I changed that snippet to only call `pdf-tools-install`. I deleted pdf-tools under my `.emacs.d/elpa`-directory and restarted Emacs, `pdf-tools-install` compiled the tools successfully. If someone else can verify that PKG_CONFIG_PATH is not needed anymore I could post a PR for changing the documentation.

I'm also wondering if this would be a case of letting OS X be officially supported by pdf-tools? Now the readme says:

> Other operating systems are currently not supported (patches welcome).

**Comment by Andre0991** [comment]
I confirm this. I myself tried to not set it when I first installed `pdf-tools` and it worked fine.

**Comment by paynito** [comment]
Interested to get this working on spacemacs and osX, have tried a private layer, can't see the pdf in emacs or in skim, can't take notes in org mode that are synced with the pdf, view all of the highlights from the pdf pulled into org mode. I need a simpler walk through.  I have org and org-ref working, but not pdf-tools.

**Comment by Andre0991** [comment]
@paynito Are you using my layer? (which will be merged soon). If so, do not hesitate to post your installation isssues at https://github.com/syl20bnr/spacemacs/pull/4627
