### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by pseudomyne** [politza/pdf-tools#179]
Hi,
Just tried to upgrade pdf-tools package and got the same issue as https://github.com/politza/pdf-tools/issues/31
I could not resolve things with the instructions in that post. What i don't understand is how to "make the variable pdf-info-epdfinfo-program point to the new epdfinfo executable in the new package directory."
Could you please be more specific ? Thank you.

ps : sorry for the title of this issue :) but i dunno how to change it now

**Comment by politza** [comment]
The easiest way would be to 

1. Delete the `pdf-tools` package.
2. Restart Emacs.
3. Reinstall `pdf-tools`.

**Comment by pseudomyne** [comment]
hi. thanks for your reply. same error: No executable `epdfinfo' found

**Comment by politza** [comment]
Well, does the executable exist ?

**Comment by pseudomyne** [comment]
where should i look for it ? in the pdf-tools directory ? Iit's not there. I also tried $ locate epdfinfo which returned nothing (unix here). is there another package to install ?

**Comment by BotAnihilator** [comment]
I have the same error. (Linux Mint)

**Comment by pseudomyne** [comment]
Pdf-tools reinstalled here with success ! (I needed to close emacs before installing libpoppler libraries)
Long life to pdf-tools :+1:
