### ISSUE TITLE
Remember PDF positions across sessions

### ISSUE THREAD

**Issue by oscarfv** [politza/pdf-tools#18]
For using pdf-tools as a book reader it would be useful to remember the visited files and the position, zoom level...

**Comment by manuel-uberti** [comment]
@oscarfv could you share your solution? I would really like to save the position in the PDF I am reading.

**Comment by alezost** [comment]
Just a related note: there is [org-pdfview](https://github.com/markus1189/org-pdfview/) package.  It also may be used to save a page.

**Comment by Andre0991** [comment]
I second this suggestion, remembering the last page would be tremendously useful.

**Comment by Andre0991** [comment]
Well, I tried this:

``` emacs-lisp
;; TODO: save bookmarks in separate file
(defun andre//pdf-tools--set-bookmark-pdf ()
    (when (eq major-mode 'pdf-view-mode)
      (bookmark-set (andre//pdf-tools--generate-bookmark-name-for-this-buffer))))

(defun andre//pdf-tools--jump-to-last-page-viewed-in-last-session ()
  (when (andre//pdf-tools--buffer-has-bookmark-from-previous-session)
    (bookmark-jump (andre//pdf-tools--generate-bookmark-name-for-this-buffer))))

(defun andre//pdf-tools--buffer-has-bookmark-from-previous-session ()
  (assoc (andre//pdf-tools--generate-bookmark-name-for-this-buffer) bookmark-alist))

(defun andre//pdf-tools--generate-bookmark-name-for-this-buffer ()
  (concat "PDF: "(buffer-file-name)))
```

But it's always saving a bookmark on the first page. I wonder if it has to do with the hook. Maybe when it runs the position on the buffer is lost, I don't know (I don't know much elisp, still learning).

Anyone?

**Comment by Andre0991** [comment]
OK, this is rather ugly, but it works:

``` emacs-lisp
;; --- Save last page viewed in pdf-view-mode ---
;; Ideally we would set this as hook instead of an advice.
;; However, for some reason, if this is done, it sets the bookmark to the first page of the PDF.

(defun andre//pdf-tools--generate-bookmark-name-for-this-buffer ()
  (concat "PDF: " (buffer-file-name)))

(defun andre//pdf-tools--set-bookmark-pdf (&optional arg1)
  (interactive)
  (when (eq major-mode 'pdf-view-mode)
    (bookmark-set (andre//pdf-tools--generate-bookmark-name-for-this-buffer))))

(defun andre//pdf-tools--jump-to-last-page-viewed-in-last-session ()
  (bookmark-maybe-load-default-file)
  (interactive)
  (condition-case err
      (bookmark-jump (andre//pdf-tools--generate-bookmark-name-for-this-buffer))
    (error
     (princ (format "Unable to get to last bookmark. Error: %s" err)))))

(andre/add-to-hook 'pdf-view-mode-hook '(spacemacs//pdf-tools--jump-to-last-page-viewed-in-last-session))
(advice-add 'kill-buffer :before 'andre//pdf-tools--set-bookmark-pdf)
;; --- End save last page viewed in pdf-view-mode ---
```

**Comment by boyanpenkov** [comment]
Can confirm Andre0991's works for me, on vanilla emacs (debian).

**Comment by politza** [comment]
Andre's first solution seems to work/should work, that is after correcting the function names added to the hooks.

**Comment by boyanpenkov** [comment]
What function names need to be changed?

**Comment by braham-snyder** [comment]
```
    ;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
    ;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
    ;; TODO: save bookmarks in separate file

    (defun brds/pdf-set-last-viewed-bookmark ()
      (interactive)
      (when (eq major-mode 'pdf-view-mode)
        (bookmark-set (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-jump-last-viewed-bookmark ()
      (when
          (brds/pdf-has-last-viewed-bookmark)
        (bookmark-jump (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-has-last-viewed-bookmark ()
      (assoc
       (brds/pdf-generate-bookmark-name) bookmark-alist))

    (defun brds/pdf-generate-bookmark-name ()
      (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

    (add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
    (add-hook 'kill-emacs-hook 'brds/pdf-set-last-viewed-bookmark)
    (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
```

**Comment by boyanpenkov** [comment]
Am I missing something here?  This does not touch my ~/.emacs.d/bookmarks after a few restarts -- while the same files under doc-view-mode work well.

**Comment by braham-snyder** [comment]
My bad--I hadn't tested the `kill-emacs-hook` bit well enough (I thought I had a weird `persp-mode`-related bug causing bookmark issues).

No one has mentioned `save-place-mode`?  I've only looked at it briefly, but, e.g., it correctly handles the `kill-emacs-hook` case (see `save-places-to-alist`)--perhaps it just needs to be slightly modified to work with `pdf-view` buffers? At the least, it seems like the perfect reference for this issue. Unfortunately, I can't work on this in the near future.

**Comment by politza** [comment]
I also think this belongs into save-place.  It has already special code
for hexl and dired mode, but I wasn't aware that it works for doc-view
buffers as well.

**Comment by boyanpenkov** [comment]
On a technical note, I'm not claiming that save-place has special code -- I do observe that my combination of save-place and bookmarks works for doc-view (but not pdf-view).

And I'm certainly under-educated here, so someone who knows should speak up.

**Comment by braham-snyder** [comment]
The `kill-emacs-hook` bit finally bothered me enough to attempt to fix it--surprisingly, this has worked perfectly for me the last few days (only changes are the last `defun` and `add-hook` calls):

```
    ;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
    ;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
    (defun brds/pdf-set-last-viewed-bookmark ()
      (interactive)
      (when (eq major-mode 'pdf-view-mode)
        (bookmark-set (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-jump-last-viewed-bookmark ()
      (when
          (brds/pdf-has-last-viewed-bookmark)
        (bookmark-jump (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-has-last-viewed-bookmark ()
      (assoc
       (brds/pdf-generate-bookmark-name) bookmark-alist))

    (defun brds/pdf-generate-bookmark-name ()
      (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

    (defun brds/pdf-set-all-last-viewed-bookmarks ()
      (dolist (buf (buffer-list))
        (with-current-buffer buf
            (brds/pdf-set-last-viewed-bookmark))))

    (add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
    (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
    (unless noninteractive  ; as `save-place-mode' does
      (add-hook 'kill-emacs-hook #'brds/pdf-set-all-last-viewed-bookmarks))
```

@boyanpenkov was something similar to this broken for you?

Tangentially, as noted in https://github.com/politza/pdf-tools/issues/199, my place is still occasionally lost intra-session (though that can be worked-around with a call to `pdf-history-backward`).

**Comment by boyanpenkov** [comment]
After incorporating the change and restarting emacs a few times, no dice, I'm afraid....

**Comment by aijony** [comment]
After restarting emacs, brds/pdf-has-last-viewed-bookmark returned nil unless I initialized the bookmark system so I put in (bokmark-set "fake"). This would only have to be done at the start up of emacs, but I was lazy.

This is what I had to do to get it to work for me.


```
 
    ;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
    ;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
    (defun brds/pdf-set-last-viewed-bookmark ()
      (interactive)
      (when (eq major-mode 'pdf-view-mode)
        (bookmark-set (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-jump-last-viewed-bookmark ()
       (bookmark-set "fake")
      (when
          (brds/pdf-has-last-viewed-bookmark)
        (bookmark-jump (brds/pdf-generate-bookmark-name))))

    (defun brds/pdf-has-last-viewed-bookmark ()
      (assoc
       (brds/pdf-generate-bookmark-name) bookmark-alist))

    (defun brds/pdf-generate-bookmark-name ()
      (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

    (defun brds/pdf-set-all-last-viewed-bookmarks ()
      (dolist (buf (buffer-list))
        (with-current-buffer buf
            (brds/pdf-set-last-viewed-bookmark))))

    (add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
    (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
    (unless noninteractive  ; as `save-place-mode' does
      (add-hook 'kill-emacs-hook #'brds/pdf-set-all-last-viewed-bookmarks))`
```

**Comment by andrewSteer** [comment]
I would just like to subscribe to this request. Saving PDF positions (maybe also zoom?) between sessions would be amazing. It is a bit annoying to have to find exactly where I was last time I checked the pdf, or having to manually set a bookmark just for that purpose (besides re-zooming every single time I open a PDF).

**Comment by braham-snyder** [comment]
You can subscribe to any GitHub issue by clicking the "Subscribe" button at the top of the issue's page on the right hand side.

If you'd just like to express your support of an issue, I (and I suspect other subscribers) would greatly appreciate it if you gave the OP a thumbs up (by clicking the smiley face in its top right corner) instead of making a "+1" post.

(In case you haven't seen it, GitHub's issue tracker can sort issues by the numbers of reactions they've garnered -- ideally, IMO, we'd have explicit issue voting with votes displayed next to the number of comments as in https://github.com/isaacs/github/issues/9 or, e.g., GitLab, but that doesn't look like it will happen in the near future.)

**Comment by caadar** [comment]
(Unusable) variant with records stored in separate file:

```
(require 'bookmark+)

(setq bookmarks-pdf "~/.emacs.d/bookmarks-pdf")

(defun brds/pdf-set-last-viewed-bookmark ()
  (interactive)
  (when (eq major-mode 'pdf-view-mode)
	(bmkp-switch-bookmark-file-create bookmarks-pdf t)
	(bookmark-set (brds/pdf-generate-bookmark-name))
	(bmkp-switch-bookmark-file-create bookmark-default-file t)))

(defun brds/pdf-jump-last-viewed-bookmark ()
  (bmkp-switch-bookmark-file-create bookmarks-pdf t)
  (bookmark-set "PDF-LAST-VIEWED: fake") ; this is new
  (when
	  (brds/pdf-has-last-viewed-bookmark)
	(bookmark-jump (brds/pdf-generate-bookmark-name)))
  (bmkp-switch-bookmark-file-create bookmark-default-file t))

(defun brds/pdf-has-last-viewed-bookmark ()
  (assoc
   (brds/pdf-generate-bookmark-name) bmkp-latest-bookmark-alist))

(defun brds/pdf-generate-bookmark-name ()
  (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

(defun brds/pdf-set-all-last-viewed-bookmarks ()
  (dolist (buf (buffer-list))
	(with-current-buffer buf
	  (brds/pdf-set-last-viewed-bookmark))))

(add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
(add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
(unless noninteractive					; as `save-place-mode' does
  (add-hook 'kill-emacs-hook #'brds/pdf-set-all-last-viewed-bookmarks))
```

It's slow cuz bookmark files savings.

**Comment by agzam** [comment]
What's the update on this issue? Did people give up? I mean it's been hanging around 2014. This and absence of continuous scrolling unfortunately makes pdf-tools quite inconvenient (almost unusable).

**Comment by politza** [comment]
I'm so sorry. I'll immediately get one of my dev-teams working shifts on this important issue.

**Comment by agzam** [comment]
My apologies if my comment makes it look demanding - wasn't my intention. I am genuinely interested, because I have recently re-discovered pdf-tools and even with all the downsides and issues it seems to be the best solution these days for handling pdf in Emacs, especially if you want to use Interleave or Org-noter.

**Comment by politza** [comment]
Never mind.  As for "continuous-view": I don't see that happening, since many, if not all, parts of the software assume a 1:1 relation between pages and windows.

**Comment by ozhap** [comment]
Here's an update to aijony's version without the fake bookmark kludge. Which works for me...
```
;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
(defun brds/pdf-set-last-viewed-bookmark ()
  (interactive)
  (when (eq major-mode 'pdf-view-mode)
    (bookmark-set (brds/pdf-generate-bookmark-name))))

(defun brds/pdf-jump-last-viewed-bookmark ()
  (when
      (brds/pdf-has-last-viewed-bookmark)
    (bookmark-jump (brds/pdf-generate-bookmark-name))))

(defun brds/pdf-has-last-viewed-bookmark ()
  (member (brds/pdf-generate-bookmark-name) (bookmark-all-names)))

(defun brds/pdf-generate-bookmark-name ()
  (concat "PDF-LAST-VIEWED: " (buffer-file-name)))

(defun brds/pdf-set-all-last-viewed-bookmarks ()
  (dolist (buf (buffer-list))
    (with-current-buffer buf
      (brds/pdf-set-last-viewed-bookmark))))

(add-hook 'kill-buffer-hook 'brds/pdf-set-last-viewed-bookmark)
(add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)
(unless noninteractive  ; as `save-place-mode' does
  (add-hook 'kill-emacs-hook #'brds/pdf-set-all-last-viewed-bookmarks)))
`
```

**Comment by AloisJanicek** [comment]
I would just like to point out that if you decide to restore last position in mode hook like this
` (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)` and you will try to open `org-pdfview` or `org-pdftools` link pointing to specific page, those two things will collide and you will end up with two pdf buffers: one showing linked location and the other one showing restored location.

Best way to use both `org-pdfview` links to pages and `brds/*` functions is to make convenient key binding in` pdf-view-mode-map` for `brds/pdf-jump-last-viewed-bookmark` and restore last position only if you really need it.

**Comment by nhmacuk** [comment]
https://github.com/politza/pdf-tools/issues/18#issuecomment-532175227 ah sadly this didn't work for me. Does it still work for you?

**Comment by ozhap** [comment]
> I would just like to point out that if you decide to restore last position in mode hook like this
> ` (add-hook 'pdf-view-mode-hook 'brds/pdf-jump-last-viewed-bookmark)` and you will try to open `org-pdfview` or `org-pdftools` link pointing to specific page, those two things will collide and you will end up with two pdf buffers: one showing linked location and the other one showing restored location.

I'm trying out `org-pdftools` and that particular problem can be solved by wrapping the call to `bookmark-jump` like this: `(save-window-excursion (bookmark-jump (brds/pdf-generate-bookmark-name)))`. I guess this also seems to make it work properly with commands such as `find-file-other-window`, though I don't know of any side-effects (the form comes with a usage warning).

**Comment by nicolaisingh** [comment]
Hi, here's a package I wrote ([saveplace-pdf-view](https://github.com/nicolaisingh/saveplace-pdf-view.)) that implements this functionality with the help of `save-place-mode`.  It's also now available in MELPA.  I've been using it for quite a while, and so far it works for my setup.
