### ISSUE TITLE
epdfinfo keeps running after shutting down emacs server

### ISSUE THREAD

**Issue by gdkrmr** [politza/pdf-tools#181]
On Ubuntu, when I run emacs as a server, open a pdf on a network drive and shut down the server with `M-x kill-emacs` before killing the buffer with the pdf, the `epdfinfo` keeps running and i cannot unmount the drive.

**Comment by politza** [comment]
`kill-emacs` should terminate all of it's child processes, including `epdfinfo`.  I don't know what's going on. What is the PPID of the `epdfinfo` process after Emacs is terminated ? As a workaround, you could try to add `pdf-info-quit` to `kill-emacs-hook`.
