### ISSUE TITLE
pdf-annot-add-markup-annotation with ivy-mode on not working as expected

### ISSUE THREAD

**Issue by ardpp** [politza/pdf-tools#182]
When I mark some text in a pdf file and call 
`pdf-annot-add-markup-annotation` then completing read in the minibuffer is activated and one can choose between ‘squiggly’, ‘underline’, ‘strike-out’ or ‘highlight’.

When ivy-mode is activated then it does not work as expected ivy's analogue of completing read 
finds no candidates. The issue seems to be that as @abo-abo says: "... that `pdf-annot-add-markup-annotation` does not conform to the API standard in its use of compelting-read. See [https://github.com/abo-abo/swiper/issues/375](https://github.com/abo-abo/swiper/issues/375)

Edit: correct link!

**Comment by kaushalmodi** [comment]
https://github.com/abo-abo/swiper/issues/375

**Comment by politza** [comment]
6b7b10a746695e22ef9aa7d29de20c05e71c7e75
