### ISSUE TITLE
failed to kill emacs

### ISSUE THREAD

**Issue by adouzzy** [politza/pdf-tools#183]
Emacs won't shutdown properly.
It showed" Removing directory: Directory not empty, /var/folders/tl/x......./T/pdf-tools-3206eSx."

Any ideas?

**Comment by politza** [comment]
Enable debugging and post a backtrace, please.

**Comment by adouzzy** [comment]
Should I look at the message buffer? Here is what it shows after I opened a pdf file and run kill-emacs:
Toggled debugging on
Quit
Prefetched page 10.
Prefetched page 8.
Prefetched page 11.
Prefetched page 7.
Prefetched page 12.
Prefetched page 6.
Prefetching done.
Prefetched page 13.
Prefetched page 5.
Prefetched page 14.
Prefetched page 4.
Prefetched page 15.
Prefetched page 3.
Prefetched page 16.
Prefetched page 2.
Prefetched page 17.
Prefetched page 1.
Prefetched page 32.
Prefetched page 27.
Prefetching done.
delete-directory: Removing directory: Directory not empty, /var/folders/tl/x0x1lt7x4n75_s6yj5ybf4xm0000gn/T/pdf-tools-3274RBc
Qui
