### ISSUE TITLE
select non-text rectangle with mouse

### ISSUE THREAD

**Issue by rdiaz02** [politza/pdf-tools#184]
I suspect the answer is that it is not possible but here is the question anyway: is it possible to select an area where there is no text just with the mouse? This would help to copy just images or pieces of images (i.e., select then C-c TAB).

**Comment by politza** [comment]
Yes, by using `M-mouse-1`.

**Comment by rdiaz02** [comment]
Thanks! What I cannot figure out  is how to save the selected region to the kill ring (clipboard) directly, so I can then paste/insert that into other programs. `C-c TAB` (`pdf-view-extract-region-image`) leaves the selected image region in a buffer (which I could save, etc), but I cannot find anything like `M-w` that will work with the image.

**Comment by politza** [comment]
You want to copy the image's data or what ?

**Comment by rdiaz02** [comment]
I want to copy the image itself; the selected rectangle actually, which might be an image with its caption, etc, but copy it as an image, so I can "paste" it into something else.

**Comment by politza** [comment]
I am not familiar with the APIs of inter-program exchange of data via
the clipboard, but I think Emacs would have to mark the contents of it
as beeing of type image. I don't know if thats possible. Maybe you want
to repeat this question on stackexchange.

**Comment by rdiaz02** [comment]
Thanks. Asked question in Emacs StackExchange: http://emacs.stackexchange.com/q/26418/13050
