### ISSUE TITLE
pdf-view-bookmark-jump-handler not working with BookmarksPlus

### ISSUE THREAD

**Issue by vapniks** [politza/pdf-tools#185]
I get the following error and backtrace when I use the default bookmark handler (`pdf-view-bookmark-jump-handler`) with [BookmarksPlus](https://www.emacswiki.org/emacs/BookmarkPlus). 
It works fine if I use `pdf-view-bookmark-jump`, but I have to edit each pdf bookmark separately to set this.
Note: the backtrace below was obtained when I did a bookmark jump from the `*Bookmark List*` buffer, but I get the same error whichever buffer I start from.

```
Debugger entered--Lisp error: (error "Buffer is not associated with any file :*Bookmark List*")
  signal(error ("Buffer is not associated with any file :*Bookmark List*"))
  error("Buffer is not associated with any file :%s" "*Bookmark List*")
  pdf-info--normalize-file-or-buffer(nil)
  pdf-info-number-of-pages()
  pdf-cache-number-of-pages()
  pdf-view-goto-page(130)
  pdf-view-bookmark-after-jump-hook()
  run-hooks(bookmark-after-jump-hook)
  byte-code(BLAHBLAH)
  bookmark--jump-via(BLAH BLAH)
  bmkp-jump-1(BLAH BLAH)
  bookmark-bmenu-this-window(nil)
  call-interactively(bookmark-bmenu-this-window nil nil)
  command-execute(bookmark-bmenu-this-window)
```

**Comment by politza** [comment]
The handler in bm+ is broken.
