### ISSUE TITLE
auto-refresh of pdf buffer after LaTeX

### ISSUE THREAD

**Issue by DrWaleedAYousef** [politza/pdf-tools#187]
I think we had solved this issue before; however, after I updated emacs yesterday this issue re-appeared. When both the tex and the pdf are opened in emacs, re-compiling the LaTeX buffer does not auto-refresh the pdf buffer. My .emacs (that was already working very well) is:

(require 'subr-x)
(defun th/pdf-view-revert-buffer-maybe (file)
  (when-let ((buf (find-buffer-visiting file)))
    (with-current-buffer buf
      (when (derived-mode-p 'pdf-view-mode)
        (pdf-view-revert-buffer nil t)))))
(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
          #'th/pdf-view-revert-buffer-maybe)

**Comment by tmalsburg** [comment]
Why not use auto-revert mode in the buffer showing the PDF.  I think I tried this once and it worked well.

**Comment by wyousef** [comment]
It reverts but the pdf goes to another page than the current. You have
to C-c C-g on the tex file.

What I wonder for is that it was working well until I just updated emacs!!

**Comment by adouzzy** [comment]
I use latexmk. Latexmk monitors tex file changes and recompile when its changed. After compile, it triggered the pdf_previewer linked to a custom latex function. The function could be (pdf-sync-forward-search)

In the .latexmk:
$pdf_previewer="emacsclient -e '(my-pdf-sync)'";
$pdflatex='pdflatex %O -interaction=nonstopmode %S';

;; The following add latexmk to C-c C-c in auctex for the file change monitoring
    (add-to-list 'TeX-command-list '("latexmk" "latexmk -pdf -pvc %t" TeX-run-TeX))

**Comment by et2010** [comment]
@adouzzy Thanks for the nice solution.

**Comment by DrWaleedAYousef** [comment]
I emailed AUCTEX authors, and surprisingly it appeared to be a
bug. Thanks to them, they fixed the bug and now the recent version of
AUCTEX on Elpa is bug-free. You have just to include the following line
in your .emacs and it everything works great.

(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)

**Comment by et2010** [comment]
@DrWaleedAYousef Thanks for the heads up.

**Comment by gyps** [comment]
@adouzzy In your post you mention a custom lisp function to revert and sync the pdf buffer. Would you mind to give an example of the function that works for you?

Thanks a lot,
Alex
