### ISSUE TITLE
Does not build with OpenBSD make

### ISSUE THREAD

**Issue by jockej** [politza/pdf-tools#188]
Hi, first thanks for this totally awesome package.

It seems GNU Make is required. I'm on OpenBSD, so when I ran M-x pdf-tools-install it tried to run the command 'make melpa-build' (pretty much), which failed because OpenBSD make doens't understand GNU make syntax.

I solved it bu going to the pdf-tools directory and running 'gmake melpa-build' manually, which worked fine.

So maybe there should be a check for whether 'make' is actually GNU make, and if it isn't try to find 'gmake'. It seems there is an autoconf macro to do this [here](http://www.gnu.org/software/autoconf-archive/ax_check_gnu_make.html).

Thanks again!

**Comment by Jehops** [comment]
See pull request #170.

**Comment by politza** [comment]
Seems to be fixed.
