### ISSUE TITLE
pdf-tools hangs when viewing pdf files

### ISSUE THREAD

**Issue by kirk86** [politza/pdf-tools#193]
Dear all,
I am facing some difficulties with pdf-tools rendering a 9.1M pdf file whereas with a smaller one pager pdf it works fine.
So far I've tried the following suggestions from @jockej to disable line numbering but for me unfortunately it didn't work out.

This is what I have in my `~/.emacs.d/init.el` for the pdf-tools setup.

`(pdf-tools-install)`
`(setq TeX-view-program-selection '((output-pdf "PDF Tools"))`
              `TeX-source-correlate-start-server t)`

`(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook`
          `#'TeX-revert-document-buffer)`

Since I am new in the world of emacs maybe I've srewed something up in the process. But it is bizzare that with a smaller one page pdf file it works fine, not so good though in the case of the bigger 9.1M continuous pdf file. It simply hangs even in the first page, and unfortunately I am unable to scroll down to consecutive pages.

**Comment by xuhdev** [comment]
Does doc-view-mode hang?

**Comment by kirk86** [comment]
@xuhdev hi, when I visit the file with `C+x` `C+f` and it opens in emacs, down in the status bar it says PDFView and then it hangs, I cannot scroll down or use `M+x` in order to change the mode or to verifyg if I am in doc-view-mode. But from some online seaches it seems that whenever you visit a pdf file from inside emacs it automatically goes to doc-view-mode. Any ideas? Thanks!

**Comment by xuhdev** [comment]
If you follow the README `pdf-tools-install` the behavior changes: emacs uses pdf-view-mode instead of the builtin one.

**Comment by kirk86** [comment]
@xuhdev so I disabled completely the `pdf-tools` and tried once again to visit the pdf file this time using `doc-view-mode` but the same behaviour was observed where emacs hangs and you can't even scroll over the pdf file. Do you have any idea how to resolve this issue?

**Comment by xuhdev** [comment]
Have you tried to disable linum-mode? You may want to delete parts of your emacs config and see which line is the culprit.

**Comment by kirk86** [comment]
@xuhdev yeah I have `linum-mode` disabled. What I am not sure is if both `pdf-tools` and `doc-view` hang in case you had some warnings at the time that you produced your pdf when you for instance compiled it. I am saying this because I have noticed this behaviour only with this particular pdf. When I try other pdfs `doc-view` works even with `linum-mode` on, of course it is slow but it works. But that shouldn't be the case or is it possible?

**Comment by xuhdev** [comment]
I really don't know... You have to figure out what configuration is the culprit. `pdf-tools` works great for me: it never hangs nor be super slow.

**Comment by kirk86** [comment]
@xuhdev ok man thanks!
