### ISSUE TITLE
LilyPond PDF links don't work (special URIs cases)

### ISSUE THREAD

**Issue by rrmdev** [politza/pdf-tools#194]
The problem manifests itself in LilyPond PDFs in particular, but is a more generic problem.

LilyPond includes backlinks to the file that should allow for a Point-and-Click edition, sending the user from the compiled PDF file to the point in the source where the feature is defined. It's SyncTeX-à-la-LilyPond.

When the P&C option is activated, LilyPond concocts special URIs for all the features of interest in the final music sheet. These come in the form of a "textedit://" uri. (More specifically: textedit:///path-to-file:[line number]:[page number]:[column number]).

LilyPond intends for these URIs to be sent to a helper application (i.e. lilypond-invoke-editor).

For xpdf, the helper application can be invoked via the configuration file (xpdfrc) with the following:
`urlCommand     "lilypond-invoke-editor %s"`

Is there an analogue way to do the same in pdf-tools?

And, more generic, how does one go about to define non-classical URIs? How does one go about telling pdf-tools what application to use to open said URIs?

Thank you.

**Comment by politza** [comment]
`pdf-links-browse-uri-function`
