### ISSUE TITLE
can not install in arch linux

### ISSUE THREAD

**Issue by cryoguy** [politza/pdf-tools#195]
I can  not seem install it in arch linux?  got following error:

emacs -Q --batch --eval \
	"(progn (package-initialize) \
		(package-install-file \
			\"pdf-tools-0.70.tar\"))"
Parsing tar file...
Parsing tar file...done
Package `let-alist-1.0.1' is unavailable
Makefile:55: recipe for target 'install-package' failed
make: *** [install-package] Error 255

Any advise?

Thanks.

Tony

**Comment by alezost** [comment]
You can install `let-alist` library from GNU ELPA

**Comment by cryoguy** [comment]
Thanks for the help,  Alex.  I installed it.  I cannot seem to activate with (pdf-tools-install).  I add(require 'pdf-tools) but emacs opens pdf in doc view.   Any advice? Sorry for these newbie questions.

Tony

**Comment by alezost** [comment]
`pdf-tools-install` should modify `auto-mode-alist` variable.
Could you check that you have the following value in this alist:
``("\\.[pP][dD][fF]\\'" . pdf-view-mode)``

Also check the value of `pdf-info-epdfinfo-program` variable.

**Comment by cryoguy** [comment]
Thanks for your assistance, alezosf.  I got it working with let-alist-1.0.1 and post some notes [here](http://tech.memoryimprintstudio.com/pdf-annotation-related-tools/).  Hope it will help someone.
