### ISSUE TITLE
How to save/open password encrypted pdf files?

### ISSUE THREAD

**Issue by LukeSwart** [politza/pdf-tools#197]
First, I want to say thanks so much for this package! It has really improved my experience when viewing pdf files.

There doesn't seem to be any support for password-protected files. It seems that Gmail has support for this as well as the Adobe's tools, so I don't think the protocol is proprietary. Although I wouldn't be surprised if it was :-P 

When trying to open such a file, we get the following messages:

> File mode specification error: (error "epdfinfo: Error opening /home/me/Downloads/my-password-protected-file.pdf:Document is encrypted")
> pdf-info-query: epdfinfo: Error opening /home/me/Downloads/my-password-protected-file.pdf:Document is encryptedError during redisplay: (eval (number-to-string (pdf-view-current-page))) signaled (wrong-type-argument numberp nil)
> Error during redisplay: (eval (number-to-string (pdf-cache-number-of-pages))) signaled (error "epdfinfo: Error opening /home/me/Downloads/my-password-protected-file.pdf:Document is encrypted")

I think this feature would be very nice to have, especially when someone sends you a password-protected file. I'm not exactly sure how to implement it though - any tips to get started would be great!

**Comment by LukeSwart** [comment]
It looks like there are numerous commandline tools that can do this here: http://www.cyberciti.biz/faq/removing-password-from-pdf-on-linux/

I'm not sure what dependencies we can expect to be installed, but if one of these is already bundled with this package, then we can just prompt the user to enter their password and trigger the appropriate command from there. Or perhaps there is a Lisp package that can be used for the encryption/decription instead...

**Comment by politza** [comment]
If you look at the function pdf-info-open, you'll see, that it already
has a password argument.  Though I've never tested it.

The error you mentioned could be caught and, if appropriate, the user be
queried for a password.

**Comment by politza** [comment]
Should work now.
