### ISSUE TITLE
Remember pdf position *within* sessions

### ISSUE THREAD

**Issue by plantarum** [politza/pdf-tools#199]
I find my position in a pdf often reverts to page 1 within a session (i.e., not like #18, the request to store positions _between_ sessions). For instance, I navigate to page 77 in a pdf, switch windows to work on a text file, and later switch back to the pdf buffer. Sometimes it's still at page 77, but often it is back to page 1. 

I haven't figured out how to reproduce this consistently. Is this a known issue, or have I broken something in my config?

Thanks,

Tyler

**Comment by politza** [comment]
#18

**Comment by plantarum** [comment]
#18 is a different issue, as I noted in my first post. I'm asking about losing my page **within** a session, #18 is asking for page numbers to be remembered **between** sessions.

**Comment by politza** [comment]
Yeah...,sorry.

**Comment by lihebi** [comment]
This occurs so often, hope to see the fix soon ..

**Comment by lihebi** [comment]
I can consistently reproduce it:

1. Create two perspective
2. open a pdf file in one of them.
3. Go to page 2 of the file.
4. Switch to the other perspective, and switch back. 

it will reset to page 1.

Here's part of the track when I instrument the `pdf-view-goto-page` function:

```
  pdf-view-goto-page(1)
  pdf-view-new-window-function
  run-hook-with-args(pdf-view-new-window-function
  image-mode-winprops(nil t)
  image-mode-reapply-winprops()
  switch-to-buffer(#<buffer pgf.pdf>)
  persp-reactivate-buffers
  persp-activate([cl-struct-perspective
  persp-switch(nil)
  call-interactively(persp-switch nil nil)
  command-execute(persp-switch)
```

And here's where the hook is bind:

```elisp
(define-derived-mode pdf-view-mode special-mode "PDFView"
  ;; .... a lot of code ....
  ;; Keep track of display info
  (add-hook 'image-mode-new-window-functions
            'pdf-view-new-window-function nil t)
```

It seems perspective active the buffer again, the `image-mode-winprops` is called, and `image-mode-new-window-functions` hooks are triggered, which triggers `pdf-view-new-window-function`. and that function will call the `pdf-view-goto-page` with argument 1

**Comment by politza** [comment]
Yes, that's to be expected.  See #232.
@plantarum Are you using some layout package as well ?

**Comment by plantarum** [comment]
Not exactly - ace-window-mode, zygospore, winner-mode. I'll take a closer look at those, and anything similar I can dig out of my .emacs.

**Comment by politza** [comment]
Seems to be #232.
