### ISSUE TITLE
Cant navigate to other buffers from PDF buffer

### ISSUE THREAD

**Issue by peterwvj** [politza/pdf-tools#200]
I'm experiencing problems when I try to navigate to other buffers from the PDF buffer. I have the following key bindings defined to navigate between buffers:

```
(global-set-key (kbd "C-x <up>") 'windmove-up)
(global-set-key (kbd "C-x <down>") 'windmove-down)
(global-set-key (kbd "C-x <right>") 'windmove-right)
(global-set-key (kbd "C-x <left>") 'windmove-left)
```

When I try to use one of these shortcuts to navigate from the PDF buffer to another buffer I can't. Instead I get the following error:

```
Wrong type argument: wholenump, -209
```

Any input on what could be wrong would be appreciated.

**Comment by peterwvj** [comment]
I should say that this problem is a bit of "glow worm" so it's hard to re-produce. I will try to add more information if I find a better way to re-produce it.

**Comment by justbur** [comment]
I'm running into the same thing. I debugged it for a little bit and this call sometimes fails in the pdf buffer

```elisp
(posn-at-point (point) (selected-window))
```

I tried to reproduce with `emacs -Q` and basic doc-view-mode but haven't been able to reproduce the error. 

My emacs version is 25.1.1 from the Fedora repos. 

I will look again when I have some more time.

**Comment by politza** [comment]
Scrolling to the bottom of a page and evaluating 
 
(null (posn-at-point (point-max) (selected-window)))

signals an error for me (at this moment).  Probably nothing I can do it
about, as the error happens inside a Emacs subr.

**Comment by justbur** [comment]
Looking a little further, it appears to be a bug in `posn-at-point`, which appears to fail if the point is not visible. The strange thing is I still can't reproduce this with `emacs -Q`. I tried with a pdf file that is not fit to the buffer size and with a large image. It seems that the error occurs in pdf-tools whenever the page is scrolled at least once.

**Comment by politza** [comment]
So, does the erroneous call to posn appear in the pdf tools code ?

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Justin Burkett <notifications@github.com> </div><div>Datum:26.10.2016  19:55  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Cant navigate to other buffers from PDF
  buffer (#200) </div><div>
</div>Looking a little further, it appears to be a bug in posn-at-point, which appears to fail if the point is not visible. The strange thing is I still can't reproduce this with emacs -Q. I tried with a pdf file that is not fit to the buffer size and with a large image. It seems that the error occurs in pdf-tools whenever the page is scrolled at least once.

**Comment by justbur** [comment]
No, it doesn't as far as I'm aware, but it's part of the window switching code in emacs. I'm confident it's an emacs bug, but I haven't been able to reproduce it yet from a simple starting state.

**Comment by politza** [comment]
I made a bug-report : http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24804

Turned out I was just getting in line.

**Comment by justbur** [comment]
Thank you @politza
