### ISSUE TITLE
The pdf display keeps blinking in pdf-view-mode if evil-mode is enabled, even in its Emacs mode

### ISSUE THREAD

**Issue by xuhdev** [politza/pdf-tools#201]
Even if I disable evil-mode, it continues blinking for a few seconds.
I'm not sure why... maybe you can give some hints?

**Comment by politza** [comment]
What blinks ? The image or a cursor around the image ?

**Comment by xuhdev** [comment]
The image

**Comment by xuhdev** [comment]
It turns out that if the cursor blinks and the pdf image was zoomed in, you see the whole pdf image blinking. If anyone has the same issue, call `(blink-cursor-mode -1)` in `pdf-view-mode-hook`.

**Comment by xuhdev** [comment]
Here is a better solution to deal the conflict with `evil-mode`:

```elisp
(add-hook__ 'pdf-view-mode-hook
  (lambda ()
    (set (make-local-variable 'evil-emacs-state-cursor) (list nil))))
```

**Comment by smalltimer** [comment]
Thanks for replying so quickly! I tried it but got this error
`Error (use-package): evil/:init: Symbol’s function definition is void: evil-set-initial-state`
