### ISSUE TITLE
Display page labels in the mode-line

### ISSUE THREAD

**Issue by xuhdev** [politza/pdf-tools#204]
Is there any way to display the page number, such as ([current page]/[total page])? I would also love to see that the actual page number in the pdf file is displayed, which is not necessarily order of the page, e.g., some pdf files have their table of contents numbered by roman numbers. Note that these features are available in evince, which in turn should be available in poppler.

**Comment by xuhdev** [comment]
Maybe displaying it in the modeline is a good idea:

    PDFView [iii/3/100]

The numbers in the brackets are: page number defined in the PDF file/the real page number/total page number.

**Comment by deb0ch** [comment]
Hi guys,

As I need the page numbers for my current task, this particular issue is starting to really bother me.

So if anyone has any indication or hint to give about where to start looking to implement that it would be gladly welcomed ! :hammer: 

Cheers.

**Comment by politza** [comment]
(define-pdf-cache-function pagelabels)

	(add-hook 'pdf-view-mode-hook
		  (lambda ()
		    (setq-local mode-line-position
				'(" ["
				  (:eval (nth (1- (pdf-view-current-page))
					      (pdf-cache-pagelabels)))
				  "/"
				  (:eval (number-to-string (pdf-view-current-page)))
				  "/"
				  (:eval (number-to-string (pdf-cache-number-of-pages)))
				  "]"))))

**Comment by deb0ch** [comment]
Thanks so much ! I didn't think it would be so simple.

I'm using [spacemacs](http://spacemacs.org) (in which your package got integrated into develop very recently), so modifying the modeline does not work the way you showed.

If it can be useful to anyone, here is my quick-and-crappy version of that quickfix:

```elisp
    (define-pdf-cache-function pagelabels)

    (defun pdf-view-page-number ()
        (interactive)
        (message " [%s/%s/%s]"
            (nth (1- (pdf-view-current-page))
                (pdf-cache-pagelabels))
            (number-to-string (pdf-view-current-page))
            (number-to-string (pdf-cache-number-of-pages))))
```

to be called interactively (ie. with M-x).

**Comment by deb0ch** [comment]
Just two quick questions:

- If it is that short and simple, how come it is not already a part of pdf-tools ?

- I do not really understand the `(define-pdf-cache-function pagelabels)` and `(nth (1- (pdf-view-current-page)) (pdf-cache-pagelabels))` parts, what do they do ?

Anyways, I'm using pdf-tools everyday as my main pdf reader so thank you very much for that amazing package :smiley:

**Comment by politza** [comment]
Thomas de Beauchêne <notifications@github.com> writes:

> * I do not really understand the (define-pdf-cache-function pagelabels) and (nth (1- (pdf-view-current-page)) (pdf-cache-pagelabels)) parts, what do they do ?

I think you can figure it out.
