### ISSUE TITLE
Symbol's function definition is void: pdf-occur-global-minor-mode

### ISSUE THREAD

**Issue by ReichKV** [politza/pdf-tools#206]
Hey, i again get this error and cannot solve the problem. (Last time i just reinstall the package Issue#72. ) In my init file i have (require 'pdf-tools). If i have in the init file the line (pdf-tools-install) i get:

Warning (initialization): An error occurred while loading `/home/ReichKV/.emacs.d/init.el':

Symbol's function definition is void: pdf-occur-global-minor-mode

Without the line i successfully load the emacs, execute (pdf-tools-install) in the scratch buffer and pdf-tools works fine.

Please, could you help me to solve the problem.

**Comment by politza** [comment]
Is there a package-initialize before the call to pdf-tools-install in
your init.el ?

-ap

**Comment by ReichKV** [comment]
I am not sure what are you talking about. I have in my init file following lines:

(require 'pdf-tools)
(pdf-tools-install)

I also can add (package-initialize 'pdf-tools) between these two lines but nothing changes.

**Comment by politza** [comment]
Try to put (package-initialize) at the very top.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: ReichKV <notifications@github.com> </div><div>Datum:03.05.2016  15:09  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Symbol's function definition is void:
  pdf-occur-global-minor-mode (#206) </div><div>
</div>I am not sure what are you talking about. I have in my init file following lines:

(require 'pdf-tools)
(pdf-tools-install)

I also can add (package-initialize 'pdf-tools) between these two lines but nothing changes.

**Comment by ReichKV** [comment]
Thanks. It is working again

**Comment by deb0ch** [comment]
Hi,

I am having this issue as well but this fix does not seem to work for me.

When using pdf-tools I can view pdf files just fine but searching words seems broken with isearch and occur (will only search the binary without highlighting anything).

When running `pdf-tools-install` I get `progn: Symbol's function definition is void: pdf-occur-global-minor-mode`.

I suspect that it might be related.

What is broken in my installation is the question.

I installed from source (branch master, commit 87690b7) on Ubuntu 16.04 using

```shell
make install-server-deps
make -s
```

added the pdf-tools-0.70 to my load-path my init file looks like this:

```elisp

(package-initialize 'pdf-tools)
(require 'pdf-tools)
(pdf-tools-install)
```

**Comment by adouzzy** [comment]
I had the same problem on Mac.
Adding package-initialize doesn't help either.
I ended up defun a dummy function called pdf-occur-global-minor-mode with one argument.

**Comment by politza** [comment]
(package-initialize 'pdf-tools)

This won't work, just use

  (package-initialize)

**Comment by amosbird** [comment]
I'm seeing the same error.
```
(use-package pdf-tools
  :mode (("\\.pdf\\'" . pdf-view-mode))
  :config
  (pdf-tools-install))
```

**Comment by CarlsonP4** [comment]
Isn't the problem that `pdf-tools.el` should have
`(require 'pdf-occur)` at or around line 89?

Otherwise users of the pdf-tools (via `(require 'pdf-tools)`) will need to remember to also add `(require 'pdf-occur)` manually before calling `(pdf-tools-install)`

**Comment by acowley** [comment]
If one doesn't want to use `package-initialize`, then adding these to the beginning of a `:config` section of a `use-package` form as @amosbird showed addresses the warnings:

````
  (use-package pdf-occur
    :commands (pdf-occur-global-minor-mode))
  (use-package pdf-history
    :commands (pdf-history-minor-mode))
  (use-package pdf-links
    :commands (pdf-links-minor-mode))
  (use-package pdf-outline
    :commands (pdf-outline-minor-mode))
  (use-package pdf-annot
    :commands (pdf-annot-minor-mode))
  (use-package pdf-sync
    :commands (pdf-sync-minor-mode))
````
