### ISSUE TITLE
Easier to add text annotations

### ISSUE THREAD

**Issue by mickesv** [politza/pdf-tools#208]
Most of the time I use text annotations. I have already rebound `pdf-annot-add-text-annotation` to a shorter key sequence, but I still have to click once to place the annotation, and once more to open it. Creatively borrowing from other parts of pdf-tools, I now invoke the following function instead:

``` lisp
	    (defun msv-annot-add-and-edit-text-annotation ()
	      (interactive)
	      (let* ((pos (posn-object-x-y (pdf-util-read-image-position "Click to position a new text annotation...")))
		     (a (and pos (pdf-annot-add-text-annotation pos))))
		(if a
		    (pdf-annot-edit-contents a))))
```
which saves me one click. I CBA to do a proper pull request, but since this fits my workflow better, I thought I'd share.

**Comment by politza** [comment]
See `pdf-annot-activate-created-annotations'.

**Comment by mickesv** [comment]
Ahem. There's that, of course. :CaughtWithMyPantsDown:

**Comment by politza** [comment]
Don't worry, nothing I haven't seen.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Mikael Svahnberg <notifications@github.com> </div><div>Datum:11.05.2016  10:14  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,State change <state_change@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Easier to add text annotations (#208) </div><div>
</div>Ahem. There's that, of course. :CaughtWithMyPantsDown:
