### ISSUE TITLE
Suggestion - open edit annotation window after highlighting selection

### ISSUE THREAD

**Issue by benmaughan** [politza/pdf-tools#209]
First, thanks for the great tool!

Usually when I highlight some selected text with `C-c C-a h` I also want to add some text to the annotation, which I then do by clicking on the newly highlighted region. Would it be possible to have the edit annotation window open automatically following the `C-c C-a h` command? Perhaps this could be an extra annotation option to add highlight plus a note instead of changing the behaviour of the existing highlight command.

**Comment by mickesv** [comment]
Ooh. I know this one: set the `pdf-annot-activate-created-annotations` variable to `t`. (See #208)

**Comment by benmaughan** [comment]
Brilliant - thanks!
