### ISSUE TITLE
invalid-function pdf-view-current-page ?

### ISSUE THREAD

**Issue by hexa00** [politza/pdf-tools#210]
Hi,
  Using interleave with pdf-tools when trying to insert a new note I get this backtrace:

Debugger entered--Lisp error: (invalid-function pdf-view-current-page)
  pdf-view-current-page()
  #[nil "\300 \207" [pdf-view-current-page] 1]()
  interleave-add-note()
  call-interactively(interleave-add-note nil nil)
  command-execute(interleave-add-note)

On:
GNU Emacs 24.4.1
pdf-tools-20160525.920
interleave-20160517.948

Any ideas?

Thanks,

**Comment by politza** [comment]
hexa00 <notifications@github.com> writes:

> Debugger entered--Lisp error: (invalid-function pdf-view-current-page)

pdf-view-current-page is a macro, not a function, but it seems to be
used as such.  Please take this up with the interleave author.
