### ISSUE TITLE
pdf-tools C-c C-c not working on osx 10.11

### ISSUE THREAD

**Issue by kirk86** [politza/pdf-tools#211]
Hi everyone,
I am facing a problem when I want to view pdf documents using the `C-c C-c` command on osx 10.11.

Currently my config for pdf-tools is as follows:

`(package-initialize)`
`(pdf-tools-install)`
`(eval-after-load 'org '(require 'org-pdfview))`
`(setq TeX-view-program-selection '((output-pdf "PDF Tools"))`
      `TeX-source-correlate-start-server t)`

`;; Update PDF buffers after successful LaTeX runs`
`(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook`
          `#'TeX-revert-document-buffer)`

`(provide 'init-pdf-tools)`

and I always get the following output: `Unknown "PDF Tools" viewer. Check the 'TeX-view-program-selection' variable.`

But I have to mention that the above config works perfectly on linux without any problems.

Am I missing something? Does anyone has the same problem?

By the way if I change `(setq TeX-view-program-selection '((output-pdf "PDF Tools"))` to `(setq TeX-view-program-selection '((output-pdf "Open"))` I can display pdfs in Preview.app. But, that's not what I want, I would like to open directly pdfs with pdf-tools.

Another thing that I noticed is that if I visit any pdf file via emacs with `C-c C-f` then the pdf opens in DocView without problem and I can even use the annotation tools from pdf-tools. However, when I am writing a .tex file and using `C-c -C-c view` pdf then I always get the message `Unknown "PDF Tools" viewer. Check the 'TeX-view-program-selection' variable.`

Any help would be appreciated?

**Comment by benquebec** [comment]
In case you still have that problem, I have it working with the caveat I'm using the latest emacs-railwaycat with spacemacs. See the second line:

;; pdfview and auctex
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
      TeX-source-correlate-start-server t) 

;; refresh buffer
(add-hook 'TeX-after-compilation-finished-functions
          #'TeX-revert-document-buffer) 


HTH.

**Comment by kirk86** [comment]
@benquebec you're awesome. Saved my day, especially the second line.
Thanks a bunch.
