### ISSUE TITLE
Build fails with Makefile:75: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by toupeira** [politza/pdf-tools#212]
This is on Debian unstable:

```
$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
[..]
$ make
Makefile:75: *** missing separator.  Stop.
```

If I comment out [lines 75-76](https://github.com/politza/pdf-tools/blob/87690b7b568ae6145dfa4ffc9fc085b80ed039fa/Makefile#L75-L76) the build completes and `pdf-tools` seems to be working fine in Emacs.

**Comment by politza** [comment]
I guess its not a problem anymore.

**Comment by toupeira** [comment]
I still had the same issue, but after giving it another look I realized it was my faulty `emacs` wrapper script, which caused `EMACS_VERSION` to be unset, which caused the make syntax error :)
