### ISSUE TITLE
Error when using windmove

### ISSUE THREAD

**Issue by llvilanova** [politza/pdf-tools#214]
To reproduce:
* Open a PDF on a separate window on the same frame.
* Select that window.
* Scroll a but down the first page of the PDF.
* Use ``windmove`` to move from the ``pdf-view-mode`` buffer to the first one.

With these steps, I get this backtrace:
<pre>
Debugger entered--Lisp error: (wrong-type-argument wholenump -14)
  posn-at-point(619194 #<window 6 on codoms-bubbles.pdf>)
  (nth 2 (posn-at-point (window-point window) window))
  (let ((posn-cons (nth 2 (posn-at-point (window-point window) window)))) (if hor (+ (or (cdr posn-cons) 1) (window-pixel-top window)) (+ (or (car posn-cons) 1) (window-pixel-left window))))
  (cond ((and (numberp sign) (< sign 0)) (if hor (1- (+ (window-pixel-top window) (window-pixel-height window))) (1- (+ (window-pixel-left window) (window-pixel-width window))))) ((and (numberp sign) (> sign 0)) (if hor (window-pixel-top window) (window-pixel-left window))) ((let ((posn-cons (nth 2 (posn-at-point (window-point window) window)))) (if hor (+ (or (cdr posn-cons) 1) (window-pixel-top window)) (+ (or (car posn-cons) 1) (window-pixel-left window))))))
  (let* ((frame (window-frame window)) (hor (memq direction (quote (left right)))) (first (if hor (window-pixel-left window) (window-pixel-top window))) (last (+ first (window-size window hor t))) (posn (cond ((and (numberp sign) (< sign 0)) (if hor (1- (+ ... ...)) (1- (+ ... ...)))) ((and (numberp sign) (> sign 0)) (if hor (window-pixel-top window) (window-pixel-left window))) ((let ((posn-cons ...)) (if hor (+ ... ...) (+ ... ...)))))) (best-edge (cond ((eq direction (quote below)) (frame-pixel-height frame)) ((eq direction (quote right)) (frame-pixel-width frame)) (t -1))) (best-edge-2 best-edge) (best-diff-2 (if hor (frame-pixel-height frame) (frame-pixel-width frame))) best best-2 best-diff-2-new) (walk-window-tree (function (lambda (w) (let* ((w-top (window-pixel-top w)) (w-left (window-pixel-left w))) (cond ((or ... ...)) (hor (cond ... ...)) ((and ... ...) (if ... ...)) ((and ... ... ...) (setq best-edge-2 w-top) (setq best-diff-2 best-diff-2-new) (setq best-2 w)))))) frame nil (and mini t)) (or best best-2))
  window-in-direction(left nil nil nil nil t)
  windmove-find-other-window(left nil nil)
  windmove-do-window-select(left nil)
  windmove-left(nil)
  #<subr call-interactively>(windmove-left nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> windmove-left nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (windmove-left nil nil))
  call-interactively(windmove-left nil nil)
  command-execute(windmove-left)
</pre>

The problem does not arise if I do not scroll the PDF buffer, where the argument to ``posn-at-point`` is 1.

I'm using Debian's emacs package (24.5.1).

Thanks,
  Lluis

**Comment by politza** [comment]
Looks like a Emacs bug to me, since window-point should never be less
than 1 (-14 in your case).

**Comment by llvilanova** [comment]
Actually, the top line of the backtrace shows a positive argument to ``posn-at-point`` (the result of ``window-point``), but then errors out with a negative.

Could it be that pdf-tools is producing so large buffer positions that they're somehow overflowing inside emacs?

**Comment by politza** [comment]
Lluís <notifications@github.com> writes:

> Could it be that pdf-tools is producing so large buffer positions that
> they're somehow overflowing inside emacs?

I don't think so.

**Comment by llvilanova** [comment]
I've just opened bug 23809 in emacs. Feel free to close the issue; I'll update it if an emacs bug is ruled out.

**Comment by politza** [comment]
Thank you.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Lluís <notifications@github.com> </div><div>Datum:20.06.2016  19:07  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Error when using windmove (#214) </div><div>
</div>I've just opened bug 23809 in emacs. Feel free to close the issue; I'll update it if an emacs bug is ruled out.
