### ISSUE TITLE
Build fails on OSX because uname -o is not supported

### ISSUE THREAD

**Issue by ury-marshak** [politza/pdf-tools#216]
The automatic build of melpa package on OSX El Capitan fails, because OSX's uname does not support the -o option. Manually removing the relevant lines from Makefile (the check for Msys) allows the build to succeed.

**Comment by politza** [comment]
Ury Marshak <notifications@github.com> writes:

> The automatic build of melpa package on OSX El Capitan fails, because OSX's uname does not support the -o option. Manually removing the relevant lines from Makefile (the check for Msys) allows the build to succeed. 

Does this work for you ?

diff -u --label /home/politza/src/pdf-tools/Makefile --label \#\<buffer\ Makefile\> /home/politza/src/pdf-tools/Makefile /tmp/buffer-content-13501dL
--- /home/politza/src/pdf-tools/Makefile
+++ #<buffer Makefile>
@@ -88,7 +88,7 @@
 
 melpa-build: server/epdfinfo
 	-cp -p server/epdfinfo ..
-	@if [ "$(shell uname -o)" = "Msys" ]; then \
+	-@if [ "$(shell uname -o)" = "Msys" ]; then \
 		for f in $(shell ldd server/epdfinfo | awk '/mingw/ {print $$3}'); do \
 			cp $$f ..; \
 		done; \

Diff finished.  Fri Jun 24 00:15:13 2016

**Comment by ury-marshak** [comment]
Yes, this allows the build to succeed, although it seems that it still runs
'uname -o' somewhere (in server/Makefile maybe?) and complains about
missing ldd:

feline:build ury$ make V=0 -kC
'/Users/ury/.emacs.d/elpa/pdf-tools-20160525.920/build'  melpa-build
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C server
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       epdfinfo-epdfinfo.o
epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is
provided
      for compatibility reasons only. Due to security concerns inherent in
the
      design of tempnam(3), it is highly recommended that you use mkstemp(3)
      instead. [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");
                  ^
/usr/include/stdio.h:391:7: note: 'tempnam' has been explicitly marked
      deprecated here
char    *tempnam(const char *, const char *) __DARWIN_ALIAS(tempnam);
         ^
1 warning generated.
  CXX      epdfinfo-poppler-hack.o
In file included from poppler-hack.cc:18:
In file included from /opt/local/include/poppler/Annot.h:42:
In file included from /opt/local/include/poppler/Object.h:42:
/opt/local/include/poppler/goo/GooString.h:179:12: warning: private field
'c' is
      not used [-Wunused-private-field]
      char c[sizeof(char*)];
           ^
/opt/local/include/poppler/goo/GooString.h:180:11: warning: private field
'i' is
      not used [-Wunused-private-field]
      int i;
          ^
/opt/local/include/poppler/goo/GooString.h:181:13: warning: private field
's' is
      not used [-Wunused-private-field]
      char* s;
            ^
3 warnings generated.
  CXXLD    epdfinfo
*uname: illegal option -- o*
*usage: uname [-amnprsv]*
*/bin/sh: ldd: command not found*
cp -p server/epdfinfo ..
/Applications/Xcode.app/Contents/Developer/usr/bin/make distclean
rm -rf -- pdf-tools-0.70
rm -f -- pdf-tools-0.70.tar
rm -f -- lisp/*.elc
! [ -f server/Makefile ] ||
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C server clean
test -z "epdfinfo" || rm -f epdfinfo
test -z "libsynctex.a" || rm -f libsynctex.a
rm -f *.o
rm -rf .cask
! [ -f server/Makefile ] ||
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C server distclean
test -z "epdfinfo" || rm -f epdfinfo
test -z "libsynctex.a" || rm -f libsynctex.a
rm -f *.o
rm -f *.tab.c
test -z "" || rm -f
test . = "." || test -z "" || rm -f
rm -f config.h stamp-h1
rm -rf -- Makefile.in aclocal.m4 config.h.in configure depcomp install-sh
missing autom4te.cache epdfinfo-0.70.tar.gz
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
rm -f config.status config.cache config.log configure.lineno
config.status.lineno
rm -rf ./.deps
rm -f Makefile
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Server successfully build.
~~~~~~~~~~~~~~~~~~~~~~~~~~~



(I have some weird issue now that I can't make the build succeed from
within emacs anymore, it fails at 'configure' stage. I had to go to the
shell and rerun ./autogen.sh and ./configure manually. That most probably
is a problem with my configuration though.)
In the end my build process looked something like this:

$ sudo port install poppler  # I use macports, not homebrew
$ export
PKG_CONFIG_PATH=/opt/local/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
$ cd ~/.emacs.d/elpa/pdf-tools-20160525.920/build/server
$ ./autogen.sh
$ ./configure
$ cd ..
$ make V=0 -kC '/Users/ury/.emacs.d/elpa/pdf-tools-20160525.920/build'
 melpa-build


After this everything seems to work.
Thank you,
Ury

**Comment by analyticd** [comment]
As a workaround, check out the (Joe's) solution to install on OS X here: https://emacs.stackexchange.com/questions/13314/install-pdf-tools-on-emacs-macosx

**Comment by politza** [comment]
Is this still relevant ?

**Comment by analyticd** [comment]
Hi, I don't think it is relevant any longer, or, at least I have
pdf-tools installed and working correctly on OS X. I overcame problems
on OSX via the following:

;;; c.f. https://emacs.stackexchange.com/questions/13314/install-pdf-tools-on-emacs-macosx
;;; Install epdfinfo via 'brew install pdf-tools' and then install the
;;; pdf-tools elisp via the use-package below. To upgrade the epdfinfo
;;; server, just do 'brew upgrade pdf-tools' prior to upgrading to newest
;;; pdf-tools package using Emacs package system. If things get messed
;;; up, just do 'brew uninstall pdf-tools', wipe out the elpa
;;; pdf-tools package and reinstall both as at the start.
(use-package pdf-tools
  :ensure t
  :after org
  :config
  (setq pdf-tools-handle-upgrades nil) ; Use brew upgrade pdf-tools instead.
  (setq pdf-info-epdfinfo-program "/usr/local/bin/epdfinfo")
  ;; org-pdfview config
  ;; NOTE auto-mode-alist already has pdf's set to open with
  ;; pdf-view-mode.
  (use-package org-pdfview
    :ensure t
    :config
   (setq org-file-apps
     (quote
      ((auto-mode . emacs)
       ("\\.mm\\'" . default)
       ("\\.x?html?\\'" . default))))
   (add-to-list 'org-file-apps
                '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))
   ;; As of org 9.0, this doesn't work anymore:
    ;; (add-to-list 'org-file-apps
    ;;              '("\\.pdf::\\([[:digit:]]+\\)\\'" .
    ;;                (lambda (file link) (org-pdfview-open link))))
    ))
(pdf-tools-install)

**Comment by politza** [comment]
No `uname -o` anymore.
