### ISSUE TITLE
midnight mode uses the unavailable 'crescent moon' unicode symbol U+1F319 in the mode line

### ISSUE THREAD

**Issue by sixpointzero** [politza/pdf-tools#219]
The 'crescent moon' Unicode symbol u+1f319 isn't available in the monospaced font that I use. It's also not available in the dejavu sans mono font which is recommended for it's Unicode support. As a result, the Emacs mode line shows an ugly Unicode symbol. Could you remove it or replace it with something else?

**Comment by politza** [comment]
9696abb82e427670b8283599365a234ddaa170b4
I hope this works.
