### ISSUE TITLE
docview:foo.pdf::25 fails after pdf-tools-install in org-mode

### ISSUE THREAD

**Issue by madjestic** [politza/pdf-tools#221]
when attempting an equivalent of 

`docview:foo.pdf::25`
after
`after pdf-tools-install`
I am getting:
`
doc-view-goto-page: Wrong type argument: stringp, nil
Error running timer 'pdf-cache--prefetch-start': (error "epdfinfo: No such page 0") [2 times]
`
error.  

In other words, I can not open a pdf at a given page as normally done with docview:foo.pdf:25 after running pdf-tools-install in org-mode.

Regards,
Vlad

**Comment by politza** [comment]
The problem lies with org-docview-open (not PDF Tools): It opens the PDF
file using org-open and expects this function to set-up doc-view-mode in
it's buffer. This assertion fails and the following call to
doc-view-goto-page in a pdf-view-mode buffer causes this error.

**Comment by madjestic** [comment]
Thanks, politza.  

I wonder what would be the best course of action on this... I do like pdf-tools, but I also like a way to open a pdf on a specific page.

**Comment by politza** [comment]
There is a package org-pdfview.

**Comment by politza** [comment]
Or try something like the following.

    (with-eval-after-load 'org-docview
      (defun org-docview-open (link)
        (string-match "\\(.*?\\)\\(?:::\\([0-9]+\\)\\)?$" link)
        (let ((path (match-string 1 link))
              (page (and (match-beginning 2)
                         (string-to-number (match-string 2 link)))))
          ;; Let Org mode open the file (in-emacs = 1) to ensure
          ;; org-link-frame-setup is respected.
          (org-open-file path 1)
          (unless (derived-mode-p 'doc-view-mode)
            (doc-view-mode))
          (when page (doc-view-goto-page page)))))
