### ISSUE TITLE
Make PDF bookmarks modifiable

### ISSUE THREAD

**Issue by QiangF** [politza/pdf-tools#224]
Hello everyone,
Bookmarks are essential for large pdf files, if it is not possible to create bookmarks, what is the alternative?
Thank you!

**Comment by politza** [comment]
You can create Emacs bookmarks and jump to them as usual, though these
are global and not local to one buffer.

If you are using desktop.el and your PDF is restored by it, you can

    (add-to-list 'desktop-locals-to-save 'pdf-view-register-alist)

and then use <m X> and <' X> to mark a position and go back to it.

If that doesn't work for you, you can try, or ask someone, to implement
persistent buffer-local variables.

**Comment by QiangF** [comment]
Perhaps what I mean is the outline, which is saved in the pdf file and can be opened in other pdf reader such as Adobe pdf reader. Some people don't use emacs to view pdf files, and buffer local variables is not portable either. Is there another alternative?
Thank you!

**Comment by politza** [comment]
Try o.

**Comment by QiangF** [comment]
I can view the outline, I mean the bookmarks I created in adobe pdf reader, but I can't find a command to create an outline heading (bookmarks in adobe reader). The outline buffer is readonly, does that mean the outline (bookmarks) can't be edited?
Thank you!

**Comment by politza** [comment]
No, it can't be edited. 

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: QiangF <notifications@github.com> </div><div>Datum:12.08.2016  4:33  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Persistent bookmarks (#224) </div><div>
</div>I can view the outline, I mean the bookmarks I created in adobe pdf reader, but I can't find a command to create an outline heading (bookmarks in adobe reader). The outline buffer is readonly, does that mean the outline (bookmarks) can't be edited?
Thank you!

**Comment by politza** [comment]
I don't see the ability to do this in any relevant frontend of poppler and it has no priority for me, so I'm closing this for the time being.

**Comment by QiangF** [comment]
I have just found a script that uses pdftk to modify bookmarks:
https://github.com/SiddharthPant/booky
Would be nice if we can:
1. extract bookmarks when opening a pdf file and save the content in a temperary buffer.
2. modify the content and the outline as user modifies the bookmarks.
3. use pdftk to merge the bookmarks when file is closed.
