### ISSUE TITLE
PDF file opens but the buffer stays blank

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#226]
Hi,

I am trying to use the [`interleave`](https://github.com/rudolfochrist/interleave) package along with `pdf-tools`. But at times, the pdf opens with a blank page. No error is generated. So I cannot get a debug backtrace.

The buffer basically looks like this:

![image](https://cloud.githubusercontent.com/assets/3578197/17861832/9d802656-6860-11e6-8d46-29c443891546.png)

It seems to have opened the PDF, and got the correct page count and all, but it is not displaying the PDF. How can I help debug this?
- The next/previous page navigation also works fine.
- Refreshing the buffer does not help.

Would it be possible for you to review the code in there that uses the `pdf-view` functions/macro?

---

I am using a build of emacs master branch built today ( [aed22ca](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=aed22ca32344c21c5868a451d1afe969642a3ba5) ).

**Comment by kaushalmodi** [comment]
More observation:

- Doing a `C-x C-f` of that PDF file works fine
- The `interleave` package interacts with the pdf using `pdf-view-next-page` and `pdf-view-previous-page` commands.. should `pdf-view-next-page-command` and `pdf-view-previous-page-command` be used instead?
- After multiple attempts (20+, probably), somehow the pdf opened via interleave package fine (did not show that blank page), and I had changed nothing! Without any error when that blank page is shown, I do not know where to start the debug.. and equally so, I have no idea why it started working again. I will not be surprised if the same blank page issue happens if I try to close and reopen that pdf file.

**Comment by politza** [comment]
Looks to me like the scrolling in that window is off, i.e. you can observe this effect by setting an obscene vscoll value with `(image-set-window-vscroll 9999)`. These kinds of display-issues are sometimes hard to debug.  Things you could try/questions you could ask:

* Does it make a difference whether the PDF is already loaded in Emacs
* Inspect the window-vscroll value
* Edebug the interleave code which displays the buffer

The pdf-view-[next|previous]-page-command are for interactive use, so this OK.

**Comment by kaushalmodi** [comment]
> Looks to me like the scrolling in that window is off, i.e. you can observe this effect by setting an obscene vscoll value with (image-set-window-vscroll 9999). 

Well, that froze my emacs! :P 

> Does it make a difference whether the PDF is already loaded in Emacs

I saw difference between the case when I already had the pdf open and the case where I allowed `interleave.el` to open the pdf file. But I couldn't see a consistent pattern.

> Inspect the window-vscroll value

I will do so next time this happens. In that case, would it be possible to *ceil* that value to a sensible value?

> Edebug the interleave code which displays the buffer

Will do that next time.

> The pdf-view-[next|previous]-page-command are for interactive use, so this OK.

OK, thanks. That's what I read from the doc-strings too. I was just going through all the differences in the pdf file interaction when interacting directly vs via `interleave`.

**Comment by politza** [comment]
I was a little unclear: It would just be enough to scroll the page out of the window, no obscene value needed.

**Comment by kaushalmodi** [comment]
> Inspect the window-vscroll value

At first it returned 7. Then I randomly tried the default bindings: `n`, `p`, `C-v`, `M-v`, etc. and now `window-vscroll` is returning 0. The buffer is still blank.

Tried `revert-buffer`, still blank.

> Edebug the interleave code which displays the buffer

The `interleave-pdf-mode` was on when this happened. Now I have turned it off, and still I cannot recover out of the blank pdf state. So not sure what to edebug in this case.

**Comment by kaushalmodi** [comment]
I finally found a workaround to get out of that blank buffer issue.. by trying to search something in the pdf using `C-s`. Does that possibly give a hint as to what's causing this?

**Comment by politza** [comment]
I still think this is a scrolling issue.  See what

(cons (image-mode-window-get 'vscroll)
      (image-mode-window-get 'hscroll))

gives in the blank pdf buffer.

**Comment by kaushalmodi** [comment]
I haven't yet been to recreate this problem. Could my earlier version of the code to scroll pdf in other window ( https://github.com/politza/pdf-tools/issues/227#issue-172741331 ) cause this issue?

**Comment by politza** [comment]
I don't think so.
