### ISSUE TITLE
Sluggish when trying to scroll pdf to previous line from another window

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#227]
Hi,

I have this wrapper function that helps me with pdf note taking with a frame split into 2 windows; one window shows the pdf, other window is an org-mode buffer.

## Issue

With point in the non-pdf buffer,

- `modi/scroll-other-window-down` is sluggish
  - `modi/scroll-other-window-down` ends up calling `pdf-view-previous-line-or-previous-page`
  - But if I `edebug` `pdf-view-previous-line-or-previous-page`, the sluggishness goes away!
  - `profiler-start` -> recreate sluggishness -> `profiler-report` does not seem to reveal anything obvious (screenshot below).
  - The sluggishness is not seen when *previous page* is executed at page boundaries instead of *previous line*.
- `modi/scroll-other-window-up` works fine in all circumstances.

**Profiler report after `modi/scroll-other-window-down` (sluggish case)**

![image](https://cloud.githubusercontent.com/assets/3578197/17899558/af550562-6929-11e6-954c-a8a097ad7a70.png)

**Profiler report after `modi/scroll-other-window-up` (good case)**

![image](https://cloud.githubusercontent.com/assets/3578197/17899647/fd27737e-6929-11e6-992c-56b54583f6e4.png)

```el
(defun modi/scroll-other-window (&optional num-lines)
  "Scroll the buffer in other window.

This command supports pdf file buffers too (`pdf-view-mode').

If NUM-LINES is positive, scroll to the next line or next page.
If NUM-LINES is negative, scroll to the previous line or previous page."
  (interactive "p")
  (let (is-other-window-disp-pdf)
    (with-selected-window (other-window-for-scrolling)
      (when (setq is-other-window-disp-pdf (derived-mode-p 'pdf-view-mode))
        (if (>= num-lines 1)
            (pdf-view-next-line-or-next-page num-lines)
          (pdf-view-previous-line-or-previous-page (- num-lines)))))
    (when (not is-other-window-disp-pdf)
      (scroll-other-window num-lines))))

(defalias 'modi/scroll-other-window-up 'modi/scroll-other-window)

(defun modi/scroll-other-window-down (ln)
  "Scroll other window down by LN lines without moving the point.
If LN is nil, defaults to 1 line."
  (interactive "p")
  (modi/scroll-other-window (- ln)))

(global-set-key (kbd "<C-M-left>") #modi/scroll-other-window-down)
(global-set-key (kbd "<C-M-right>") #modi/scroll-other-window-up)
```

On the other hand, if I manually switch to the pdf window and then call `pdf-view-previous-line-or-previous-page` or `pdf-view-next-line-or-next-page`, then I see no sluggishness.

---
Emacs version:
> Emacs version: GNU Emacs 25.1.50.35 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23)
 of 2016-08-22, built using commit c325e199668a2449a9b0d662e114eec9d4802288.

> ./configure options:
  --with-modules --prefix=/home/kmodi/usr_local/apps/6/emacs/master 'CPPFLAGS=-fgnu89-inline -I/home/kmodi/usr_local/6/include -I/usr/include/freetype2 -I/usr/include' 'CFLAGS=-ggdb3 -O0' 'CXXFLAGS=-ggdb3 -O0' 'LDFLAGS=-L/home/kmodi/usr_local/6/lib -L/home/kmodi/usr_local/6/lib64 -ggdb3' PKG_CONFIG_PATH=/home/kmodi/usr_local/6/lib/pkgconfig:/home/kmodi/usr_local/6/lib64/pkgconfig:/cad/adi/apps/gnu/linux/x86_64/6/lib/pkgconfig:/cad/adi/apps/gnu/linux/x86_64/6/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:/lib/pkgconfig:/lib64/pkgconfig

> Features:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 MODULES

**Comment by politza** [comment]
Do you mean by sluggish, that the page sometimes does not appear to move if you execute your command once ?

**Comment by kaushalmodi** [comment]
No, the page eventually moves .. But if the page was supposed to scroll by 1 line, it takes roughly 5-6 seconds to do so (not exaggerating, and the proflier report doesn't even show that). And if I am at a page boundary, the response is instantaneous. Again, this applies to only `pdf-view-previous-line-or-previous-page`.  

The "next" counterpart of this function works perfectly fine, whether scrolling by a line or page.

**Comment by kaushalmodi** [comment]
> Again, this applies to only `pdf-view-previous-line-or-previous-page`.

And of course, that is **only** when calling that function from the wrapper function `modi/scroll-other-window` with my point being in the window other than the one showing the pdf.

As I said earlier, calling `pdf-view-previous-line-or-previous-page` directly in the pdf buffer works fine.

## Summary

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides" align="center" class="table-striped">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Point</th>
<th scope="col" class="org-left">Function</th>
<th scope="col" class="org-left">At page boundary</th>
<th scope="col" class="org-left">Good/Bad</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">in pdf win</td>
<td class="org-left">next line/page</td>
<td class="org-left">Yes</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">in pdf win</td>
<td class="org-left">next line/page</td>
<td class="org-left">No</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">in pdf win</td>
<td class="org-left">previous line/page</td>
<td class="org-left">Yes</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">in pdf win</td>
<td class="org-left">previous line/page</td>
<td class="org-left">No</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">outside pdf win</td>
<td class="org-left">next line/page (in with-selected-window wrapper)</td>
<td class="org-left">Yes</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">outside pdf win</td>
<td class="org-left">next line/page (in with-selected-window wrapper)</td>
<td class="org-left">No</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">outside pdf win</td>
<td class="org-left">previous line/page (in with-selected-window wrapper)</td>
<td class="org-left">Yes</td>
<td class="org-left">Good</td>
</tr>

<tr>
<td class="org-left">outside pdf win</td>
<td class="org-left">previous line/page (in with-selected-window wrapper)</td>
<td class="org-left">No</td>
<td class="org-left"><b>Bad</b></td>
</tr>
</tbody>
</table>

**Comment by politza** [comment]
Yes, I got that.  I can remember, that in some tests I made, scrolling sometimes was, as you described it, sluggish.  But that usually involved multiple images in one window.  Anyway, try if it works with the following version of your function.

```el
(defun modi/scroll-other-window (&optional num-lines)
  (interactive "p")
  (let* ((window (other-window-for-scrolling)))
    (if (pdf-util-pdf-window-p window)
        (with-current-buffer (window-buffer window)
          (with-selected-window window
            (if (>= num-lines 1)
                (pdf-view-next-line-or-next-page num-lines)
              (pdf-view-previous-line-or-previous-page (- num-lines))))
          (set-window-point window (point)))
      (scroll-other-window num-lines))))
```

**Comment by kaushalmodi** [comment]
> try if it works with the following version of your function.

Awesome! That worked! 

Why did that work? And why need that just for the previous line/page fn?

I hit `W` to fit the pdf by width so that I can scroll by line (instead of by page). That worked for about 3-4 line scroll executions and then I was hit with the blank pdf issue all of a sudden ( https://github.com/politza/pdf-tools/issues/226 ).

Let me know (continuing to that other issue thread), what debug info I can provide for that.

`(window-vscroll)` returns 7.

**Comment by politza** [comment]
I don't know exactly why it works.

Can this be closed ?

**Comment by kaushalmodi** [comment]
> Can this be closed ?

I dislike these mysterious auto-resolving issues. Because they are just reappear as mysteriously as they went away :) In any case, currently pdf-tools is working great for me. So I will close this issue.

Thanks.
