### ISSUE TITLE
Two Column View (follow-mode)

### ISSUE THREAD

**Issue by lihebi** [politza/pdf-tools#228]
Hi, I wonder if a _two column view_ is worth implementing. It enables to display two pages side by side, and scroll every two pages.  A straight forward way is using `follow-mode`, but it does not work out-of-box.
Personally I think this is useful to browse pdfs with large font size, or quickly go through the papers.

**Comment by politza** [comment]
This has been discussed before.

Yes, it would be worth implementing.  But, I'd rather have multiple pages per windows.

**Comment by lihebi** [comment]
Yeah, I agree it is more native to be in the same window. But it should be easier to implement by adapting to follow-mode ...
If you think this is something that is possible, and worth implementing, I'm willing to look into this.
