### ISSUE TITLE
Install pdf-tools on debian 

### ISSUE THREAD

**Issue by pprw** [politza/pdf-tools#229]
Hey,

I would like to install pdf-tools on debian unstable.

I noticed two packages available on debian unstable repositories which seems to provide pdf-tools : `elpa-pdf-tools` and `elpa-pdf-tools-server`.

However, after installing these packages, emacs still open pdfs with docview. I tried to add `(require 'pdf-tools)` in my .emacs without any effect.

What are the necessary steps to install pdf-tools in Debian using apt packages?

**Comment by politza** [comment]
Put `(pdf-tools-install)` in your .emacs as stated on the front page.
