### ISSUE TITLE
Error after upgrading to poppler 0.48.0

### ISSUE THREAD

**Issue by akirakyle** [politza/pdf-tools#230]
Hi,
On Mac OS X the homebrew poppler formula recently upgraded to the new 0.48.0 poppler release and after upgrading I get the following error whenever I try to open any pdf:
`Error (use-package): pdf-tools :config: Wrong type argument: number-or-marker-p, "Trace/BPT trap: 5"`
This is on emacs 25.1 and for now I've reverted my homebrew poppler back to 0.47.0 and everything works fine.

**Comment by politza** [comment]
If you upgrade some library in your system, in a lot of cases programs
linked against become broken.  Easiest way out of this is to reinstall
pdf-tools.

-ap

**Comment by akirakyle** [comment]
That seems to have done the trick, thanks!
