### ISSUE TITLE
Hide password when using sudo

### ISSUE THREAD

**Issue by notetiene** [politza/pdf-tools#234]
When installing with `(pdf-tools-install)`, `sudo apt-get` is used. However, when entering the password in the prompt, characters are shown. Could we simply hide what's written as terminals usually do?

**Comment by politza** [comment]
We are just using standard Emacs stuff here.  Does it hide the password if you evaluate `(compile "sudo false" t)` ?

**Comment by notetiene** [comment]
Yes, it does.

**Comment by politza** [comment]
Reopen, if this is still a problem.
