### ISSUE TITLE
Disabling splitting windows for small displays.

### ISSUE THREAD

**Issue by stdcall** [politza/pdf-tools#236]
My 13" monitor is too small to make it comfortable to view 2 windows at the same time. Can I disable window-splitting for pdf-tools?

**Comment by politza** [comment]
There are multiple variables determining how buffers are displayed, which you find via

    M-x apropos-variable pdf action RET

These are display actions as described in the variable `display-buffer-alist`'s documentation. But there seem to be still places where this is hard-coded.

Anyway, It's probably easier to use a single action for all PDF related buffers like in the following.

    (defun pdf-tools-buffer-p (buffer &rest _)
      (with-current-buffer buffer
        (derived-mode-p 'pdf-view-mode
                        'pdf-outline-buffer-mode
                        'pdf-annot-list-mode
                        ;;... (might not be complete)
                        )))

    (add-to-list 'display-buffer-alist
                 '(pdf-tools-buffer-p (display-buffer-same-window (inhibit-same-window))))


Or try this

    (add-to-list 'display-buffer-alist
                 '("." (display-buffer-same-window (inhibit-same-window))))

in case you want to display everything in one window.

**Comment by usharf** [comment]
How will it work with `pdf-outline-display-buffer-action`? Does it expect a function or a value? I'm only interested in togeling the display of the a PDF and it's outline in the same window.

**Comment by politza** [comment]
It expects a display-buffer-action.  See help for the display-buffer
function, also (info "(elisp) Choosing Window") .

**Comment by usharf** [comment]
I was able to see that links in the outline are controlled here (if I understand correctly), which suggests it's hard coded not to reuse the window where the outline buffer is displayed (the call to `display-buffer`)? 

Also, realized  `imenu` is populated but it's not as usefull as the outline buffer for me.

```emacs-lisp
(defun pdf-outline-get-pdf-window (&optional if-visible-p)
  (save-selected-window
    (let* ((buffer (cond
                    ((buffer-live-p pdf-outline-pdf-document)
                     pdf-outline-pdf-document)
                    ((bufferp pdf-outline-pdf-document)
                     (error "PDF buffer was killed"))
                    (t
                     (or
                      (find-buffer-visiting
                       pdf-outline-pdf-document)
                      (find-file-noselect
                       pdf-outline-pdf-document)))))
           (pdf-window
            (if (and (window-live-p pdf-outline-pdf-window)
                     (eq buffer
                         (window-buffer pdf-outline-pdf-window)))
                pdf-outline-pdf-window
              (or (get-buffer-window buffer)
                  (and (null if-visible-p)
                       (display-buffer
                        buffer
                        '(nil (inhibit-same-window . t))))))))
      (setq pdf-outline-pdf-window pdf-window))))
```

**Comment by politza** [comment]
Yes, you're right.  Opening the document when following a link is
currently hard-coded to not reuse the outline's window.  But you should
still be able to override this via display-buffer-alist, e.g.

(setq display-buffer-alist
      '(("." display-buffer-same-window (inhibit-same-window . nil))))

or something more specific.
