### ISSUE TITLE
melpa

### ISSUE THREAD

**Issue by ReichKV** [politza/pdf-tools#24]
Thank you for this amazing package. Since 0.4 it works fast.

Do you plan to add the pdf-tools in melpa repository?

**Comment by politza** [comment]
Last time I checked, melpa did not support compiling anything other
than lisp files.  I guess a solution could be to include a
precompiled, statically linked binary.

**Comment by politza** [comment]
The way to go seems to be to hook up the build process into the setup
code of the package, like e.g. [irony-mode]
(https://github.com/Sarcasm/irony-mode/blob/master/irony.el#L476) .

**Comment by politza** [comment]
Well, I went ahead and made a pull request.  Let's see how this turns out.

**Comment by politza** [comment]
http://melpa.org/#/pdf-tools

**Comment by ReichKV** [comment]
Thank you.
