### ISSUE TITLE
pdf-tools-sync-view sometimes throws "Invalid image specification: nil"

### ISSUE THREAD

**Issue by antoine-levitt** [politza/pdf-tools#240]
Hi,

I use pdf-tools with auctex
(setq TeX-view-program-selection '((output-pdf "pdf-tools")))
(setq TeX-view-program-list '(("pdf-tools" "TeX-pdf-tools-sync-view")))
and I have synctex on.

Sometimes when I do TeX-command-run-all, I get

Debugger entered--Lisp error: (error "Invalid image specification: nil")
  signal(error ("Invalid image specification: nil"))
  error("Invalid image specification: %s" nil)
  image-display-size(nil t)
  pdf-view-image-size(t)
  pdf-util-required-vscroll((8 833 8 871))
  pdf-util-tooltip-arrow(833)
  pdf-sync-forward-search()
  TeX-pdf-tools-sync-view()
  TeX-run-function("View" "TeX-pdf-tools-sync-view" "paper")
  TeX-run-discard-or-function("View" "TeX-pdf-tools-sync-view" "paper")
  TeX-command("View" TeX-master-file 0)
  TeX-command-sequence(t nil TeX-master-file)
  TeX-command-sequence-sentinel(#<process LaTeX> "finished\n")

This bug appears erratically, and I am not sure what exactly triggers it.

I think the problem is that pdf-tools isn't run in the correct buffer. TeX-pdf-tools-sync-view does not appear to do a (with-current-buffer), shouldn't it do it?

**Comment by politza** [comment]
Are you sure about the missing `with-current-buffer` ? What auctex version do you have installed.  This is how it looks in 11.89.7 :


    (defun TeX-pdf-tools-sync-view ()
      (unless (fboundp 'pdf-tools-install)
        (error "PDF Tools are not available"))
      (unless TeX-PDF-mode
        (error "PDF Tools only work with PDF output"))
      (add-hook 'pdf-sync-backward-redirect-functions
                #'TeX-source-correlate-handle-TeX-region)
      (if (and TeX-source-correlate-mode
               (fboundp 'pdf-sync-forward-search))
          (with-current-buffer (or (when TeX-current-process-region-p
                                     (get-file-buffer (TeX-region-file t)))
                                   (current-buffer))
            (pdf-sync-forward-search))
        (let ((pdf (concat file "." (TeX-output-extension))))
          (pop-to-buffer (or (find-buffer-visiting pdf)
                             (find-file-noselect pdf))))))

**Comment by antoine-levitt** [comment]
I'm not using a region, so that with-current-buffer is a noop. I think
the problem is that pdf-view-image-size expects the current buffer to be
the pdf buffer, but in this case it is the tex buffer. Looking more in
detail, I see that the (with-current-buffer) I was looking for (the one
that sets the current buffer to be the pdf one) is in
pdf-sync-forward-search, not TeX-pdf-tools-sync-view, sorry.

I'm not sure what causes the bug, and I haven't been able to reproduce
it consistently, so I'm posting this report in the hopes it someone will
know what to do with it.

29 November 2016 16:27 +01, politza <notifications@github.com>:
> Are you sure about the missing `with-current-buffer` ? What auctex version do you have installed.  This is how it looks in 11.89.7 :
>
>
>     (defun TeX-pdf-tools-sync-view ()
>       (unless (fboundp 'pdf-tools-install)
>         (error "PDF Tools are not available"))
>       (unless TeX-PDF-mode
>         (error "PDF Tools only work with PDF output"))
>       (add-hook 'pdf-sync-backward-redirect-functions
>                 #'TeX-source-correlate-handle-TeX-region)
>       (if (and TeX-source-correlate-mode
>                (fboundp 'pdf-sync-forward-search))
>           (with-current-buffer (or (when TeX-current-process-region-p
>                                      (get-file-buffer (TeX-region-file t)))
>                                    (current-buffer))
>             (pdf-sync-forward-search))
>         (let ((pdf (concat file "." (TeX-output-extension))))
>           (pop-to-buffer (or (find-buffer-visiting pdf)
>                              (find-file-noselect pdf))))))

**Comment by politza** [comment]
> I'm not using a region, so that with-current-buffer is a noop.

Yes, I wasn't thinking very much when I wrote this remark.

> I think the problem is that pdf-view-image-size expects the current buffer to be the pdf buffer, but in this case it is the tex buffer.

Have you confirmed this or is this just a guess ?  Anyway `pdf-sync-forward-search` displays the PDF  with the following code fragment.

    (with-selected-window (display-buffer
                           buffer pdf-sync-forward-display-action)
      (pdf-util-assert-pdf-window)
      (pdf-view-goto-page page)
      (let ((top (* y1 (cdr (pdf-view-image-size)))))
        (pdf-util-tooltip-arrow (round top))))


As far as I can see, there is no way, the selected-window and current-buffer display resp. contain a buffer which is *not* in pdf-view-mode.  Leading to the conclusion that this code should actually fail sooner then in the pdf-util-tooltip-arrow function.  But, again, I don't see where the window/buffer correlation could change in this code.

Maybe you could try to trace it with something like the following.

    (defun pdf-sync-forward-search (&optional line column)
      "Display the PDF location corresponding to LINE, COLUMN."
      (interactive)
      (cl-labels ((log (n)
                    (message ">>> %d: %s, %s" n (current-buffer) (selected-window))))
        (cl-destructuring-bind (pdf page _x1 y1 _x2 _y2)
            (pdf-sync-forward-correlate line column)
          (let ((buffer (or (find-buffer-visiting pdf)
                            (find-file-noselect pdf))))
            (with-selected-window (display-buffer
                                   buffer pdf-sync-forward-display-action)
              (log 0)
              (pdf-util-assert-pdf-window)
              (log 1)
              (pdf-view-goto-page page)
              (log 2)
              (let ((top (* y1 (cdr (pdf-view-image-size)))))
                (log 3)
                (pdf-util-tooltip-arrow (round top))
                (log 4)))
            (with-current-buffer buffer
              (run-hooks 'pdf-sync-forward-hook))))))



Otherwise this is going to be difficult ...
