### ISSUE TITLE
Split window position

### ISSUE THREAD

**Issue by jagrg** [politza/pdf-tools#241]
With the configuration below, when I run the `TeX-command-master` command (C-c C-c) on a tex file and choose "View", the window splits below (with the pdf buffer displayed on the bottom window). Is it possible to split the window side-by-side instead (with the pdf buffer displayed on the right)?

```
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
      TeX-source-correlate-start-server t)
```

**Comment by politza** [comment]
This works the same as for other buffers, see (info "(elisp) Choosing Window").

You may either make Emacs prefer splitting windows vertically in general, utilize display-buffer-alist or use the variable pdf-sync-forward-display-action.  The last one may hold a display-action, which is solely used when displaying a PDF buffer in conjunction with a synctex forward search.

Maybe you want repeat this question on emacs.stackexchange.com .

**Comment by jagrg** [comment]
Thanks for pointing me in the right direction. Setting `display-buffer-alist` does what I want:

```
(add-to-list
 'display-buffer-alist
 '("\\.pdf$*" (display-buffer-reuse-window display-buffer-in-side-window)
   (window-width . 0.5)
   (side . right)))
```
