### ISSUE TITLE
LaTeX fragments aren't rendered in annotation tooltips with latest org-mode version because org preview functions are void

### ISSUE THREAD

**Issue by amnelio** [politza/pdf-tools#242]
I had to manually downgrade org-mode to release 20160926 (release version 8.3.6 before milestone 9) in order to get the preview of latex fragments in annotation tooltips back. With the latest release of org-mode installed (package manager/ELPA), pdf-tools fails to render these because some used org-functions are void/deleted (I remember org-mode...-formula-...dvipng something, also during compiling there are some warings about obsolete functions). I would be very glad to see this issue fixed but I also understand that it is very time consuming chasing and adjusting to new org changes (i.e. export interface)!

My pdf-tools-version: 20161206.1639

**Comment by politza** [comment]
That's annoying.

**Comment by politza** [comment]
Should be working again.

**Comment by amnelio** [comment]
First of all, thank you very much for the fast reply and respective commit! I tried out the latest master branch, together with org version 9.0.1, and unfortunately now I receive another error: org-export-get-backend is void. But maybe I need to change settings within org-mode so I try to investigate and figure that out. As I'm new user to the Emacs ecosystem, do you now whether the problems is because of my missing configuration or else?

**Comment by politza** [comment]
Looks like a bug/feature in org-mode.  See if (require 'ox) fixes this.

**Comment by amnelio** [comment]
Thank you very much for this excellent hint! Now it works perfectly again. Keep going on, the idea to integrate annotations in this way is awesome!
