### ISSUE TITLE
Display meta information in mode-line

### ISSUE THREAD

**Issue by gyps** [politza/pdf-tools#243]
Dear all,
after reading about the implementation of showing the current page number in the mode-line I wonder if it would be possible to display more information here when e.g. presenting slides. Since discovering pdf-tools I use PDFView to present all my slides, but this results in in two footers (one from latex beamer, one from mode-line). I suppose it should be possible to place the information about current section, authors, etc. in PDF-meta information and display it in the mode-line making the footer in the beamer presentation unnecessary. I don't know if this is possible but if so it should be easy to implement.
What do you think?
Cheers,
   Alex

**Comment by politza** [comment]
If you want to avoid duplication of on-screen information, why don't you
simply hide the mode-line ?

**Comment by gyps** [comment]
Well, I agree that just hiding the mode-line by setting it to nil is a solution to the problem. But on the other  hand at the same time it eliminates all the possibilities, that com with the mode-line (like displaying time left, etc.). I really don't know about pdf-metadata - is it easy to include it (and access it vie pdf-tools) or would this be a forbiddingly hard to implement?

**Comment by politza** [comment]
The PDF Standard offers many options to attach some data to a document.
And some (probably just one) of those are supported by the glib back-end
of poppler.  (But this can be extended, if necessary.)

I guess some consideration has to be taken as to other PDF programs not
getting confused by and them not destroying this data.

No, I don't think that it is "forbiddingly hard".

**Comment by politza** [comment]
I guess what you could do right now is store the data (a Lisp List or
whatever) inside an invisible highlight-annotation, i.e. with an empty
display rectangle.

**Comment by gyps** [comment]
OK, what do you think about this solution:
In LaTeX I insert into my beamer template something like:
`    \pdfcomment[opacity=0]{PDFView:mode-line\protect\insertauthor{} : }
    \pdfcomment[opacity=0]{PDFView:mode-line\protect\inserttitle{} : } 
    \pdfcomment[opacity=0]{PDFView:mode-line\insertframenumber{}/\inserttotalframenumber}
`
In Emacs I can now access my modeline-text:
`(require 'cl-lib)

(defun pdf-get-mode-line-annot (pg)
  (letrec ((annot-list (pdf-annot-getannots pg 'text))
	   (mode-line-annots (remove-if-not (lambda  (a)
					      (string-prefix-p "PDFView:mode-line" (pdf-annot-print-property a 'contents)))
					    annot-list))
	   (mode-line-text (mapcar (lambda (a) (substring (pdf-annot-print-property a 'contents) (length "PDFView:mode-line")))
				   mode-line-annots )))
    (mapconcat 'identity mode-line-text "")
    ))
`

**Comment by politza** [comment]
Well, does it work ?

**Comment by gyps** [comment]
Sure.
