### ISSUE TITLE
/usr/lib/libharfbuzz.so.0: undefined reference to 'FT_Get_Var_Blend_Coordinates'

### ISSUE THREAD

**Issue by gquittet** [politza/pdf-tools#245]
Since the last update of pdf-tools, I can't compile it. I've got an code 2 error.
My operating system: ArchLinux
My Emacs version: 25.1.1

Fix it because I can't build it and it's my pdf reader.

Here's the log:

make V=0 -kC '/home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build'  melpa-build
make : on entre dans le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build »
cd server && ./autogen.sh
Running autoreconf...
configure.ac:15: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
cd server && ./configure -q

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

make -C server
make[1] : on entre dans le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build/server »
make  all-am
make[2] : on entre dans le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build/server »
  CC       libsynctex_a-synctex_parser.o
  CC       libsynctex_a-synctex_parser_utils.o
  AR       libsynctex.a
ar: le modificateur « u » est ignoré puisque « D » est le défaut (consultez « U »)
  CC       epdfinfo-epdfinfo.o
  CXX      epdfinfo-poppler-hack.o
  CXXLD    epdfinfo
epdfinfo-epdfinfo.o : Dans la fonction « mktempfile » :
/home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build/server/epdfinfo.c:354: avertissement : the use of `tempnam' is dangerous, better use `mkstemp'
/usr/lib/libharfbuzz.so.0 : référence indéfinie vers « FT_Get_Var_Blend_Coordinates »
collect2: erreur : ld a retourné 1 code d'état d'exécution
make[2]: *** [Makefile:451: epdfinfo] Error 1
make[2]: La cible « all-am » n'a pas été refabriquée à cause d'erreurs.
make[2] : on quitte le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build/server »
make[1]: *** [Makefile:346: all] Error 2
make[1] : on quitte le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build/server »
make: *** [Makefile:61: server/epdfinfo] Error 2
make: La cible « melpa-build » n'a pas été refabriquée à cause d'erreurs.
make : on quitte le répertoire « /home/gquittet/.emacs.d/elpa/pdf-tools-20161207.521/build »

Compilation exited abnormally with code 2 at Tue Jan 17 14:12:52

**Comment by politza** [comment]
This is a problem with your system.  Try `pacman -Syu` and build again.

**Comment by gquittet** [comment]
I fixed it! The bug was infinality. These fonts sucks!
- I needed to edit my `/etc/pacman.conf` and remove all the infinality lines
- I needed to reinstall cairo, freetype2, fontconfig with this command:
`sudo pacman -S freetype2 cairo fontconfig lib32-fontconfig lib32-cairo lib32-freetype2 `
- I needed to remove all the infinality fonts that I've installed.
- Finally, I've updated my packages list with `sudo pacman -Syyu`

Thank's for your help!
