### ISSUE TITLE
enable copy / paste feature between emacs buffer

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [politza/pdf-tools#248]
sometimes I want to copy the code example in the pdf
but the text show that it is not a identify ascii character
when I paste it to another buffer in emacs
it should not happen if I use default mac pdf viewer

-----------

I also have some trouble use this with google-translate package
the problem is the same as above
the text in pdf mode can't invert into normal ascii character

**Comment by nistara** [comment]
Same here. I can't copy paste from pdfs open in emacs.

**Comment by nistara** [comment]
Never mind. I wasn't able to paste because I use default cmd-v in the next buffer. It worked by going to `Edit -> Select and Paste` and choosing what I wanted pasted.
