### ISSUE TITLE
Melpa installation does not compile on Cygwin

### ISSUE THREAD

**Issue by TobiasZawada** [politza/pdf-tools#249]
Dear user Politza,
thank you for the package. I am using it under Cygwin.

Only issue is that `(pdf-tools-install)` does not work for me. (The executable is not found.)
After update via melpa I have to go to the `.emacs.d/elpa/pdf-tools-20170130.300/build` folder run `make` there and copy `epdfinfo.exe` from the `server` sub-directory to the install directory `.emacs.d/elpa/pdf-tools-20170130.300/`.
Afterwards, `pdf-tools` runs fine.
Occasionally but not often, I epdfinfo hangs. In such a case I kill it and let emacs restart it.

Note, this is more like an info instead of an issue report.

Best regards,
Tobias

**Comment by politza** [comment]
I don't know, maybe @tuhdo can answer this.
