### ISSUE TITLE
Build failed on OSX10.12.3

### ISSUE THREAD

**Issue by shenrun** [politza/pdf-tools#250]
My Emacs and Spacemcs are both of the most late version. When I excuted make -s in pdf-tools-20170130.300/build, following issues occurred
Loading subst-jis...
Loading subst-ksc...
Loading subst-big5...
Loading subst-gb2312...
Loading subst-jis...
Loading subst-ksc...
Loading subst-big5...
Loading subst-gb2312...
Running autoreconf...
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is provided for compatibility reasons only.
      Due to security concerns inherent in the design of tempnam(3), it is highly recommended that you use
      mkstemp(3) instead. [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");
                  ^
/usr/include/stdio.h:397:7: note: 'tempnam' has been explicitly marked deprecated here
char    *tempnam(const char *__dir, const char *__prefix) __DARWIN_ALIAS(tempnam);
         ^
1 warning generated.
make: *** No rule to make target `lisp/*.el', needed by `pdf-tools-0.70.tar'.  Stop.

I am a green hand in using Emacs and Spacemacs. Thanks.

**Comment by politza** [comment]
The melpa distribution contains only a subset of the actual repository.
It also has its own build command, try

    make melpa-build

**Comment by shenrun** [comment]
Using command make melpa-build, the pdf-tools has been bulit successfully. Thanks for your help sincerely.
