### ISSUE TITLE
better handling of broken epdfinfo

### ISSUE THREAD

**Issue by unhammer** [politza/pdf-tools#253]
I tried this on a machine where I haven't read pdf's through emacs in a while, and got

`The epdfinfo server quit, restart it ? (y or n)` 

on opening a PDF. What I at first didn't see due to that message, was that the *Messages* buffer also said 

`Error during redisplay: (eval (number-to-string (pdf-cache-number-of-pages))) signaled (error "Error running ‘/home/me/.emacs.d/elpa/pdf-tools-0.70/epdfinfo’: /home/me/.emacs.d/elpa/pdf-tools-0.70/epdfinfo: error while loading shared libraries: libpoppler.so.58: cannot open shared object file: No such file or directory`

I tried `M-x pdf-tools-install`, but that of course did nothing since `(file-executable-p pdf-info-epdfinfo-program)`. 

Could perhaps pdf-tools-install (or even better, pdf-view-mode) do some more sanity check of epdfinfo? Because if it compiles its own dynamically linked epdfinfo, it's obviously going to go stale at some point.

A simple test that works on the command line:
```
$ echo |/usr/bin/epdfinfo ; echo $?
0
$ echo |.emacs.d/elpa/pdf-tools-0.70/epdfinfo ; echo $?
.emacs.d/elpa/pdf-tools-0.70/epdfinfo: error while loading shared libraries: libpoppler.so.58: cannot open shared object file: No such file or directory
127
```

**Comment by politza** [comment]
Doesn't it give a appropriate error message, if you hit `y` on that question ?

**Comment by unhammer** [comment]
It asks me again immediately and I have to C-g

**Comment by politza** [comment]
39120f642e7a771647da86c4a0253c1dae5e9656

**Comment by politza** [comment]
See 39120f642e7a771647da86c4a0253c1dae5e9656.
