### ISSUE TITLE
Use elpa-pdf-tools-server from apt if available?

### ISSUE THREAD

**Issue by unhammer** [politza/pdf-tools#254]
Using https://packages.debian.org/stretch/elpa-pdf-tools-server / http://packages.ubuntu.com/yakkety/elpa-pdf-tools-server if possible would make an installation more future-proof against dist-upgrades breaking the compile (e.g. https://github.com/politza/pdf-tools/issues/253 ), while still allowing the user to run e.g. Emacs 25 or such (the http://packages.ubuntu.com/yakkety/elpa-pdf-tools package unfortunately depends on emacs24). 

Yakkety has 

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety
```
while (the source of) Debian stretch/sid's https://packages.debian.org/sid/base-files is 
```
$ cat /etc/os-release 
PRETTY_NAME="Debian #OSNAME# 9 (stretch)"
NAME="Debian #OSNAME#"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by politza** [comment]
I see what I can do.

**Comment by politza** [comment]
Ok, the package will now prefer an existing `epdfinfo` program.
