### ISSUE TITLE
Is this possible to do a backward-sync when searching text in pdf-view-mode?

### ISSUE THREAD

**Issue by tddsg** [politza/pdf-tools#256]
Hi,

I'd like to ask whether it is possible to do the backward-sync from `pdf-view` to `auctex` when using searching for text in the PDF file?

Currently, the backward-sync can be done by mouse-clicking, but, it will be very convenient if during the `isearch`, I can press a key to jump back to the TeX file position corresponding with the highlight text in the PDF file.

Thanks!

**Comment by politza** [comment]
8fc137673c59c8cab392f519dab967051a0b07f0
