### ISSUE TITLE
all dependencies installed yet pdf-tools *still* wants to install them!

### ISSUE THREAD

**Issue by boudiccas** [politza/pdf-tools#258]
I've just installed manually all the required dependencies for pdf-tools manually, in that I installed them without recourse to your makefile. However, 'gtklp' is not available in debian 8, so its had to be installed from 'stretch', the upcoming debian 9. 

But still pdf-tools wants to install them, even though all dependencies are satisfied. Is it not possible for the makefile to do a quick dependency check, and if they're all there to proceed with the build, and if they're not there to ask to install them please?

As at the moment, I'm unable to use pdf-tools because its stuck in a loop of wanting to install them, even though 'gtklp' is not available. So my only option is to comment pdf-tools out, or uninstall it, neither of which I really want to do. So can you help to resolve this situation please?

**Comment by politza** [comment]
Actually, it should ask, whether dependencies should be installed or
not. Anyway, you can compile it manually by running the following command
in a shell or via M-x compile and assuming default paths.

make -C ~/.emacs.d/elpa/pdf-tools*/build/ melpa-build

**Comment by boudiccas** [comment]
Sorry, the build is failing, heres the error report

`````
make -C ~/.emacs.d/elpa/pdf-tools*/build/ melpa-build
make: Entering directory '/home/boudiccas/.emacs.d/elpa/pdf-tools-20170228.2312/build'
cd server && ./autogen.sh
Running autoreconf...
configure.ac:15: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:56: installing './config.guess'
configure.ac:56: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
cd server && ./configure -q
./configure: line 4743: syntax error near unexpected token `png,'
./configure: line 4743: `PKG_CHECK_MODULES(png, libpng)'
Makefile:63: recipe for target 'server/Makefile' failed
make: *** [server/Makefile] Error 2
make: Leaving directory '/home/boudiccas/.emacs.d/elpa/pdf-tools-20170228.2312/build'
````

**Comment by politza** [comment]
This error about PKG_CHECK_MODULES seems to come up from time to time...

Do you have `pkg-config` installed ? If yes, you could try the solution mentioned in [https://github.com/kanaka/libvncserver/issues/1] (this) thread.

**Comment by politza** [comment]
Feel free to reopen.
