### ISSUE TITLE
Problem with `pdf-sync-display-pdf`

### ISSUE THREAD

**Issue by szozda** [politza/pdf-tools#26]
I would really like to be able to `C-c C-g` to jump to the location in the `pdf` file corresponding to the line/column position in `tex` file, however I always get 

`pdf-info-query: epdfinfo: Destination not found`

message.  I initially thought that some of my other LaTeX related packages may be interfering, but `emacs -Q` followed by
```elisp
(require 'package)
(package-initialize)

(package-activate 'auctex)
(setq TeX-source-correlate-method 'synctex)
(add-hook 'LaTeX-mode-hook 'TeX-source-correlate-mode)

(package-activate 'pdf-tools)
(pdf-tools-install)
```
and opening the tex and pdf files yields the same message.

I have `pdf-tools` 8e423bffe19dc36a5a7f500be42a5de8fc00639b so the only commits following this one are the MELPA related ones.

Other info:
```
emacs-version
GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.3) of 2014-10-21 on bitzer.hoetzel.info

auctex-11.88
```

**Comment by politza** [comment]
SyncTeX's file-resolution is a bit messy.  I am working on a general
solution.

Meanwhile, can you try to determine the cause of the problem, i.e
what's the value of

    (TeX-master-file "pdf")

in your document and what's the SYNCTEX-NAME of it in the synctex.gz
file ?  (There should be line starting with Input: corresponding to
the master file.) Are symbolic links involved ? Is this

    (file-equal-p SYNCTEX-NAME (TeX-master-file "pdf"))

true ?

Thanks.

**Comment by szozda** [comment]
Thanks so much. Yes it was symlinks that messed stuff up. I had the `tex` and `pdf` file opened from a directory symlinked from a Dropbox folder and the `synctex.gz` had 
```
Input:1:/home/user/Dropbox/path/to/something/./file.tex
```
while `(buffer-file-name)` on the `tex` and `pdf` files returned
```
/home/user/shortpath/file.tex
/home/user/shortpath/file.pdf
```
Now I only have to get rid of my muscle memory when opening files and change `org-mode` links. But it's worth it just to be able to use `C-c C-g` with `pdf-tools`.

Thanks!

**Comment by politza** [comment]
I commited a change regarding this.  Could you please try, whether it
works with your use-case ?

**Comment by szozda** [comment]
It works. Thanks!

**Comment by politza** [comment]
Hopefully it stays that way.
