### ISSUE TITLE
Upgraded pdf-tools from package menu, problems when restarting Emacs

### ISSUE THREAD

**Issue by hakonhagland** [politza/pdf-tools#261]
Hi!

I tried to upgrade package pdf-tools from the Emacs package menu ( I am using Emacs 25.1 on 
Ubuntu 16.10). After I restarted Emacs, I got the following errors:

```
Need to build the server, do it now ? (y or n)
```
I press here `y`, then

```
Should I try to install dependencies with apt-get ? (y or n)
```

Here I press `y` again, then in `*scratch*` buffer:
```
Warning (initialization): An error occured while loading '/home/hakon/.emacs':
error: No executable 'epdfinfo' found
```

Then below in `*Warnings*` buffer:

```
*Warnings* (Special Compiling)
(In buffer *compile pdf-tools*) make: Entering directory '/home/hakon/.emacs.d/elpa/pdf-tools-20170228.2312/build'
sudo apt-get install gcc g++ make automake autoconf libpng-dev libz-dev libpoppler-glib-dev
[sudo] password for hakon: 
```

When I now try to type password at the prompt, it seems keyboard input is not allowed. For example,
if I start type my password and press a key, for example "a", I get error:

```
a is undefined
```

And I cannot continue, for example if I press `C-g` to abort, I get error

```
C-g is undefined
```

So I need to kill Emacs.

I tried:

```
cd  /.emacs.d/elpa/pdf-tools-20170228.2312/build
make
```

This generates the executable `epdfinfo`, but it does not change any of the errors above.

I also tried
```
cd  /.emacs.d/elpa/pdf-tools-20170228.2312/build/server
sudo make install 
```

and this copies `epdfinfo` to `/usr/local/bin/epdfinfo`. Now `epdfinfo` is accessible from the Shell.
So it is indeed reachable from `$PATH`, but still noen of the above errors go away when I restart Emacs.

**Comment by politza** [comment]
Try
make melpa-install
instead.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Håkon Hægland <notifications@github.com> </div><div>Datum:09.03.2017  12:23  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: [politza/pdf-tools] Upgraded pdf-tools from package menu, problems
  when restarting Emacs (#261) </div><div>
</div>Hi!

I tried to upgrade package pdf-tools from the Emacs package menu ( I am using Emacs 25.1 on
Ubuntu 16.10). After I restarted Emacs, I got the following errors:

Need to build the server, do it now ? (y or n)
I press here y, then

Should I try to install dependencies with apt-get ? (y or n)
Here I press y again, then in *scratch* buffer:

Warning (initialization): An error occured while loading '/home/hakon/.emacs':
error: No executable 'epdfinfo' found
Then below in *Warnings* buffer:

*Warnings* (Special Compiling)
(In buffer *compile pdf-tools*) make: Entering directory '/home/hakon/.emacs.d/elpa/pdf-tools-20170228.2312/build'
sudo apt-get install gcc g++ make automake autoconf libpng-dev libz-dev libpoppler-glib-dev
[sudo] password for hakon: 
When I now try to type password at the prompt, it seems keyboard input is not allowed. For example,
if I start type my password and press a key, for example "a", I get error:

a is undefined
And I cannot continue, for example if I press C-g to abort, I get error

C-g is undefined
So I need to kill Emacs.

I tried:

cd  /.emacs.d/elpa/pdf-tools-20170228.2312/build
make
This generates the executable epdfinfo, but it does not change any of the errors above.

**Comment by NLisa** [comment]
What worked for me on pdf-tools-20170721.718  was to build server/epdfinfo directly. There may be an issue with the Makefile...?

$ make V=0 -kC '/PATH/TO/.emacs.d/elpa/pdf-tools-20170721.718/build'  server/epdfinfo

**Comment by politza** [comment]
Feel free to reopen.
