### ISSUE TITLE
pdf-info-check-epdfinfo raises a file-error

### ISSUE THREAD

**Issue by vp1981** [politza/pdf-tools#263]
Hello,
today I faced strange behavior of Emacs related with pdf-tools so I even can't run Emacs without `--debug-init` option . I'm not sure about the reason because I didn't use pdf-tools last week though I was able to start Emacs without problem. Today I compiled Emacs from git repo (commit `84b6bc9eff`) and got following backtrace (just the top):
```
Debugger entered--Lisp error: (file-error "Setting current directory" "Permission denied" "~")
  call-process("/usr/bin/epdfinfo" "/tmp/pdf-info-check-epdfinfo23093cxE" #<buffer  *temp*> nil)
  apply(call-process "/usr/bin/epdfinfo" "/tmp/pdf-info-check-epdfinfo23093cxE" #<buffer  *temp*> nil nil)
  pdf-info-check-epdfinfo()
  pdf-info-process-assert-running()
  pdf-info-query(features)
  pdf-info-features()
  pdf-info-markup-annotations-p()
```

I don't understand this message but I tried to investigate the code of `pdf-info-check-epdfinfo` function and saw that `~` seems to come from `default-directory`. I changed it to `/tmp` and now Emacs starts normally. Below is my patch
```
diff --git a/lisp/pdf-info.el b/lisp/pdf-info.el
index 3167f03..b1a37b9 100644
--- a/lisp/pdf-info.el
+++ b/lisp/pdf-info.el
@@ -200,7 +200,7 @@ server, that it never ran.")
       (unless (file-writable-p pdf-info-epdfinfo-error-filename)
         (error "pdf-info-epdfinfo-error-filename should be nil or a writable filename")))
     (let ((tempfile (make-temp-file "pdf-info-check-epdfinfo"))
-          (default-directory "~"))
+          (default-directory "/tmp"))
       (unwind-protect
           (with-temp-buffer
             (with-temp-file tempfile
@@ -250,7 +250,7 @@ error."
       (error "The epdfinfo server quit"))
     (pdf-info-check-epdfinfo)
     (let* ((process-connection-type)    ;Avoid 4096 Byte bug #12440.
-           (default-directory "~")
+           (default-directory "/tmp")
            (proc (apply #'start-process
                         "epdfinfo" " *epdfinfo*" pdf-info-epdfinfo-program
                         (when pdf-info-epdfinfo-error-filename

```

P.S. This may be unrelated with pdf-tools and related with recent changes to `tramp` because it's function `tramp-completion-handle-expand-file-name` gives me two errors on my config but that could be error in my config as well.

**Comment by politza** [comment]
Debugger entered--Lisp error: (file-error "Setting current directory" "Permission denied" "~")

It means that Emacs is unable to cd to your home directory, which seems
ridiculous.  I think it may be related to the following commit.

commit ed33337c3e0d0b1a8b140e23168421ea43d79324
Author: Michael Albinus <michael.albinus@gmx.de>
Date:   Mon Mar 13 18:05:59 2017 +0100

    Require method in remote file name syntax

**Comment by vp1981** [comment]
Hello,
Ok, then I interpreted the message correctly. Unfortunately, I couldn't make a small example to show the problem and open a bug report. Thank you.

**Comment by vp1981** [comment]
On second thought...
I read Emacs Lisp manual about `call-process` and `default-directory` and think that setting `default-directory` to `~` for `call-process` within `pdf-info-check-epdfinfo` is wrong: why current working directory is `~` if temporary file is created in `/tmp`?

**Comment by politza** [comment]
Have you tried `make bootstrap` ?

**Comment by vp1981** [comment]
You mean `make bootstrap` to compile Emacs? In short: yes. Long story: I'm using Archlinux x86_64 and use standard way to make emacs package for my distribution, here is my PKGBUILD: http://cgit.vl-lomov.ru/pkgbuild/plain/emacs/PKGBUILD and I follows emacs recommendation.

**Comment by ardpp** [comment]
I am also using emacs from git on Archlinux (also did make bootstrap). Some update yesterday evening introduced the same error which appears when I try to open a pdf-file. During the day I was using emacs and pdf-tools all the time and it was working fine. 

I cannot say if it was emacs or a system update because I did both. Reverting to the commit before 
`commit ed33337c3e0d0b1a8b140e23168421ea43d79324`
didn't seem to help in my case.

**Comment by politza** [comment]
The variable default-directory is set in case the current value does not
exist, that's the only reason.

**Comment by politza** [comment]
I'm unable to reproduce this problem using commit
84b6bc9eff770d8252fc400119c2e8fca5df2e48.

What does `(file-accessible-directory-p "~")` return for you ?

**Comment by ardpp** [comment]
`(file-accessible-directory-p "~")` returned `nil` in my case. Last commit of emacs that I installed a few minutes ago returns `t` and pdf-tools works as it used to. For me the bug is gone.

**Comment by politza** [comment]
Ok thanks. I suppose this can be closed then.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: ardpp <notifications@github.com> </div><div>Datum:14.03.2017  21:03  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] pdf-info-check-epdfinfo raises a file-error
  (#263) </div><div>
</div>(file-accessible-directory-p "~") returned nil in my case. Last commit of emacs that I installed a few minutes ago returns t and pdf-tools works as it used to. For me the bug is gone.

**Comment by vp1981** [comment]
Thank you politza and ardpp, now emacs works fine.
