### ISSUE TITLE
Open pdf from git history give error

### ISSUE THREAD

**Issue by Titan-C** [politza/pdf-tools#266]
I'm keeping in version control a document that includes png and pdf images. When I use magit to open old versions of a png image, emacs has no problem opening them.
On the contrary if I try to open a pdf from any version which is not HEAD I get:
```
Error running timer 'pdf-cache--prefetch-start`: (error "Buffer is not associated with any file :image_file.pdf.~master~6~")
```
But it opens a buffer with the pdf contents in text and renders Emacs useless. I cannot kill that buffer in any way and any call to ibuffer/helm or anything else to change the buffer result in a split frame, with the new windows both of which repeat the pdf text context and ibuffer/helm never show up.

**Comment by politza** [comment]
Does magit remove the file from the file-system ?

And please post a backtrace, i.e. set debug-on-error to a non-nil before
the error occurs.

-ap

**Comment by Titan-C** [comment]
> Does magit remove the file from the file-system ?

I guess that is the wrong point of view. The last version of the file is on the file-system, was is not on the file system is the previous versions. My guess is that magit just calls the next command:
```bash
$ git show master~12:IPT_EF_quasiparticle_AB_coex.pdf
```
To which git just outputs to stdout. Then I guess is a matter on how emacs captures that output for display.

The full backtrace is:
```
Debugger entered--Lisp error: (error "Buffer is not associated with any file :IPT_EF_quasiparticle_AB_coex.pdf.~master~12~")
  signal(error ("Buffer is not associated with any file :IPT_EF_quasiparticle_AB_coex.pdf.~master~12~"))
  error("Buffer is not associated with any file :%s" "IPT_EF_quasiparticle_AB_coex.pdf.~master~12~")
  pdf-info--normalize-file-or-buffer(nil)
  pdf-info-pagesize(1)
  pdf-cache-pagesize(1)
  pdf-view-desired-image-size(1 #<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  pdf-view-create-page(1 #<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  pdf-view-display-page(1 #<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  pdf-view-redisplay(#<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  pdf-view-goto-page(1)
  pdf-view-new-window-function((#<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~> (window-size 146 . 22) (overlay . #<overlay from 1 to 35879 in IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>) (page . 1)))
  run-hook-with-args(pdf-view-new-window-function (#<window 3 on IPT_EF_quasiparticle_AB_coex.pdf.~master~12~> (window-size 146 . 22) (overlay . #<overlay from 1 to 35879 in IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>) (page . 1)))
  image-mode-winprops(nil t)
  image-mode-reapply-winprops()
  #<subr set-window-buffer>(nil #<buffer IPT_EF_quasiparticle_AB_coex.pdf.~master~12~> nil)
  ad-Advice-set-window-buffer(#<subr set-window-buffer> nil #<buffer IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  apply(ad-Advice-set-window-buffer #<subr set-window-buffer> (nil #<buffer IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>))
  set-window-buffer(nil #<buffer IPT_EF_quasiparticle_AB_coex.pdf.~master~12~>)
  #[(buffer-or-name &optional norecord force-same-window) "\306!\211\307 =\204s
```

**Comment by politza** [comment]
Normally, if pdf-view-mode is activated in some buffer without a
filename or without an existing filename, but with PDF document as
content, it should create a temporary file and work on that.

The fact that this does not seem to happen seems to indicate, that magit
does first set up the major-mode and then inserts the actual
content. Can you confirm that ?

Having a recipe starting from `emacs -Q` with an assumed magit
installation would be nice.
