### ISSUE TITLE
Offer to use an Emacs print function instead of gtklp

### ISSUE THREAD

**Issue by dinojr** [politza/pdf-tools#267]
pdf-tools seem to only offer external gui applications for printing. I'd rather use the lpr-command, making use of the lpr-switches and printer-name variables.  Can it be achieved ?

**Comment by politza** [comment]
What is stopping you from doing that ?

**Comment by dinojr** [comment]
Indeed,

```
(setq pdf-misc-print-programm-args `("-o landscape" "-o sides=two-sided-short-edge" "-o page-ranges=1-" "-P"  ,printer-name))

(setq pdf-misc-print-programm lpr-command)
```
works fine.

**Comment by politza** [comment]
Glad you found them variables.  Guess I could have mentioned them.
