### ISSUE TITLE
Browsing past the end of a pdf (using space bar) raises an error

### ISSUE THREAD

**Issue by JalapenoGremlin** [politza/pdf-tools#269]
I often run my emacs with `debug-on-error` set to `t`. 
When I am "scrolling" through a PDF using 'n': `(pdf-view-next-page-command &optional N)`, I get a nice message of "user-error: Last page". If I use the space bar `(pdf-view-scroll-up-or-next-page &optional ARG)`, I get an `(error...) ` call in `pdf-view-goto-page` rather than the "user-error: Last page.". 

Any way the behavior can be the same, namely "user-error: Last Page"?

**Comment by politza** [comment]
The first function is explicitly marked as `interactive-only` and not used by other code, while the other one, respectively it's callee `pdf-view-next-page`, is at various places.  If `pdf-view-next-page-command` is called with an invalid page number, we now the user made an error.  But in the other case, it could also be simply a bug in the calling library.  So, it seems to me that the current situation is how it's supposed to be (?).

**Comment by justbur** [comment]
I understand why in some cases you would want the error, but it's too much in my opinion for indicating that you want to scroll past the end of the page. Here are two possible alternatives: 

  1. Wrap calls to `pdf-view-next-page` to catch errors when the caller is called interactively. Could use a macro for this, too.
  2. Use a `noerror` argument for these functions that is set when they're called interactively. 

I can work on this if you want @politza

**Comment by politza** [comment]
3. Use interactive-p arg and signal user-error if appropriate. 

I would favour this,  because you don't have to change the program flow.

**Comment by politza** [comment]
A function error-or-message or error-or-uerror or what ever would be good.

**Comment by ChanderG** [comment]
@politza, does PR#300 solve this?

**Comment by JalapenoGremlin** [comment]
Well It is sort of fixed.

<SPC> bound to (pdf-view-scroll-up-or-next-page) works
C-n bound to (pdf-view-next-line-or-next-page &optional ARG)  tosses an error("No such page: %d 2)
C-p bound to (pdf-view-previous-line-or-prevous-page &optional ARG) also tosses an error("No such page: %d 0)

I'll rebind my keys a necessary or add some advice. 

I'll have to dig more into what PR # 300 (and the see me PR#299) do.

**Comment by JalapenoGremlin** [comment]
Here is a  solution I found for my particular situation, if others "google got me here" users are interested....
```emacs-lisp
(defun pdf-view-catch-error (old-function &rest args)
    (condition-case err
        (apply old-function args)
      (error
       (user-error "%s" (error-message-string err)))))

(advice-add #'pdf-view-scroll-up-or-next-page :around #'pdf-view-catch-error)
(advice-add #'pdf-view-scroll-down-or-previous-page :around #'pdf-view-catch-error)

(advice-add #'pdf-view-previous-line-or-previous-page :around #'pdf-view-catch-error)
(advice-add #'pdf-view-next-line-or-next-page :around #'pdf-view-catch-error)

(advice-add #'pdf-history-forward :around #'pdf-view-catch-error)
(advice-add #'pdf-history-backward :around #'pdf-view-catch-error)
```

I suppose the `(condition-case err...` could be added around the function calls  to `(pdf-view-next-page)` and `(pdf-view-previous-page)` with the `(condition-case` in the interacive functions, to which  I have added around-advice. 

However, `pdf-history-forward`, and `pdf-history-backward` use `(error` rather than `(user-error)`. Not certain why, but, I guess there is some reason that those interactive functions are also called from within the engine.
