### ISSUE TITLE
Is there a way to interact with org-mode?

### ISSUE THREAD

**Issue by RanTaimu** [politza/pdf-tools#271]
Just like "docview:foo.pdf::NNN", we can open the specific NNNth page from notes written by org-mode. So if there is a way like, click a link in org-mode, which specifies the index of an annotation or a label (e.g. foo.pdf::labelNNN), "pdf-tools" then open the page containing it?

**Comment by sherter** [comment]
See https://github.com/markus1189/org-pdfview
Linking to annotations seems not to be supported though...

**Comment by RanTaimu** [comment]
@sherter OK, thanks very much!
