### ISSUE TITLE
"insert text" annotations not shown in annotation list

### ISSUE THREAD

**Issue by kleinschmidt** [politza/pdf-tools#272]
I have many PDFs that are marked up in Adobe Reader, with a mix of highlights, text comments, strikeout, and text insert annotations.  All except the insert text annotations are processed and listed correctly.  The insert text annotations are generally processed as I'd expect, but don't show up in the list.  They're rendered (correctly) as little blue arrows below the line.  When you click on one, the inserted text shows up correctly in the edit annotation buffer.  But they don't appear in the list of annotations, and selecting "List annotation" from the mouse-2 contextual menu produces an error ("Unable to find annotation").

I'm not sure if these annotations are really supported (they're shown as "No Subject", unlike the highlight etc. annotations, and the author isn't shown unlike with the other types).  But the annotation list is very useful to me for processing feedback, and without showing these annotations it's of limited utility.  Moreover, the insert annotation sometimes gets buried beneath other annotations (e.g., highlights) and can't be easily accessed by clicking.

**Comment by politza** [comment]
Have you tried changing pdf-annot-list-listed-types .

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Dave Kleinschmidt <notifications@github.com> </div><div>Datum:25.04.2017  21:03  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: [politza/pdf-tools] "insert text" annotations not shown in annotation
  list (#272) </div><div>
</div>I have many PDFs that are marked up in Adobe Reader, with a mix of highlights, text comments, strikeout, and text insert annotations. All except the insert text annotations are processed and listed correctly. The insert text annotations are generally processed as I'd expect, but don't show up in the list. They're rendered (correctly) as little blue arrows below the line. When you click on one, the inserted text shows up correctly in the edit annotation buffer. But they don't appear in the list of annotations, and selecting "List annotation" from the mouse-2 contextual menu produces an error ("Unable to find annotation").

I'm not sure if these annotations are really supported (they're shown as "No Subject", unlike the highlight etc. annotations, and the author isn't shown unlike with the other types). But the annotation list is very useful to me for processing feedback, and without showing these annotations it's of limited utility. Moreover, the insert annotation sometimes gets buried beneath other annotations (e.g., highlights) and can't be easily accessed by clicking.

**Comment by kleinschmidt** [comment]
Nope, that's embarrassing. I was looking for "caret". Perhaps that should be enabled by default? Thanks, and sorry to use issues for tech support.
