### ISSUE TITLE
Compilation Makefile directory inconsistencies (pdf-tools-20170417.150)

### ISSUE THREAD

**Issue by bobwoodham** [politza/pdf-tools#273]
Makefile expects *.el files to be in a lisp/ sub directory.  There isn't one (in the melpa distribution).  The relevant section of the Makefile is:

```
$(PACKAGE_NAME).tar: server/epdfinfo lisp/*.el
	mkdir -p '$(PACKAGE_DIR)'
	cp lisp/*.el README server/epdfinfo '$(PACKAGE_DIR)'
	echo '$(PKGFILE_CONTENT)' > '$(PACKAGE_DIR)/pdf-tools-pkg.el'
	tar cf '$(PACKAGE_NAME).tar' '$(PACKAGE_DIR)'

```
I hacked the Makefile to get things to work for me.  But, my solution isn't robust.

Also, "Compilation" section of the GitHub README.org says "cd /path/to/pdf-tools".  For me, this needed to be a cd to the build sub-directory of /path/to/pdf-tools/.

Issue both on Ubuntu 14.04 / Emacs 24.3 and Ubuntu 16.04 Emacs 24.4

**Comment by politza** [comment]
The Makefile contains special rules to build the server from a melpa
package, but in general is meant to be used from within the repository.
Likewise, the README, for the most part, refers to actions taken from
within the repository.

**Comment by bobwoodham** [comment]
OK.  Thanks for pointing out this distinction.

I got to the point I got to because following (what I perceived to be) a
standard melpa package build/install failed on the target epdfinfo.  I
dug deeper based on what emacs had downloaded.  I did not clone the
repository.

Sorry if my contribution is just noise.

P.S. I'm now enjoying pdf-tools.  Thanks.

**Comment by politza** [comment]
Added a note about this in the README.
