### ISSUE TITLE
Indicator for previous line position after scrolling

### ISSUE THREAD

**Issue by lihebi** [politza/pdf-tools#275]
Hi,

I found a indicator to show the position before scrolling helpful. Often I have a hard time to find the line I was reading after scrolling up the page using `pdf-view-scroll-up-or-next-page`.

I was trying to create an advice around both `pdf-view-scroll-up-or-next-page` and `pdf-view-scroll-down-or-previous-page`, and create temporary overlay for highlighting the first and last lines. The code looks like this

```elisp
(defun my-highlight-advice (oldfunc &optional arg)
  "highlight first and last line."
  ;; get current position
  (let ((vscroll (window-vscroll)))
    ;; apply the scroll up and down function
    (apply oldfunc arg)
    ;; temporarily highlight
    (scroll-highlight begin end 0.5)))

(advice-add 'pdf-view-scroll-up-or-next-page :around
            #'my-highlight-advice)
(advice-add 'pdf-view-scroll-down-or-previous-page :around
            #'my-highlight-advice)
```
The temporary highlight looks like this:
```elisp
(defface scroll-highlight-line-face
  '((t (:background "cadetblue4" :foreground "white" :weight bold)))
  "Font Lock mode face used to highlight line."
  :group 'scroll-screen)

(defun scroll-highlight (beg end delay)
  "Highlight a region temporarily."
  (let ((ov (make-overlay beg end)))
    (overlay-put ov 'face 'scroll-highlight-line-face)
    (sit-for delay)
    (delete-overlay ov)))
```

However, the overlay seems not working on image-mode (i tried to use fill-column-indicator mode and the overlay doesn't show in pdfview either). By looking into how pdf-tools displays annotation, I found the `pdf-annot-show-annotation` function here: 
https://github.com/politza/pdf-tools/blob/7cca03bd2fc534a6b42eafc2afef20099bf83dbf/lisp/pdf-annot.el#L902

I'm having some trouble understanding how the position and rendering exact works, but I don't have time to read through the source code to understand it yet. Any suggestions?

Thanks,
Hebi

**Comment by sherter** [comment]
@politza Maybe you can add this feature directly to pdf-tools? Would be really useful!

**Comment by politza** [comment]
Yes, it would be useful.  But using an overlay won't work.

**Comment by lihebi** [comment]
I got an idea of an easier (and maybe even better) solution: simply add 3 horizontal lines to divide the document into 4 even parts. The lines are good to indicate the positions between scrolls.

**Comment by lihebi** [comment]
I've hacked it to add horizontal helper lines. It might look weird, but it does its job so far. Screenshot attached. This is not likely to be something everybody likes, so I'm just posting [this commit](https://github.com/lihebi/pdf-tools/commit/58e403d7ce704b883b0d0ec891586c8be7f6c625) for those who want this feature.

The server-side epdfinfo.c file is modified to add three lines when the client retrieve a pdf, so it will work for all the pdf, you can not turn it down.

![whole](https://user-images.githubusercontent.com/4576201/30897953-96e750b8-a31e-11e7-94b1-79ebecd543c8.png)
![large](https://user-images.githubusercontent.com/4576201/30897962-9d475a66-a31e-11e7-8283-3c2df15c4cb2.png)
