### ISSUE TITLE
Binding `pdf-view-next-page` to mouse wheel

### ISSUE THREAD

**Issue by budsbenzer** [politza/pdf-tools#276]
Since I like fast scrolling of pages in a PDF, I added the shortcut
```
(define-key pdf-view-mode-map (kbd "<mouse-5>") 'pdf-view-next-page)
```
to my init.el.

When the current window belongs to PDFView, this works nicely.  However, when my current window is another one (e.g. one with the LaTeX buffer of the document I'm writing), I get the following error:

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  image-mode-winprops(nil)
  image-mode-window-get(page nil)
  pdf-view-next-page(1)
  funcall-interactively(pdf-view-next-page 1)
  call-interactively(pdf-view-next-page nil nil)
  command-execute(pdf-view-next-page)
```

How could I fix this?

**Comment by politza** [comment]
Adding a @ to the interactive spec should select the right window before
scrolling it, e.g. like the following function.

(defun pdf-view-next-page-mouse (&optional n)
  (interactive "@p")
  (pdf-view-goto-page (+ (pdf-view-current-page)
                         (or n 1))))

**Comment by budsbenzer** [comment]
Yes, this works. Thank you! :)
