### ISSUE TITLE
add fedora dependency details to README.org

### ISSUE THREAD

**Issue by bdarcus** [politza/pdf-tools#277]
Installing pdf-tools on a debian system went smoothly. On Fedora, not so much.

Perhaps you could add the yum/dnf equivalents comparable to the examples you have for debian/ubuntu?

I believe the following is the equivalent package names.

`sudo dnf install make automake autoconf gcc gcc-c++ ImageMagick libpng-devel zlib-devel poppler-glib-devel`

**Comment by politza** [comment]
I think I'd like to avoid managing a list of package names for all the distributions times versions.  It is fairly easy to map from debian packages to any other distribution using google.

**Comment by bdarcus** [comment]
Your prerogative of course. But I wasted far more time figuring out the equivalent package names than I did posting this issue.

**Comment by politza** [comment]
Ok, there is already such a list, so I added it anyway.
