### ISSUE TITLE
Server doesn't build in NixOS

### ISSUE THREAD

**Issue by thblt** [politza/pdf-tools#279]
Hi,

The server cannot be built using the standard process in NixOS, because NixOS requires an isolated build environment (a "shell") to be created before building, because it's impossible to have build-time dependencies available to the current user.   Would you accept a pull request adding the option to build in such a shell if the OS appears to be Nix?  It should be a very small modification, but I prefer to ask beforehand because I'm still new to Elisp, so it will probably take me some time to get it right.

**Comment by politza** [comment]
Yes, sure.

**Comment by periklis** [comment]
@thblt let me know if you made the patches ready. I can assist for stdenv.darwin.

**Comment by thblt** [comment]
@periklis Will do, thanks!

**Comment by periklis** [comment]
@politza Does this build now?

**Comment by politza** [comment]
Just wanted to see if some still cares.

**Comment by thblt** [comment]
I have one last thing to finish before I start working on this, but I still care.  Apologies for the (very long) delay; I've had much less time than I'd expected.
