### ISSUE TITLE
Install failed due to missing `tablist'

### ISSUE THREAD

**Issue by wrachwal** [politza/pdf-tools#28]
Package `tablist-0.50' is unavailable

**Comment by politza** [comment]
Please read the README or wait 'til it's available on melpa.

**Comment by wrachwal** [comment]
Ok, reverted to v0.40 tag and built as so far. I will wait for melpa bundle. Thanks.

**Comment by politza** [comment]
I changed my mind on this.  You should be able to install it like before (in v0.40).
