### ISSUE TITLE
is it possible to use pdf-view in terminal

### ISSUE THREAD

**Issue by kirk86** [politza/pdf-tools#280]
Hi, I was wondering if it's possible to use the `pdf-view` inside a terminal since I'm used to running emacs in terminal mode. If so how can we do that? Thanks!

**Comment by politza** [comment]
No, it's not possible. 
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kirk86** [comment]
@politza thanks. I'm closing this issue, since it's not possible at the moment.
