### ISSUE TITLE
Ability to set annotation colour in midnight-mode

### ISSUE THREAD

**Issue by emacsomancer** [politza/pdf-tools#284]
Midnight-mode (esp. customised) is brilliant and really facilitates my being able to stand reading long PDFs.  However, I also make copious use of pdf-tools' equally brilliant annotation features. It would be ideal if I could set the annotation (underline &c.) colour to be something different from the foreground colour.  Is this technically feasible?

**Comment by politza** [comment]
You can change the color of annotations, but Midnight mode simply runs the completely rendered page through a filter. 

Does that answer it?

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Benjamin Slade <notifications@github.com> </div><div>Datum:23.06.2017  18:26  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: [politza/pdf-tools] Ability to set annotation colour in midnight-mode
  (#284) </div><div>
</div>Midnight-mode (esp. customised) is brilliant and really facilitates my being able to stand reading long PDFs. However, I also make copious use of pdf-tools' equally brilliant annotation features. It would be ideal if I could set the annotation (underline &c.) colour to be something different from the foreground colour. Is this technically feasible?

**Comment by emacsomancer** [comment]
Right, I know I can change the colour of the annotations generally. But is there any way that Midnight Mode's filter could handle annotations differently from text?

**Comment by politza** [comment]
No, it's not possible.  

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Benjamin Slade <notifications@github.com> </div><div>Datum:23.06.2017  19:17  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Ability to set annotation colour in
  midnight-mode (#284) </div><div>
</div>Right, I know I can change the colour of the annotations generally. But is there any way that Midnight Mode's filter could handle annotations differently from text?
