### ISSUE TITLE
pdf-info-check-epdfinfo: pdf-info-epdfinfo-program is not executable

### ISSUE THREAD

**Issue by idontgetoutmuch** [politza/pdf-tools#288]
Same as https://github.com/politza/pdf-tools/issues/179. I tried closing and re-installing but no joy. Let me know what information you need.

**Comment by politza** [comment]
Have you called pdf-tools-install ? Does the epdfinfo binary exists in the elpa subdirectory ? If yes: Are you able to execute it from within a shell ?

**Comment by idontgetoutmuch** [comment]
Apologies - I didn't see I had to call `pdf-tools-install` after installing the package via emacs.
