### ISSUE TITLE
No markup annotation in Parabola

### ISSUE THREAD

**Issue by broncodev** [politza/pdf-tools#291]
Hello. Thank you for PDF-tools. I use it everyday, and would like to use it with Parabola (GNU/Linux based on Arch) as well. I have tried to build it with the regular steps several times, and I haven't managed to make the markup annotations to work. Could you help me with this? Thanks!

**Comment by politza** [comment]
Define "not working".

**Comment by broncodev** [comment]
Oops! Sorry: The option in the PDF Tools menu which says "Add markup annotation" is not active. If I try to add an annotation, it tells me that "The region is not active". The option "Add text annotation" is active. Basically, I cannot add markup annotations. I don't know if this helps.

I downloaded from git. `package-list-packages` shows pdf-tools 0.70. Let me know if there is any other information that you need. Thanks.

**Comment by politza** [comment]
You need to select a region of text with the mouse first, then apply the command.

**Comment by broncodev** [comment]
Thanks! It is _that_ simple :)

**Comment by politza** [comment]
Sometims it is.
