### ISSUE TITLE
[Windows 10 64bit] Elpa build fails because pdf-tools.el determines wrong architecture

### ISSUE THREAD

**Issue by carlton87** [politza/pdf-tools#292]
I just started to try out Spacemacs (I started out with the emacs-w64 binaries). After including the pdf-tools layer the server build didn't succeed because it couldn't find the necessary compilers and libraries even though I installed MSYS2 and all the libraries (64 bit) described in the Readme ("Compilation and installation on Windows"). It turned out that the problem is in lines 297-303 of pdf-tools.el. The function
```elisp
(compile (format "%susr/bin/bash.exe --login -c 'MSYSTEM=%s source /etc/profile; LANG=C make V=0 -kC \"%s\" melpa-build'"
	   msys2-install-directory
	   arch
           build-directory))
```
gets the wrong value for `arch` from the previous line
```elisp
(let* ((arch (upcase (nth 2 (split-string system-configuration "-"))))
```
because it evaluates to `MINGW32` (`system-configuration` gives `x86_64-mingw32`) and thus doesn't access the previously installed mingw64 libraries. Manually changing `arch` to `MINGW64` solves the problem.

**Comment by politza** [comment]
Is there a way to correctly determine the system architecture ?

**Comment by carlton87** [comment]
@politza Since the scope of the code region in question seems to be only concerned with compiling via mingw on Windows it might be enough to check `(upcase (nth 0 (split-string system-configuration "-")))` which either evaluates to "I686" if emacs was built with mingw32 or to "X86_64" if emacs was built with mingw64. If it is a 32-bit emacs it should be likely that the mingw environment will also be 32-bit and analoguously for the case of a 64-bit emacs. Maybe this simple heuristic works and you could use something like
```elisp
(let* ((sysconf (upcase (nth 0 (split-string system-configuration "-")))))
  (if (string-equal sysconf "X86_64")
      (set 'arch "MINGW64")
    (if (string-equal sysconf "I686")
        (set 'arch "MINGW32")
      (message "System architecture could not be determined!"))
    )
)
```
could be used to set `arch` (I have never in my life written any elisp before, so please forgive me, if this code snippet is weird or anything).

**Comment by politza** [comment]
Makes sense.  I don't quite understand why `system-configuration`'s suffix is  _mingw32_, even though it is a 64bit build.

**Comment by politza** [comment]
c70520068cb316f736811e922a015347fdbcd30b

**Comment by carlton87** [comment]
@politza Thanks for patching it.
