### ISSUE TITLE
[macOS] Slow loading

### ISSUE THREAD

**Issue by justbur** [politza/pdf-tools#293]
I noticed pdf-tools was taking around 10sec to load. I'm on mac sierra with emacs 25.2.1. I profiled `(require 'pdf-tools)` starting from `emacs -Q` and got

```
- command-execute                                                4821  98%
 - call-interactively                                            4821  98%
  - funcall-interactively                                        4660  95%
   - eval-last-sexp                                              4169  85%
    - elisp--eval-last-sexp                                      4169  85%
     - eval                                                      4169  85%
      - require                                                  4159  84%
       - byte-code                                               4111  83%
        - require                                                4093  83%
         - byte-code                                             3957  80%
          - char-displayable-p                                   3754  76%
           - mapc                                                   1   0%
              #<compiled 0x4048f7a1>                                1   0%
          + require                                               133   2%
         + file-truename                                          109   2%
       + debug                                                     46   0%
   + execute-extended-command                                     491  10%
  + byte-code                                                     161   3%
+ ...                                                              73   1%
+ redisplay_internal (C function)                                   1   0%
```

Searching the code for `char-displayable-p` I only found [these lines](https://github.com/politza/pdf-tools/blob/master/lisp/pdf-view.el#L1110-L1117) which seem non-essential. After commenting these lines out, my load time fell to under a second. I don't know enough about fonts and such to go further.

**Comment by politza** [comment]
The purpose of the code is to display unicode character in the mode-line if an appropriate font is available. 
I remember there being a bug report about slow font look-up a couple of months ago, but can't seem to find it right now.

**Comment by justbur** [comment]
OK, it is something like that. I have a little more info. It was originally about 10sec for me to load. The font lookup was failing on the second character (the moon). I installed a font that had that character in it, and the load time fell to about 3-4sec. It's still much slower than the half second it takes to load when I comment those lines out, which is strange.

**Comment by politza** [comment]
I'm thinking of guarding this code with an undocumented variable, e.g. `pdf-view-inhibit-unicode-ligther`, since it seems this problem only occurs on very little machines.  Any opinion on this ?

**Comment by justbur** [comment]
Sounds good to me. I'm not that interested in unicode characters in the mode-line anyway. Thanks

**Comment by politza** [comment]
Ok, set `pdf-view-use-unicode-ligther` to nil before loading or customize it.

**Comment by justbur** [comment]
Thank you
		
		

		
	




On Fri, Aug 11, 2017 at 12:48 PM -0400, "politza" <notifications@github.com> wrote:












Ok, set pdf-view-use-unicode-ligther to nil before loading or customize it.
