### ISSUE TITLE
"No such annotation" when trying to save an exiting note

### ISSUE THREAD

**Issue by ghost** [politza/pdf-tools#294]
Keep getting this error, and forced to abandon changes made. Typically in buffer editing existing annotations;

```
pdf-info-query: epdfinfo: No such annotation: annot-11-1 [2 times]
Save changes to this annotation ? y
pdf-info-query: epdfinfo: No such annotation: annot-11-1
Save changes to this annotation ? y
pdf-info-query: epdfinfo: No such annotation: annot-11-1
Press C-c C-c to commit your changes, C-c C-q to abandon them.
```

epdfinfo seems to be working.

```
The epdfinfo program appears to be working.
```

**Comment by politza** [comment]
I need more info on this: What are the circumstances of this happening ? Is there a deterministic way, a recipe, to trigger this behavior ?

**Comment by usharf** [comment]
Still trying to reproduce... I had an impression that it happened when I browsed the PDF file I was annotating, while there was an active buffer displayed, editing a particular annotation. I'm not able to reproduce this though.

**Comment by politza** [comment]
Did you by any chance revert the document ?

**Comment by usharf** [comment]
I tried to explicitly revert (pdfview buffer) with ```C-S q``` but it says the buffer is "read only"... is there another waty I could have inadvertently done that?

```
command-execute: Buffer is read-only: #<buffer הד_הופמן_1994_יחידה 1 - מונטסקייה והמכתבים הפרסיים.pdf> [3 times]
No image animation. [2 times]
```

**Comment by politza** [comment]
What is this key bound to ?

**Comment by usharf** [comment]
it's boud to `revert-buffer` ... 

Strangely when using `C-S q` I see the read only buffer message, when invoking `revert-buffer` as a command, I'm warend ... 

```
Revert buffer from file /home/uri/Desktop/Bibliography/הד_הופמן_1994_יחידה 1 - מונטסקייה והמכתבים הפרסיים.pdf? (y or n) n
```

In any case, what's important is that I couldn't have reverted the buffer accidentally, I guess.

**Comment by usharf** [comment]
I'm able to see this message after explicitly delteing an annotation (in the pdfview buffer) while a buffer is opened with that comment's content for editing. 

When I try to commit (C-c C-c), I can see (in messages buffer the following:

```
Annotation deleted
pdf-info-query: epdfinfo: No such annotation: annot-1-0
```
First one fo the actual deletion (right click, delete);
Second line for trying to commit.
