### ISSUE TITLE
Running pdf-annot-delete with `C-c C-a D` fails with "No annotation at position"

### ISSUE THREAD

**Issue by LordZorgoth** [politza/pdf-tools#295]
The only way to effectively delete an annotation is to right click on it and delete, which works.

Running the command `pdf-annot-delete` or equivalently hitting `C-c C-a D` and clicking on the annotation results in the following error:

    No annotation at position

This appears to be the result of a bug in `pdf-annot-at-position`

**Comment by politza** [comment]
I believe it to be fixed with the latest commit.  Please give it a try and thanks for reporting it.

**Comment by LordZorgoth** [comment]
Thanks. It works now. I was almost done fixing it myself, but was beaten to it :D
