### ISSUE TITLE
How to update annotations properties i.e. subject...

### ISSUE THREAD

**Issue by usharf** [politza/pdf-tools#297]
The header of a buffer displaying an annotation seem to display some properties, but is there a way to actually edit them. Specificaly a subjet?

**Comment by politza** [comment]
Some properties can be changed, but I'm afraid there is not much of a
user-interface for doing so.  Anyway, here is a list:

* color
* contents
* edges
* flags
* icon
* is-open
* label
* opacity
* popup
* popup-is-open

This list is currently determined by what the back-end (poppler-glib)
supports.  As you can see, subject is not among those items.

**Comment by usharf** [comment]
I see. Thank you.
