### ISSUE TITLE
separate colors for different types of annotations (e.g. strike-out and highlight)

### ISSUE THREAD

**Issue by brittAnderson** [politza/pdf-tools#301]
If this can already be done, please tell me how. If not, it would be nice to be able to have, e.g. strike-outs black or red, but still leave highlights yellow. (enhancement)

**Comment by politza** [comment]
You could advice the interactive form of `pdf-annot-add-strikeout-annotation`.  

In short there is infrastructure for doing this, but no ui.

**Comment by brittAnderson** [comment]
First time I have tried anything like this. Came up with:

    (defun pdftools-strikeout-black (oldfun loe)
       (apply oldfun loe '("black")))

    (advice-add 'pdf-annot-add-strikeout-markup-annotation :around #'pdftools-strikeout-black)

Would appreciate any suggestions you have about this approach, and then feel free to close (or I can).

**Comment by politza** [comment]
I think it would be safer and more predictable to use the same arguments as the original function and then only pass your default color if the original argument is nil.  Or alternatively only ovveride the interactive form as I said earlier, at least I think that is possible with advice.  But as long as it works...

**Comment by politza** [comment]
61cff64edd177eeb26d067108f4337ef5293a5a5
