### ISSUE TITLE
Search with swiper shows garbage

### ISSUE THREAD

**Issue by cryoguy** [politza/pdf-tools#307]
Did anybody report that search pdf with emacs pdf-tools showing garbage?  C-r with regex search highlights the text ok.   Any thoughts and advice?

Thanks

**Comment by politza** [comment]
I guess, it takes the displayed text directly from the buffer, which contains the document's data (or "garbage" as you call it).  I think you should take this up with the swiper people.  I may assist, if they choose to do something about it.

**Comment by kevinrichardgreen** [comment]
I noticed this awhile ago too. I get around it by only using `isearch-forward` in PDFView buffers.  It's not as nice as swiper, but it gets the job done.
