### ISSUE TITLE
With dotspacemacs-line-numbers t, scrolling PDFs is slow and sluggish. PDF window blinks and hangs

### ISSUE THREAD

**Issue by LouisAsh** [politza/pdf-tools#308]
Since I was able to install `pdf-tools` to use in Spacemacs under Windows 10 64 bits, I have struggled with the following. Opened pdfs have been slow and sluggish to scroll. They also blink heavily when scrolling and occasionally lead Spacemacs to freeze. All that happens independently of if I scroll with the mouse wheel or keyboard, although the former is worse than the later.

After trying many different things, specially commenting on/out all lines in my `.spacemacs` file, today I finally found a way to extremely ameliorate the problem. For some reason, all that seems to be directly linked to having `dotspacemacs-line-numbers t`. When I set `dotspacemacs-line-numbers nil` then the scrolling becomes a thousand times better and smoother. And Spacemacs never freezes again.

In my ideal world, I would like to use one of the great things that Spacemacs bring from Vim, which is the relative line numbering. Thus, I also tried `dotspacemacs-line-numbers 'relative`. Unsurprisingly, that also gave the exact same problems (and made the situation very much worse in terms of slow scrolling).

I guess this might be somewhat related to an issue tickets posted last year: https://github.com/politza/pdf-tools/issues/189

Also, I think it might be good to mention that I have `latex` layer installed and active. But the problem appears even if I am opening a PDF file that is unrelated to any LaTeX file.

**Comment by politza** [comment]
Yes, [that](https://github.com/politza/pdf-tools#linum-mode) is a well-known problem and the spacemacs people should be aware of it.

**Comment by LouisAsh** [comment]
Oh, thanks for the feedback. I searched for a long time but never came across to that obvious reference there. Sure, it makes sense that activating any kind of `linum-mode` in a PDF buffer is a bad idea. But wouldn't it be then possible to have it activated only for the windows that have other buffers, not the PDF buffer?

**Comment by LouisAsh** [comment]
@politza Thanks for the feedback. I searched for a long time but never came across to that obvious reference there.

Sure, it makes sense that activating any kind of linum-mode in a PDF buffer is a bad idea. Nevertheless, and forgive my ignorance since I am just trying to understand the process, wouldn't it be then possible to have it activated only for the windows that have other buffers, not the PDF buffer?

Lastly, you mention that Spacemacs people should be aware of it. I got curious: was it a matter of speaking or is it a problem that is harder to solve for Spacemacs than for Emacs in general?

**Comment by vasselai** [comment]
@LouisAsh @politza I struggled with not being able to use line numbering + pdf-tools for quite a bit, then I found what seems to be quite an easy solution, not very well known. So I think it might be worth trying and seeing whether it works for others as well. Instead of having ` dotspacemacs-line-number t` or ` dotspacemacs-line-number 'relative` in the user-config session of my `.spacemacs` file, I did the following:

```
   dotspacemacs-line-numbers '(:relative t
                               :disabled-for-modes dired-mode
                                                   doc-view-mode
                                                   markdown-mode
                                                   org-mode
                                                   pdf-view-mode
                              )
```
That is, maybe the idea of enabling line numbers on a per-mode basis is indeed the path follow to solve this long-lasting issue.

**Comment by politza** [comment]
The solution for regular Emacs users is to not enable `global-linum-mode`, but do it only for specific modes, e.g. for all programming modes with

    (add-hook 'prog-mode 'linum-mode)

Here linum stands for whatever library is providing that feature (linum , nlinum, etc.).  I can't do much about it but [issue a warning](https://github.com/politza/pdf-tools/commit/b1784a144803103e6840369cb40a6cc2a776bb3b): I think it's to tricky attempting to deactivate this mode from inside pdf-tools.  So, I guess I want to close this issue at this point.
