### ISSUE TITLE
Jumping from latex source to PDF file does not work

### ISSUE THREAD

**Issue by andrewSteer** [politza/pdf-tools#309]
When working with AUCTeX, it is fairly intuitive how to jump from the PDF file to the respective location in the latex file: it is just about clicking a word in the PDF. However, I simply can't make it work the other way around. I have tried the `C-mouse-1` shortcut described in the README.MD, but nothing happens. Actually, I get the message in the bottom saying that `<C-mouse-1>` is undefined.

So, how could I jump from a given part of a latex file to its correspondent in the PDF file?

By the way, shouldn't such an important feature have a keybinding that is less hard to type, e.g. one that does not require a mouse click?

**Comment by ardpp** [comment]
The readme nothing says: 
```
jump to PDF location from source | C-c C-g
```
