### ISSUE TITLE
epdfinfo executable not found

### ISSUE THREAD

**Issue by boccaperta-it** [politza/pdf-tools#31]
I am on Debian sid, using GNU Emacs 25.0.50.1.
If I use your package by cloning the repo and building it following your instructions, everything works fine.
If I try to use the version now on MELPA it doesn't work. It is looking for epdfinfo executable and can't find it.
If you need me to do other tests or require other informations to better debug the issue please let me know.

**Comment by politza** [comment]
Either restart Emacs or make the variable `pdf-info-epdfinfo-program` point to the new `epdfinfo` executable in the new package directory.

**Comment by boccaperta-it** [comment]
```pdf-info-epdfinfo-program``` points to the new ```epdfinfo```. After restarting Emacs again, it now works.
So this is what I have done:
- remove old version pdf-tools (coming from github)
- installed pdf-tools from MELPA
- restarted Emacs: error about ```epdfinfo``` executable
- restarted Emacs again: success

**Comment by boccaperta-it** [comment]
You can close the issue. Just need to answer ```yes``` the first time I run Emacs after an upgrade from MELPA. Then, upon restart, Emacs finds ```epdfinfo``` and everything works fine.
