### ISSUE TITLE
NTEmacs using Cygwin compiled server causes path error when opening file

### ISSUE THREAD

**Issue by technician77** [politza/pdf-tools#310]
- I'm using NTEmacs `GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24` and `pdf-tools-20170908.108`
- I compiled the server using cygwin as instructed in the readme.
- After compiling I move epdfinfo.exe to cygwin64/bin
- In emacs I said no to compile the server
- Running `pdf-info-check-epdfinfo` gives me `The epdfinfo program appears to be working.`
- But when opening a pdf I get `File mode specification error: (error epdfinfo: Error opening z:/Test.pdf:The pathname “z:/Test.pdf” is not an absolute path)`

Any idea? Z:/Test.pdf seems a pretty absolute path to me.

Debugger Output:
```
Debugger entered--Lisp error: (error "epdfinfo: Error opening z:/Test.pdf:The pathname “z:/Test.pdf” is not an absolute path")
  signal(error ("epdfinfo: Error opening z:/Test.pdf:The pathname “z:/Test.pdf” is not an absolute path"))
  pdf-info-encrypted-p()
  pdf-view-decrypt-document()
  pdf-view-mode()
  set-auto-mode-0(pdf-view-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Test.pdf> "z:/Test.pdf" nil nil "z:/Test.pdf" (14636698789044557 1083207576))
  find-file-noselect("z:/Test.pdf")
  #[770 "\305\306r\211\203\205
```

**Comment by politza** [comment]
See #75, I don't know how to solve this.

**Comment by technician77** [comment]
How about keeping the issue open, since it is not solved? Maybe other people then see the open issue and post a pull request? Who would look in closed issues for open bugs to solve?
