### ISSUE TITLE
installation failed with spacemacs 0.200.9@25.2.2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by yubrshen** [politza/pdf-tools#311]
When I let spacemacs's layer for pdf-tools to install pdf-tools, I got the following error message:

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20170912.711/build/server/" -*-
Comint started at Tue Sep 12 09:45:47

/home/yubrshen/.emacs.d/elpa/pdf-tools-20170912.711/build/server/autobuild -i /home/yubrshen/bin/
error: file ‘nixpkgs’ was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13

Comint exited abnormally with code 1 at Tue Sep 12 09:45:50

```
However, if I manually execute the same command:
`/home/yubrshen/.emacs.d/elpa/pdf-tools-20170912.711/build/server/autobuild -i /home/yubrshen/bin/`

It worked. It seems to me that the script might confuse with my Ubuntu as Nixos when executing from emacs.

**Comment by politza** [comment]
The script looks for a `nix-shell` executable and will try to use that above all else.  Maybe that wasn't such a good idea.  I can't imagine how this error could happen without this program being installed, apparently not in a usable way.  The difference you described (regarding inside and outside Emacs compilation) may be explained by a different `PATH` setting.  Try `(executable-find "nix-shell")`.

**Comment by yubrshen** [comment]
Here is the execution result of (executable-find "nix-shell") in *scratch* of my emacs:
`"/home/yubrshen/.nix-profile/bin/nix-shell"`

I checked the above path does not exist in my computer. That may have caused the error message in emacs. 

However, why it did work outside of emacs with the same autobuild script? Maybe, it uses different scripts?

**Comment by politza** [comment]
Like I said, compare `(getenv "PATH")` with the output of `$ echo $PATH`.

**Comment by yubrshen** [comment]
Yes, you're right. The content from (getenv "PATH") has lots of
duplications. After removing the duplication, I found that the only
difference from that of 'echo $PATH' is just this:
/home/yubrshen/.nix-profile/bin
/home/yubrshen/.nix-profile/sbin

They are bogus paths. This may have suggested to the script of autobuild to
believe that it's a nixos system.

How can I fix this wrong PATH in emacs, while it's correct outside of emacs?

**Comment by politza** [comment]
The environment (including `PATH`) is usually inherited from the process starting the program, i.e. it depends on your setup.  You could hard-code it in Emacs using `setenv`.

I don't think these are "bogus", by which I under non-existent, paths.  The script looks for the executable `nix-shell` in `PATH` and uses it if found.  So, it must be around somewhere on your system, `M-! which nix-shell` should reveal where.
