### ISSUE TITLE
Let autobuild continue, even if system was not recognized

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#312]
Hello,

I am on RHEL 6.6 and I have the libpoppler dependency installed locally in my $HOME. I do not have sudo access so I cannot install stuff regularly (work machine).

So looks like the usual OS checks fail and I get 

> Failed to recognize this system

**Comment by kaushalmodi** [comment]
I can get the build to pass after I comment out the `exit 1 ` line in build/server/autobuild

```
os_nixos   "$@"	|| \
os_macos   "$@"	|| \
os_freebsd "$@" || \
os_arch    "$@"	|| \
os_centos  "$@"	|| \
os_fedora  "$@"	|| \
os_debian  "$@"	|| \
os_msys2   "$@"	|| \
{
    echo "Failed to recognize this system"
 #   exit 1
}
```

Also the new *Installation directory:* prompt feels strange.. Earlier it just installed in the elpa dir.

**Comment by politza** [comment]
"Feels strange" is not very specific.  The point of choosing a different directory is so that updating `pdf-tools` does not automatically enforce (in most cases needless) recompilation of the binary.

Anyway, its probably a good idea to just continue with the compilation, even though we are unable to install any packages. I can see that now.

**Comment by kaushalmodi** [comment]
> "Feels strange" is not very specific.

Sorry about that.. I meant that why even prompt for that directory name.. if `pdf-info-epdfinfo-program` is a string ending in "bin/epdfinfo", just install in that "bin/" directory if that directory exists.

I just updated my `pdf-info-epdfinfo-program` to be below.

```el
(defvar modi/pdf-tools-bin-directory (let ((dir (concat user-emacs-directory
                                                        "misc/pdf-tools/bin/"))) ; must end with /
                                       (make-directory dir :parents)
                                       dir)
  "Directory to hold the executable(s) for pdf-tools.")

(setq pdf-info-epdfinfo-program (expand-file-name "epdfinfo" modi/pdf-tools-bin-directory))
```

> Anyway, its probably a good idea to just continue with the compilation, even though we are unable to install any packages. I can see that now.

Thanks.

**Comment by politza** [comment]
I see.  But the directory of this variable should be the default anyway (unless it's inside the elpa directory), so it's just one more `RET`.

**Comment by kaushalmodi** [comment]
Earlier set the `epdfinfo` location to be inside Elpa dir set to the latest pdf-tools installation dir. So the prompt was even *stranger* :) .. it defaulted to `~/bin`. 

With the above setting, it atleast now defaults to where I like. But it's still *strange* as now 2 returns are needed.. one at the "you need to install the Pdf-tools" prompt and second at the Build installation directory prompt.

**Comment by politza** [comment]
`~/bin` is a standard directory for user installed binaries, nothing strange about it.  And I think the "2 key presses" discussion gets a little bit silly.  People may run their config on a plethora of systems and I don't want to silently install software on them based on some variable, which may not be setup properly for a particular system.

Anyway, I'm going to change the installation procedure, such that it'll fall through even though the system was not recognized.

**Comment by kaushalmodi** [comment]
> And I think the "2 key presses" discussion gets a little bit silly. People may run their config on a plethora of systems and I don't want to silently install software on them based on some variable, which may not even be setup properly for that particular system.

Fair point. Thanks!

**Comment by zakame** [comment]
>"Feels strange" is not very specific. The point of choosing a different directory is so that updating pdf-tools does not automatically force a (in most cases needless) recompilation of the binary.

Sorry to chime in, but for me, it does feel strange, because it broke my current install/configuration without providing some form of prior documentation and/or mechanism to facilitate moving towards your intended direction of prompting to user where to install epdfinfo (and what's more, it doesn't seem to be working correct as intended per #313.)

Also, regarding Linux OS detection: it seems poor form to detect based on the Linux distros or to distro-specific packages.  Wouldn't it be better to use `pkg-config` and detect by libraries instead, e.g. from my own use-package [config](https://github.com/zakame/.emacs.d/blob/master/init.el#L596-L603) of this:

```emacs-lisp
  :if (and (string= system-type 'gnu/linux)
           (eq (call-process-shell-command "pkg-config" nil nil nil "--exists" "poppler") 0))
```

**Comment by jabranham** [comment]
```
    (pdf-tools-build-server
     (lambda (success) (when success (pdf-tools-install)))
     (file-name-directory pdf-info-epdfinfo-program))
```

Thanks, that almost does what I want. Is there a way to stop it from attempting to use my package manager to install poppler and a few other packages? 

Of course, where before all I needed was:

```
(pdf-tools-install t)
```

now I have: 


```
(if (file-exists-p pdf-info-epdfinfo-program)
      (pdf-tools-install)
    (pdf-tools-build-server
     (lambda (success) (when success (pdf-tools-install)))
     (file-name-directory pdf-info-epdfinfo-program)))
```

to make sure that the epdfinfo program gets compiled if it's needed...

**Comment by politza** [comment]
Then you should be happy that you can revert to you old code.

I guess, I reconsidered and implemented @kaushalmodi suggestion, aka the previous behavior + install where `pdf-info-epdfinfo-program` points to.  Actually, this is much better and also easier for me.

@zakame  The purpose of  the OS-specific code is to install the right packages using the right package-manager.

**Comment by kaushalmodi** [comment]
Thanks! This is much better.. now I simply set `pdf-info-epdfinfo-program` and run `pdf-tools-install`. In addition, I realized a need to have this function:

```el
(defun modi/pdf-tools-re-install ()
  "Re-install `epdfinfo' even if it is installed.
The re-installation is forced by deleting the existing `epdfinfo'
binary.

Useful to run after `pdf-tools' updates."
  (interactive)
  (delete-file pdf-info-epdfinfo-program)
  (pdf-tools-install))
```

Now as the `epdfinfo` is not saved in elpa, it wouldn't get auto-re-installed after each pdf-tools update.

**Comment by politza** [comment]
(pdf-tools-install :no-query)

in your init would also work, unless the process exits for some reason after an update.
