### ISSUE TITLE
On newest emacs 26.0.50 the need to install server is whenever I start a new emacs

### ISSUE THREAD

**Issue by hisnawi** [politza/pdf-tools#313]
Whenever I start a new emacs instance I get the "server needs to be installed...etc" when hitting yes it doesn't default to the elpa/pdf-tools...etc directory instead to ~/bin.

I tried installing it in ~/bin and in the default directory (entering it manually ..../server) but it still keeps asking to install server on every new start.

And if I ignore the installing message PDF files don't open. I tried uninstalling pdf-tools and reinstalling it, but that did not help.

**Comment by politza** [comment]
Can you please post the output of the compilation process ?

**Comment by hisnawi** [comment]
I am on MAC if that makes a difference. In this case I selected the first option it gave me ~/bin.

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20170912.711/build/server/" -*-
Comint started at Tue Sep 12 12:41:47

/Users/hinawi/.emacs.d/elpa/pdf-tools-20170912.711/build/server/autobuild -i /Users/hisnawi/bin/
---------------------------
    Installing packages    
---------------------------
brew install pkg-config poppler automake
Warning: pkg-config 0.29.2 is already installed, it's just not linked.
You can use `brew link pkg-config` to link this version.
Warning: poppler 0.59.0_1 is already installed
Warning: automake 1.15.1 is already installed

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/hisnawi/bin/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes


---------------------------
       Installing          
---------------------------
make -s install
 ./install-sh -c -d '/Users/hisnawi/bin'
  /usr/bin/install -c epdfinfo '/Users/hisnawi/bin'
make[1]: Nothing to be done for `install-data-am'.

===========================
   Build succeeded. :O)    
===========================

Comint finished at Tue Sep 12 12:41:55

```

**Comment by hisnawi** [comment]
This is my emacs setup:

```
  (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-width)
    (bind-keys :map pdf-view-mode-map
               ("\\" . hydra-pdftools/body)
               ("<s-spc>" .  pdf-view-scroll-down-or-next-page)
               ("g"  . pdf-view-first-page)
               ("G"  . pdf-view-last-page)
               ("l"  . image-forward-hscroll)
               ("h"  . image-backward-hscroll)
               ("j"  . pdf-view-next-page)
               ("k"  . pdf-view-previous-page)
               ("e"  . pdf-view-goto-page)
               ("u"  . pdf-view-revert-buffer)
               ("al" . pdf-annot-list-annotations)
               ("ad" . pdf-annot-delete)
               ("aa" . pdf-annot-attachment-dired)
               ("am" . pdf-annot-add-markup-annotation)
               ("at" . pdf-annot-add-text-annotation)
               ("y"  . pdf-view-kill-ring-save)
               ("i"  . pdf-misc-display-metadata)
               ("s"  . pdf-occur)
               ("b"  . pdf-view-set-slice-from-bounding-box)
               ("r"  . pdf-view-reset-slice))
    (use-package org-pdfview
      :ensure t))

```

**Comment by politza** [comment]
* What's the value of `pdf-info-epdfinfo-program` after the installation ?
* Is there a message in the `*Messages*` buffer like "Building the PDF Tools server succeeded" ? 
* Can you open a shell and `cd ~/bin ; echo quit | ./epdfinfo` ?

**Comment by hisnawi** [comment]
pdf-info-epdfinfo-program value : /Users/hisnawi/bin/epdfinfo

Messages buffer has these lines:
Comint finished
Building the PDF Tools server succeeded
/Users/ammari/bin/epdfinfo

shell command:
➜  bin echo quit | ./epdfinfo
OK
.

Like I mentioned, I am able to open pdf files after the installation as everything seems normal. But once I close emacs and reopen it then I am unable to open any pdf files unless I install the server again.

**Comment by politza** [comment]
Well, I certainly didn't understand it that way.

The program's location is saved via customize. It's possible that your are not loading the `custom-file`.
Try to inspect it via `(find-file custom-file)`, it should contain the line

    '(pdf-info-epdfinfo-program "/Users/ammari/bin/epdfinfo")

As a workaround, put `(setq pdf-info-epdfinfo-program "/Users/ammari/bin/epdfinfo")`  in between the `:config` and `(pdf-info-install)` lines of your `use-package` form.

**Comment by hisnawi** [comment]
What is the custom-file? The evaluation of (find-file custom-file) yields void.

I actually prefer installing the server in its default location in the elpa directory.
1. So why I am not getting the option to install it there.
2. Why it is not recognizing that it was installed already on the next run.

**Comment by hisnawi** [comment]
I ran on an older version of emacs 25.2 which I used forever on a different machine. I updated pdf-tools package using list-packages and now I see the same behavior. It is keeps asking me to install the server every startup of emacs, and it doesn't have the elpa..etc path as a default, only ~/bin. I don't think it is a problem with custom-file...it is a problem with the latest update to your package.

**Comment by jabranham** [comment]
I just updated and am experiencing the same behavior. `(pdf-tools-install)` defaults to `~/bin`.

**Comment by zakame** [comment]
Chiming in to confirm reproducing this issue on Emacs 25.3 under Slackware 14.2-current.

**Comment by politza** [comment]
It defaulted to `~/bin` because that's what I've chosen as a default.  Anyway, I backtracked/reconsidered/gave up/became wise and more or less reinstated the old behaviour (d736cd4dfd8e51d53444f6c56f162d3d9a35ee26).

**Comment by hisnawi** [comment]
Good. Things are back to normal now. It installs the server in the default "elpa....etc" and it doesn't ask to resinstall on every new emacs instance.
