### ISSUE TITLE
Opening a second pdf file resets the first one

### ISSUE THREAD

**Issue by hisnawi** [politza/pdf-tools#314]
When I open a second pdf file I noticed that the first one gets reset to the first page. Is that an expected behavior? Is there an option to maintain where I am in the pdf file?

**Comment by politza** [comment]
Believe, it is not purposefully resetting the page.  
Usually this happens when you are using a window-layout package, which deletes and recreates windows.  Do you ?

**Comment by hisnawi** [comment]
Got it. Thanks.
