### ISSUE TITLE
Make autobuild work with Gentoo

### ISSUE THREAD

**Issue by politza** [politza/pdf-tools#316]
See the discussion starting at https://github.com/politza/pdf-tools/pull/296#issuecomment-328778675 .

**Comment by azahi** [comment]
On Gentoo ``poppler-glib`` can be installed with enabling ``USE="cairo"`` flag for ``app-text/poppler`` package.

**Comment by politza** [comment]
Like this 

    sudo euse -E -p app-text/poppler cairo

?

**Comment by azahi** [comment]
something like ``USE="cairo" emerge app-text/poppler`` should be sufficient

**Comment by westofer** [comment]
I did as you said, added '/usr/lib64' to my path and still didn't work
the reason was that emacs wanted libpoopler.so.99 and I had version 101

I did this and it worked
  sudo ln -s /usr/lib64/libpoppler.so.101 /usr/lib64/libpoppler.so.99

**Comment by westofer** [comment]
I also think it would be a good idea to  close the issue
