### ISSUE TITLE
auto-enable midnight mode

### ISSUE THREAD

**Issue by pprw** [politza/pdf-tools#317]
Is there a way to enable the midnight mode for all document opened with pdf-tools?

p-s : by curiosity, what does the "printed mode"? I see no difference

**Comment by politza** [comment]
How about this.
    (add-hook 'pdf-view-mode-hook #'pdf-view-midnight-minor-mode)

In "printed mode" the pdf is rendered like it would be printed, e.g.  without annotations.

**Comment by pprw** [comment]
Thanks !!

**Comment by pprw** [comment]
Is it possible to customize the colors used in the midnight mode? I use the tango-dark theme and want to have the same background / foreground color.
