### ISSUE TITLE
Doesn't build on Emacs 26

### ISSUE THREAD

**Issue by nyraghu** [politza/pdf-tools#318]
pdf-tools master doesn't build with Emacs 26 because Cask doesn't build with Emacs 26 [cask/cask#391].  pdf-tools bdfc54ad9f71080d37888f32c038589130da6b18 and earlier build successfully with Emacs 26.  The problem starts with pdf-tools 4e0c7a82ac2ec33d4262017107f3f9e19328ed05.  Since Cask doesn't seem to be actively maintained now [cask/cask#376], is it possible to revert to the earlier build system for pdf-tools, which doesn't use Cask?

**Comment by politza** [comment]
I was rather glad getting rid of it. 

The error may be a spurious one, which is not uncommon on Emacs master branch.  Let's see how this cask situation develops and leave it as it is for now.  Note that you can still build the package using a different Emacs,  (but still run it in any Emacs).
   
    EMACS=/path/to/emacs-25 make

**Comment by sambrightman** [comment]
Cask is being maintained and as far as I know has no issues on Emacs 26 for the last few months. I believe the main issue being referenced was a breaking change in `package-build` that was not originally accompanied by a version bump.
