### ISSUE TITLE
Any info as to how to make or use virtual PDFs

### ISSUE THREAD

**Issue by cryoguy** [politza/pdf-tools#321]
One of the best tools!!  Is there any info about how to make or use virtual PDFs?

**Comment by politza** [comment]
Try this.

1. Open a PDF in a directory with many more PDF files.
2. `M-x pdf-virtual-global-mode`
3. `M-x pdf-virtual-create-buffer`
4. `C-c C-c`

The file-format is explained in the buffer.  This would be much more fun, if we could display multiple pages (i.e. snippets of multiple math-definitions, which you can't seem to remember) per window.
