### ISSUE TITLE
`image-mode-map` is overridden by pdf-tools with Evil mode

### ISSUE THREAD

**Issue by Ambrevar** [politza/pdf-tools#324]
A minimal example run from Evil's `make emacs` (assuming pdf-tools and its dependency tablist are installed in package-user-dir):

```
(require 'package)
(setq package-user-dir "~/projects")
(setq package-load-list '((pdf-tools t) (tablist t)))
(package-initialize)
(require 'pdf-tools)
(pdf-tools-install)

(evil-set-initial-state 'pdf-view-mode 'motion)
(evil-define-key 'motion pdf-view-mode-map "j" 'pdf-view-next-line-or-next-page)
(evil-set-initial-state 'image-mode 'motion)
(evil-define-key 'motion image-mode-map "j" 'image-next-line)
```

Open an image file and press `j`: you'll get an error because it calls `pdf-view-next-line-or-next-page`.

I've also reported the issue on Evil's side: https://github.com/emacs-evil/evil/issues/938

**Comment by politza** [comment]
This is clearly a problem with evil, not pdf-tools.  The parent keymap of `pdf-view-mode-map` is set to `image-mode-map`, but defining keys in the former should have no effect on the later.

**Comment by Ambrevar** [comment]
Yes, but... Evil has no issue with other maps, not even parent maps.  I tested with text-mode and outline-mode: they are fine.

**Comment by politza** [comment]
Maybe the difference is that pdf-view-mode inherits from special-mode, but uses image-mode-map as parent keymap.

**Comment by wasamasa** [comment]
@Ambrevar Can you test whether https://github.com/emacs-evil/evil/pull/982 resolved this for you?

**Comment by Ambrevar** [comment]
It does! Thank you very much for this, that was a huge issue for github.com/jojojames/evil-collection.
