### ISSUE TITLE
magic-mode-alist file detection interferes with background functions

### ISSUE THREAD

**Issue by madalu** [politza/pdf-tools#328]
I find the recent addition of a magic-mode-alist detection (aaaaef6fbcd40364aea32013dcb12a31fa726523) is causing undesired behavior. This variable can have unexpected effects for users who use elisp functions to process buffers in the background. 

For instance, I have a gnus-mm function to convert pdfs to text within a mail buffer:

     (defun inline-no-pdf (handle)
       "Insert pdf attachment described in HANDLE into article buffer."
       (let ((file (mm-make-temp-file "pdf.")))
         (mm-with-unibyte-buffer
           (mm-insert-part handle)
           (write-file file))
         (insert (shell-command-to-string (concat "pdftotext -layout -nopgbrk " file " -"))))
       (goto-char (point-max))
       (mm-handle-set-undisplayer
        handle
        `(lambda ()
           (let (buffer-read-only)
             (delete-region ,(point-min-marker)
                            ,(point-max-marker))))))

It seems that because of magic-mode-alist detection, pdf-tools now tries to process the unibyte buffer above when the pdf attachment/handle is inserted. This results in the failure of the function and the following error messages:

Buffer pdf.89330eI modified; kill anyway? (y or n) y
pdf-info-query: epdfinfo: Error opening /tmp/pdf.89330eI:PDF document is damaged

I was wondering if this could be made an optional setting. The emacs manual (23.3) seems to suggest that this is a variable for users to configure:

>   Third, Emacs tries to determine the major mode by looking at the text at the start of the buffer, based on the variable ‘magic-mode-alist’. By default, this variable is ‘nil’ (an empty list), so Emacs skips this step; however, you can customize it in your init file.

**Comment by politza** [comment]
`write-file` visits the file, i.e. it installs some `major-mode' depending on the extension etc.  The function more suitable for your case would be `write-region` or `with-temp-file` .
