### ISSUE TITLE
Can't save file from /tmp to new location

### ISSUE THREAD

**Issue by entropiece** [politza/pdf-tools#33]
Hi, I download pdf files to `/tmp` and sometimes I need to save them to my home folder. However, when I use `C-x C-w` to `save-as`  (e.g. new file name `test.pdf`) I get 
`pdf-info-query: epdfinfo: Error opening /home/user/test.pdf:No such file or directory`

**Comment by politza** [comment]
Yes, that doesn't work at the moment.

**Comment by politza** [comment]
I think this is fixed here: 6ffd0b2ed5ad7eab9091c2eb99c94ec43a6aa0c8

**Comment by entropiece** [comment]
Yes updated the package and now everything works now. Thanks
