### ISSUE TITLE
Error with gnus-mime-copy-part and encrypted pdf

### ISSUE THREAD

**Issue by renatofdds** [politza/pdf-tools#332]
Opening an encrypted pdf from an email attachment with ```gnus-mime-copy-part``` fails with:
```
Debugger entered--Lisp error: (error "epdfinfo: Error opening /tmp/pdf-tools-24244QGo/example.pdf-24244HHy/example.pdf-242445QB:Document is encrypted")
signal(error ("epdfinfo: Error opening /tmp/pdf-tools-24244QGo/example.pdf-24244HHy/example.pdf-242445QB:Document is encrypted"))
error("epdfinfo: %s" "Error opening /tmp/pdf-tools-24244QGo/example.pdf-24244HHy/example.pdf-242445QB:Document is encrypted")
pdf-info-query(number-of-pages "/tmp/pdf-tools-24244QGo/example.pdf-24244HHy/example.pdf-242445QB")
pdf-info-number-of-pages()
pdf-cache-number-of-pages()
pdf-view-goto-page(1)
pdf-view-new-window-function((#<window 99 on example.pdf<2>> (window-size 105 . 18) (overlay . #<overlay from 1 to 71280 in example.pdf<2>>)))
run-hook-with-args(pdf-view-new-window-function (#<window 99 on example.pdf<2>> (window-size 105 . 18) (overlay . #<overlay from 1 to 71280 in example.pdf<2>>)))
image-mode-winprops(nil t)
image-mode-reapply-winprops()
read-string("Enter password for `~/example.pdf': " nil t nil)
read-passwd("Enter password for `~/example.pdf': ")
password-read("Enter password for `~/example.pdf': " "/pdf-tools/home/user/example.pdf")
(setq password (password-read prompt key))
(while (and (> i 0) (pdf-info-encrypted-p)) (setq i (1- i)) (setq password (password-read prompt key)) (setq prompt "Invalid password, try again: ") (condition-case nil (progn (pdf-info-open nil password)) (error nil)))
(let ((prompt (format "Enter password for `%s': " (abbreviate-file-name (buffer-file-name)))) (key (concat "/pdf-tools" (buffer-file-name))) (i 3) password) (while (and (> i 0) (pdf-info-encrypted-p)) (setq i (1- i)) (setq password (password-read prompt key)) (setq prompt "Invalid password, try again: ") (condition-case nil (progn (pdf-info-open nil password)) (error nil))) (pdf-info-open nil password) (password-cache-add key password))
(progn (let ((prompt (format "Enter password for `%s': " (abbreviate-file-name (buffer-file-name)))) (key (concat "/pdf-tools" (buffer-file-name))) (i 3) password) (while (and (> i 0) (pdf-info-encrypted-p)) (setq i (1- i)) (setq password (password-read prompt key)) (setq prompt "Invalid password, try again: ") (condition-case nil (progn (pdf-info-open nil password)) (error nil))) (pdf-info-open nil password) (password-cache-add key password)))
(if (pdf-info-encrypted-p) (progn (let ((prompt (format "Enter password for `%s': " (abbreviate-file-name (buffer-file-name)))) (key (concat "/pdf-tools" (buffer-file-name))) (i 3) password) (while (and (> i 0) (pdf-info-encrypted-p)) (setq i (1- i)) (setq password (password-read prompt key)) (setq prompt "Invalid password, try again: ") (condition-case nil (progn (pdf-info-open nil password)) (error nil))) (pdf-info-open nil password) (password-cache-add key password))))
pdf-view-decrypt-document()
pdf-view-mode()
set-auto-mode-0(pdf-view-mode nil)
set-auto-mode()
#[256 "\303 \210\211?\206	
```

OTOH if I use `gnus-mime-view-part` (which creates a temporary file) all works well.

**Comment by politza** [comment]
Are you entering a password ? Or are you saying that there should be no
password prompt at all ?

**Comment by renatofdds** [comment]
I'm entering the password. It errors after i submit the password.

**Comment by politza** [comment]
How do you know that you entered the correct password ?

**Comment by renatofdds** [comment]
Because if I save the attachment with ```gnus-mime-save-part``` and open the file normally (using the
same password) it works.

**Comment by politza** [comment]
I'm unable to reproduce this problem.  Sent myself a encrypted PDF and
gnus-mime-copy-part works just fine.

Does it accept the password you enter, or does it say "Invalid password,
try again " ?

**Comment by renatofdds** [comment]
Apparently it accepts, but spits:
```
File mode specification error: (error epdfinfo: Error opening /tmp/pdf-tools-877IYa/example.pdf-877Vig/example.pdf-877ism:Document is encrypted)
```
-- 
Att.,
Renato Ferreira

**Comment by renatofdds** [comment]
I found time to debug this issue and what ultimately happens is that due to various possible scenarios ```(pdf-info-query)``` gets called before the document is decrypted, which throws the error. 

Scenarios on which ```(pdf-info-query)``` gets called prematurely includes ```(gnus-mime-copy-part)``` for me because the buffer gets displayed before its decrypted and therefore: 
- mode-line updating -> mode-line constructs can query number-of-pages
- image-mode hooks gets called such as ```(pdf-view-maybe-redisplay-resized-windows)``` and ```(pdf-view-new-window-function)```

As a workaround, if i hoist ```(pdf-view-decrypt-document)``` on ```(pdf-view-mode)``` to just after ```(setq-local transient-mark-mode t)```, my scenarios are fixed, but it's important to notice that the race condition remains latent.

**Comment by renatofdds** [comment]
Any updates on this ?

**Comment by politza** [comment]
`pdf-view-decrypt-document` indirectly calls `accept-process-output`, which can run all kinds of code.  I think this is the root of all problems and arranging this call such that no %dangerous% calls will be made while waiting for its output should be a valid solution.

Anyway, I pulled the call  even closer to the beginning of the mode-function: 086fa62bbfc6e4b3353e6f149e360e02edac57ed .

I you have no objections, I'll push it later onto the master branch.

**Comment by renatofdds** [comment]
Please merge this branch cause it fixes the problem.

**Comment by renatofdds** [comment]
@politza has the fix been merged ?
