### ISSUE TITLE
Compilation on Ubuntu failing: cask not found

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [politza/pdf-tools#335]
I got an error, which I have never had before on Ubuntu (I couldn't figure out a root cause), which I solved. Cask was not being found, so I had to install it as per the official Cask website, running:

`$ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python`

Here was the error I was getting:

```
$ make -s
Using Emacs 25.3 
make: cask: Command not found
Makefile:44: recipe for target '.cask/25.3' failed
make: *** [.cask/25.3] Error 127
```
Here are the relevant lines in `Makefile`:
```
42# Init cask                                                                                                                                        
43.cask/$(emacs_version):
44        cask install
```
The Cask file is in the cloned repository and all stated dependencies are met. This didn't happen on the same Ubuntu 16.04 system about 6 months back.

**Comment by Nicholas-Mitchell** [comment]
Five months later and I am getting the same issue as described above, but this time my fix isn't working.

**Comment by djrmarques** [comment]
I am getting the exact same error too. Anyone found a fix?

**Comment by Proton-Panther** [comment]
same here.

**Comment by politza** [comment]
You probably need to install cask.

**Comment by politza** [comment]
Looks like [this cask issue](https://github.com/cask/cask/issues/421).

**Comment by Proton-Panther** [comment]
i am using arch linux and installed cask via AUR.
and it did not help, but i found a workaround by just installing via melpa.
all i needed to do was M-x package-refresh-contents and then M-x package-install pdf-tools.
not sure if that's the best way but worked for me

**Comment by lbkvu** [comment]
@Nicholas-Mitchell if you're on ArchLinux, use **cask-git** package instead of **cask**. It will solve the problem

**Comment by Cenderme** [comment]
Installing cask from the git repository fixed it for me.
`curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python`

**Comment by pepa65** [comment]
I'm on Ubuntu 20.04 and the suggested fixes didn't work. I did:
```
wget -O getcask raw.githubusercontent.com/cask/cask/master/go
python getcask
export PATH="~/.cask/bin:$PATH"
make -s
```
