### ISSUE TITLE
Feature: Support booklet, n-up, rotation (stapler, pdftk)

### ISSUE THREAD

**Issue by ecraven** [politza/pdf-tools#336]
Is there interest in supporting some of the pdftk/stapler operations in pdf-tools?
Possible use cases:
- Convert to booklet
- Convert to n-up format
- Rotate (some) pages
- Only select some / drop some pages
I'd be willing to work on this, if this is deemed useful. Right now, I use stapler, pdftk, psnup, etc. for this, but would prefer pdf-tools.

**Comment by politza** [comment]
Sounds like something that would perfectly fit in a auxiliary package.
