### ISSUE TITLE
Export outline as org file

### ISSUE THREAD

**Issue by manojm321** [politza/pdf-tools#338]
It will be nice If one can export the outline as an org file to take some notes.

**Comment by pprw** [comment]
+1

**Comment by apnewberry** [comment]
This functionality is `M-x org-noter-create-skeleton` from https://github.com/weirdNox/org-noter.

**Comment by lokihsx** [comment]
(defun pdf-outline-export-to-org ()
  " Export pdf outlines as org mode "
  (interactive)
  
  (let* ((pdf-buffer (current-buffer))
         (filename (file-name-sans-extension (buffer-name pdf-buffer)))
         (org-filename (concat filename ".org"))
         (outline-info (pdf-info-outline pdf-buffer)))

    ;; Insert outline heading
    (with-temp-buffer
      (org-mode)
      (insert (concat "#+TITLE: " filename "学习大纲\n"))
      (when outline-info
        (dolist (item outline-info)
          (let ((title (assoc-default 'title item))
                (page (assoc-default 'page item))
                (level (assoc-default 'depth item)))
            (insert (format
                     "%s [[pdfview:%s.pdf::%s][%s]]\n"
                     (make-string level ?*)
                     (concat default-directory filename)
                     page title))
            (org-set-property "page" (number-to-string page))
            (org-todo 'todo)
            ))
        (write-file (concat default-directory org-filename))))))

some code here

**Comment by whatacold** [comment]
@lokihsx Nice work, thanks.

It's awesome except that the link of pdf can't be open in org-mode with `org-open-at-point`,
not sure whether it's fault of my config.
Then I come up a way to fix it by replacing the org link type `pdfview:` with `file:`,
and customizing the `org-file-apps` variable.

Cheers!

``` emacs-lisp
(defun whatacold/org-pdf-app (file-path link-without-schema)
  "Open pdf file using pdf-tools and go to the specified page."
  (let* ((page (if (not (string-match "\\.pdf::\\([0-9]+\\)\\'"
                                      link-without-schema))
                   1
                 (string-to-number (match-string 1 link-without-schema)))))
    (find-file-other-window file-path)
    (pdf-view-goto-page page)))

(setq org-file-apps
      '((auto-mode . emacs)
        ("\\.x?html?\\'" . "firefox %s")
        ("\\.pdf\\(::[0-9]+\\)?\\'" . whatacold/org-pdf-app)
        ("\\.gif\\'" . "eog \"%s\"")
        ("\\.mp4\\'" . "vlc \"%s\"")
        ("\\.mkv" . "vlc \"%s\"")))
```

**Comment by vv111y** [comment]
fyi [org-noter](https://github.com/weirdNox/org-noter) does this with command ```org-noter-create-skeleton```.  
It will also give the option of extracting annotations (highlights, underlines, squigglies, text notes, strikeouts, links, ALL)  
It's been spectacular so far.
