### ISSUE TITLE
Warning: the use of `tempnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by TheJJ** [politza/pdf-tools#339]
```
epdfinfo-epdfinfo.o: In function `mktempfile':
~/.emacs.d/elpa/develop/pdf-tools-20171012.2226/build/server/epdfinfo.c:354: warning: the use of `tempnam' is dangerous, better use `mkstemp'
```

**Comment by politza** [comment]
I'm familiar with that warning. What's your point ?

**Comment by TheJJ** [comment]
To better use `mkstemp` :)

**Comment by politza** [comment]
Except that mkstemp is a different function, which does different things.

**Comment by TheJJ** [comment]
I can't tell if the usage of the function has security implications in that use-case, but I thought it was in your interest to get rid of compiler warnings. If you don't care, feel free to close the issue.

**Comment by politza** [comment]
It has as much security implications as opening any other file has.  

The warning is hard coded into the header file and AFAIK "ungetriddable".

Transfering data via a filename is part of the protocol and this name has to be created somewhere.

So everything has a reason. 

Please close it yourself or tell me why this has to be changed.  

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Jonas Jelten <notifications@github.com> </div><div>Datum:12.12.2017  0:29  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Warning: the use of `tempnam' is dangerous,
  better use `mkstemp' (#339) </div><div>
</div>I can't tell if the usage of the function has security implications in that use-case, but I thought it was in your interest to get rid of compiler warnings. If you don't care, feel free to close the issue.

**Comment by TheJJ** [comment]
It "has" to be changed to get rid of a compiler warning. I understand that it may not be feasible as the function shall return the file name only. I hoped to make the build warning-free, that's it.

**Comment by chiraag-nataraj** [comment]
Isn't the function `mktempfile` very similar to `mkstemp`? It generates a new filename and opens it, returning an error if the temporary file could not be created. I'm not too confident in my C, so I could very well be missing something...

**Comment by chiraag-nataraj** [comment]
I mean, the reason `tempnam` is considered dangerous is because of possible race conditions, and the usage of it here seems to be susceptible to that very issue.

**Comment by chiraag-nataraj** [comment]
Never mind, I see why this is an issue - you need the filename generated. I suspect that can be worked around, however, since `mkstemp` returns a file descriptor which we should be able to query to get the filename.
