### ISSUE TITLE
Some PDFs cause a full emacs freeze

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#34]
Also posted to http://permalink.gmane.org/gmane.emacs.help/102470

Attempting to open the following pdf (and I hate to think what other ones) with PDF Tools causes my emacs to freeze without listed error and it is unresponsive to C-g. I have to kill the process, which causes all kinds of problems. So far I'm not sure why; other PDFs work great.

http://orys.us/breaksemacspdf

I'm running PDF-Tools 20150129.1435 from MELPA, with GNU Emacs 24.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.10.9) of 2014-09-30 on buildvm-10.phx2.fedoraproject.org

**Comment by politza** [comment]
Should be fixed now. The reason was a invalid response, due to
`unusual` links in the PDf, which made Emacs wait forever.
