### ISSUE TITLE
Error while processing tq callback: Wrong type argument: listp, t

### ISSUE THREAD

**Issue by goodmami** [politza/pdf-tools#340]
I get the following error as soon as I load a PDF:

```
Debugger entered--Lisp error: (wrong-type-argument listp t)
  nconc(t t t t t t t t t t t t t t t t t t t t t t)
  apply(nconc (t t t t t t t t t t t t t t t t t t t t t t))
  pdf-annot-hotspot-function(2 (880 . 1138))
  #[257 "\211\300\301\"\207" [2 (880 . 1138)] 4 "\n\n(fn FN)"](pdf-annot-hotspot-function)
  mapcar(#[257 "\211\300\301\"\207" [2 (880 . 1138)] 4 "\n\n(fn FN)"] (pdf-annot-hotspot-function pdf-links-hotspots-function pdf-view-text-regions-hotspots-function))
  pdf-view-apply-hotspot-functions(nil 2 (880 . 1138))
  pdf-view-create-page(2)
  ; --- snip ---
  tq-process-buffer((nil #<process epdfinfo> . #<buffer  tq-temp-epdfinfo>))
  tq-filter((nil #<process epdfinfo> . #<buffer  tq-temp-epdfinfo>) "OK\n/tmp/epdfiSNti6s\n.\n")
  #[514 "\301\300\"\207" [(nil #<process epdfinfo> . #<buffer  tq-temp-epdfinfo>) tq-filter] 5 "\n\n(fn PROC STRING)"](#<process epdfinfo> "OK\n/tmp/epdfiSNti6s\n.\n")
```

(I omitted the lines after `pdf-view-create-page(2)`; then `tq-process-buffer` is the next function call. The temp file `/tmp/epdfiSNti6s` does not exist on my filesystem.)

At first I thought this was similar to #80, as I'm using a dark theme, but I get the error even when I start emacs with `emacs -Q` and execute only the following expressions:

```lisp
(package-initialize)
(pdf-tools-install)
(setq debug-on-error t)
```

I also tried: `package-delete<Enter>pdf-tools`, closing emacs, removing emacs, reinstalling emacs (25.1.1), starting emacs, `package-install<Enter>pdf-tools`. I installed pdf-tools 20171012.2226 from Melpa. Upon visiting a smallish PDF, it built the server without issue, and loaded the document with no errors. When I then visit a longer PDF without annotations, or one with annotations, I get the error above. This error consistently happens (or consistently doesn't happen) for the same PDFs.

I'm pretty new to elisp, but it looks like `pdf-annot-hotspot-function` is building a bad argument list for nconc. Is there anything I can try to help debug?

**Comment by goodmami** [comment]
Update: I was going to try building from source, but I decided to try the packaged version for Ubuntu 17.04. After installing `elpa-pdf-tools` and `elpa-pdf-tools-server` I was able to load and view PDFs with annotations. I still see some errors with annotations, such as `Wrong type argument: integer-or-marker-p, t` when i try to "Display Annotations" via the menu or C-c C-a l, but I think that's a separate issue.

As to the original issue, could there be some incompatibility with the Melpa version of pdf-tools?

**Comment by politza** [comment]
It seems that in order for this to occur the function `pdf-annot-create-hotspots` needs to return the value `t` and I don't see how this could be happening, unless the `push` macro was broken at the time pdf-tools was compiled, i.e. installed.  

Does page 2 of that document contain any annotations ?

I don't know whether the other error is related.  There could  be a connection due to the value `t`, though it's in a different context.

**Comment by goodmami** [comment]
> unless the push macro was broken at the time pdf-tools was compiled, i.e. installed.

My `.emacs` file loads some things (e.g., [here](http://svn.emmtee.net/trunk/dot.emacs)) that might change things for Franz Allegro lisp, but I don't see any indication that it changes the definition of `push`, and besides I tried starting emacs without loading these files. Is there any way I can test this?

> Does page 2 of that document contain any annotations ?

Actually no (although see next paragraph). They start on page 14. And I also noticed that I'm unable to view the pages with annotations. If I scroll down to page 13, then it stays on that page as I scroll until I get to the next page without annotations, at which point it jumps there.

Page 2 is the table of contents, which has links to chapters and sections. I recall in the `pdf-annot-hotspot-function` function there is a test for links (I guess links are annotations?), so maybe the problem isn't in `pdf-annot-create-hotspots` but in some faulty invocation of the `unless` macro there? I.e., maybe it's returning `t` when it encounters a link, rather than evaluating the next part?

And I got the same error for some PDFs without any annotations, such as this [Lenovo Thinkpad manual](https://cdn.cnetcontent.com/3a/1d/3a1da1db-75ae-4523-840e-db734d2fe746.pdf), although it probably has links.

**Comment by politza** [comment]
The 2nd form in your init file is a redefinition of `unless` which is the cause of this and most likely also of the other error.

**Comment by goodmami** [comment]
Yes, I saw that while I was writing the last comment, but I had to run and couldn't explore it further. I agree that the problem is with my setup and not with pdf-tools. Two things:

* I tried closing all instances of emacs and removing the line in my `.emacs` that loaded that file (the one redefining `unless`), but the problem persisted. Do you know if Emacs caches these definitions somewhere?
* This [EmacsWiki guide](https://www.emacswiki.org/emacs/WhenToUseIf) suggests `when` and `unless` should be used when the return value is unimportant. Maybe it would be better to use an `if` instead of `unless` here?

Meanwhile, I go ask the maintainer of that dot.emacs file why it's redefining `unless` and `when`.

**Comment by politza** [comment]
> * I tried closing all instances of emacs and removing the line in my
> `.emacs` that loaded that file (the one redefining `unless`), but the
> problem persisted. Do you know if Emacs caches these definitions
> somewhere?

Yes, in the bytecode of compiled files.  You need to remove those definitions and recompile (e.g. by reinstallation) all affected Lisp files.

**Comment by goodmami** [comment]
Thanks for all your help!
