### ISSUE TITLE
Org major-mode for Annotation Buffer

### ISSUE THREAD

**Issue by mankoff** [politza/pdf-tools#341]
Is there a way to add a hook so that annotation (note) buffers are in Org Mode? It would be nice to add longer text and even Org Babel code blocks in the comments/notes embedded in the PDF.

Possible side-effects or other changes that would help make this workflow smoother:

1) Make annotation buffers larger
2) Re-define `C-c C-c` so that it behaves as Org expects (e.g. execute Babel blocks) and doesn't terminate the annotation

**Comment by politza** [comment]
Take a look at pdf-annot-edit-contents-display-buffer-action and
pdf-annot-edit-contents-setup-function.
