### ISSUE TITLE
README is messy

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [politza/pdf-tools#345]
The "server prerequisites" [section](https://github.com/politza/pdf-tools#server-prerequisites) says : 
> You’ll need GNU Emacs ≥ 24.3 and some form of a GNU/Linux OS. Other operating systems are currently not supported (patches welcome).

However, reading the recent issues, it turns out that
* `pdf-tools` is installable on top of Cygwin and (at least) the Cygwin version of `emacs-w32` ;
* `pdf-tools` seems to be installable on Mac OS X.

Shouldn't this section read something like : 
> You'll need a platform able to compile and run some GNU/Linux utilities. The development is made on a GNU/Linux OS, and the following instruction work without modification on a Debian-like distribution. Note that some of these distributions (such as Debian) include binary packages of `pdf-tools` and the relevant server, thus avoiding the need for compilation.

> However, `pdf-tools` can also run on Mac OS X with the relevant libraries \<_Insert some relevant link_\>, Windows with the [Cygwin](https://www.cygwin.com/) library and utilities or the [Windows Subsystem for Linux](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) (usable with Windows 10 64-bit). Below, you may find installation instructions for some of these systems (complements and patches welcome...).

And possibly : 
> A binary executable of the port of the image server to Windows, for use with Gnu native Emacs [port](http://ftp.gnu.org/gnu/emacs/) is available at \<_some place_\>.

**Comment by politza** [comment]
The Readme is outdated in more than one place.
