### ISSUE TITLE
How to specify the resolution of an image capture?

### ISSUE THREAD

**Issue by kskyten** [politza/pdf-tools#348]
Thans for making pdf-tools. It's awesome.

I'm trying to automate the generation of outlines for pdfs that are missing them using OCR. The image captured by pdf-tools was too low resolution for OCR to work. Is it possible to specify the resolution for the output image? Alternatively, how do I use the edges from a selection to extract the image using imagemagick?

**Comment by politza** [comment]
Take a look at the pdf-info-renderpage function.

**Comment by kskyten** [comment]
Not sure what I'm looking for. I suppose `(pdf-info-renderpage page width :crop-to region)` captures the correct region. Is the resolution controlled by the `width` argument?

**Comment by politza** [comment]
Yes.
