### ISSUE TITLE
Default markup colors 

### ISSUE THREAD

**Issue by pank** [politza/pdf-tools#35]
It seems all of the `pdf-annot-add-*-markup-annotation` functions support color.  I have not found a way to set the color persistently, and for some reason the default color on my system (Gnome 3.14) is black...

![screenshot of dark highlight](http://i.imgur.com/KEpMqlB.png)

I don't know if it depends on the `region` face, which for some reason takes on `foreground: gtk_selection_fg_color` and `background: gtk_selection_bg_color` which either are weird or wrong (black on black) .

Would it be possible to add default values to colors for markups?

Thanks,
Rasmus

**Comment by politza** [comment]
Yes, you can define initial annotation attributes via `pdf-annot-default-markup-annotation-properties`, though this is not very well documented at the moment. E.g.:

    (push '(color . "orange") pdf-annot-default-markup-annotation-properties)

I should probably add a default color.

You can change the color by right-clicking the annotation.  Whatever you choose, will be added to `pdf-annot-color-history` and also serve as the current default color (provided above defaults don't contain a color key).  This variable should be persistent, provided `savehist-mode` is activated.

**Comment by pank** [comment]
politza <notifications@github.com> writes:

> Yes, you can define initial annotation attributes via
> `pdf-annot-default-markup-annotation-properties`, though this is not
> very well documented at the moment. E.g.:
>
>     (push '(color . "orange") pdf-annot-default-markup-annotation-properties)
>
> I should probably add a default color.

Perfect.  Maybe at least put it in the commentary-section of
`pdf-annot.el`.

> You can change the color by right-clicking the annotation.  Whatever
> you choose, will be added to `pdf-annot-color-history` and also serve
> as the current default color (provided above defaults don't contain a
> color key).  This variable should be persistent, provided
> `savehist-mode` is activated.

Yeah, I tested if this was saved and it was not.  I have `savehist-mode`
activated, but I do not see persistence over saves, even for the same
file.

Thanks,

**Comment by politza** [comment]
> Yeah, I tested if this was saved and it was not.

I think this is the real problem.  So I am going to fix this and leave the defaults alone, since
it's seems to be more likely that you want to reuse the last used color instead of a constant one.

**Comment by pank** [comment]
politza <notifications@github.com> writes:

>> Yeah, I tested if this was saved and it was not.
>
> I think this is the real problem.  So I am going to fix this and leave the defaults alone, since
> it's seems to be more likely that you want to reuse the last used color instead of a constant one.

I see.  Yet the default black (if that is indeed the default) is no good.
So even a better default would be good.  So if last color is saved
somewhere it would be good if the initial color would be, say, yellow.

—Rasmus

-- 
And I faced endless streams of vendor-approved Ikea furniture. . .

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> I see. Yet the default black (if that is indeed the default) is no
> good.
> So even a better default would be good. So if last color is saved
> somewhere it would be good if the initial color would be, say, yellow.

The way it currently is (pdf-annot-default-markup-annotation-properties
superseding the history), the best would probably to populate the
history with an initial color.

**Comment by pank** [comment]
I think it would be better to use a yellow by default for markups (rather than red).  For instance Evince uses `#ffff00`.  I find `#ffd700` to be very nice.  This is very minor though so (obviously/always) feel free to ignore.

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> I think it would be better to use a yellow by default for markups

Done.

**Comment by pank** [comment]
politza <notifications@github.com> writes:

> pank <notifications@github.com> writes:
>
>> I think it would be better to use a yellow by default for markups
>
> Done.

I tested this from my other PC and everything seems to work as expected
out of the box now.

Thanks,
Rasmus

-- 
May the Force be with you

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> I tested this from my other PC and everything seems to work as
> expected
> out of the box now.

OK, thank you.
