### ISSUE TITLE
Text annotations not visible on OSX/Preview and derived tools

### ISSUE THREAD

**Issue by mickesv** [politza/pdf-tools#354]
I know this is most likely not related to pdf-tools, but I would appreciate a discussion about it anyway. 

I recently noticed that text annotations I create in pdf-tools are not visible in OSX/Preview and other tools that use the same rendering engine. They show up as a yellow box in the document, but there is no text associated with them, and clicking on them does nothing.

The annotations are, however, there as they should be when opening the document in Adobe Acrobat, so I don't think there is anything wrong per se with how pdf-tools creates and stores the annotations, but maybe the annotations are not created *right enough*. 

Do you have any ideas about what might be going on?

**Comment by arademaker** [comment]
Is it related to #399?

**Comment by mickesv** [comment]
I think maybe #399 is a combination of several issues?

Here is the current status: I deleted the pdf-tools directory from `~/.emacs.d/elpa/`, ran `M-x package-refresh-contents`, then rebooted emacs. I now have `pdf-tools-20190301.2214`.

I then created a text annotation in a test-PDF and opened it in what I have available:

- Skim :: white box with grey outline instead of the little icon, not clickable.
- Preview :: white box with grey outline instead of the little icon, opens an empty annotation box that I can edit, but the text that I entered in pdf-tools is not there.
- Adobe Acrobat Pro :: As in Preview

**Comment by politza** [comment]
Are you able to create an annotation using evince or okkular and test that ?

**Comment by mickesv** [comment]
For you, anything. :-) 500 dependencies later, I now have Evince installed.

Annotations created in Evince work in Preview, Acrobat, and PDF-tools. Annotations created in PDF-tools show up in the same way in Evince as it did in preview.

**Comment by politza** [comment]
Mikael Svahnberg <notifications@github.com> writes:

> Annotations created in PDF-tools show up in the same way in Evince as
> it did in preview.

So, you are saying that text-annotations created in pdf-tools do not
display properly in Evince ? Because this works on my machine.

**Comment by mickesv** [comment]
Weird. I re-did the tests from yesterday, and now it works (Annotation in PDF-tools works as intended in evince).

**Comment by arademaker** [comment]
What is the reason for this problem? I thought pdf has only one api for annotations

**Comment by politza** [comment]
A PDF consists basically of a number of dictionaries with key/value
pairs and each one might be interpreted slightly different by different
PDF reader/creator.  E.g. by not reading the standard closely, which I
might be guilty of.

Regarding text-annotations it's a three step process with poppler-glib:

1. Create the annotation.

2. Create the region it applies to.

3. Add the annotation with the region to the document.
