### ISSUE TITLE
jump to PDF location from source won't work with multiple tex files

### ISSUE THREAD

**Issue by imyanggao** [politza/pdf-tools#355]
Hi,

I find a problem when working with multiple tex files for the jump from source to pdf functionality. For example, if we have two tex file, main.tex and chap1.tex, and in main.tex we use \include{chap1} to contain chap1, finally we generate a single main.pdf with pdflatex.  In this scenario, "jump to PDF location from source" with C-c C-g don't work when I am working on chap1.tex. The error is reported as follows:
epdfinfo: Error opening chap1.pdf: No such file or directory

But interestingly, the inverse function "jump source location from PDF" works great when I am using the mouse to click on main.pdf, and pdf-tools takes me to the right location in chap1.tex. 

Hopefully, this would help reproduce the issue and thank you for the authors to provide such a great tool.

Best,
Yang

**Comment by politza** [comment]
The wrong filename `chap1.pdf` is reported by the function `TeX-master-file' from auctex.  You need to properly setup your project.
