### ISSUE TITLE
Display pdf in other frame without splitting current frame

### ISSUE THREAD

**Issue by DrWaleedAYousef** [politza/pdf-tools#356]
For my working env., I need the tex and the pdf in two separate frames (not buffers) so that after AucTex the pdf opens in the other frame. I like the pdf to be open always on that frame so that when I re-compile, the pdf in that frame refreshes. All of that happens nicely, however, with the undesired action that the Tex frame splits to show the pdf. So, at the end I have the pdf opened once in the separate frame and second in the split tex buffer. I have to keep closing it after each compilation!

Another undesired effect is this: when I reverse sync from the pdf frame it splits this frame and opens a second tex buffer. It does not use the already opened tex frame.

**Comment by politza** [comment]
Please ask on http://emacs.stackexchange.com , as this is a general question about buffer display in Emacs.
