### ISSUE TITLE
Feature request: Support AUCTeX region files in backward search

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#36]
AUCTeX supports compiling only a given region (for speedy compilation of the part you currently work on in large TeX docs).  It does that by creating a region file (`TeX-region`) containing the header of your document, the marked region, and the trailer, and then compiles that.

Now it would be awesome if when you open the `TeX-region` PDF with `pdf-view-mode` and double-click in there, you'd backward search to the original tex document, not the artificial `TeX-region` file.

The `TeX-region` file's buffer (which you can assume exists) has a buffer-local variable `TeX-region-orig-buffer` naming the buffer the region is extracted from, i.e., the buffer where you actually want to jump to.  Now what's missing is the right line number which you can compute from the offset markers like `\message{ !name(the-real-doc.tex) !offset(353) }` that are placed just before and after the cut out region.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> Now it would be awesome if when you open the TeX-region PDF with
> pdf-view-mode and double-click in there, you'd backward search to the
> original tex document, not the artificial TeX-region file.

I think the function doing the redirection job should be part of auctex
and not pdf-tools. E.g. if the macros involved change at some point in
the future.

I guess there could be a hook function of some kind for this in
pdf-tools.

**Comment by tsdh** [comment]
Yes, there must be a hook or something that calls such a redirection function with the file/line/column information. That function would return f/l/c information again that are used instead of the original one.

I guess a plain variable pdf-sync-redirect-tex-function will do. I don't see the need for a hook which implies that you can add multiple functions.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> I guess a plain variable pdf-sync-redirect-tex-function will do.

Yes.
