### ISSUE TITLE
Emacs sub-process epdfinfo suddenly take high CPU on some triggers

### ISSUE THREAD

**Issue by stardiviner** [politza/pdf-tools#361]
When I switching window with `[C-x o]` or with `ace-window`, or split-window on PDF
buffer, or change PDF window size. The sub-process `epdfinfo` will suddenly take a
high CPU resource. I tried to use Emacs built-in `profiler`. But have not found any pdf-tools related functions invocation high CPU resource. Might because `epdfinfo` is a sub-process.

**Comment by politza** [comment]
At certain times some pages are speculative pre-rendered, which is CPU intensive. Does not look like a problem to me.

**Comment by stardiviner** [comment]
I see, thanks :)
