### ISSUE TITLE
Export highlighted text + annotations

### ISSUE THREAD

**Issue by trenkert** [politza/pdf-tools#364]
I think a context-menu function to export the highlighted text of a pdf as, for instance, blockquotes into org-mode would be very interesting. Similar to the approach here: http://tech.memoryimprintstudio.com/pdf-annotation-related-tools/

Another further enhancement would be to define more than one highlight color and let them be associated with specific org-mode properties, tags or keywords. This way, a red highlight could be exported as TODO and so on:

```
* TODO thesis.pdf p. 251 :bad_grammar:

#+BEGIN_QUOTE
I can't get no satisfaction!
#+END_QUOTE

** annotation
no double negations!

```

**Comment by et2010** [comment]
org-noter can extract outline and highlight positions: https://github.com/weirdNox/org-noter

I implement highlight extraction on my fork. But I have no idea on how to extract annotations. Would you shed some light on this? @politza 

Also, I use the function from this [link](https://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/) to extract highlighted text:

``` emacs-lisp
;; this is stolen from https://github.com/pinguim06/pdf-tools/commit/22629c746878f4e554d4e530306f3433d594a654
(defun pdf-annot-edges-to-region (edges)
  "Attempt to get 4-entry region \(LEFT TOP RIGHT BOTTOM\) from several edges.
We need this to import annotations and to get marked-up text, because annotations
are referenced by its edges, but functions for these tasks need region."

  (let ((left0 (nth 0 (car edges)))
        (top0 (nth 1 (car edges)))
        (bottom0 (nth 3 (car edges)))
        (top1 (nth 1 (car (last edges))))
        (right1 (nth 2 (car (last edges))))
        (bottom1 (nth 3 (car (last edges))))
        (n (safe-length edges)))
    ;; we try to guess the line height to move
    ;; the region away from the boundary and
    ;; avoid double lines
    (list left0
          (+ top0 (/ (- bottom0 top0) 2))
          right1
          (- bottom1 (/ (- bottom1 top1) 2 )))))
```

However, sometimes the extracted text may lose some lines, especially when the PDF is multi-column layout. Any ideas?

**Comment by politza** [comment]
Markup-annotations have an associated area to which they apply.  In the simplest case, it's a list with a single list of edges, i.e. top, left, bottom and right.

But in general it may contain multiple elements, e.g. if multiple non-contiuous paragraphs are part of the same annotation (usually created via shift (or was it ctrl?) -click.

The function you've posted discards these other edges and may therefore extract the text only partially.

**Comment by politza** [comment]
Anyway, out of the scope of this package.
