### ISSUE TITLE
Ugly pdf rendering, solutions ?

### ISSUE THREAD

**Issue by hubgitname** [politza/pdf-tools#365]
Hi, 
For the most part, opening the pdfs works great and most functionalities are working well.
Just that the pages rendered look ugly compared to opening on an external pdf reader.
Is there some config that can make it look better ? Maybe an option to change the backend
rendering engine, anti-aliasing etc. ?  Please see the attached pic: left is pdf-tools right is the Clearview app on MacOS.
<img width="1266" alt="pdf-tools_vs_clearview" src="https://user-images.githubusercontent.com/37636187/38213084-e3326540-3674-11e8-991b-78f3cdc5ebfc.png">

Thanks.

**Comment by yanghaoxie** [comment]
Which mode are you in? doc-view-mode or pdf-view-mode? if it is former, try change it to pdf-view-mode.

**Comment by politza** [comment]
Looks to me like the difference lies in the usage of different fonts for
this document.  It probably looks the same in other poppler-based
viewer, e.g. evince.

**Comment by politza** [comment]
Most likely this: #51 .
