### ISSUE TITLE
Unable to select text in pdf-tools...

### ISSUE THREAD

**Issue by louiscleung** [politza/pdf-tools#366]
hi,
I've installed pdf tools for emacs (Mac OSX 10.12.6, Emacs 25.4.1), but for some reason, Add Markup Annotation is greyed out (See screenshot) and I cannot select text, which gives this error:

`x-create-frame-with-faces: Wrong type argument: integerp, (0.5)`

Any ideas? anyone seen that before?

Thanks to anyone who can help, it would boost my workflow a lot if i could highlight + annotate pdfs from within emacs!

<img width="265" alt="screen shot 2018-04-06 at 7 25 39 pm" src="https://user-images.githubusercontent.com/32150215/38450296-63bb671c-39d0-11e8-938f-e5880f9b35b0.png">

**Comment by louiscleung** [comment]
It took a while to narrow down in my .emacs but turns out it has nothing to do with pdf-tools itself but was a conflict from settings I use to auto adjust the emacs window size on start up.

`(add-to-list 'default-frame-alist '(height . 50)) 
 (add-to-list 'default-frame-alist '(width . 170))`

Commenting them out brought back the option to add markup annotations and to select/copy and highlight annotations.

**Comment by jussiviinikka** [comment]
I'm having the same or similar problem, can't select text and the "add markup annotation" option is greyed out. 

I'm on OSX running
GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2019-10-05

installed from 
https://github.com/railwaycat/homebrew-emacsmacport

When I try to select text I get this message in the minibuffer:
```
invalid function track-mouse
```

and this in the messages buffer:
```
pdf-view-mouse-set-region: Invalid function: track-mouse 
```

I load pdf-tools with use-package like:
```
(use-package pdf-tools
 :pin manual ;; manually update
 :config
 ;; initialise
 (pdf-tools-install)
 ;; open pdfs scaled to fit page
 (setq-default pdf-view-display-size 'fit-page)
 ;; automatically annotate highlights
 (setq pdf-annot-activate-created-annotations t)
 ;; use normal isearch
 (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward))
```

The original issue refers to conflict arising from some window size settings, but disabling this (the only setting of this type I think I have) did not help:
```
(add-to-list 'default-frame-alist '(fullscreen . maximized))
```

I have tried to select text both with mouse and touchpad, but no success. Not sure if its related somehow but right clicking on the opened pdf with mouse works (opens the pdf-tools menu), but ctrl+touchpad (works as right click in most places) does not. 

Also not sure if this has anything to do with it but while debugging this I occasionally get something like this to terminal:
```
Emacs[40477:2764356] -_continuousScroll is deprecated for NSEventTypeScrollWheel. Please use -hasPreciseScrollingDeltas.
```

Any ideas?

**Comment by politza** [comment]
`track-mouse` is a core macro defined in subr.el .  You've likely broken something in your init-file.

**Comment by jussiviinikka** [comment]
I created a minimal init.el to check this. I didn't touch the PDF-Tools installation.

init.el:
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)
(use-package pdf-tools
 :pin manual ;; manually update
 :config
 ;; initialise
 (pdf-tools-install)
 ;; open pdfs scaled to fit page
 (setq-default pdf-view-display-size 'fit-page)
 ;; automatically annotate highlights
 (setq pdf-annot-activate-created-annotations t)
 ;; use normal isearch
 (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward))
```

C-h v says when opening pdf file:
```
major-mode is a variable defined in ‘C source code’.
Its value is ‘pdf-view-mode’
Original value was fundamental-mode
Local in buffer lecture1-2018-09-05.pdf; global value is fundamental-mode

  Automatically becomes buffer-local when set.

Documentation:
Symbol for current buffer’s major mode.
The default value (normally ‘fundamental-mode’) affects new buffers.
A value of nil means to use the current buffer’s major mode, provided
it is not marked as "special".

You can customize this variable.
```

The problem remains. I can select text with mouse/touchpad from other buffers (with the original init.el too).

**Comment by politza** [comment]
Open pdf-view.elc and see if it contains the symbol track-mouse. If so your installation is broken: Delete the package, restart Emacs, reinstall.

**Comment by jussiviinikka** [comment]
Did this, works now, thanks! Not sure how I broke it in the first place, but I now cloned the repository to `~/.emacs.d/elpa`and removed the `:pin manual` from call to `use-package` and it installed fine & mouse selection works.
