### ISSUE TITLE
Error 255 when compiling on macOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by zenshinji** [politza/pdf-tools#367]
I am installing pdf-tools on a recently rebuilt Mac. After following the instructions in the README and manually installing tablist, undercover, and ert-runner from MELPA, and ignoring the tempnam warning I get the following:

```
$ make -s
Using Emacs 25.3

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is provided for compatibility reasons only. Due to
      security concerns inherent in the design of tempnam(3), it is highly recommended that you use mkstemp(3) instead.
      [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");
                  ^
/usr/include/stdio.h:306:1: note: 'tempnam' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in th...
^
/usr/include/sys/cdefs.h:180:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((deprecated(_msg)))
                                                      ^
1 warning generated.
Wrong number of arguments: #[(rcp version) "!!È
\"Ä\"
(
ÊË$(ÌÍ
        \"4ÎÏ
               \"[
                   GÐUGÑ
                        @@	$[Ð
                                    GWXÒ
                                        	$[ÎÓ!," [rcp source-dir file-specs files name package-build-default-files-spec package-recipe--working-tree package-build--config-file-list package-build-expand-file-specs eieio-oref ...] 6 ("/Users/paul/.emacs.d/.cask/25.3/bootstrap/package-build-20180330.2032/package-build.elc" . 30212)], 5
make: *** [pdf-tools-.tar] Error 255
```

Any idea how to unwedge this?

Thanks!

**Comment by slavniyteo** [comment]
The same error on **Ubuntu 16.04.4**

Emacs version: 24.5
Pdf-tools version: 0.90 (last commit on master)

**Comment by ipstone** [comment]
I have the same compiling error on mac os x:

sing Emacs 25.3
Wrong number of arguments: #[(rcp version) "!!È
\"Ä\"
(
ÊË$(ÌÍ
        \"4ÎÏ
               \"[
                   GÐUGÑ
                        @@  $[Ð
                                    GWXÒ
                                            $[ÎÓ!," [rcp source-dir file-specs files name package-build-default-files-spec package-recipe--working-tree package-build--config-file-list package-build-expand-file-specs eieio-oref ...] 6 ("/Users/_user_/.emacs.d/.cask/25.3/bootstrap/package-build-20180330.2032/package-build.elc" . 30212)], 5
make: *** [pdf-tools-.tar] Error 255

**Comment by politza** [comment]
I think what's going on is that cask depends on a function
(package-build-package) in a library
(https://github.com/melpa/package-build), which has changed it's
signature sometime in the last year.

Maybe a fallout from the unmaintainedness of the cask package.

**Comment by ipstone** [comment]
idea/suggestion for a fix?

**Comment by politza** [comment]
Install from melpa or build a package by hand.

**Comment by zenshinji** [comment]
I did install manually from Melpa. It raised another issue which I will open separately. But that approach solved this issue. Closing.

**Comment by politza** [comment]
Install pdftools from melpa.

**Comment by zenshinji** [comment]
I downloaded the pdf-tools package from the MELPA site. Then in Emacs I did a M-x 'package-install-file' for the downloaded MELPA file.
