### ISSUE TITLE
Add ability to "stamp"

### ISSUE THREAD

**Issue by publicimageltd** [politza/pdf-tools#368]
I love using emacs to grade academic papers, and so: thanks for making it possible with pdf-tools. I am missing a few things, but what I miss most is the ability to add "stamps" in the margins of the paper I correct. So is it difficult to implement something so that chosen images can be added ad a given position?

**Comment by sje30** [comment]
yes please.  (Or another application is signing a pdf using a predefined bitmap.)

**Comment by politza** [comment]
Check if it's supported by poppler, write a patch and I'll merge it.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Stephen Eglen <notifications@github.com> </div><div>Datum:06.05.2018  7:12  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Add ability to "stamp" (#368) </div><div>
</div>yes please. (Or another application is signing a pdf using a predefined bitmap.)

**Comment by sje30** [comment]
Thanks.  Unfortunately I can't see anything resembling an ImageAnnotation in the poppler src.
