### ISSUE TITLE
Cannot display any pdf (pdfinfo server quit)

### ISSUE THREAD

**Issue by pprw** [politza/pdf-tools#371]
Pdf-tools was working perfectly for months. But today I have an error "The epdfinfo server quit" (which seems unrelated to [this bug report](https://github.com/politza/pdf-tools/issues/246)).

I cannot ready any pdf (It displays in coded text).

Any idea?

![capture du 2018-04-19 15-17-11](https://user-images.githubusercontent.com/5262986/38993768-cd683b2c-43e4-11e8-9034-eb3dad9c5981.png)

**Comment by pprw** [comment]
Zathura isn't working eitheir.
```

$ zathura
zathura: symbol lookup error: zathura: undefined symbol: synctex_next_result

```

Evince and mupdf are working fine.

**Comment by pprw** [comment]
Zathura was fixed by a update yesterday. So it's a bug from pdf-tools alone.

**Comment by politza** [comment]
There is nothing I can go on here, way to unspecific.

**Comment by pprw** [comment]
What information can I provide? Which logs do you need?

In fact, I can display pdf but the synctex option is not working and I have the message   
"The epdfinfo server quit unexpectedly." every time when I open pdfs.

I have other computer running debian unstable and all are affected.

**Comment by politza** [comment]
My best bet is that you installed new versions of one or more libraries, while epdfinfo is still linked against the old ones.
