### ISSUE TITLE
clicking on external links fails for some links

### ISSUE THREAD

**Issue by jlapeyre** [politza/pdf-tools#375]
When viewing a pdf in emacs using pdf-tools, clicking on links to urls containing parens  `(`, `)` fails to open the page. The characters in the url following the close paren `)`, are removed from the url when it appears in the browser (chrome or firefox).  I have noticed this for the past couple of years. But, in particular on the versions below. Note that clicking the same link in a different pdf viewer  *does* correctly open the link.

emacs 25.2.2, linux, gtk V 3.22.20  (modified by debian)

Version: 20180422.935

**Comment by politza** [comment]
I reconsidered and changed the handling of URI, i.e. wrapping them in double-brackets. 

5209f620c85e6c7c23e96768ebae6b5c6f79f3e1

**Comment by jlapeyre** [comment]
Thanks! Using double brackets is a good solution.
