### ISSUE TITLE
Issues with Auctex

### ISSUE THREAD

**Issue by djrmarques** [politza/pdf-tools#382]
Hello,

I am not able to set up synctex with Auctex + pdf-tools. I did set the TeX-source-correlate-method variable to Synctex, enabled Tex-source-correlate-mode and the pdf-sync-mode on the pdf buffer. Still the C-c C-g binding is not recognized on the pdfView buffer and if I do C-Mouse-1 on the Tex buffer only the buffer menu shows up. 

Additionally, The hook to revert the document is not working on my setup. I have the compiled pdf in another buffer that is not "in view" while I am editiing the TeX source. If I compile the source it shows the pdf nicely. But if I hide that buffer, recompile the source, and show the PDF buffer again, it does not show my pdf but it shows some "code", and I have to revert the buffer manually.

Anyway I can get this working? 

Thank you guys

**Comment by politza** [comment]
emacs.stackexchange.com is a better place for this kind of questions.
