### ISSUE TITLE
searching a pdf is searching the pdf code

### ISSUE THREAD

**Issue by map7** [politza/pdf-tools#388]
When I search a pdf book I purchased and use Swiper to search it searches the code of pdf instead of the rendered text.

Example;
![image](https://user-images.githubusercontent.com/8230/40519886-907b7002-6005-11e8-8cc4-0053aee16d64.png)

**Comment by map7** [comment]
I just loaded pdf-tools without swiper and pdf-tools works fine with ido. So this is more a compatibility with swiper.

**Comment by kevinrichardgreen** [comment]
If you want to keep swiper for everything else, you can simply redefine your search key in PDFView mode: `(define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)`
