### ISSUE TITLE
Server side did not build

### ISSUE THREAD

**Issue by ericsfraga** [politza/pdf-tools#39]
I installed pdf-tools via melpa and then, within emacs, tried to build the server by M-x pdf-tools-install RET.  I immediately got an error: pdf-tools-install: No executable `epdfinfo' available.  The compilation went ahead but failed as well:

-*- mode: compilation; default-directory: "~/s/research/shale.gas.environmental.footprint/pr/" -*-
Compilation started at Thu Feb  5 08:49:48

make V=0 -kC '/home/ucecesf/.emacs.d/elpa/pdf-tools-20150204.1206/build'  melpa-build
make: Entering directory `/home/ucecesf/synced/dotfiles/emacs.d/elpa/pdf-tools-20150204.1206/build'
cd server && ./autogen.sh
Running autoreconf...
configure.ac:14: installing './ar-lib'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am:10: warning: compiling 'synctex_parser.c' with per-target flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
Makefile.am: installing './depcomp'
cd server && ./configure -q
./configure: line 4613: syntax error near unexpected token `png,'
./configure: line 4613: `PKG_CHECK_MODULES(png, libpng)'
make: *** [server/Makefile] Error 2
make: Target `melpa-build' not remade because of errors.
make: Leaving directory `/home/ucecesf/synced/dotfiles/emacs.d/elpa/pdf-tools-20150204.1206/build'

Compilation exited abnormally with code 2 at Thu Feb  5 08:49:55

**Comment by politza** [comment]
Eric S Fraga <notifications@github.com> writes:

> I immediately got an error: pdf-tools-install: No executable
> `epdfinfo' available.

This is to be expected. 

> Makefile.am:10: warning: compiling 'synctex_parser.c' with per-target
> flags requires 'AM_PROG_CC_C_O' in 'configure.ac'

Required in automake < 1.14 . I'll add it to configure.ac .

> ./configure: line 4613: syntax error near unexpected tokenpng,'
> ./configure: line 4613: PKG_CHECK_MODULES(png, libpng)'

This looks like `pkg-config` is not available on your system, is that
the case ?

**Comment by ericsfraga** [comment]
On Thursday,  5 Feb 2015 at 10:03, politza wrote:
> Eric S Fraga <notifications@github.com> writes:
>
>> I immediately got an error: pdf-tools-install: No executable
>> `epdfinfo' available.
>
> This is to be expected. 

Okay.

>> Makefile.am:10: warning: compiling 'synctex_parser.c' with per-target
>> flags requires 'AM_PROG_CC_C_O' in 'configure.ac'
>
> Required in automake < 1.14 . I'll add it to configure.ac .

Thanks.

>> ./configure: line 4613: syntax error near unexpected tokenpng,'
>> ./configure: line 4613: PKG_CHECK_MODULES(png, libpng)'
>
> This looks like `pkg-config` is not available on your system, is that
> the case ?

I do have pkg-config installed, version 0.26.

-- 
This signature purposely left blank.

**Comment by politza** [comment]
Eric S Fraga <notifications@github.com> writes:

>>> ./configure: line 4613: syntax error near unexpected tokenpng,'
>>> ./configure: line 4613: PKG_CHECK_MODULES(png, libpng)'
>>
>> This looks like `pkg-config` is not available on your system, is
> that
>> the case ?
>
> I do have pkg-config installed, version 0.26.

What OS are you running ?

**Comment by ericsfraga** [comment]
On Thursday,  5 Feb 2015 at 11:24, politza wrote:

[...]

> What OS are you running ?

Linux.  On this particular system, ubuntu relatively up to date although
not the latest non-LTS version:

NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"

-- 
: Professor Eric S Fraga, CPSE, Chemical Engineering, UCL
: GnuPG/PGP key 0xFFFCF67D, http://www.ucl.ac.uk/~ucecesf

**Comment by politza** [comment]
>> What OS are you running ?
>
> NAME="Ubuntu"
> VERSION="14.04.1 LTS, Trusty Tahr"

That should be OK.  So, I hope the PKG_CHECK_MODULES problem is just a
result of the first one.

**Comment by politza** [comment]
I guess the automake macro solved the other problem.
