### ISSUE TITLE
pdf-tools often hang emacs

### ISSUE THREAD

**Issue by fu123456** [politza/pdf-tools#394]
I use pdf-tools with emacs , and very love  pdf-tools. But I find that pdf-tools often hang my Emacs.
I exclude other all minor mode not required and close the lum*-mode. Especially when I use mouse to select some text, this pdf-tools often hang my Emacs. So I need to restart my Emacs, this makes me very inconvenient。So how I should solve this problem.

**Comment by whatacold** [comment]
Hi,

Have you turned `linum-mode` down? As noted in "Known problems" section of README.
For me, it works fine now after disabling it.

If you want to enable `linum-mode` globally, but disable it for some specific modes,
take a look at this excellent SO answer: https://stackoverflow.com/a/3879664/910978

**Comment by fu123456** [comment]
yeh. I use Spacemacs with evil-mode. I have disabled linum-mode and almost not use this mode.
I find that if I use evil-mode, the pdf-tools often hange Emacs, but close evil-mode, it seems to does work well. So I think that the reason of this hang is often due to evil-mode. Do you test pdf-tools with evil-mode?

**Comment by whatacold** [comment]
I use evil-mode too, but not spacemacs.
It works for me, and I've confirmed that evil-mode is also enabled for the pdf buffer.

Maybe you should post your version info, so that someone may help you a bit, hopefully.

**Comment by politza** [comment]
Sorry, but I don't think this will ever get resolved.  Many people use evil with pdf-tools.

**Comment by fu123456** [comment]
Thanks. I very like pdf-tools and often use it. However, I find that is sometimes slow to render pdf file.
In theory, the speed of it and that of evince should be similar.
I fell that it is slower than Evince, Zathura. Can this problem be improved?

**Comment by politza** [comment]
Yes, it should be similar to other poppler-based viewers, though it is expected to be a bit slower.   This mostly stems from the fact that the rendered images are converted to and from an image-format.

Additionally, poppler can be slow, compared to other e.g. mupdf, when rendering some pages.  

If you have a concrete case, where it is slower than Evince, please post it.

**Comment by fu123456** [comment]
I am a PHD candidate, and often view and annotate  a large number of PDF files. But I find that the plugin pdf-tools is so slow. Opening a 2M file, it need to nearly one minutes. Why? I can not stand it. If its speed is faster, this plugin may be a magic plugin. Now, this plugin is so slower, so that I may give up it.
Morevoer, I use Emacs27, spacemacs config, Manjaro system.

**Comment by fu123456** [comment]
Hi, I am a big fan of pdf-tools. I often use this plugin with Emacs to read my
pdf files. But this plugin also often induce emacs hang, and I can not find any
true reason leading to this. So I want to know how to debug this plugin to find
some useful cues that cause this hang. This drawback is very noisy and even
lead to fully not use it.

**Comment by CDitzel** [comment]
I second this problem. Regular hang ups for a couple of seconds up to half a minute

**Comment by jcguu95** [comment]
Seconded. Is there a way to fix it? With that fixed `pdf-tools` would be perfect..
