### ISSUE TITLE
pdf-tools seems to interfere with dired rename

### ISSUE THREAD

**Issue by ginabythebay** [politza/pdf-tools#398]
Note: it is possible this is a windows-only issue.

My use case is that I have a directory full of pdfs that I want to organize/rename using dired.  If there is an open buffer lurking around, the rename fails with `file-error Renaming Permission denied`.  If I then find the associated buffer and do the rename, it succeeds.

I don't know if it is practical to hook something in dired mode to close the buffer before the rename automatically.  Or maybe instead I need to come up with a way to easily close all buffers associated with files in the current directory.

Its not clear to me if this ought to be fixed in pdf-tools or elsewhere, but just noting the problem for feedback on that.

**Comment by politza** [comment]
I think what happens is that the poppler library opens the file and reads PDF objects from it on-demand, preventing the file to be deleted.  Windows is stupid that way.  What you can do is shut down the program via `pdf-info-quit` and restart it after the renaming via `pdf-info-process-assert-running`. (Though it should start automatically. See also the variable `pdf-info-restart-process-p`.) 

Make sure your annotations are saved.
