### ISSUE TITLE
annotations of highlighted text are not visible in other pdf viewers

### ISSUE THREAD

**Issue by dzklaim** [politza/pdf-tools#399]
it is not possible to view an annotation in evince for example created using the highlight text + annotation functionality. I can see the the highlighted text, the indication that there is an annotation on the sidepane but it seems that evince fails to recognize that there is some text associated with the highlighted text.

**Comment by vspinu** [comment]
On tablet I have tried many readers and only ezPDF seem to recognize annotations. 

On desktop linux Okular has no problems recognizing annotations.

**Comment by hyiltiz** [comment]
But none of the following can read the annotations wrote to `pdf` in `pdf-tools`:
- Adobe Acrobat
- macOS Preview
- pdf.js, the default pdf viewer in Firefox
- built-in pdf viewer in Chrome

**Comment by politza** [comment]
I think the problem was that I set the Rect entry of the annotation to the empty rectangle, but the specification says to ignore all markup outside this rectangle.  With commit 30be1f75cc47a719ba88e4a2c2af2df4f05ba934 I changed it to the smallest rectangle containing all markup.  I verified that it works in Acrobat and Evince, please check it out.

**Comment by politza** [comment]
No, those would be in need of fixing.  The following function should accomplish this, be careful.

    (defun pdf-annot-fix-broken-edges (&optional file-or-buffer verbosep)
      (interactive (list (current-buffer) t))
      (let ((nfixed 0))
        (dolist (a (pdf-info-getannots nil file-or-buffer))
          (let-alist a
            (when (and (memq .type '(squiggly underline strike-out highlight))
                       (equal .edges '(0.0 0.0 0.0 0.0)))
              (pdf-info-mvannot
               .id  
               (apply #'pdf-util-edges-union
                      (apply #'append
                             (mapcar
                              (lambda (e)
                                (pdf-info-getselection .page e nil file-or-buffer))
                              .markup-edges)))
               file-or-buffer)
              (cl-incf nfixed))))
        (when verbosep
          (message "Fixed %d annotations" nfixed))
        nfixed))

**Comment by hyiltiz** [comment]
Just compiled https://github.com/politza/pdf-tools/commit/30be1f75cc47a719ba88e4a2c2af2df4f05ba934, uninstalled `pdf-tools` from `list-packages` then installed the compiled `.tar` archive. `pdf-tools` seems to be working, but neither the old highlighted annotations with text nor a newly created one got picked up by other readers.

Just saw the function you mentioned above. Shall I just `M-:` run it? Or it needs to be hooked in somewhere?

**Comment by politza** [comment]
I just pushed another update.

You would also have to reload the library or restart Emacs.

Use M-x in the Pdf's buffer.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Hörmet Yiltiz <notifications@github.com> </div><div>Datum:24.09.2018  19:05  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] annotations of highlighted text are not
  visible in other pdf viewers (#399) </div><div>
</div>Just compiled 30be1f7, uninstalled pdf-tools from list-packages then installed the compiled .tar archive. pdf-tools seems to be working, but neither the old highlighted annotations with text nor a newly created one got picked up by other readers.

Just saw the function you mentioned above. Shall I just M-: run it? Or it needs to be hooked in somewhere?

**Comment by hyiltiz** [comment]
Great, that fixed it! I had to run the above function on the old pdf (some comments were lost when I used https://github.com/politza/pdf-tools/commit/30be1f75cc47a719ba88e4a2c2af2df4f05ba934 but I guess I'll have to live with that since I had no backups) before it shows up in other viewers. This is a major usability upgrade 👏 👏

**Comment by politza** [comment]
What do you mean by "lost contents", how ?

**Comment by hyiltiz** [comment]
I had multiple annotation content/text corresponding to highlights in a few PDFs. Only very old ones, or ones that are at the beginning (roughly 10%) of the document are still there after loading the PDFs with the newly compiled pdf-tools, while newer annotations (at around 60-100% of the PDFs) were completely lost. In other terms, it was as if my annotations made last night was not there while the ones I made during last week was there.
It may or may not be a `pdf-tools` issue, as I did `killall emacs` yesterday night, which might produce the same result, if the annotations weren't written to PDFs upon `C-c C-c`.

**Comment by politza** [comment]
The new code affects new annotations only, so I guess it was due to
killing Emacs without saving.

**Comment by thibault-gajdos** [comment]
Dear Politza
I get exactly the same issue with latest version of pdf-tools under OSX: annotations do not appear when I open the file with Aperçu or Acrobat. 
Do you know how I could fix that (if there is a way)? I find your package awesome, and this is the only feature that prevent me to use it instead classical pdf viewers.

**Comment by politza** [comment]
Please install the latest version of this package, force a rebuild by removing the epdfinfo executable and then see if the issue persists.

**Comment by thibault-gajdos** [comment]
I just tried that, and get the same result: in acrobat (or Apercu), i only can see an empty white box instead of the comment. But i don't want to take too much of your time. 
best.

**Comment by politza** [comment]
Can you upload an example PDF somewhere ?

**Comment by thibault-gajdos** [comment]
https://we.tl/t-bGlfkXmPaE

**Comment by thibault-gajdos** [comment]
[duque2016.pdf](https://github.com/politza/pdf-tools/files/3130089/duque2016.pdf)
There is an annotation p2, top of second paragraph.

**Comment by politza** [comment]
That does not look like the annotation on page 2 was created with pdf-tools.

**Comment by thibault-gajdos** [comment]
Well... yes It was, actually...
Do you want me to do it again?

**Comment by thibault-gajdos** [comment]
The problem maybe come from the fact that i tried to open the annotation from another pdf reader. Here is a new document, with an annotation made in pdf-tools, not opened in any other reader
[Angelini2015.PDF](https://github.com/politza/pdf-tools/files/3136909/Angelini2015.PDF)
 (p.1).

**Comment by samspo** [comment]
It still doesn't work when I try to read annotated documents on preview (mac os). I tried with some documents I annotated and with duque2016-2.pdf

I obtain white square with no annotation: 

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1280210/61346251-f9388d00-a825-11e9-9ba2-535501574819.png">

It works on acrobat
