### ISSUE TITLE
Only ask about apt-get installation if apt-get is available

### ISSUE THREAD

**Issue by pank** [politza/pdf-tools#40]
In `pdf-tools--melpa-build-server` `pdf-tools` shold only try to install dependencies if `(executable-find "apt-get")` is non-nil.  If you want I could provide a patch asking about dependencies if `pacman` is found.

**Comment by tsdh** [comment]
@pank On Arch packages aren't split into "normal" and -dev packages, and there's almost no chance that a computer running Arch and X11 has no libpng and poppler installed.  `pactree emacs` reveals that emacs itself depends indirectly on libpng, and poppler is required by pretty much standard packages like cups or libreoffice.

But anyway, the "should I try installing deps using apt-get" should go away. :-)

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> [...] If you want I could provide a patch asking about dependencies if
> pacman is found.

That would be good.

**Comment by pank** [comment]
Tassilo, the point is that it should be more modular so that the dependency installation step is a matter of adding a `defun` and checking for the existence of some binary, say `pacman`, to the extend that checking for a binary is valid identification.  This might not hold for e.g. `yum`. . . 

Is `/etc/os-release` a reliable identification mechanism?

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> [...] the point is that it should be more modular [...]
>
> Is /etc/os-release a reliable identification mechanism?

Better not make any assumption.  What about an alist

((PREDICATE . TARGET)

, where PREDICATE tests for a particular OS and TARGET is either another
function or a make target.  I'd prefer the later, because I think it's
easier to implement.

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> In pdf-tools--melpa-build-server pdf-tools shold only try to install
> dependencies if (executable-find "apt-get") is non-nil.

d0bf5e8d630d85e0a4b801accd4b6cca0ca0736a

**Comment by pank** [comment]
If you are willing to move the dependency check out of `make` something like this could be used.  I could then provide a real patch.

    (defconst pdf-tools--server-dependencies
      '(("apt-get" '("gcc" "g++" "make" "automake" "autoconf"
                    "libpng-dev" "libz-dev" "libpoppler-glib-dev"
                    "libpoppler-private-dev")
         nil)
        ("pacman" ("gcc" "automake" "autoconf" "libpng" "poppler") pdf-tools--pacman-installed-p))
      "Alist of package managers.

    A cell is of the format
       (\"package-tool\" \"dependencies\" \"check-command\")

    Each dependencies is tested by \"check-command\", which should be
    lisp-function.")

    (defun pdf-tools--dependencies ()
      "Try to resolve dependencies.

    This is a helper function when installing via MELPA.
    "
      (let* ((sudo-like-command (executable-find "sudo"))
             (package-tool
              (car (delq nil
                         (mapcar (lambda (pkg) (and (executable-find pkg) pkg))
                                 (mapcar 'car pdf-tools--server-dependencies)))))
             (check-command
              (and package-tool
                   (nth 2 (assoc package-tool pdf-tools--server-dependencies))))
             (missing-dependencies
              (and check-command
                   (delq nil (mapcar
                              (lambda (pkg) (if (funcall check-command pkg) nil pkg))
                              (nth 1 (assoc package-tool pdf-tools--server-dependencies))))))
             (buf (and missing-dependencies
                       (get-buffer-create "*pdf-tools-install-buffer*"))))
        (if (and sudo-like-command
                 package-tool
                 missing-dependencies
                 (y-or-n-p
                  (format "Should I try to install dependencies with %s?")
                  package-tool))
            (progn
              (switch-to-buffer buf)
              (erase-buffer)
              (start-process-shell-command
               "Installing pdf-tools dependencies..."
               buf
               ;; TODO: Isn't there a better way to do this such that
               ;; password isn't echoed?  Also, can this be made
               ;; compatible with su?
               (concat "echo " (shell-quote-argument (read-passwd "sudo password: "))
                       " | sudo -S "
                       package-tool missing-dependencies)))
          (unless package-tool
            (y-or-n-p
             "Are libpng and poppler developer libraries available?")))))

    (defun pdf-tools--pacman-installed-p (pkg)
      "Test if a package is installed"
      (zerop (shell-command (concat "pacman -T " pkg))))

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> If you are willing to move the dependency check out of make

I have no problem with this.

> A cell is of the format
>    (\"package-tool\" \"dependencies\" \"check-command\")

I would do it differently, as I've said earlier.  I would keep both the
recognition of the OS at hand and how to install the needed dependencies
low level, i.e. encapsulated in some functions.

What if the executability of some command is not sufficient ? What if
the package-tool needs additional arguments ?  Also some Ubuntu versions
don't have a libpoppler-private-dev package.  On these systems it is
contained in the main package.

Maybe the sudo part can be solved with tramp, i.e. by setting up a
default-directory with root permissions and using
`start-file-process-shell-command`.

-ap

**Comment by pank** [comment]
politza <notifications@github.com> writes:

> I would do it differently, as I've said earlier.  I would keep both the
> recognition of the OS at hand and how to install the needed dependencies
> low level, i.e. encapsulated in some functions.

I apparently didn't pay enough attention.  The
   (predicate . install-function) j
makes a lot of sense.  I'll look into it later.

—Rasmus

-- 
Together we'll stand, divided we'll fall

**Comment by politza** [comment]
> [...] The (predicate . install-function) j makes a lot of sense. I'll
> look into it later.

OK.  Maybe getting root permissions can be leveraged.  

    (let ((buffer (get-buffer-create "*whoami*"))
          (default-directory "/su::/"))
      (display-buffer buffer)
      (process-file-shell-command "whoami" nil buffer))

This seems to work fine (except for MS Windows).

-ap

**Comment by politza** [comment]
Since the original issue seems to be resolved, I'm closing this.
