### ISSUE TITLE
Compiling on OSX fails without specifying CXX and CXXFLAGS

### ISSUE THREAD

**Issue by hunterx7d** [politza/pdf-tools#403]
Building on OS X 10.11.6 fails, when using the standard compiler g++, which is just a symlink to clang.
This is due to an invalid conversion in poppler-hack.cc:

``
poppler-hack.cc: In function 'void xpoppler_annot_set_rectangle(PopplerAnnot*, PopplerRectangle*)':
poppler-hack.cc:88:49: warning: invalid conversion from 'const GooString*' to 'GooString*' [-fpermissive]
     GooString *state = a->annot->getAppearState ();
poppler-hack.cc: In function 'gchar* xpoppler_annot_markup_get_created(PopplerAnnotMarkup*)':
poppler-hack.cc:108:27: warning: invalid conversion from 'const GooString*' to 'GooString*' [-fpermissive]
     text = annot->getDate ();
``

Forcing make to use the g++ from homebrew and adding CXXFLAGS=-fpermissive fixes this error to a warning.

**Comment by politza** [comment]
Should be fixed in commit 50a5297b82e26cfd52f6c00645ddc1057099d6a7 .
