### ISSUE TITLE
PDFs don't work when bookmarked

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#405]
When I bookmark a PDF from viewing the PDF itself and then try to load that bookmark, it fails because it's trying to work in the wrong buffer. 

I fixed this with #395 although Travis seem to be mis-configured so doesn't pass it. The fix still works for me though. 

Politza responds to issues more often and I don't have an email, so here's hoping the commit will be merged :)

**Comment by politza** [comment]
See #395.
