### ISSUE TITLE
Some annotations are not listed but you can open them in pdf-tool

### ISSUE THREAD

**Issue by falematte** [politza/pdf-tools#406]
Here is an example:
![selection_999 583](https://user-images.githubusercontent.com/25055204/43892985-0831ba8c-9bbd-11e8-8860-3c17894549db.jpg)

If I pass the mouse on the first annotation I can read the text in ut. Anyway list annotation is not showing it.

**Comment by politza** [comment]
That is because by default it lists supported annotations only.

    pdf-annot-list-listed-types

    => (text file squiggly highlight underline strike-out)

But you can easily change this and maybe it should be more inclusive by default.

    (setq pdf-annot-list-listed-types
          pdf-annot-annotation-types)

    => (3d caret circle file free-text highlight ink line link movie poly-line polygon popup printer-mark screen sound square squiggly stamp strike-out text trap-net underline unknown watermark widget)

**Comment by falematte** [comment]
THank you for the answer. I think it should be more inclusive by default. If I add the last command in my init file i get this error:
`
Symbol's value as variable is void: pdf-annot-annotation-types`

**Comment by politza** [comment]
That's because you haven't loaded the library where this variable is defined.

**Comment by falematte** [comment]
Could you please tell me how to load this library?
