### ISSUE TITLE
C-c C-o for "open in external/default PDF tool" and RET for "open in pdf-tools"

### ISSUE THREAD

**Issue by novoid** [politza/pdf-tools#409]
Hi!
Can you please help me? I'd like to have my default PDF application opened when I do `C-c C-o` on a PDF `file:` link in my Org mode. However, when I do press `RET` (Enter) on the very same link, I'd like to open up pdf-tools with the linked pdf file.

I am not sure how this is set up. I guess it's related to:
```
  (add-to-list 'org-file-apps '("\\.pdf\\'" . org-pdfview-open))
  (add-to-list 'org-file-apps '("\\.pdf::\\([[:digit:]]+\\)\\'" . org-pdfview-open))
  ;; workaround for https://github.com/markus1189/org-pdfview/issues/14 on Org-mode 9/Windows:
  (when (my-system-type-is-windows)
    (add-to-list 'org-file-apps '("\\.pdf\\'" . (lambda (file link) (org-pdfview-open link))))
  )
```

Thanks for any help!

**Comment by politza** [comment]
Please ask this kinds of question on http://emacs.stackexchange.com .
