### ISSUE TITLE
Wrong version after build from cloned repo?

### ISSUE THREAD

**Issue by rkrug** [politza/pdf-tools#41]
I just build pdf-tools from a cloned repo and I got a tar.gz which is named
```
df-tools-0.20.tar
```
But shouldn't this be 0.50?

**Comment by rkrug** [comment]
I somehow compiled version 0.20 - dom't know how.

**Comment by politza** [comment]
Rainer M Krug <notifications@github.com> writes:

> I just build pdf-tools from a cloned repo and I got a tar.gz which is
> named
>
> [p]df-tools-0.20.tar
>
> But shouldn't this be 0.50?

You cloned this repo

https://github.com/axot/pdf-tools

which is a fork of pdf-tools for OSX.  I pointed you to the only commit
of this fork as a starting point.

This version is stone-old.

What you should do is clone this repo

https://github.com/politza/pdf-tools

apply this patch

https://github.com/axot/pdf-tools/commit/4c33ea937eec6188837c021375e36a54958e5811.diff

and see how it's going.

**Comment by rkrug** [comment]
Thanks - changed to other repo.
