### ISSUE TITLE
add label to annotation

### ISSUE THREAD

**Issue by fxkrait** [politza/pdf-tools#410]
related to https://github.com/politza/pdf-tools/issues/297

How do I add a label?
There are the categories Pg, Type, Label, Date. 
But I can't add any labels?

**Comment by politza** [comment]
You are being very vague.

**Comment by fxkrait** [comment]
![nolabels](https://user-images.githubusercontent.com/7407672/44551239-635eb580-a6db-11e8-85db-cb5f91f08304.png)

**Comment by politza** [comment]
Yes.  

There is currently no user-interface for this. But you can do it programmatically like this:

    (let ((a (car (pdf-annot-getannots))))
      (pdf-annot-put a 'label "Joe"))

**Comment by gmoutso** [comment]
Is pdf annotation label used only for author's name always? I am wondering if this is a non-necessary convention. I could put meaningful names for each annotation instead. I couldn't find a description of label in the pdf reference.
