### ISSUE TITLE
annotation page number sorting

### ISSUE THREAD

**Issue by fxkrait** [politza/pdf-tools#411]
The page number sorting for annotations only looks at the first number.

So EX:
   13 text                                Tue Aug 21 19:12:48 2018
   14 highlight                           Tue Aug 21 18:29:04 2018
   14 text                                Tue Aug 21 19:13:34 2018
   28 highlight                           Tue Aug 21 19:10:15 2018
   42 highlight                           Tue Aug 21 18:18:20 2018
   46 highlight                           Tue Aug 21 18:30:45 2018
    5 highlight                           Tue Aug 21 18:27:40 2018

The 5 should be at the top, but it is not.

**Comment by politza** [comment]
074fcf9fe2bbdb8587ffdff4f22be8d6eadbb7d5
