### ISSUE TITLE
(pdf-tools-install) .emacs initialization

### ISSUE THREAD

**Issue by fxkrait** [politza/pdf-tools#412]
Per the instructions, to have pdf-tools auto-load, this needs to be added to my .emacs.
(pdf-tools-install)

However, I get this error: 
Symbol's function definition is void: pdf-tools-install

I have to manually run M-x pdf-tools-install for it to work. 
Is there a solution to that error so I don't have to manually load it each time.

**Comment by politza** [comment]
You need to initialize package (via package-initialize) before the
call to pdf-tools-install .

**Comment by fxkrait** [comment]
Yes, that did fix the issue. I was running emacs 27 a while ago, and it complained about package-initialize before, so I had removed it from my config.

I think the package-initialize requirement should be added to the installation guide.

Thanks.
