### ISSUE TITLE
pdf -> LaTeX source not working

### ISSUE THREAD

**Issue by RobinTournemenne** [politza/pdf-tools#413]
Hello, 
after many manipulations I lost the behavior jumping from pdf to tex.

I reinstalled pdf-tools many times and I still get the same thing written in the minibuffer when I double click on a word:

epdfinfo: Expected a relative edge: 0.3265542....

Any idea?

**Comment by politza** [comment]
That's strange because it seems that the parsing of the string as a
double fails for some reason.  What is the exact error ?

**Comment by RobinTournemenne** [comment]
I have no error output just a message in the message buffer. Here are two complete examples when I double click on different places in the pdf document:

pdf-info-query: epdfinfo: Expected a relative edge: 0.28550512445095166
pdf-info-query: epdfinfo: Expected a relative edge: 0.4128843338213763

pdf-info-heck-epdfinfo is also saying:
The epdfinfo program appears to be working.

Using list-packages, I deleted pdf-tools + restarded emacs and installed pdf-tools again. Here is the compilation message obtained evaluating (pdf-tools-install)

-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20180428.1527/build/server/" -*-
Comint started at Thu Aug 23 21:31:06

/Users/JohnDoe/.emacs.d/elpa/pdf-tools-20180428.1527/build/server/autobuild -i /Users/JohnDoe/.emacs.d/elpa/pdf-tools-20180428.1527/

 Installing packages    
---------------------------
Skipping package installation (already installed)

 Configuring and compiling 
---------------------------
autoreconf -i
configure.ac:15: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:78: installing './config.guess'
configure.ac:78: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
./configure -q --bindir=/Users/JohnDoe/.emacs.d/elpa/pdf-tools-20180428.1527/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

epdfinfo.c:354:19: warning: 'tempnam' is deprecated: This function is provided for
      compatibility reasons only. Due to security concerns inherent in the design of
      tempnam(3), it is highly recommended that you use mkstemp(3) instead.
      [-Wdeprecated-declarations]
      filename =  tempnam(NULL, "epdfinfo");
                  ^
/usr/include/stdio.h:391:7: note: 'tempnam' has been explicitly marked deprecated here
char    *tempnam(const char *, const char *) __DARWIN_ALIAS(tempnam);
         ^
1 warning generated.

Installing          
---------------------------
make -s install
 /usr/local/bin/gmkdir -p '/Users/JohnDoe/.emacs.d/elpa/pdf-tools-20180428.1527'
  /usr/local/bin/ginstall -c epdfinfo '/Users/JohnDoe/.emacs.d/elpa/pdf-tools-20180428.1527'
make[1]: Nothing to be done for `install-data-am'.


Build succeeded. :O)    


Comint finished at Thu Aug 23 21:31:23


Here is the part of my init.el setting the pdf-tools mode:

(setq pdf-view-use-unicode-ligther nil)
(pdf-tools-install)
(add-hook 'LaTeX-mode-hook 'turn-on-reftex)   ; with AUCTeX LaTeX mode
;; (add-hook 'latex-mode-hook 'turn-on-reftex)   ; with Emacs latex mode
;; Use pdf-tools to open PDF files
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-view-program-list '(("PDF Tools" TeX-pdf-tools-sync-view))
      TeX-source-correlate-start-server t)
;; Update PDF buffers after successful LaTeX runs
(add-hook 'TeX-after-compilation-finished-functions
          #'TeX-revert-document-buffer)

;; anti linum
(setq linum-mode-inhibit-modes-list '(pdf-view-mode
                                      doc-view-mode))

(defadvice linum-on (around linum-on-inhibit-for-modes)
  "Stop the load of linum-mode for some major modes."
    (unless (member major-mode linum-mode-inhibit-modes-list)
      ad-do-it))

(ad-activate 'linum-on)

**Comment by RobinTournemenne** [comment]
10:06:06 synctex-backward-search:/Users/JohnDoe/Document/ACTA_2018.pdf:1:0.7011661807580175:0.7522522522522522
10:06:06 ERR
Expected a relative edge: 0.7011661807580175

Thanks a lot for your support by the way. Since it worked before and not anymore, I have the feeling it may has to do something with the order of the lines in my init.el

**Comment by politza** [comment]
I doubt that.  You should be able to reproduce the error in a terminal
with a command like

echo synctex-backward-search:/Users/JohnDoe/Document/ACTA_2018.pdf:1:0.7011661807580175:0.7522522522522522 | ./epdfinfo

**Comment by RobinTournemenne** [comment]
It works in the terminal!
Result:

OK
/Users/JohnDoe/Documents/ACTA_2018.tex:107:-1

**Comment by RobinTournemenne** [comment]
I worked on another pdf and I switched on and off TeX-source-correlate-mode. After some restart and deletion of the emac desktop file, I got it finally running again. 

Thanks for all the information you gave me. It definitely helped in the end because I knew it wasn't the fault of your perfect epdfinfo.

**Comment by RobinTournemenne** [comment]
Hello! 

After one month, the problem is unfortunately still here: randomly, at a certain point in time, I get the error I showed you at the end of august when I double click on the pdf to go back to the source:

10:06:06 synctex-backward-search:/Users/JohnDoe/Document/ACTA_2018.pdf:1:0.7011661807580175:0.7522522522522522
10:06:06 ERR
Expected a relative edge: 0.7011661807580175

Sometime, after a random reboot of my mac book air, the behavior comes back... and everything works fine for some time.

The good news is that I think I just found why: I am french and floating number are not seperated by a point but a coma: 
we don't write 0.5654 but 0,5654 

In the pdf-info-log buffer I found that when my system principal language is french epdfinfo needs the french notation! Indeed the getselection output from the pdf-info-log buffer is:

18:11:58 getselection:/Users/robintournemenne/Documents/WORK/TRAVAIL/2018_01_OPTIM_JASA_THESE/Article/JASA_2018.pdf:14:0 0 1 1:0
18:11:58 OK
0,099673 0,051768 0,294118 0,066919
0,529412 0,051768 0,578431 0,066919
0,088235 0,068182 0,099673 0,070707
0,517974 0,068182 0,529412 0,070707
0,088235 0,070707 0,490196 0,079545
0,517974 0,070707 0,919935 0,079545
0,099673 0,079545 0,490196 0,101010
0,529412 0,079545 0,919935 0,101010
0,099673 0,101010 0,343137 0,116162
0,529412 0,101010 0,919935 0,116162
0,529412 0,116162 0,638889 0,117424
0,088235 0,117424 0,099673 0,119949
0,529412 0,117424 0,638889 0,119949
0,088235 0,119949 0,490196 0,128788
0,529...[truncated]

Hence, when doing the synctex-backward-search it needs the french writing and not the english one!

When I switch to english as my machine principal language, everything works like a charm: I get points instead of comas as output from getselection and synctex-backward-search works as expected!

I was wondering if you could easily patch the source to get around the problem directly in epdfinfo? Or drive me toward the source that should be modified in order that I propose you a pull request?

Best regards, your package is incredibly nice!

**Comment by politza** [comment]
That's odd. The locale of a C program should be "C" (i.e. default), unless explicitly set otherwise by the programmer.  I've noticed a couple of `setlocale` calls in the syntex parser, but it only temporary sets it to the "C" locale and restore it afterwards.  In otherwords it does not change it.

Do you get different outputs in a terminal for the following commands ?

    echo getselection:/path/to/pdf:1:0 0 1 1:0 | LC_NUMERIC=fr_FR.UTF-8 ./epdfinfo
    echo getselection:/path/to/pdf:1:0 0 1 1:0 | LC_NUMERIC=C ./epdfinfo

_Note_ the actual name of your locale may be different._

In that case you could start the server with a special setup, like so

    (define-advice pdf-info-process-assert-running (:around (fn &optional force))
      (let ((process-environment
             (cons "LC_NUMERIC=C" process-environment)))
        (funcall fn force)))

**Comment by politza** [comment]
> PS: the two tests you gave me returned the same result (with points and no comas)

That's unexpected.

There must be something going on in your system/setup.  Many people use locales, where the numeric dot is a comma, i.e. this should have come up more often.
