### ISSUE TITLE
Compile fail on Solus

### ISSUE THREAD

**Issue by pierrebonbon** [politza/pdf-tools#414]
Trying to compile pdf-tools on Solus without success. Here's the output on the terminal:

<pre>cd server &amp;&amp; ./configure -q
configure: error: in `/home/nunop/Downloads/pdf-tools-0.80/server&apos;:
configure: error: C compiler cannot create executables
See `config.log&apos; for more details
make: *** [Makefile:64: server/Makefile] Error 77
</pre>

Here's the [config.log](https://github.com/politza/pdf-tools/files/2320873/config.log). Any hint on what could be wrong very much appreciated!

**Comment by pierrebonbon** [comment]
Thanks for the quick reply. You're right about that I think. Installing `solbuild` and `system.devel` seemed to do the trick, at least partially, as I'm getting stuck somewhere else. I'm enclosing an updated version of [config.log](https://github.com/politza/pdf-tools/files/2320938/config.log). I wonder if these lines have something to do with it, especially the ones saying `g++: fatal error: no input files`:

<pre>configure:4220: $? = 0
configure:4209: g++ -V &gt;&amp;5
g++: error: unrecognized command line option &apos;-V&apos;
g++: fatal error: no input files
compilation terminated.
configure:4220: $? = 1
configure:4209: g++ -qversion &gt;&amp;5
g++: error: unrecognized command line option &apos;-qversion&apos;; did you mean &apos;--version&apos;?
g++: fatal error: no input files
compilation terminated.
</pre>

**Comment by politza** [comment]
No, that's not a problem.  The configure script is just trying a couple
of options which are unsupported by the GNU compiler.

What's the actual error ?

**Comment by pierrebonbon** [comment]
Ohh, ok. Right know, this is what I'm getting:

<pre>cd server &amp;&amp; ./configure -q
./configure: line 4743: syntax error near unexpected token `png,&apos;
./configure: line 4743: `PKG_CHECK_MODULES(png, libpng)&apos;
make: *** [Makefile:64: server/Makefile] Error 2
</pre>

**Comment by politza** [comment]
pkg-config installed ?

**Comment by pierrebonbon** [comment]
yep, version 0.29.2

**Comment by politza** [comment]
Take a look [here](https://github.com/politza/pdf-tools/issues?utf8=%E2%9C%93&q=is%3Aissue+%22syntax+error+near+unexpected+token%22).

**Comment by pierrebonbon** [comment]
Closing since the issue was since resolved with the solution mentioned above. Successfully removed and installed `pdf-tools` a couple more times afterwards and wasn't able to reproduce the issue.
