### ISSUE TITLE
Question: Is there any way I can highlight on an image PDF?

### ISSUE THREAD

**Issue by lbkvu** [politza/pdf-tools#415]
Please help me with the question in the title.

**Comment by politza** [comment]
I'm not a mind-reader and I have no idea what you're asking.

**Comment by randomwangran** [comment]
Hi @politza:

I've done a Telepathy to @lbkvu. He was saying that he could not highlight on a PDF file that is a scanned paper. : )

I go through the source code, Issues, and Pull request, but I could not find the related function.

Let me know if you cannot read my mind.

Thanks for your effort for making such great tool!

**Comment by politza** [comment]
Highlight what ? 

Anyway, Isearch won't work since there simply no textual information in a scanned image.

**Comment by randomwangran** [comment]
For example:

This guy is playing drum, and I want to highlight his hand for
future reference. Please see this gif.

This is what I feel. It seems that the current highligt function
is based on textual information, so it won't work for pictures.
Sometime, a whole PDF file has no textual information, so I
cannot highlight anything on that PDF file.

Currently, I had to switch to SumatraPDF (pre-release) program to
such job on my working computer (Win-7).

![demo-highlight](https://user-images.githubusercontent.com/8197831/62667670-c41be800-b956-11e9-8792-9e21e73c6b4a.gif)

**Comment by randomwangran** [comment]
@randomwangran just OCR the pdf, problem solved.
