### ISSUE TITLE
occur match highlighting in the actual pdf document makes text unreadable

### ISSUE THREAD

**Issue by wildgruber** [politza/pdf-tools#416]
Hi,

where can I customize how pdf-tools occur matches are highlighted on the actual pdf (not on the emacs match list buffer).

On my installation, these matches appear in a shrill yellow and make the underlying text of the pdf (black on white) unreadable.

Thanks

**Comment by wildgruber** [comment]
Thanks! Actually, that's the first thing I tried :-) but can't find it here; in the customization buffer I get:
Pdf Isearch Batch, Pdf Isearch Lazy, Pdf Isearch Match, Pdf Links Read Link, Pdf View Rectangle and Pdf View Region.
None of these seem to cover the occur match face on the pdf, or do I miss something?

**Comment by politza** [comment]
Yes, it's a bit more complicated.  The face should be the
pdf-isearch-match.  Try to customize both variants, i.e. light and dark.
If the face inherits from another face, the colors could be displayed
wrongly.

**Comment by wildgruber** [comment]
I'm sorry, but I couldn't find any of the settings you were referring to under the "Pdf Isearch Match" config; what do you mean by "variants" light and dark? and which font characteristics would have to be modified? ("background"?)
Could you perhaps provide the corresponding elisp code that changes just the yellow of the matches?

Thanks.

**Comment by wildgruber** [comment]
I did the following:

1. customise pdf-isearch-face

**Comment by wildgruber** [comment]
What I did was this:

- customize pdf-isearch-match face
- define a face for background brightness "light" and one for "dark"
- by activating "support attributes" and
- setting the "foreground" and "background" attributes to white and black accordingly (in the same manner for both variants)
- I left all other attributes untouched
- I didn't define any inheritance
- save for future sessions, quit and restart emacs
- in the "custom-set-faces" part of the emacs init file I get this:

`'(pdf-isearch-match ((((background light) (supports :foreground "white" :background "black")) nil) (((background dark) (supports :foreground "white" :background "black")) nil)))`

But unfortunately this doesn't change anything: matches on the pdf are still highlighted white on yellow (absolutely unreadable in any context, so I wonder where this comes from!).

And BTW: the default colors (inherited from the isearch face)  also seem to have no relation whatsoever to the way matches are highlighted.

Is this really the right face to customize? 

Any help on this?

thanks

**Comment by politza** [comment]
I suppose this has been resolved.

**Comment by Xunius** [comment]
I got the same problem. And I tried messing the `pdf-isearch-match` customization a bit but it doesn't seem to make any difference. Please help.

My emacs version: GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-30
