### ISSUE TITLE
pdf-links-action-perform doesn't work on Windows because of encoding issues

### ISSUE THREAD

**Issue by oantolin** [politza/pdf-tools#417]
I recently tried `pdf-tools` on Windows and run into two minor problems with `pdf-links-action-perform`:

1. First, the default value of `pdf-util-convert-program` is `(executable-find "convert")`, which on Windows sadly find the system command `"c:/WINDOWS/system32/convert.exe"`. This is of course easy for the user to fix, just set the variable to point to your own installation of ImageMagick's `convert` (there's probably no good way to do this automatically, since I don't think there is a standard installation location for this on Windows).

2. The more serious issue was an error of the form:
```
convert.exe: improper image header `c:/Users/MyUserNAME/AppData/Local/Temp/pdf-util-convertMNmzDC.png' @ error/png.c/ReadPNGImage/4231.
```

I tracked this down to a coding system problem: `pdf-links-action-perform` calls on `pdf-util-convert-page` to overlay the PDF page with the link hints. When `pdf-util-convert-page` saves the image with the link hints it doesn't worry about coding systems. This works fine on Unix, of course, but on Windows you always have to worry about text vs binary :(. Adding the line:
```
            (set-buffer-file-coding-system 'binary)
```

to `pdf-util-convert-page` right after the line `(set-buffer-multibyte nil)` solved the problem.

(So, to be clear: I've solved my problem and can happily use pdf-tools on Windows now --only link hints were not working, by the way, everything else seems to work just fine--, but I opened this issue in case you want to add the `binary` fix for other Windows users.)

**Comment by politza** [comment]
fbd31dba4ce536a49a0094bf78e9e901692f8f42

Thanks.
