### ISSUE TITLE
Setting colors for markup?

### ISSUE THREAD

**Issue by wildgruber** [politza/pdf-tools#420]
Hi,

how can I set a default for the colors that are used on the pdf

- in highlighting
- in underlining

I see that it is possible to change the colors via mouse-2, but that's tedious to repeat that every time. Where are these colors defined?

Thanks

**Comment by politza** [comment]
You can't.  I've introduced a new variable `pdf-annot-default-annotation-properties` in commit 61cff64edd177eeb26d067108f4337ef5293a5a5, which allows to set default properties for all annotations types separately.

**Comment by politza** [comment]
No, the set of annotations which are creatable is much more limited, i.e. what is already implememted.
