### ISSUE TITLE
wrong-type-argument number-or-marker-p "Abort trap: 6"

### ISSUE THREAD

**Issue by arademaker** [politza/pdf-tools#421]
Mac OS, Emacs 26.1. Installed via melpa with `package-list-packages`. Many different pdf files and I got the same problem, it does not render the PDF, showing the error and a buffer with garbage. any idea?

**Comment by politza** [comment]
I think this means that a segmentation fault happened, i.e. a program
error in either epdfinfo or one of it's libraries.  The OS seems to
write the corresponding error message to stdout, which is subsequently
handled as input in Lisp, leading to the wrong-type-argument error.

It's difficult to figure out what exactly goes wrong, without using a
debugger.  You could try to run the command from a terminal and see if
that is already triggers it, e.g. cd to the program directory and

  echo quit | ./epdfinfo

or

  echo renderpage:/path/to.pdf:1:800 | ./epdfinfo

.

**Comment by arademaker** [comment]
Hi, I got

```
$ echo quit | ./epdfinfo
dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler.77.dylib
  Referenced from: /Users/ar/.emacs.d/elpa/pdf-tools-20180428.1527/./epdfinfo
  Reason: image not found
Abort trap: 6
```

but I double checked the dependencies and I have both installed:

```
$ brew install poppler automake
Warning: poppler 0.68.0 is already installed and up-to-date
To reinstall 0.68.0, run `brew reinstall poppler`
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`
```

Any idea?

**Comment by politza** [comment]
I think the problem is, that you linked against an older version of
poppler.  This kind of error should be detected when you invoke
pdf-tools-install and automatically rebuild the program.

**Comment by arademaker** [comment]
How can I solve it? In the directory `/Users/ar/.emacs.d/elpa/pdf-tools-20180428.1527/build` I didn't find any file to edit and change the reference to the right version of poppler lib.

**Comment by arademaker** [comment]
Solved! I cleanup the old versions of poppler with `brew cleanup` and reexecuted the `pdf-tools-install` ! thank you.
