### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jstaursky** [politza/pdf-tools#422]
Is it possible for pdf-tools to format annotated comments as org mode comments?
So for example, I after highlighting some text, I decide to add an annotation, separate buffer pops up and is in org-mode.
This would be useful as sometimes I want to annotate and then use org-insert-link to insert a link inside my annotation to another page within the pdf (for example, to jump to the definition of some word defined earlier in the text).

**Comment by politza** [comment]
You can customize  how annotations are displayed and which  mode is used
in  the   edit  buffer  (See   pdf-annot-print-annotation-functions  and
pdf-annot-edit-contents-setup-function).  Also,  you may want to  take a
look at the interleave package.

**Comment by jstaursky** [comment]
Ok I will take a look thank you.

**Comment by jstaursky** [comment]
Here is my hacky work-around probably could use something more idiomatic though...
`  (setq pdf-annot-edit-contents-setup-function
        (lambda (_annot)
          (org-mode)
          (run-at-time "1 sec" nil #'org-toggle-latex-fragment)
          ))`

**Comment by jstaursky** [comment]
Even better
```
 (setq pdf-annot-edit-contents-setup-function
        (lambda (_annot)
          (org-mode)
          (run-at-time ".1 sec" nil #'px-preview)
          ))
```
uses package 'preview-latex to handle a difficulty the original hack had with rendering latex after a heading has been introduced.

**Comment by politza** [comment]
I changed the order of insertion of the contents and setting up the major-mode: 213d6858a267ae3a0b7121db3c00701fe3d48a2f

**Comment by politza** [comment]
We could change the order of insertion of contents and choosing the major-mode.

**Comment by jstaursky** [comment]
[213d685](https://github.com/politza/pdf-tools/commit/213d6858a267ae3a0b7121db3c00701fe3d48a2f)
appears to have fixed issue, now using
```
 (setq pdf-annot-edit-contents-setup-function
        (lambda (_annot)
          (org-mode)
          (px-preview)
          ))
```
Works as expected, thank you!
