### ISSUE TITLE
Making pdf-tools refresh without distracting interruptions

### ISSUE THREAD

**Issue by Nidish96** [politza/pdf-tools#423]
Following some of the guidelines in [https://github.com/politza/pdf-tools/issues/25](url) I did manage to set up auto-revert with pdf-tools (yay!), but there's a small snag that's irritating me.
When I set it up with doc-view, the update is very seamless. But of course, doc-view is not searchable and has issues and I don't want to use it.
![docview](https://user-images.githubusercontent.com/17080531/45777219-ced46e00-bc1a-11e8-9805-83a0d58a4abe.gif)
^gif1: Doc-view with latexmk running in the background. Looks good and smooth.

But then when I do the same with pdf-tools, the pdf buffer blinks for a moment before reloading the file. For small files (like in the gif), this is not too long, but for larger documents this really takes some time. Has anyone faced this before/found a way to solve it?
![pdf-tools](https://user-images.githubusercontent.com/17080531/45777291-0511ed80-bc1b-11e8-9a32-075531838816.gif)
^gif2: pdf-tools with latexmk running in the background. The right side buffer blinks each time I save the tex file.

**Comment by politza** [comment]
Seems difficult to figure out exactly why this happens.

**Comment by politza** [comment]
I'm sorry but I don't think this will get ever resolved.  This kind of redisplay problems are very tricky, e.g. last month I found out that disabling the menu-bar in .Xresources lead to noticeable flickering all over the place.
