### ISSUE TITLE
Avoid messages and open buffers relating to the .synctex.gz files

### ISSUE THREAD

**Issue by antoine-levitt** [politza/pdf-tools#424]
It's annoying that every time synctex is used for a forward search in tex, pdf-tools opens the synctex file: it displays

Reverting file file.synctex.gz...
uncompressing file.synctex.gz...done
Reverting file file.gz...done

and leaves an (uninteresting) buffer open. Could this be done silently?

**Comment by politza** [comment]
It should only be displayed, if the file has changed on disk.  Not keeping the buffer around also means to uncompress it once for every search (in case it has not changed).  Anyway, I don't want to invest time in working on this minor issue.

By the way, you can get rid of the uncompressing message via `jka-compr-verbose` and silence `find-file-noselect` in the relevant `pdf-sync-synctex-file-name` function with some advice/`cl-letf` trickery.

**Comment by politza** [comment]
See d0d9e6c89e561419fa2c97652970e4e2df5e1b66 .

**Comment by antoine-levitt** [comment]
Great, thanks!
