### ISSUE TITLE
Change Annotate buffer mode from `latex-mode` to `org-mode`

### ISSUE THREAD

**Issue by hyiltiz** [politza/pdf-tools#425]
Is there any options/variables/function customization that provides `org-mode` for the annotation text buffer? It currently defaults to `latex-mode` in my spacemacs installation for which I compiled `pdf-tools` myself and manually installed it using the compiled `.tar` file locally.

**Comment by politza** [comment]
See `pdf-annot-edit-contents-setup-function'.

**Comment by politza** [comment]
See [this comment](https://github.com/politza/pdf-tools/issues/422#issuecomment-424056463).
