### ISSUE TITLE
my pdf-tools seems to  doesn't work

### ISSUE THREAD

**Issue by zzhwaxy** [politza/pdf-tools#426]
when I use it ,it runs like this and displayed in binary,but I use evince ,it runs well
**messsage**
File 汇编语言——基于Linux环境（第三版）.pdf is large (47M), really open? (y or n) y
File mode specification error: (error epdfinfo: Error opening /home/emacser/Downloads/汇编语言——基于Linux环境（第三版）.pdf:PDF document is damaged)
pdf-info-query: epdfinfo: Error opening /home/emacser/Downloads/汇编语言——基于Linux环境（第三版）.pdf:PDF document is damaged

my configure about pdf-tools is this
 (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    )

**Comment by zzhwaxy** [comment]
when I download again my pdf and evince,it shows like this and I can do nothing with it
![2018-09-25 08-38-28](https://user-images.githubusercontent.com/37314747/45986490-6fed7980-c09e-11e8-95d8-746b70a60908.png)

**Comment by politza** [comment]
Sorry, but I don't have time to remote debug this error, which is most likely a problem with your OS-setup.
