### ISSUE TITLE
Don't use nix

### ISSUE THREAD

**Issue by izahn** [politza/pdf-tools#427]
`M-x pdf-tools-install` now results in 

> error: cannot connect to daemon at '/nix/var/nix/daemon-socket/socket': Connection refused

Why is pdftools trying to use nix, and how can I tell it not to do that?

**Comment by politza** [comment]
You have a (seemingly) defunct nix-shell program in your PATH, i.e. its
executable and the script tries to use it, but fails.

**Comment by izahn** [comment]
Well, its not so much defunct as as intentionally disabled for the moment. I supposed I can make sure to remove it from my PATH while its disabled and put it back when I enable it. Still, I would prefer not to use nix even if it were enabled...

**Comment by politza** [comment]
Is there a way to test for this ? Something like a no-op nix-shell
command which would fail ?

**Comment by politza** [comment]
Maybe something like

    nix-shell --run true

?

**Comment by izahn** [comment]
I don't think so, but then I don't understand now nix works very well at all. That's the reason I have it disabled in the first place! 

`nix-shell --run true` gives me

> error: getting status of '/home/<myuser>/default.nix': No such file or directory

regardless of whether the daemon is running or not.

**Comment by moyamo** [comment]
Unfortunately, I'm running arch but would like the installer to use nix by default #468
