### ISSUE TITLE
Freezes on debug-on-error + "no such page"

### ISSUE THREAD

**Issue by vemv** [politza/pdf-tools#429]
The "No such page" errors seem generally harmless in my machine, except if I had hit `M-x toggle-debug-on-error` right before.

### Failing scenario

* `M-x toggle-debug-on-error`
* Scroll past the beginning or end of a pdf
* Debugger will pop up showing the stacktrace, but then Emacs will freeze

### Environment

macOS, https://github.com/railwaycat/homebrew-emacsmacport, `brew install poppler`, fresh `pdf-tools` from MELPA.

Thanks - Victor

**Comment by politza** [comment]
I'm unable to reproduce it and I've never had this issue before or heard about. Which leads me to suspect, that this problem is dependent on your particular setup (i.e. packages installed, customizations).

Does it happen when you `emacs -Q` ?

Can you quit (C-g) out of the freeze ?

**Comment by vemv** [comment]
Hey there, thanks for the support

> Can you quit (C-g) out of the freeze ?

Nope

> Does it happen when you `emacs -Q` ?

I'll give it a try asap

**Comment by zellerin** [comment]
I have same setup on my machine and t does not freeze, but  relatively frequent popping out of debug stack buffer is annoying anyway, as the condition (doing page up from first page, etc) is harmless.

I would suggest just showing message in this situation and saturating to first/last page, not throwing error.

Similar cases: (goto-char 99999) silently goes to end of file. (backward-char) on fist character says beginning of buffer.
