### ISSUE TITLE
Recommend how to lazily run pdf-tools-install

### ISSUE THREAD

**Issue by vemv** [politza/pdf-tools#430]
Adding `(pdf-tools-install)` to my .emacs (as the README recommends) slows down startup by a couple seconds.

If feasible, please consider recommending instead some lazy initialization technique.

Thanks - Victor

**Comment by vemv** [comment]
Fat fingered issue submission, sorry for the empty email you probably received

**Comment by politza** [comment]
I have a branch somewhere for this and it uses `auto-mode-alist` as a tool for loading the package.

**Comment by politza** [comment]
See d8dc23f48a44135f48b2bace16a182d501fa9744.

**Comment by vemv** [comment]
Thanks for the commit!

I updated my package but I can't get the new `(pdf-loader-install)` function to work.

I either evaluate it by hand or by placing it in .emacs, and after that, opening a .pdf file will still show it in Fundamental mode.
