### ISSUE TITLE
Scrolling to last section of a page

### ISSUE THREAD

**Issue by memeplex** [politza/pdf-tools#434]
When scrolling to the last section of a page the bottom of the page is aligned to the bottom of the window. This makes difficult to keep the reading flow since the next line is somewhere inside the window, not necessarily at its top. Could you add an option to scroll in a way the the next line is always at the top of the window, even if this leaves the bottom part of the window blank?

**Comment by dalanicolai** [comment]
Maybe you could use [pdf-continuous-scroll-mode](https://github.com/dalanicolai/dala-emacs-lisp/blob/master/pdf-continuous-scroll.el)
