### ISSUE TITLE
Add PDF page number in custom mode line

### ISSUE THREAD

**Issue by basille** [politza/pdf-tools#435]
I'm trying to get a simplified mode line, with minimal information. I have been able to tailor it to my needs, but there is one thing I can't manage to have, that is page number in my custom mode line.

I understand that this comes from the `pdf-misc-size-indication-minor-mode` minor mode, in conjunction with `mode-line-position`. If I don't customize my mode line, this works perfectly, i.e. I have page number (e.g. "All P1/21"). As soon as I try to customize my mode line, I can't get it to work properly, e.g. `mode-line-position` now indicates "All (1,0)" for all pages… 

To make it even more complicated, I'd like to customize the way line/column numbers are displayed, so I'm not even using `mode-line-position` at all, but `"%l:%c (%p)"` instead.

Relevant pieces of my `.emacs` for PDF-tools:

```
(add-hook 'pdf-view-mode-hook 
          '(lambda ()
             (pdf-misc-size-indication-minor-mode)))
```

and for my mode line:

```
(setq-default mode-line-format (list
                                "%e"  ; Error message about full memory
                                mode-line-front-space
                                "%* " ; Modified or read-only buffer
                                mode-line-buffer-identification
                                "      "
                                '(vc-mode vc-mode)
                                "  "
                                mode-line-remote ; Remote file
                                "      "
                                "%m" ; Only major mode
                                "      "
                                "%l:%c (%p)" ; line number : column number (percent)
                                mode-line-misc-info
                                mode-line-end-spaces
                                ))
```

**Comment by politza** [comment]
The size indication currently works by altering the variable `mode-line-position`, so it needs to be activated after this variable has been set.

You should use unevaluated symbols in the value of `mode-line-format`:

    (setq-default mode-line-format
                  '(;; ... skipped ...
                    mode-line-position
                    ;; ... skipped ...
                    ))

Then you can set a default/buffer-local value to what ever you like.

**Comment by basille** [comment]
Thanks for your super quick answer! Evaluation was indeed the key, but it does not seem to matter if `mode-line-format` appears before or after `pdf-misc-size-indication-minor-mode`. At least I've got it working using `mode-line-position`. Is there any possibility to actually tweak the resulting format? For instance, removing the "All" and only keep "P1/21"?

**Comment by politza** [comment]
Deactivate the minor-mode.

**Comment by basille** [comment]
Thanks for your answer. I'm rather confused now. I actually have the same result whether I activate or not the `pdf-misc-size-indication-minor-mode`, with percentage (in the page) and page numbers through `pdf-view-mode`, using `mode-line-position`. Am I missing something?

**Comment by politza** [comment]
I think w/o the minor-mode you are seeing Emacs default, which shows the
percentage as relating to point and point-max.
