### ISSUE TITLE
Arity of alist-get in pdf-loader.el

### ISSUE THREAD

**Issue by alastairdb** [politza/pdf-tools#436]
`pdf-loader.el` calls `alist-get` with five arguments. Such a version of `alist-get` is only available in newer versions of Emacs -- and even the version of `alist-get` defined in `pdf-util.el` as a backport  accepts only four arguments, as does my version of `alist-get` from the standard `subr.el` library in Emacs 25.2.2

Here is the five argument version:
``` elisp
(defun alist-get (key alist &optional default remove testfn)
  "Return the value associated with KEY in ALIST.
If KEY is not found in ALIST, return DEFAULT.
Use TESTFN to lookup in the alist if non-nil.  Otherwise, use `assq'.

This is a generalized variable suitable for use with `setf'.
When using it to set a value, optional argument REMOVE non-nil
means to remove KEY from ALIST if the new value is `eql' to DEFAULT."
  (ignore remove) ;;Silence byte-compiler.
  (let ((x (if (not testfn)
               (assq key alist)
             (assoc key alist testfn))))
    (if x (cdr x) default)))
```
Note, the test in `pdf-util.el` - `(unless (fboundp 'alist-get) ;;25.1` is not good enough. You have to test for the arity as well as the existence of the function to decide whether to define (or redefine) it. Or you test for the Emacs version. But I do not know at what version the five arity form was introduced.

**Comment by alastairdb** [comment]
Oops! That version of `alist-get` is no good as a backport. It depends on a three arity version of `assoc`, which apparently appeared in Emacs 26.

**Comment by politza** [comment]
I just removed the usage of alist-get from pdf-loader.el altogether. Loading the ~1000 lines pdf-util.el file (with the alist-get definition) seems like defeating the purpose of the other library.

**Comment by politza** [comment]
Thanks.
