### ISSUE TITLE
Support free-text annotations

### ISSUE THREAD

**Issue by kinleyd** [politza/pdf-tools#438]
Currently there is support only for text annotations and no way to insert text into a pdf file, as one would do when filling in a pdf form.

The glibc API documentation for poppler suggests that there is support for inserting text (with the poppler_form_field_text_set_text () function). 

It would be a killer feature if pdf-tools could add support for inserting text.

**Comment by politza** [comment]
The function you've mentioned is dealing with forms, which is not the same as annotations.  What you are looking for is called a free-text annotation, which is not part of the glib API for creating annotations.

**Comment by kinleyd** [comment]
Ah, what a shame! Thank you @politza for the clarification.

**Comment by rdiaz02** [comment]
Interestingly, pdf-tools can open and modify what Okular calls "Inline notes" and "Typewriter" notes, which I guess are "free-text" annotations. I can add/modify text and color. But the limits of the box I cannot change from pdf-tools, so the added text is not visible directly (it is is you click on the note); nor I can add these types of notes directly from pdf-tools.  I am attaching an example.
[ex-annot.pdf](https://github.com/politza/pdf-tools/files/5117299/ex-annot.pdf)
