### ISSUE TITLE
Failure finding libpoppler.so.78 when building epdfinfo server

### ISSUE THREAD

**Issue by ryw89** [politza/pdf-tools#440]
Upgraded to the latest versions of poppler and poppler-glib on Arch Linux a few days ago. After I did so, pdf-tools prompts me to rebuild the epdfinfo server when launching Emacs, but fails after complaining about not finding the shared object libpoppler.so.78.

The following workaround seems to solve the problem; pdf-tools builds successfully and appears to be working normally:

```
cd /usr/lib/
ln -s libpoppler.so.81 libpoppler.so.78
```

**Comment by calebreister** [comment]
If you installed it from melpa-stable, that is an old version. I was able to get it working by installing from melpa (unstable).

**Comment by ryw89** [comment]
I'm not using melpa-stable, so I don't think that's it.

Unfortunately for my pdf-tools, poppler and poppler-glib upgraded yet again yesterday, and now libpoppler.so.81 was replaced by libpoppler.so.82. After modifying my previous workaround mentioned above:

```ln -s libpoppler.so.82 libpoppler.so.78```

The build fails with the following error being mentioned several times:

```/usr/local/bin/epdfinfo: symbol lookup error: /usr/local/bin/epdfinfo: undefined symbol: _ZNK9GooString16hasUnicodeMarkerEva```

(Without the symbolic link pdf-tools complains about not finding libpoppler.so.78, as before.)

**Comment by politza** [comment]
Try this:

    (delete-file pdf-info-epdfinfo-program)
    (pdf-tools-install)
