### ISSUE TITLE
Support sidecar files for annotations

### ISSUE THREAD

**Issue by bremner** [politza/pdf-tools#441]
My current workflow using xournal to annotate pdfs uses sidecar files, with the pdf being annotated stored read-only in git-annex. It would be great from my point of view if pdf-tools could store annotations as some kind of overlay file (ideally text, but I guess it doesn't matter that much), rather than modifying the original pdf file.  I had a quick look at epdf-info, and I guess it would require a layer of abstraction between epdf-info and poppler that currrently does not exist.

**Comment by oantolin** [comment]
Have you tried [org-noter](https://github.com/weirdNox/org-noter), @bremner ?
