### ISSUE TITLE
pdf-tools is lagging

### ISSUE THREAD

**Issue by sorawee** [politza/pdf-tools#442]
First of all, thanks for pdf-tools. It works really great!

The problem I encountered is that, normally I can activate the Spacemacs menu and then close it really fast. However, when a buffer in `pdf-tools` mode is on screen, activating the Spacemacs menu is really lagging, taking several seconds. The pdf-tools buffer also seems to rapidly refresh(?), switching between the actual pdf and black screen. Note that I did disable linum.

Here's a GIF that illustrates the problem:

![untitled](https://user-images.githubusercontent.com/9099577/47887797-82c23f00-ddfe-11e8-8382-85846bdc7414.gif)

**Comment by politza** [comment]
Does this also happen if you use a fixed scale (e.g. `(setq pdf-view-display-size 1.0)`) ?

**Comment by sorawee** [comment]
I think you are onto something. For `1.0`, it's still slow, but much better than `fit-width`. For `0.1`, it's as fast as normal.

But the problem is that even though `1.0` or `0.1` makes it faster, the text will be too small to be readable.

**Comment by politza** [comment]
Starting from `emacs -Q` and installing `pdf-tools` and `guide-key`, I am not able to reproduce the problem you've described.  Thus, I suggest that it is the result of the interaction of those packages combined with some more included in spacemacs.
