### ISSUE TITLE
Incosistent annotation rendering when underlining more than one line

### ISSUE THREAD

**Issue by wildgruber** [politza/pdf-tools#444]
Hi,

whenever I try to underline _more than one line_ in a pdf with pdf-tools, a strange discontinuity occurs:

1. all but the last line show a stronger/thicker underlining than usual
2. only the last line marked receives underlining in normal thickness

(By "normal" thickness I mean: how the underlining looks if I mark only _one_ line.)

This results in a rather ugly and untidy look of the marked pdf document.

Any possibility to avoid that?

Thanks!

**Comment by politza** [comment]
This looks like a bug in poppler.  You can observe it also using Evince.

**Comment by wildgruber** [comment]
Is this workaround something you could yourself provide? It would be of great help as the actual state of underlining display makes it a rather displeasing experience (btw and strangely: squiggly has no problem whatsoever! only straight lines are affected).

Also I didn't find any poppler bug report with regard to this; it is hard to believe that no one remarked earlier or didn't take offense in the aspect of the pdf it produces, this is also strange I think.

Thanks

**Comment by politza** [comment]
I think it's unlikely that this problem occurs due to glib's glue-code,
but is result of the rendering code.  Note that okkular,
i.e. qt-poppler, uses a different rendering back-end, which might
explain the difference in display.

Maybe you want to report it then.
