### ISSUE TITLE
Tooltip arrow of pdf-sync-search-forward does not appear when running Emacs in daemon mode

### ISSUE THREAD

**Issue by tddsg** [politza/pdf-tools#447]
Hi, 

I'm running Emacs in the daemon mode (with the flag --daemon) and when running the fucntion pdf-sync-search-forward, the tooltip arrow does not appear. If I call this function repeatedly many times, this tooltip might flash very quickly.

Could you double check this issue in the daemon mode?
FIY, the tooltip arrow appears normally when I run Emacs in the standard mode.

Thanks!

**Comment by politza** [comment]
Do you notice anything regarding other tool-tips when running in daemon mode ?

**Comment by tddsg** [comment]
Unfortunately, I don't use any other packages that can show tool-tips in Emacs. 
However, the problem with pdf-tools tool-tips happens in all my computers that running Emacs in daemon mode (2 PCs and 1 laptop).

**Comment by politza** [comment]
Just move the pointer on the mode-part of the mode-line and a tool-tip should appear.

**Comment by tddsg** [comment]
I'm currently using Spacemacs and it seems that the tool-tip at the mode-line is disabled by default.

FYI, I also tested pdf-tools with the default configuration of Emacs (emacs -q) in the daemon mode, then the tool-tip of pdf-tools can be displayed normally.

So, I guess there is a conflict in the tool-tip setting of Spacemacs in the daemon mode (in the normal mode of Spacemacs, the tool-tip can be displayed ok)

**Comment by politza** [comment]
Sounds like it.
