### ISSUE TITLE
Have to manually update the `pdf-info-epdfinfo-program' variable after each update of pdf-tools package

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#45]
Hi,

I have noticed that you have been constantly working on making this package better. The apt-get check is really helpful as it means getting rid of a redundant step where I always hit "n" in the installation process.

Another issue also plagued me.. I am not sure if everyone faced the same problem. Here's a description of what would happen if I had pdf-tools version x installed and I had to upgrade to version y using MELPA:

1. I'd go to MELPA and choose to upgrade pdf-tools
2. It would give an error saying that it cannot remove the version x directory of pdf-tools (because the older version directory has the epdfinfo process running in it).
3. Then on trying `M-x pdf-tools-install`, it would complain that "pdf-tools-version-x-dir/build" does not exist. This would happen because the package manager already deleted the x version folder and so the old build folder doesn't exist any more and also the `pdf-info-epdfinfo-program` variable still has the old value.
4. I would then manually update that variable to point to "pdf-tools-version-y-dir/epdfinfo"
5. Manually delete "pdf-tools-version-x-dir" after finding the process id of the old epdfinfo by doing `lsof +D pdf-tools-version-x-dir` and killing that process
6. Retry `M-x pdf-tools-install`. This time the build would finish successfully.

To reduce the time of this whole process, I automated the updating of `pdf-info-epdfinfo-program` using this piece of elisp in [my setup](https://github.com/kaushalmodi/.emacs.d/commit/ad166cedacaab4ecfc1d44ddaec6566bb6df8203).

```elisp
(defun my/get-latest-pdf-tools-dir ()
  "Get the full directory path of the latest installed version of
pdf-tools package."
  (interactive)
  ;; Get a list of directories and files in `package-user-dir'
  (let ((my/package-dirs (directory-files package-user-dir)))
    ;; `break' implementation in elisp
    ;; http://ergoemacs.org/emacs/elisp_break_loop.html
    (catch 'break
      (dotimes (index (safe-length my/package-dirs))
        (let ((dir-name (pop my/package-dirs))
              full-dir-name)
          ;; (message "%s" dir-name) ; debug
          ;; Find a directory name that matches "pdf-tools-*"
          (when (string-match "pdf\\-tools\\-.*" dir-name)
            (setq full-dir-name (concat package-user-dir "/" dir-name))
            ;; To ensure that the directory is valid, ensure that it
            ;; contains "pdf-tools.el"
            (when (locate-file "pdf-tools.el" (list full-dir-name))
              ;; break the `dotimes' loop on finding this directory
              ;; and return its full path
              (throw 'break full-dir-name))))))))

(defun my/pdf-tools-install ()
  (interactive)
  ;; Update the `pdf-info-epdfinfo-program' variable to point to
  ;; the directory containing the latest version of `pdf-tools'
  (setq pdf-info-epdfinfo-program
        (concat (my/get-latest-pdf-tools-dir) "/epdfinfo"))
  ;; Call the original `pdf-tools-install' function after updating the
  ;; `pdf-info-epdfinfo-program' variable
  (pdf-tools-install))
```

I still need to do the `lsof +D` and old directory removal steps but then I do `M-x my/pdf-tools-install` instead of calling the original function.

I pieced that code together after searching how to do each step in that. So I am sure a more efficient method exists. But it works for me :)

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> I have noticed that you have been constantly working on making this
> package better. 

I try not to make it worse, at least.

> Another issue also plagued me.. I am not sure if everyone faced the
> same problem. Here's a description of what would happen if I had
> pdf-tools version x installed and I had to upgrade to version y using

I think about it, how to streamline updating.

[...]
> 2 It would give an error saying that it cannot remove the version x
>   directory of pdf-tools (because the older version directory has the
>   epdfinfo process running in it).

Mh, I don't get this error.  Is this Emacs complaining or the OS (and
which one) ?  

[...]

> To reduce the time of this whole process, I automated the updating of
> pdf-info-epdfinfo-program using this piece of elisp in my setup.

Restarting Emacs after the upgrade should also do the job, if it weren't
for your second point.

**Comment by kaushalmodi** [comment]
> I think about it, how to streamline updating.
I cursorily read in the new `pdf-dev.el` that you can restart the server. It would be useful if the package can detect that it needs to get updated and it kills the running `epdfinfo` process so that the old folder can be deleted (though I am not sure how that hand-shake between `package.el` and `pdf-tools` will work out.)
 
> Mh, I don't get this error.  Is this Emacs complaining or the OS (and which one) ?
I see the error in the emacs `*Messages*` buffer. I don't have the exact message right now but I will mention it here the next time I update `pdf-tools`. The message is along that lines that it can't remove the old folder and it is probably put out by `package.el` or the `paradox` package. The OS is Redhat Enterprise or RHEL 5.10.

> Restarting Emacs after the upgrade should also do the job, if it weren't for your second point.
 Yes, that would also work. But I like to finish updating all packages, rebuild stuff as needed for `epdfinfo` and then restart emacs.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

[...]
>     It would be useful if the package can detect that it needs to get
>     updated and it kills the running epdfinfo process so that the old
>     folder can be deleted (though I am not sure how that hand-shake
>     between package.el and pdf-tools will work out.)

Killing the server will also abandon all modifications made to any PDF
buffer and leave them in a rotten state.  That would be the next issue:
,,Updating pdf-tools made me loose all my work !!!''.

**Comment by kaushalmodi** [comment]
I understand that.. but can the killing be made conditional on the fact that none of the buffers have any of the pdf-tools' modes open? Else, it's alright. I just wanted to share that elisp snippet and wanted to know if anyone faced the same problem. The package works great for me and this issue can be closed unless you'd like to push an update based on this :)

**Comment by politza** [comment]
Sorry, I am probably tired.

Kaushal Modi <notifications@github.com> writes:

> [...] I just wanted to share that elisp snippet and wanted to know if
> anyone faced the same problem.

Yes everyone, and there should be some solution to it.

**Comment by politza** [comment]
I pushed something to streamline this updating.  Please see if it works
for you.

**Comment by kaushalmodi** [comment]
Thanks! I have updated. I'll provide feedback on how the next update goes based on this Melpa update streamlining improvement.

**Comment by tsdh** [comment]
I just updated to the MELPA version `pdf-tools-20150207.2058`, and now the installation is broken for me.  My ~/.emacs contains just `(pdf-tools-install)`.  After restarting Emacs and saying "yes" as the prompt if I want to build the server, I get the error `(error "No executable `epdfinfo' found")`.

I can reproduce that using `M-x pdf-tools-install`.  However, the epdfinfo command seems to be there:

```
% ll ~/.emacs.d/elpa/pdf-tools-20150207.2058/epdfinfo 
-rwxr-xr-x 1 horn horn 399712  8. Feb 09:50 /home/horn/.emacs.d/elpa/pdf-tools-20150207.2058/epdfinfo
```

And the value of `pdf-info-epdfinfo-program` is correct, too.

```
pdf-info-epdfinfo-program is a variable defined in `pdf-info.el'.
Its value is
"/home/horn/.emacs.d/elpa/pdf-tools-20150207.2058/epdfinfo"
Original value was 
"/home/horn/.emacs.d/elpa/epdfinfo"
```

So what's the matter?

**Comment by boccaperta-it** [comment]
Same issue here. ```epdfinfo``` is there (after having restarted Emacs), but keeps saying it is not.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> So what's the matter?

The check for programm was commented out...

5f3092f52a4ba46f97c139b6bd684e9f4fcc801d

**Comment by boccaperta-it** [comment]
I can confirm it is working fine now. Thank you.

**Comment by kaushalmodi** [comment]
I need to run `my/pdf-tools-install` to update the `pdf-info-epdfinfo-program` variable but that's alright. With your updates, the package manager initiated updated complete fine as it is now able to successfully delete the old pdf-tools folder. 

Now the installation process is smooth:

- Update `pdf-tools` from package manager/paradox.
- Run `my/pdf-tools-install`

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> I need to run my/pdf-tools-install to update the
> pdf-info-epdfinfo-program variable but that's alright.

That should happen automatically.

**Comment by kaushalmodi** [comment]
Sorry but that issue with removing old directories is back. 

This happened after I updated to `pdf-tools-20150208.715` from MELPA.

<pre>
km²~/.emacs.d/:elpa_24_4> remove pdf-tools-20150208.320
rm: cannot remove `pdf-tools-20150208.320/.nfs00000000065b835e00000079': Device or resource busy

km²~/.emacs.d/:elpa_24_4> lsof +D pdf-tools-20150208.320/
COMMAND    PID  USER  FD   TYPE DEVICE SIZE/OFF      NODE NAME
epdfinfo 10491 kmodi txt    REG   0,46   378056 106660702 pdf-tools-20150208.320/.nfs00000000065b835e00000079

km²~/.emacs.d/:elpa_24_4> kill -9 10491

km²~/.emacs.d/:elpa_24_4> remove pdf-tools-20150208.320

km²~/.emacs.d/:elpa_24_4>
</pre>

*`remove` is my alias to `\rm -rf`*

Still on doing `C-h v pdf-info-epdfinfo-program`, I get 

    pdf-info-epdfinfo-program's value is "/home/kmodi/.emacs.d/elpa_24_4/pdf-tools-20150208.320/epdfinfo"

It's value should have been updated to the new version to `"/home/kmodi/.emacs.d/elpa_24_4/pdf-tools-20150208.715/epdfinfo"`.

But the incorrect variable issue is averted by running `my/pdf-tools-install`.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> km²~/.emacs.d/:elpa_24_4> remove pdf-tools-20150208.320
> rm: cannot remove `pdf-tools-20150208.320/.nfs00000000065b835e00000079': Device or resource busy

So your package directory is on a nfs file-system ? 

> pdf-info-epdfinfo-program's value is
> "/home/kmodi/.emacs.d/elpa_24_4/pdf-tools-20150208.320/epdfinfo"

Does the upgrade automatically start a compilation of the new epdfinfo
program ? 

-ap

**Comment by boccaperta-it** [comment]
On my Emacs, I can confirm latest upgrade automatically starts the compilation of the new epdfinfo.

**Comment by kaushalmodi** [comment]
@politza 

Yes, I am on an NFS system. The package manager cannot (nor can I from the command line) delete the old pdf-tools-* folder while the epdfinfo process is running.

The upgrade don't auto start the compilation; I need to call `my/pdf-tools-install`.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> Yes, I am on an NFS system. The package manager cannot (nor can I from
> the command line) delete the old pdf-tools-* folder while the epdfinfo
> process is running.
> The upgrade don't auto start the compilation; I need to call
> my/pdf-tools-install.

One reason we would see this happening is if the package manager would
delete the old package before installing the new one, which package.el
does not seem to do.

You said earlier that you use a package manager called `paradox' ?

**Comment by kaushalmodi** [comment]
Alright, next time I will update using `package.el` instead of `paradox` and update this thread.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> Alright, next time I will update using package.el instead of paradox
> and update this thread.

More importantly, the check in pdf-tools.el whether an upgrade is
happening is specifically targeted at package.el.  It didn't occur to me
that people might use other managers.

-ap

**Comment by boccaperta-it** [comment]
Not try to be a PITA here, but I use Paradox and everything went as I wrote before.

**Comment by politza** [comment]
It might, I don't know how Paradox works.

**Comment by kaushalmodi** [comment]
Hi,

I updated pdf-tools with `package.el` today. I did not have to delete the old directory manually but I had to run `pdf-tools-install` after the update because I got this error:

> Error in post-command-hook (pdf-tools--upgrade): (error "The variable pdf-info-epdfinfo-program is unset or not executable: /home/kmodi/.emacs.d/elpa_25_0/pdf-tools-20150212.1539/epdfinfo")

This time I was updating on the latest emacs version from its git master as of yesterday; same OS and NFS system.

**Comment by tsdh** [comment]
Kaushal Modi <notifications@github.com> writes:

> I updated pdf-tools with package.el today. I did not have to delete the old
> directory manually but I had to run pdf-tools-install after the update because
> I got this error:
>
>     Error in post-command-hook (pdf-tools--upgrade): (error "The variable
>     pdf-info-epdfinfo-program is unset or not executable:
>     /home/kmodi/.emacs.d/elpa_25_0/pdf-tools-20150212.1539/epdfinfo")

Yeah, I've had that too with the last MELPA update on a system with no
additional complications like NFS.

Bye,
Tassilo

**Comment by politza** [comment]
I don't know what to do about this, since I'm unable to reproduce it and can't see how this could happen, appart from guessing.

**Comment by kaushalmodi** [comment]
Closing this issue as it seems specific to the file system on my machine and also because I have a workaround.

**Comment by kaushalmodi** [comment]
I wanted to let you know that this issue seems to have been fixed since last 2 melpa updates. I don't need to use my workaround function.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> I wanted to let you know that this issue seems to have been fixed
> since last 2 melpa updates. I don't need to use my workaround
> function.

Great. I may have been a transitional error, with old code still
interfering.
