### ISSUE TITLE
Correct way to defer `pdf-tools` with `use-package`

### ISSUE THREAD

**Issue by matthew-piziak** [politza/pdf-tools#450]
I would like to use `use-package pdf-tools` to defer loading of the packages until the new binaries are available.

I thought this might work...
```lisp
  (use-package pdf-tools
    :straight t
    :defer 10
    :init
    (pdf-tools-install 'no-query)
    :config
    (require 'let-alist)
    (require 'pdf-tools)…
```
…but this fails whenever I upgrade the package, which means I have to restart Emacs again. Not a big deal in the big scheme of things, but I figure it should be possible to set this up.

**Comment by politza** [comment]
I'm not following.  What binaries and what fails if you upgrade ?

**Comment by matthew-piziak** [comment]
So when Emacs starts, in the compilation buffer I get this:
```
---------------------------
       Installing          
---------------------------
make -s install
make[1]: Entering directory '/home/matt/.emacs.d/straight/build/pdf-tools/build/server'
 /nix/store/920k63py2w97xpfyb5ps9l6wbidvzfjz-coreutils-8.29/bin/mkdir -p '/home/matt/.emacs.d/straight/build/pdf-tools'
  /nix/store/920k63py2w97xpfyb5ps9l6wbidvzfjz-coreutils-8.29/bin/install -c epdfinfo '/home/matt/.emacs.d/straight/build/pdf-tools'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/matt/.emacs.d/straight/build/pdf-tools/build/server'

===========================
   Build succeeded. :O)    
===========================
```

But meanwhile in the `*Warnings*` buffer I get this:
```
Error (use-package): pdf-tools/:config: pdf-info-epdfinfo-program is not executable
```

This might be an edge case not worth worrying about.

**Comment by sirikid** [comment]
But you need to load the package before you start making new binaries. Do you see a contradiction?
