### ISSUE TITLE
Consider `image-scaling-factor` in Emacs > 26.1

### ISSUE THREAD

**Issue by dzop** [politza/pdf-tools#454]
For a while I was wondering why my PDF's always appeared off center when using `pdf-view-auto-slice-minor-mode` and why the link hotspots where offset as well. I think I was finally able to track it down to the variable `image-scaling-factor`, introduced in Emacs 26.1. From its documentation

```
When displaying images, apply this scaling factor before displaying.
```

When  I set the scaling to 1, the offsets disappear, so I'm thinking the issue is due to `pdf-tools` not considering this scaling factor when calculating the image slice and hotspots.

I tried to fix the issue for link hotspots by applying the scaling calculated from `image-compute-scaling-factor` to the image size in `pdf-view-apply-hotspot-functions` before calling the hotspot functions, but it didn't seem to work. This was mainly a shot in the dark, since I'm not familiar at all in how the `:map` property of an image works, in particular if it considers the scale of the image. It doesn't look to be the case though.

**Comment by politza** [comment]
I don't see any point in using another scaling factor with pdf-tools, since it already performs its own scaling.  So, my solution would be to deactivate `image-scaling-factor` in PDF buffers.  What do you think ?

**Comment by dzop** [comment]
Sounds good.

**Comment by politza** [comment]
See 7a6c238 .
