### ISSUE TITLE
compilation error possibly due to change in poppler GooString

### ISSUE THREAD

**Issue by gergelyszirmai** [politza/pdf-tools#455]
Hi there,

There was a compilation error in the update: pdf-tools-20181118.2051 on arch linux 64 bit. The poppler library was just updated to 0.72.0-1

Unfortunately, I didn't keep the compilation log, it throw an error at the poppler-hack.cc file about the
GoString::getCString() method in line 65.

It is changed in poppler to GoString::c_str()

Solution: change line 65 to:
result = g_convert (s->c_str () + 2,

All the best,
Gergely

**Comment by politza** [comment]
Update pdf tools.

**Comment by gergelyszirmai** [comment]
You are right. Sorry. For some reason, spacemacs for me only updates the gnu archive now.
