### ISSUE TITLE
Crash on Mingw64 with ImageMagick

### ISSUE THREAD

**Issue by fpopineau** [politza/pdf-tools#458]
Hi,

I build emacs master with Mingw64 and with a set of patches to get ImageMagick 7.
Emacs is crashing with the following sequence:
- split window vertically
- open a pdf in the left pane with pdf-tools
- open a jpeg in the right pane (with IM)
Unfortunately, for the moment I can't find a way to track down this issue.
All I get is a crash in the middle of IM:
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006b3df0a2 in ?? () from /mingw64/bin/libMagickCore-7.Q16HDRI-6.dll
(gdb) where
#0  0x000000006b3df0a2 in ?? () from /mingw64/bin/libMagickCore-7.Q16HDRI-6.dll
#1  0x000000006b3e1a0c in ?? () from /mingw64/bin/libMagickCore-7.Q16HDRI-6.dll
#2  0x0000000068416f0a in ?? () from /mingw64/bin/libMagickWand-7.Q16HDRI-6.dll
#3  0x00000004002ff111 in imagemagick_load_image (f=0x400c91600 <dumped_data+4556224>, img=0x2673930, contents=0x0, size=0,
    filename=0xaa31f68 "c:/Users/Fabrice/Downloads/318-29590.jpg") at ../../emacs/src/image.c:9212
#4  0x00000004002ff503 in imagemagick_load (f=0x400c91600 <dumped_data+4556224>, img=0x2673930) at ../../emacs/src/image.c:9345
#5  0x00000004002f2981 in lookup_image (f=0x400c91600 <dumped_data+4556224>, spec=0xaa2de83) at ../../emacs/src/image.c:1876
#6  0x00000004002f0ad9 in Fimage_size (spec=0xaa2de83, pixels=0xcf60, frame=0x0) at ../../emacs/src/image.c:1001

Any idea would be welcome.
Regards,

**Comment by politza** [comment]
If Emacs crashes, please report it to the Emacs bug-tracker.
