### ISSUE TITLE
feature request: trimming whitespace on page edges

### ISSUE THREAD

**Issue by tpapp** [politza/pdf-tools#46]
This would be very useful for viewing eg LaTeX documents side-by-side with their source, especially if screen space is limited. Ideally, this could work similarly to okular: establish a bounding box for a page, trim the excess (leaving only a bit), then apply relevant magnification (W, P).

**Comment by politza** [comment]
This ?

    ,----[ C-h f lisp RET ]
    | pdf-view-set-slice-from-bounding-box is an interactive Lisp closure in
    | `pdf-view.el'.
    | 
    | (pdf-view-set-slice-from-bounding-box &optional WINDOW)
    | 
    | Set the slice from the page's bounding-box.
    | 
    | The result is that the margins are almost completely cropped,
    | much more accurate than could be done manually using
    | `pdf-view-set-slice-using-mouse'.
    | 
    | See also `pdf-view-bounding-box-margin'.
    | 
    | [back]
    `----

-ap

**Comment by tpapp** [comment]
Thanks, I was not aware of this. I would find the following two features useful:
1. have a state, eg `pdf-view-trim`, that is toggled with a key (eg `T`),
2. if the state is non-nil, trim each page automatically upon display. This would mean examining the bounding box for each state (may not be uniform, frequently isn't).

**Comment by politza** [comment]
See  `pdf-view-set-slice-from-bounding-box'.
