### ISSUE TITLE
inline rendering of pdf in org mode

### ISSUE THREAD

**Issue by gdkrmr** [politza/pdf-tools#462]
I am not sure if this is the right place to ask.

In `org-mode` I can include figures like this and render them inline with `org-toggle-inline-images`:
```org
[[file:figs/fig1.png]]
```

most of the time I use pdf, export works fine, but I cannot render them inline:
```org
[[file:figs/fig1.pdf]]
```

**Comment by politza** [comment]
It's not possible to display a PDF inline in another buffer, while using the PDF Tools features.  You could render a specific page and display it somewhere, e.g. in an org-mode buffer.   The code for this would have to be added to `org-display-inline-images`.
