### ISSUE TITLE
changing username in comments

### ISSUE THREAD

**Issue by sobyrne** [politza/pdf-tools#463]
Is there a way of removing or changing the username designation on pdf comments?  I would like to use pdf-tools to annotate paper reviews, but it seems that all the comments I insert have my username attached.  I would like to anonymise the resulting pdf by having nothing or 'anonymous' as the user name on comments.

**Comment by dzop** [comment]
You have to modify `pdf-annot-default-annotation-properties` to remove your name from annotations you insert. I don't know about changing existing annotations though.

**Comment by sobyrne** [comment]
Thanks very much:  it's sufficient for me that I can do it for future documents.
