### ISSUE TITLE
Consider changing the default key for pdf-sync-forward-search from "C-c C-g"

### ISSUE THREAD

**Issue by hpdeifel** [politza/pdf-tools#464]
I know it's configurable through `pdf-sync-forward-display-pdf-key`, but it tripped me up a lot until I figured out what was going on: 

The <kbd>C-g</kbd> key is usually used to cancel key sequences, as explained in [(elisp)Key Binding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html). Cancelling key sequences this way is muscle memory for me and probably lots of other users.

<kbd>C-c</kbd> is a very common prefix key and so I end up unintentionally invoking `pdf-sync-forward-search` a lot, leaving me puzzled over the result. Since it's unconscious muscle memory, the perceived effect is just "My Emacs randomly jumps to different buffers".

**Comment by politza** [comment]
Yes, it's a bad choice.  Any suggestions ?

**Comment by hpdeifel** [comment]
Is it necessary at all? Auctex's own `TeX-pdf-tools-sync-view` also jumps to the correlated position in the pdf if `TeX-source-correlate-mode` is active. And it's bound to `C-c C-v` by default, if pdf-tools is selected as viewer.

**Comment by politza** [comment]
7a6c238
