### ISSUE TITLE
fitting width (W) and page (P) results in too large pages

### ISSUE THREAD

**Issue by tpapp** [politza/pdf-tools#465]
I am using `pdf-tools` version `20190118` (melpa) on Emacs `27.0.50`, from the `emacs-snapshot` Ubuntu 18.10 package (from [this PPA](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa)).

When I press `P` or `W`, the size is calculated incorrectly, resulting in a magnification which is about 20-30% too large for the desired fit.

Things work fine with Emacs 26.

I am happy to provide further debugging information if that helps.

**Comment by politza** [comment]
Does it help if you set `image-scaling-factor` to `1` in the PDF buffer ? See also #454 .

**Comment by tpapp** [comment]
Yes,
```elisp
(setq image-scaling-factor 1)
```
fixes the issue.

I added this to `pdf-view-mode-hook`, but perhaps it could be set by default for this mode?

**Comment by politza** [comment]
See 7a6c238 .
