### ISSUE TITLE
Forward search indicator arrow constantly above correct line

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#47]
I use a current Emacs from git and `pdf-tools-20150208.320` from MELPA.  When I call `pdf-sync-forward-search` from inside AUCTeX (or AUCTeX's "PDF Tools" viewer command), the red arrow indicating the line in the PDF buffer is constantly shown a bit too high.

I usually use slicing (`s b`) so that the margins are cut off, however that doesn't seem to be the culprit.  It seems the arrow is always a fixed amount of centimeters/pixels too high, i.e., the distance between the arrow and the correct line is always ~2cm here on my screen even when setting the zoom level to "very large" or "very small".

I'm pretty sure that last week (with the current pdf-tools/emacs versions at that time) I didn't have that issue.  I'm also happy to do any debugging that might help to spot the problem.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> I use a current Emacs from git and pdf-tools-20150208.320 from MELPA.
> When I call pdf-sync-forward-search from inside AUCTeX (or AUCTeX's
> "PDF Tools" viewer command), the red arrow indicating the line in the
> PDF buffer is constantly shown a bit too high.


Try this for a start

    (pdf-util-tooltip-in-window "Hey" 0 0)

This should display a tooltip aligned with the window's body (sans
fringes etc.).

-ap

**Comment by tsdh** [comment]
That's already shown too high.

![screenshot from 2015-02-10 07 53 30](https://cloud.githubusercontent.com/assets/103854/6122873/3199298e-b0fa-11e4-8d87-a4c51ce4b089.png)

I also tried with emacs -Q, then leading the `pdf-tools-autoloads.el` file followed by finding a PDF.  And then, the tooltip's upper left corner started in the middle height of the toolbar.  When I disable toolbar and menubar, the tooltip also starts some pixels above the window decorations of the emacs frame but slightly less than with my normal emacs configs.

The current MELPA version `pdf-tools-20150208.715` behaves the same.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> That's already shown too high.
>
> screensh
>

I just remember that I run a patched Emacs, where
`window-inside-pixel-edges' works correctly.  In stock Emacs it does not
account for the window-manager's borders (bug #5721).

Apparently you've changed your window-manager setup.

-ap

**Comment by tsdh** [comment]
Too bad, it seems the bug stalled. :-1: 

And no, I didn't change my window manager setup.  But my "used to work last week" might be wishful thinking.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> Too bad, it seems the bug stalled. 
> :-1:

It's not a bug, it's a feature (as it seems).  

The arrow should go away anyway and the position displayed as some
markup in the image.

-ap

**Comment by tsdh** [comment]
Ah, ok, that would be even better.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> Ah, ok, that would be even better.

'Til then I guess I could add an offset variable, since it is basically
just the title bar, which is more or less constant.

pos-tip.el , for example, uses xwininfo get at this information.  But I
don't really like to include a bunch of code dealing with this.

-ap

**Comment by tsdh** [comment]
It's not too important for me.
