### ISSUE TITLE
How to pdf-tools open pdf file on current window instead of other new opened window?

### ISSUE THREAD

**Issue by fu123456** [politza/pdf-tools#470]
Hi, I use pdf-tool as my main tool to view my many pdf files. But there is a noisy operation that pdf-tools open a new pdf file on other new window. So my question is how to open pdf file in current window, not open new window. It may be easy, but please help me.

**Comment by politza** [comment]
In which window PDFs are displayed is determined entirely outside of
pdf-tools, i.e. by your configuration of Emacs.  E.g. C-x C-f would
display the PDF in the selected window.

**Comment by fu123456** [comment]
thanks.
