### ISSUE TITLE
aclocal-1.15: command not found

### ISSUE THREAD

**Issue by bbuccianti** [politza/pdf-tools#472]
Hi!

I have a problem building pdf-tools.

I pulled the repo and when running make autobuild I'm getting an error. The error says `WARNING: 'aclocal-1.15' is missing on your system` 

After the WARNING: of the missing output I get this error:
    `make[1]: *** [Makefile:397: aclocal.m4] Error 127`

I tried to run with the '-d' option but I can't understand the output so I decided to come here for help.

Seems like the problem is the version of automake. I have version 1.16.1 but seems like I need 1.15.1. This is correct? I never downgraded a package before so maybe is a good opportunity to learn.

Thank you!

**Comment by politza** [comment]
Seems like a broken autoconf/automake installation.  Have you tried reinstalling those packages ?

**Comment by bbuccianti** [comment]
I resolved the issue deleting the pdf-tools from emacs with package-delete and installing again.

Thank you!
