### ISSUE TITLE
Can't build the package - `libpng` not found

### ISSUE THREAD

**Issue by squiter** [politza/pdf-tools#475]
Hello guys, maybe I missed something but my package was not building... the error message is:

```
configure: error: Package requirements (libpng) were not met:

No package 'libpng' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables png_CFLAGS
and png_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
```

But I already have the package:

```
dpkg -l | rg libpng
ii  libpng-dev:amd64                           1.6.34-1ubuntu0.18.04.1                      amd64        PNG library - development (version 1.6)
ii  libpng-tools                               1.6.34-1ubuntu0.18.04.1                      amd64        PNG library - tools (version 1.6)
ii  libpng16-16:amd64                          1.6.34-1ubuntu0.18.04.1                      amd64        PNG library - runtime (version 1.6)
```

Can someone help me?

**Comment by politza** [comment]
Try to reinstall the libpng package.

**Comment by squiter** [comment]
Same error :cry:

**Comment by politza** [comment]
Locate the png.pc file or whatever its called.

**Comment by squiter** [comment]
```
$ locate png.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/cairo-png.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libpng.pc
```

**Comment by politza** [comment]
Then try to set the pkg-config variable as instructed in its output.

**Comment by squiter** [comment]
Yes, this fix did the trick! I added this line before the installation of `pdf-tools`:

```
(setenv "PKG_CONFIG_PATH" "/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig")
```

Thank you for the help

**Comment by msonnad** [comment]
I am also experiencing the same issue. From where I can download the installable libpng package for Linux(centos). What is the process to install?

**Comment by politza** [comment]
I don't know, but libpng is a very common library.

**Comment by Cumol** [comment]
For some reason I was missing the common paths for pkg-config

setting this in the terminal before starting emacs solved the issue

`export PKG_CONFIG_PATH=/usr/share/pkgconfig/:/usr/lib/x86_64-linux-gnu/pkgconfig/`

**Comment by yevhenshymotiuk** [comment]
Same issue on the latest OS X (Big Sur Beta 11). Exporting `PKG_CONFIG_PATH` with a path to `libpng.pc` (`/usr/local/lib/pkgconfig` in my case) doesn't help

**Comment by kontrapant** [comment]
experiencing the same problem on Big Sur Beta

**Comment by pkerpedjiev** [comment]
FWIW, I was able to solve a similar issue by doing `conda install pkgconfig`.
