### ISSUE TITLE
Forward search tooltip position in two column documents

### ISSUE THREAD

**Issue by Pouya-moh** [politza/pdf-tools#476]
In two column documents, e.g. IEEE conference format, the tooltip arrow of forward search always appears on the left side of the left column even if the query is in the right column. Is it possible to have the arrow appear next to the correct column? Or perhaps, if possible, highlight the relevant part similar to texstudio or other editors for better visibility?

Note that the tooltip is pointing to the correct line just wrong column.

Cheers.

**Comment by politza** [comment]
The tooltip is shown at the left margin, it has no notion of a column.
