### ISSUE TITLE
Broken with mismatching pnglib 

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#48]
Using a fresh-built 25.0.5 version neither DocView nor PDF-Tools work. I see the following error:
PNG warning: Application built with libpng-1.6.6 but running with 1.5.17 [8 times]

It doesn't sound fatal, but sure enough nothing shows up but an empty box. This is probably related to issues I'm having with 25.0.5 where I can't install without an older pnglib; I've submitted a bug report for that. Nonetheless, wanted to report this here so that you're aware of it (although it's probably out of your hands).

**Comment by politza** [comment]
Try
    sudo ldconfig /usr/local/lib
.

**Comment by WorldsEndless** [comment]
Unfortunately doesn't seem to change anything. 

--8<---------------cut here---------------start------------->8---
$ sudo ldconfig -v /usr/local/lib | grep "libpng"
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
	libpng16.so.16 -> libpng16.so.16.16.0
	libpng16.so.16 -> libpng16.so.16.6.0
	libpng12.so.0 -> libpng12.so.0.50.0
	libpng16.so.16 -> libpng16.so.16.6.0
	libpng15.so.15 -> libpng15.so.15.17.0
$ whereis libpng
libpng: /usr/lib64/libpng15.so /usr/lib64/libpng16.so /usr/lib64/libpng.so /usr/local/lib/libpng16.a /usr/local/lib/libpng.a /usr/local/lib/libpng.la /usr/local/lib/libpng16.so /usr/local/lib/libpng.so /usr/local/lib/libpng16.la /usr/share/man/man3/libpng.3.gz
--8<---------------cut here---------------end--------------->8---

**Comment by WorldsEndless** [comment]
Fixed when installing libpng with ./configure --prefix=~anaconda
