### ISSUE TITLE
pdf-tools-install fail

### ISSUE THREAD

**Issue by cxb811201** [politza/pdf-tools#480]
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/27.0/develop/pdf-tools-20190309.744/build/server/" -*-
Comint started at Mon Mar 11 13:06:58

/Users/chenxianbin/.emacs.d/elpa/27.0/develop/pdf-tools-20190309.744/build/server/autobuild -i /Users/chenxianbin/.emacs.d/elpa/27.0/develop/pdf-tools-20190309.744/
---------------------------
    Installing packages    
---------------------------
brew install pkg-config poppler automake
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: poppler 0.74.0 is already installed and up-to-date
To reinstall 0.74.0, run `brew reinstall poppler`
Warning: automake 1.16.1_1 is already installed and up-to-date
To reinstall 1.16.1_1, run `brew reinstall automake`

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/chenxianbin/.emacs.d/elpa/27.0/develop/pdf-tools-20190309.744/ && make -s
configure: error: Package requirements (poppler-glib >= 0.16.0) were not met:

Package 'libffi', required by 'gobject-2.0', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_glib_CFLAGS
and poppler_glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Mon Mar 11 13:07:01

**Comment by bouvin** [comment]
I’m seeing much the same, using GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31 from https://emacsformacosx.com on macOS 10.14.3.

I update regularly, and the previous version built just fine.

[failed-pdf-tools-build.txt](https://github.com/politza/pdf-tools/files/2956858/failed-pdf-tools-build.txt)

**Comment by politza** [comment]
Looks to me like a broken brew package.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: bouvin <notifications@github.com> </div><div>Datum:12.03.2019  13:45  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] pdf-tools-install fail (#480) </div><div>
</div>I’m seeing much the same, using GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31 from https://emacsformacosx.com on macOS 10.14.3.

I update regularly, and the previous version built just fine.

failed-pdf-tools-build.txt

**Comment by m-falconi** [comment]
Do you know how to report a bug of homebrew poppler formula?

**Comment by danjin250** [comment]
I had this same issue, also on
Mac Mojave, Emacs 26, using Spacemacs specifically.
I found installing it from homebrew solved the issue.

`brew install --HEAD dunn/homebrew-emacs/pdf-tools`

After installing from homebrew, installing the package manually through package-list
or using use-package, and then running (pdf-tools-install) worked for me.

Credits to below:
https://emacs.stackexchange.com/a/22591/21890

**Comment by cxb811201** [comment]
Thanks

**Comment by politza** [comment]
`poppler` depends on `glib`, which in turn depends on `libffi` as can be examined [here](https://formulae.brew.sh/formula/poppler).  So it should have been installed.

**Comment by carlosgeos** [comment]
`libffi` is keg-only (maybe it wasn't before), therefore only exists in `/usr/local/Cellar`. 

There is no `libffi.pc` in `/usr/local/lib/pkgconfig/`, and pkgconfig cannot find it. There is no problem with brew I believe.

I solved it temporarily by using:

```
(setenv "PKG_CONFIG_PATH" "/usr/local/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig")
```

**Comment by sbacelar** [comment]
I have a similar error on Mac:
```
./configure -q --bindir=/Users/sergiobacelar/.emacs.d/elpa/pdf-tools-20190413.2018/ && make -s
configure: error: Package requirements (poppler-glib >= 0.16.0) were not met:

Package 'libffi', required by 'gobject-2.0', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_glib_CFLAGS
and poppler_glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.
```

**Comment by vancleve** [comment]
> `libffi` is keg-only (maybe it wasn't before), therefore only exists in `/usr/local/Cellar`.
> 
> There is no `libffi.pc` in `/usr/local/lib/pkgconfig/`, and pkgconfig cannot find it. There is no problem with brew I believe.
> 
> I solved it temporarily by using:
> 
> ```
> (setenv "PKG_CONFIG_PATH" "/usr/local/lib/pkgconfig:/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig")
> ```

This works for me too. Also, I used this, inspired by https://github.com/seanfarley/pdf-tools/commit/90cfab0623146c0e1d2c8ffdca1de4c105dc00d6: 
`(setenv "PKG_CONFIG_PATH" (concat (shell-command-to-string "printf %s \"$(brew --prefix libffi)\"") "/lib/pkgconfig/"))`

**Comment by guoqinglei** [comment]
I have tried to install pdf tools in emacs 26.3, my macOS version is macOS Catalina 10.15.4.
The install errors are as follow:

-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20181118.2051/build/server/" -*-
Comint started at Fri May  1 21:27:46

/Users/hahaha/.emacs.d/elpa/pdf-tools-20181118.2051/build/server/autobuild -i /Users/hahaha/.emacs.d/elpa/pdf-tools-20181118.2051/
---------------------------
    Installing packages    
---------------------------
brew install pkg-config poppler automake
Warning: pkg-config 0.29.2_3 is already installed and up-to-date
To reinstall 0.29.2_3, run `brew reinstall pkg-config`
Warning: poppler 0.88.0 is already installed and up-to-date
To reinstall 0.88.0, run `brew reinstall poppler`
Warning: automake 1.16.2 is already installed and up-to-date
To reinstall 1.16.2, run `brew reinstall automake`

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/Users/hahaha/.emacs.d/elpa/pdf-tools-20181118.2051/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

poppler-hack.cc:65:30: error: no member named 'getCString' in 'GooString'
      result = g_convert (s->getCString () + 2,
                          ~  ^
1 error generated.
make[1]: *** [epdfinfo-poppler-hack.o] Error 1
make: *** [all] Error 2
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Fri May  1 21:28:03

Anyone can give me any advice ?

**Comment by politza** [comment]
Remove the package, restart Emacs and reinstall.
