### ISSUE TITLE
Is there a way to defer pdf-tools with use-package while retaining its functionality?

### ISSUE THREAD

**Issue by mrbig033** [politza/pdf-tools#482]
#### Runtime Environment ####

- MX Linux 18
- GNU Emacs 27.0.50
- Evil version 1.2.14
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- use-package: 20181119.2350
- pdf-tools: 20190129.1822

#### Issue ####

With the configuration,

```
(use-package pdf-tools
  :defer t
  :init
  (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode)))
```

I get the following error whenever I try to open a PDF file:

`File mode specification error: (void-function pdf-view-mode)`

If I remove the deferring it opens PDFs normally, but I get a huge loss in performance. Other modes work fine with deferring. Is there something I can do?

**Comment by politza** [comment]
Try this instead.  

(use-package pdf-loader
  :config (pdf-loader-install))

Note, there is no need to modify auto-mode-alist.

**Comment by JalapenoGremlin** [comment]
John Wiegley (the author of `use-package`) has this in the documentation:  https://github.com/jwiegley/use-package#magic-handlers


```emacs-lisp
(use-package pdf-tools
  :load-path "site-lisp/pdf-tools/lisp"
  :magic ("%PDF" . pdf-view-mode)
  :config
  (pdf-tools-install :no-query))
```

> This registers an autoloaded command for pdf-view-mode, defers loading of pdf-tools, and runs pdf-view-mode if the beginning of a buffer matches the string "%PDF".

**Comment by cilia** [comment]
Tried the above suggestion, but with the latest `pdf-tools` and `use-package` the following error occurs:
`File mode specification error: (error Autoloading file /Users/cilia/Dropbox/emacs/elpa/pdf-tools-20191031.642/pdf-occur.elc failed to define function pdf-occur-global-minor-mode`
