### ISSUE TITLE
Different zoom level in two buffers displaying the same file

### ISSUE THREAD

**Issue by novakboskov** [politza/pdf-tools#484]
Hello @politza! 
First things first, thank you for the great work!

In my everyday workflow I use `pdf-tools` a lot. Usually I split my window vertically and open the same file in both buffers. On the right side is the page that I am currently reading and on the left is a page with some figures or references. I would like to zoom only the buffer with the page that displays the images without zooming my buffer that contains the page that I am reading. Is this behavior supported?

**Comment by politza** [comment]
No, not currently.  But it would be possible to make `pdf-view-display-size` a window-local property, like e.g. the current page.
