### ISSUE TITLE
`pdf-annot-list-annotations` does not properly show the window with the text of the selected annotation

### ISSUE THREAD

**Issue by mbork** [politza/pdf-tools#485]
The echo area says:
`tablist-display-buffer-split-below-and-attach: Wrong number of arguments: (3 . 4), 5`
This happens on a fresh Emacs: GNU Emacs 27.0.50 (build 25, x86_64-pc-linux-gnu, GTK+ Version 3.24.7) of 2019-04-10.

**Comment by politza** [comment]
The function you mention uses an internal function which has changed its arity  in Emacs-git.  I'm going to write a fix soon.

**Comment by politza** [comment]
If you update pdf-tools from melpa, it should work now.

**Comment by mbork** [comment]
Unfortunately, it seemingly doesn't...

**Comment by mbork** [comment]
Sorry for the noise. I didn't update tablist. It's working now.
