### ISSUE TITLE
My Manjaro system cannot install pdf-tools.

### ISSUE THREAD

**Issue by fu123456** [politza/pdf-tools#487]
Hi, I use Manjaro system (Archlinux). But I need to often reinstall my pdf-tools plugin due to my system update. I think that this may be caused by poppler version. I get the following error:
------------------------------------------------------------------------------------------------------------------------------
/usr/bin/ld: epdfinfo-epdfinfo.o: in function `mktempfile':
/home/fg/.emacs.d/elpa/develop/pdf-tools-20190129.1822/build/server/epdfinfo.c:354: warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_out(__mbstate_t&, wchar_t const*, wchar_t const*, wchar_t const*&, char*, char*, char*&) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_always_noconv() const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::collate<char> const& std::use_facet<std::__cxx11::collate<char> >(std::locale const&)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_in(__mbstate_t&, char const*, char const*, char const*&, wchar_t*, wchar_t*, wchar_t*&) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `typeinfo for std::__codecvt_utf16_base<wchar_t>@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler-glib.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_max_length() const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_replace(unsigned long, unsigned long, wchar_t const*, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_unshift(__mbstate_t&, char*, char*, char*&) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_encoding() const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler-glib.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::~__codecvt_utf16_base()@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler-glib.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `std::__codecvt_utf16_base<wchar_t>::do_length(__mbstate_t&, char const*, char const*, unsigned long) const@GLIBCXX_3.4.21'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../lib/libpoppler.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:471: epdfinfo] Error 1
make: *** [Makefile:366: all] Error 2
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Sun Apr 14 21:51:45
--------------------------------------------------------------------------------------------------------------------------------
So, how can I solve this problem. Please help me.

**Comment by cjk** [comment]
Have you installed `poppler-glib` which seems to be a required dependency?
