### ISSUE TITLE
Installing PDF-Tools Windows(non-geek tutorial)

### ISSUE THREAD

**Issue by nima87** [politza/pdf-tools#488]
Hi,
I want to use pdf-tools to anotate pdf files using `org-mode` or viewing pdf outputs of my tex files which I hope it wil support `syntex`. I am following the official help to build for windows. I want to comprehensively tell my situation before and after the steps I've taken.

 1. I have `cygwin`, `Imagemagick`, `git` before being introduced to pdf-tools
 2. Emacs: I have a windows built not a cygwin built. I downloaded the
    200 MB version of emacs 26 from this [link](https://ftp-gnu-org.ip-connect.vn.ua/emacs/windows/emacs-26/emacs-26.2-x86_64.zip)

Now following what Official help requires:

> _If using the GNU binaries for Windows, support for PNG and zlib must first be installed by copying the appropriate dlls into emacs’ bin/ directory. Most third-party binaries come with this already done._

I check the `bin` folder of emacs and these files were there: `zlib.dll`, `libjpeg-8.dll`, `libpng16-16.dll`. I tested to see if I can open PNG or JPEG files in emacs and I could. Then I installed `msys2`. Then I clicked start button typed msys and chose `MSYS2 MinGW 64bit`. Then I followed all the steps below:
```
$ pacman -Syu
$ pacman -S base-devel  
$ pacman -S mingw-w64-x86_64-toolchain  
$ pacman -S mingw-w64-x86_64-zlib
$ pacman -S mingw-w64-x86_64-libpng
$ pacman -S mingw-w64-x86_64-poppler
$ pacman -S mingw-w64-x86_64-imagemagick
```

The next step is:

> _3. Install PDF tools in Emacs, but do not try to compile the server. Instead, get a separate copy of the source somewhere else._

For this step, I went to Emacs folder and right-click on `lib` folder and clicked `GITBash here`, and then entered `git clone https://github.com/politza/pdf-tools` and this created a folder named `PDF-Tools` in `lib` folder with the size about 4MB. I don't know how to effect the next two steps, i.e.:
> _4. Open mingw64 shell (Note: You must use mingw64.exe and not msys2.exe)
> 5. Compile pdf-tools `$ cd /path/to/pdf-tools $ make -s`_
> 
I don't know where my mingw64.exe is located. Would you please help me.
I've looked many websites for MINGW64 but couldn't understand what I should download and from where. Please provide help for this and the next step. Really appreciate your help.
P.S. I tried this command `make install-server-deps` on `cygwin` and also `MSYS2 MinGW 64bit` but both of them returned this: `-bash: make: command not found`.

**Comment by politza** [comment]
This documentation is outdated.  You should just install Emacs using
MSYS2 as described here

          https://www.gnu.org/software/emacs/download.html#windows

and then pdf-tools from melpa and everything should just work.  Though
currently it installs much more MSYS2 packages as needed.  I plan to
change that.

**Comment by nima87** [comment]
Hi, 
I did this. Then I couldn't find my init file for this new installation so I created one in `~/.emacs.d/init.el` and added the melpa() to my init file and from `list-ackages` I installed pdf-tools but at some point it crashes and returns this message:

> `-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20190413.2018/build/server/" -*-
Comint started at Thu Apr 18 11:33:39

c\:/msys64/home/nima/.emacs.d/elpa/pdf-tools-20190413.2018/build/server/autobuild -i 

c\:/msys64/home/nima/.emacs.d/elpa/pdf-tools-20190413.2018/

Installing packages    

Skipping package installation (already installed)

 Configuring and compiling 

autoreconf -i

=

Build failed.  ;o(    

=

Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Thu Apr 18 11:33:42
` 
Also in the echo area it said `Building the PDF Tools server failed.` Could you guess where the problem lies?
Thank you.

**Comment by politza** [comment]
Is that everything the script put out ?

**Comment by nima87** [comment]
No, The first time I hit `pdf-tools-install RET` it actually talked much more, listing the packages it was installing, this message is the second time output of that command. I couldn't reproduce the first time's messages by deleting pdf-tools from `package--list-packages`.

**Comment by nima87** [comment]
Hi,
I decided to remove cygwin, image magick, msys2 and bunch of other applications I had, then I installed MSYS2 anew and then Emacs through `MSYS2`. Then added melpa as explained [here](http://ergoemacs.org/emacs/emacs_package_system.html) then used `list-packages` and installed `pdf-tools` and hit `C-x C-c` and restarted emacs and then `M-x pdf-tools-install` and after a couple of minutes it returned this:
````
===========================
   Build succeeded. :O)    
===========================

Comint finished at Sun Apr 21 20:30:17
````
It's great. Thank you.
Now I open a pdf file and hit `M-x pdf-view-mode` and I can view df files in emacs, but still can't annotate or use go to source from pdf or vice-versa. Can you help me on this?
I just have another favor to ask, suppose suddenly there is no MSYS and no melpa. Is it possible that you compose a tutorial on how to install pdf-tools maually.-)
I would like to express my thanks again for this beautiful piece of software.
