### ISSUE TITLE
Dependencies problem on OpenSUSE

### ISSUE THREAD

**Issue by gochit** [politza/pdf-tools#493]
Hi all,

I am trying to install pdf-tools server for Emacs on my laptop with OpenSUSE. When I run the build script with this command:

    ./autobuild -d -i ~/.emacs.d/elpa/pdf-tools-20190413.2018y

The results is:
```
ailed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/home/hieu/.emacs.d/elpa/pdf-tools-20190413.2018y && make -s
configure: error: cannot find necessary  poppler-private header (see README.org)
===========================
     Build failed.  ;o(    
===========================
```
I searched OpenSUSE's repository but I cannot found the package. How can I resolve this missing?

**Comment by politza** [comment]
Do you have the poppler package installed ?

**Comment by gochit** [comment]
Hi @politza, 

I installed `libpoppler-devel` and `libpoppler-glib-devel`.

**Comment by politza** [comment]
Sounds like SUSE does not include the xpdf-header (aka private-header) in its distribution of poppler.
