### ISSUE TITLE
pdf-annot-add-highlight-markup-annotation

### ISSUE THREAD

**Issue by N214** [politza/pdf-tools#494]
Hello, 

When I use pdf-tools's 'pdf-annot-add-highlight-markup-annotation to highlight my pdfs, there is always a popup frame "Edit annotation", I know it's a normal behaviour but I would like to know if I can disable that? I don't want popups

Thank you

**Comment by politza** [comment]
That's due to your Emacs configuration.

**Comment by N214** [comment]
What should I put in my config to disable this?

**Comment by kkerin** [comment]
I want to know your solutions about not popuping...

**Comment by gmoutso** [comment]
`pdf-annot-activate-created-annotations` to configure is there is a popup.
