### ISSUE TITLE
centos7 "fatal error: zlib.h: No such file or directory"

### ISSUE THREAD

**Issue by cmarmstrong** [politza/pdf-tools#495]
I get the following error when attempting to compile on centos7:

```
synctex_parser.c:274:12: fatal error: zlib.h: No such file or directory
 #  include <zlib.h>
            ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:486: libsynctex_a-synctex_parser.o] Error 1
make: *** [Makefile:352: all] Error 2
```

Generally it seems this error is caused by failing to install ```zlib-devel```, but that doesn't seem to be the case here.  I began the installation process in emacs by placing ```(pdf-loader-install)``` in my ```init.el``` file and attempting to open a pdf; emacs then prompted for a sudo password and downloaded all the dependencies; I verified that ```zlib-devel``` was among them.

I've also consulted the README and, although this instruction was specified for Mac OS not CentOS, I also attempted to modify the ```PKG_CONFIG_PATH``` variable to include ```/usr/include```, which is where I noticed the ```zlib.h``` file hanging out; this had no effect.

In addition to compiling within emacs, I've attempted to enter the source directory and run ```configure``` and ```make``` by hand, but I get the same results.

The instructions in the repo ```README``` had no further steps for CentOS beyond ensuring the dependencies are installed.  I've searched Google and this projects issues archive, and can't find anything related.  When that happens I find I'm usually doing something completely goofy, but in this instance I can't seem to figure out what that is...

**Comment by politza** [comment]
What c-compiler are you using ?

It seems broken if it does not include /usr/include.  And apparently
pkg-config thinks it does.

Try this: Open a shell, cd to the pdf-tools/server directory.  Enter

CFLAGS=-I/usr/include ./configure && make clean all

and see if that works.

**Comment by cmarmstrong** [comment]
This is what I get from searching for gcc
```
$ yum list installed | grep -i --color gcc
gcc.x86_64                         4.8.5-36.el7_6.2                    @updates 
gcc-c++.x86_64                     4.8.5-36.el7_6.2                    @updates 
gcc-gfortran.x86_64                4.8.5-36.el7_6.2                    @updates 
libgcc.x86_64                      4.8.5-36.el7_6.2                    @updates 
```
After running your suggestion I get a different error, which is often progress :)
Now I get: 
```
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lglib-2.0
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lpoppler-glib
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgio-2.0
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcairo
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lgobject-2.0
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lglib-2.0
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lpoppler
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lpng15
/home/miniconda/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:458: epdfinfo] Error 1
make[1]: Leaving directory '/home/cmarmstrong/.emacs.d/elpa/pdf-tools-20190413.2018/build/server'
make: *** [Makefile:352: all] Error 2
```
Looks like linked libraries?  My ```LD_LIBRARY_PATH``` is ```/usr/lib64/mpich/lib:/home/cmarmstrong/miniconda2/lib/R/library/Rmpi/libs:/home/cmarmstrong/miniconda2/lib/R/library/Rmpi/libs```
This might be a problem with my system?  I'm searching for a solution now.

**Comment by cmarmstrong** [comment]
thanks for your help, politza.  In this case it was my goofy system--the miniconda paths are in front of the system paths.  I commented out the conda startup in my .bashrc and it installed without a hitch.  I don't think I would have noticed this was the original problem if I hadn't tried your suggestion, so you've been a great help.

Still, I don't think I've ever had this happen before--I think the conda compilers have names different from what the build scripts usually call and are intended only for compiling conda packages.  I can't figure out why this package was finding those compilers and not the system...  It's probably some goofy setting on my system; I'm closing this ticket but please reopen and advise if you think there might be some weird interaction with your build script and anaconda.
