### ISSUE TITLE
Rectangular highlight around annotation hinders readability

### ISSUE THREAD

**Issue by rien333** [politza/pdf-tools#496]
If I select an annotation from the annotation list by pressing `SPC`---thus calling `pdf-annot-list-display-annotation-from-id`---it highlights it using a rectangular shape. Handy, but in some cases the rectangle severely overlaps with the text in the document, rendering it very hard to read. Is there any way to change it's size, color or appearance? Or disable it all together (even if only temporarily)?

**Comment by politza** [comment]
Try something like this:

(define-advice pdf-annot-show-annotation (:filter-args
                                          (annotation &optional highlight-p window))
  (list annotation nil window))

**Comment by rien333** [comment]
Thanks for the suggestion, but if I add that to my `init.el` nothing happens when I press space, and I get the following error message: "Error running timer: (wrong-type-argument number-or-marker-p nil)"

**Comment by hebdon** [comment]
I'm so happy that rien333 brought this up because this has been a key limitation for me as well. When shown to colleagues PDF-Tools in emacs wows them, until when doing an Isearch (and often when highlighting) and the text is covered by black blocks.

**Comment by rien333** [comment]
Yeah unfortunately I still get the same error.

**Comment by politza** [comment]
I must say that the ability of Emacs-users to figure something out by themselves has somewhat declined in the last years.  The :filter-args advice expects one argument, that was the error.

    (define-advice pdf-annot-show-annotation
        (:filter-args (args) suppress-highlight)
      (pcase-let ((`(,annotation ,highlight-p ,window) args))
        (list annotation nil window)))

@hebdon I don't understand your comment about black blocks.
