### ISSUE TITLE
Error with pdf-annot-list-annotations when using global-display-line-numbers-mode

### ISSUE THREAD

**Issue by adamliter** [politza/pdf-tools#497]
I'm using `global-display-line-numbers-mode`, but I'm turning it off in PDFView mode with

```lisp
(add-hook 'pdf-view-mode-hook
          (lambda ()
            (display-line-numbers-mode -1)))
```

This mostly works fine. However, when using `C-c C-a l` (`pdf-annot-list-annotations`), a persistent error arises:

> error in post-command-hook (global-display-line-numbers-mode-check-buffers): (error "No PDF document associated with this buffer")

This error seems to persist in that it prevents me from executing other commands. For example, once this error has been triggered, I cannot kill the buffer with `C-x C-k`. Trying to do so just prints the error again. Is this a bug, or is there something further I should be doing in my configuration in order to avoid this error?

**Comment by politza** [comment]
I pushed a fix for this.  Please try it out once it hits melpa.

**Comment by adamliter** [comment]
@politza Yes, the issue seems to be resolved now. Will this fix also make it to MELPA Stable at some point, too? Anyway, thanks for the quick response and fix!
