### ISSUE TITLE
"Revert buffer" on change does nothing

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#50]
Writing in Tex I often reproduce the pdf file, which is already open in another buffer. Upon using `tex-view', which is set to switch to my pdf viewer (in this case pdf-tools) I'm prompted, "Revert buffer from file <correct location>? (yes or no)". I happily answer "yes". However, regardless of what I answer, it doesn't actually DO anything; I am forced to hit "g" as soon as I load the buffer to actually view the new PDF. 

Using Emacs 25.0.5 with the latest pdf-tools package (as of 2015.2.13)

**Comment by politza** [comment]
"Tory S. Anderson" <notifications@github.com> writes:

> [...] Upon switching to that buffer I'm prompted, "Revert buffer from
> file ? (yes or no)".

What is triggering this, are you using auto-revert-mode ?

-ap

**Comment by WorldsEndless** [comment]
This behavior occurs when reading a .tex file in Auctex mode, then executing the function `tex-view', which is described as follows:

--8<---------------cut here---------------start------------->8---
C-c C-v runs the command TeX-view (found in LaTeX-mode-map), which is an interactive autoloaded compiled Lisp function in `tex-buf.el'.

It is bound to C-c C-v.

(TeX-view)

Start a viewer without confirmation.
The viewer is started either on region or master file,
depending on the last command issued.
--8<---------------cut here---------------end--------------->8---

I've tried with and without autorev mode enabled, with no difference.

**Comment by politza** [comment]
So you are using git-auctex where `TeX-view` can be customized to use PDF Tools ?

Anyway, I don't think this is a problem in my package.  You could try to `toggle-debug-on-quit` and then press `C-g` after the `revert-buffer` prompt appears, which would tell you from where it is actually called.  Also, while in the debug buffer you should be able to determine the buffer which is currently supposed to be reverted (via `e` and `(current-buffer)`).

**Comment by WorldsEndless** [comment]
Ah, arev does work here! That solves my practical problem.
