### ISSUE TITLE
No such page XXX

### ISSUE THREAD

**Issue by Sbozzolo** [politza/pdf-tools#503]
Editing LaTeX files, sometimes it happens that the number of pages of a document changes. Suppose I am visiting the last page with `pdf-tools`, and, as a result of a new compilation, the number of pages decreases, then `pdf-tools` complains with:
```
Error running timer ‘pdf-cache--prefetch-start’: (error "epdfinfo: No such page XXX")
```
but it is impossible to scroll back to the previous page (which on the other hand exists). The workaround I found is to press `C-c C-c`a bunch of times until the page displayed is the last one that actually exists.

**Comment by thblt** [comment]
An easier solution is `pdf-view-goto-page`, which is bound to your binding for `goto-line`.

But it would be nice to just fall back to the last page of the PDF is the visible page doesn't exist anymore.

**Comment by hafid68** [comment]
I agree with @thblt ! 

> it would be nice to just fall back to the last page of the PDF is the visible page doesn't exist anymore.
