### ISSUE TITLE
Compiler-macro error for cl-typep: (error "Unknown type pdf-isearch-match")

### ISSUE THREAD

**Issue by smallzhan** [politza/pdf-tools#504]
Emacs 27.0.50.  doom-emacs develop branch https://github.com/hlissner/doom-emacs/commit/f754d4ff93a7e21e498f0228e480c78211fe05d7

After starting emacs, some info like 
>Compiler-macro error for cl-typep: (error "Unknown type pdf-isearch-match") [2 times]

appears in \*Messages\* buffer.

I wonder whether it concerns,  or it is safe to ignore ?

**Comment by hlissner** [comment]
This is an issue with Doom Emacs, not pdf-tools, and will be resolved there shortly. You can close this issue.
