### ISSUE TITLE
Garbled text in some PDFs

### ISSUE THREAD

**Issue by weirdNox** [politza/pdf-tools#505]
Hi there!
I've been using this package for a long time, without any problems until now (thanks!), so this bug surprised me. 

Today, I downloaded a collection of handouts and some of them become completely garbled after executing some actions (eg. scrolling or zooming):
![image](https://user-images.githubusercontent.com/3155049/65155459-3dfac300-da25-11e9-8cd4-98107984cd8b.png)

As you can see, it not only uses an incorrect font size (both smaller and bigger) in some sections (and changes randomly with each zoom), but also places characters which should not even be there, sometimes replacing the actual characters completely (like the word at the top, which reads "Fork ulário", should read "Formulário").

To make things even worse, when this problem starts happening in this file, it also starts showing up in other files, which makes me think that something funny is happening in epdfinfo.

This picture was taken with vanilla Emacs, only with the latest `pdf-tools` loaded. 

I thought that it could be a problem with poppler, but I tried okular and it works fine. Firefox's viewer also works ok. Anyway, I use Arch and I updated it completely today.

The file in the picture is this one: [Formulario de codigos corretores de erros e de Teoria da Informacao.pdf](https://github.com/politza/pdf-tools/files/3626816/Formulario.de.codigos.corretores.de.erros.e.de.Teoria.da.Informacao.pdf)

**Comment by politza** [comment]
Can you provide an example pdf where this happens ?

**Comment by weirdNox** [comment]
An update on this:
I started reading your epdfinfo code and commenting everything until only a blank page is rendered.
It turns out that it probably isn't pdf-tool's fault, but cairo's, unless there is something misconfigured when using the library in your code. The image data written to the surface has those incorrect characters in it.

As a workaround, I downgraded cairo to the previous version and (with only a minute or 2 to check) it seems the problem doesn't happen anymore. It was updated on my machine last monday.

Maybe the other PDF viewers don't use this backend? I don't know.

**Comment by politza** [comment]
[This](https://www.hochschule-trier.de/~politza/pub/issue-505.png) is how it looks here.  Is that correct ?

**Comment by politza** [comment]
Evince uses cairo, but may a different image-format.

**Comment by weirdNox** [comment]
> [This](https://i.postimg.cc/Sx2qV1s7/pdf.png) is how it looks here. Is that correct ?

It's almost correct; take a look at the following image, you'll see that the `P(i,n)` has been replaced by `.(6n)` in your image, for example:
![image](https://user-images.githubusercontent.com/3155049/65177138-0b18f500-da4e-11e9-8cfb-992ab2e75c17.png)

Anyway, I think it is safe to say that this may be closed, because I tried with Evince, like you suggested and the result is the same!
![image](https://user-images.githubusercontent.com/3155049/65177247-40254780-da4e-11e9-8d8b-ae664bac3e3e.png)

Thanks for the awesome package and for the swift response :)

**Comment by weirdNox** [comment]
Just took a look at their bugtracker, and the bug is already been taken care of :)

https://gitlab.freedesktop.org/cairo/cairo/issues/376
