### ISSUE TITLE
New pdf-tools version breaks under emacs 26.3 on Windows 10

### ISSUE THREAD

**Issue by Nathan-Furnal** [politza/pdf-tools#506]
EDIT : I can confirm it also breaks on Ubuntu 19.10, using emacs 26.1 ; same error except that I can easily rebuild on Linux.

Hi, I'm using pdf-tools with emacs 26.3 with Windows 10 and since the update I get:

> Need to (re)build the epdfinfo program, do it now ? ( y or n)

If I hit yes, I'm asked if I have msys2 installed (which I don't) and nothing happens.

If I hit no however, I'll get :

> PDF tools not activated

and my install will work properly but for `pdf-tools`.

Is there a way to fix it, reinstalling does not work ?

Thanks!

**Comment by politza** [comment]
What happens if you remove `(pdf-tools-install)` from your init-file and run the code below after you've started Emacs.  

    (require 'pdf-info)
    (pdf-info-check-epdfinfo)

What error message, if any, does it produce ?

**Comment by politza** [comment]
Could it be that you modify `pdf-info-epdfinfo-program` after you call `pdf-tools-install` ?

**Comment by Nathan-Furnal** [comment]
@politza I didn't modify anything but downloading msys2 fixed the problem since I was able to rebuild everything on Windows 10. I could rebuild no problem on Linux

**Comment by politza** [comment]
So this problem is solved ?

**Comment by Nathan-Furnal** [comment]
Sure !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : politza <notifications@github.com>
Envoyé : Tuesday, September 24, 2019 4:38:29 PM
À : politza/pdf-tools <pdf-tools@noreply.github.com>
Cc : Nathan Furnal <nathan_furnal@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [politza/pdf-tools] New pdf-tools version breaks under emacs 26.3 on Windows 10 (#506)

So this problem is solved ?
