### ISSUE TITLE
missing links and menu item

### ISSUE THREAD

**Issue by knubee** [politza/pdf-tools#507]
Recently I started having trouble with pdf-tools: links do not work -- and once I noticed this, I realised that the pdf-tools menu no longer appears.

I have emacs built from latest source on Ubuntu 19.04 and pdf-tools 20190918.1715 installed from elpa. Because of unresolvable errors with `Void function definition: pdf-occur-global-minor-mode`, I have reduced my `use-package pdf-tools` to a minimum.

```
(use-package pdf-tools
  :ensure t
  :magic ("%PDF" . pdf-view-mode)
  :hook (pdf-view-mode . pdf-links-minor-mode)
)
```

First, internal links don't work in displayed pdf docs. The same links work just fine in pdf viewers (eg, evince). This is a recent problem.

Second, the pdf-tools menu item no longer appears -- and right-clicking on a pdf no longer pops up the pdf-tools menu.

Perhaps I have removed some necessary option(s), but it seems odd that the pdf-tools menu item is completely gone.

I would appreciate seeing a minimum working example of `use-package pdf-tools` that restores these. Thanks.

**Comment by politza** [comment]
(use-package pdf-tools
      :init (pdf-tools-install))

or

    (use-package pdf-tools
      :init (pdf-loader-install))

**Comment by knubee** [comment]
Both those options result in errors.

```
(use-package pdf-tools
  :init (pdf-loader-install))

Error (use-package): pdf-tools/:init: Symbol’s function definition is void: pdf-loader-install
```

And:

```
(use-package pdf-tools
  :init (pdf-tools-install))

Error (use-package): pdf-tools/:init: Symbol’s function definition is void: pdf-occur-global-minor-mode
```
All other calls to `pdf-tools` have been removed or commented out.

As noted in my earlier post, I have emacs built from latest source on Ubuntu 19.04 and pdf-tools 20190918.1715 installed from elpa. The `pdf-occur-global-minor-mode` error has been occurring for a while now. I have tried removing pdf-tools and reinstalling via package interface -- and even tried deleting the elpa folder for pdf-tools and installing again from scratch.

Any suggestions for how to debug this?

**Comment by politza** [comment]
Both functions are declared as autoloads. Your errors indicate that the
package was not properly setup, i.e. by installing it and calling
package-initialize in your init.

**Comment by knubee** [comment]
I do call `package-initialize` in my init. All my many other calls to `use-package` work fine.

I was finally able to get `pdf-tools` to load correctly by copying John Wiegley's own `pdf-tools` `use-package` setup:

```
(use-package pdf-tools
  :magic ("%PDF" . pdf-view-mode)
  :config
  (dolist
      (pkg
       '(pdf-annot pdf-cache pdf-dev pdf-history pdf-info pdf-isearch
                   pdf-links pdf-misc pdf-occur pdf-outline pdf-sync
                   pdf-util pdf-view pdf-virtual))
    (require pkg))
  (pdf-tools-install))
```
I'm not sure why this works and your suggestion above does not:

```
(use-package pdf-tools
  :init (pdf-tools-install))
```
But in any case, my problem is solved.

Thanks for your help and thanks for this fantastic `pdf-tools` package!
