### ISSUE TITLE
Forward searching on pdf-tools hangs Emacs and exhausts system memory

### ISSUE THREAD

**Issue by Sparsa** [politza/pdf-tools#510]
Hi,
I am using pdf-tool with emacs for latex edition purposes and it works great. But, sometimes when I search the pdf for a particular word, it starts consuming memory until it exhausts the system memory and hangs the system, eventually, Linux kills emacs for over memory usage. It happens sometimes not every time, and when it happens I have to force close Emacs and start it over.

**Comment by randomwangran** [comment]
[Maybe the cause is actually of an ecological nature.](https://github.com/politza/pdf-tools/issues/535)

**Comment by Sparsa** [comment]
what does it mean?

**Comment by yuuyins** [comment]
this happens to me pretty often. it locks Emacs and memory usage go to 90%+. Then I have to kill Emacs with sigkill
