### ISSUE TITLE
Selected text not in region for shell-command-on-region?

### ISSUE THREAD

**Issue by cleinias** [politza/pdf-tools#515]
I am trying to use shell-command-on-region after selecting text, yet the region passed to the command seems to be always empty, even though copying it works as expected. 

For instance, selecting a word (with the mouse) and then copying to kill-ring buffer with M-w works.
But selecting the word and then using the usual M-| shortcut plus "cat" returns:
`(Shell command succeeded with no output)`

This may be the same issue as #73, but I am not sure.

**Comment by politza** [comment]
M-w is implemented as a special command with its own region handling. While the shell command uses regular text extraction functions. But they don't work in the pdf buffer, since an image is not text.

**Comment by cleinias** [comment]
Would it be hard to replicate M-w's special handling of the region for the shell command ?

**Comment by politza** [comment]
No.

**Comment by politza** [comment]
Right. Remove the kill-new call and pass the result to an appropriate shell function.

**Comment by politza** [comment]
See #517.

**Comment by cleinias** [comment]
Thanks!
