### ISSUE TITLE
annotation tooltip displays in minibuffer but not as tooltip

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#518]
As far as I can tell, tooltips generated e.g. by `pdf-annot-print-annotation-default` are being displayed in the minibuffer, but not in a tooltip proper. Is this the intended behaviour, and if not, how would you like me to help with debugging?

**Comment by politza** [comment]
You likely have enabled `tooltip-use-echo-area`.  If not try to reproduce it with `emacs -Q`, then evaluate

    (package-initialize)
    (pdf-tools-install)

and see if its still not displaying a tool-tip. Also, do other features display tool-tips ? Or are they all limited to the mini-buffer ?

**Comment by titaniumbones** [comment]
jeez, you were right, I had `(tooltip-mode -1)` in my init file, sorry for the noise & thanks for the quick response.
