### ISSUE TITLE
Is imagemagick not recommended

### ISSUE THREAD

**Issue by nverno** [politza/pdf-tools#519]
Is imagemagick generally not preferred?  I see the note in the `pdf-view-use-imagemagick` variable and remember reading somewhere recently that emacs was moving away from using imagemagick.

I ran into issues after building new emacs with scrolling in pdf-view I thought might be related, but after applying patch from #516 it works great.

**Comment by politza** [comment]
libpng is faster, that's why its preferred.

**Comment by nverno** [comment]
Thanks!
