### ISSUE TITLE
pdf-view-scroll commands fail to move to next page

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#520]
Emacs 27.1, a pretty recent build, lots of other stuff open.  `pdf-view-scroll-up-or-next-page` will never scroll to the next page because the return values of `(window-scroll)` and `(image-scroll-up)` are no longer equal.  So for instance at the bottom of a page in one PDF, ` (message "%s" (image-scroll-up))` returns `352`, while, ` (message "%s" (window-vscroll))` prints `13.037037037037036`. This causes a `when` test to fail on line 719 of `pdf-view.el`.  

something similar seems to be at work with `pdf-view-next-line-or-next-page` though I haven't instrumented that ~~file~~ function. 

I don't know enough about any of the functions involved to suggest a fix; for now I'm just amending pdf-view-next-page with an extra (image-bob) to allow me to scroll that way. Please let me know if there's something else I can try.

**Comment by politza** [comment]
See #513 and #516.

**Comment by titaniumbones** [comment]
thanks, didn't think to search in the PR's. 

On Wed, Oct 30 2019, politza wrote:

> See #513 and #516.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


--
