### ISSUE TITLE
Problem (re)building epdfinfo program

### ISSUE THREAD

**Issue by jchkoch** [politza/pdf-tools#521]
I think that I have to have a similar issue to #439 and #493 as I recently went into the package manager in Emacs and upgraded pdf-tools package. On restarting Emacs, I was asked whether I want to (re)build the epdfinfo program at which I encountered the following error:

```
/home/jkoch/.emacs.d/elpa/pdf-tools-0.90/build/server/
Failed to recognize this system, trying to continue.
---------------------------
 Configuring and compiling 
---------------------------
./configure -q  && make -s
Preparing installation files ...
Installing ...
Finished
configure: error: in `/home/jkoch/.emacs.d/elpa/pdf-tools-0.90/build/server':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Mon Nov  4 13:39:14
```
I have tried to remove pdf-tools completely and install fresh but this did not work. I am somewhat confused as to what has changed on my system since the last time I upgraded pdf-tools. Any insights would be most appreciated as pdf-tools is a great package.

**Comment by politza** [comment]
So, what system are you using ?

**Comment by cwittern** [comment]
I have a similar problem.  After upgrading, I am asked to rebuild.  If I say yes, the following happens:
`/home/chris/.emacs.d/elpa/pdf-tools-20171012.2226/build/server/autobuild -i /home/chris/.emacs.d/elpa/pdf-tools-20171012.2226/
---------------------------
    Installing packages    
---------------------------
Skipping package installation (already installed)

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/home/chris/.emacs.d/elpa/pdf-tools-20171012.2226/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes

poppler-hack.cc: In function ‘char* _xpoppler_goo_string_to_utf8(GooString*)’:
poppler-hack.cc:62:30: error: ‘class GooString’ has no member named ‘getCString’
   62 |       result = g_convert (s->getCString () + 2,
      |                              ^~~~~~~~~~
poppler-hack.cc: In function ‘void xpoppler_annot_set_rectangle(PopplerAnnot*, PopplerRectangle*)’:
poppler-hack.cc:88:49: error: invalid conversion from ‘const GooString*’ to ‘GooString*’ [-fpermissive]
   88 |     GooString *state = a->annot->getAppearState ();
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 const GooString*
poppler-hack.cc: In function ‘gchar* xpoppler_annot_markup_get_created(PopplerAnnotMarkup*)’:
poppler-hack.cc:108:27: error: invalid conversion from ‘const GooString*’ to ‘GooString*’ [-fpermissive]
  108 |     text = annot->getDate ();
      |            ~~~~~~~~~~~~~~~^~
      |                           |
      |                           const GooString*
make[1]: *** [Makefile:552: epdfinfo-poppler-hack.o] Error 1
make: *** [Makefile:363: all] Error 2
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Thu Nov  7 09:47:35`

I hope this helps identifying the problem.
ALl the best,  Christian

**Comment by politza** [comment]
These look like the result of  incompatible changes in poppler.

**Comment by jchkoch** [comment]
> So, what system are you using ?

Opensuse leap 15.1
Emacs >25.2

**Comment by politza** [comment]
That system is not supported by the autobuild script.  You need find out
the required packages to compile pdf-tools under Opensuse and install
them.  You can orientate yourself by looking at the package-list for other
linux-systems as listed in the autobuild script in the pdf-tools folder.

Judging by the error-message, you need to install at least a c-compiler,
i.e. gcc.

**Comment by cwittern** [comment]
> These look like the result of  incompatible changes in poppler.

Ah, so then this is a different issue.  How can I resolve it?

**Comment by politza** [comment]
@cwittern You need to update pdf-tools, I think I fixed this a while ago.

**Comment by cilia** [comment]
This may or may not be related, but it does occur with (re)building epdfinfo program when I install pdf-tools. The error msg is:
```
error in process sentinel: pdf-tools-install-noverify: Autoloading file /Users/cilia/Dropbox/emacs/elpa/pdf-tools-20191031.642/pdf-occur.elc failed to define function pdf-occur-global-minor-mode
```
though it also says:
```
Comint finished
Building the PDF Tools server succeeded
```
Is this an error that can be safely ignored?

**Comment by politza** [comment]
Are you using use-package ?

**Comment by cilia** [comment]
> Are you using use-package ?

Yes, and relevant portion of use-package config as below:

```
(use-package pdf-tools
  :ensure t
  :pin melpa
  :defer t
  :magic ("%PDF" . pdf-view-mode)
  :config
  (pdf-tools-install)
  ...)
```
I also get the following when open a pdf file with pdf-tools

`File mode specification error: (error Autoloading file /Users/cilia/Dropbox/emacs/elpa/pdf-tools-20191031.642/pdf-occur.elc failed to define function pdf-occur-global-minor-mode`

**Comment by cwittern** [comment]
> @cwittern You need to update pdf-tools, I think I fixed this a while ago.

@politza : Indeed, updating solved the issue.  I somehow assumed quelpa would take care of it, but that is not the case.  Everything fine on my side now:-)

**Comment by jchkoch** [comment]
> That system is not supported by the autobuild script. You need find out the required packages to compile pdf-tools under Opensuse and install them. You can orientate yourself by looking at the package-list for other linux-systems as listed in the autobuild script in the pdf-tools folder. Judging by the error-message, you need to install at least a c-compiler, i.e. gcc.

@politza thanks for the response. I will figure this out for myself when I get the chance.

**Comment by politza** [comment]
That's a known incompatibility with usepackage.  You should find the answer, i.e. correct way to use both packages together, in one of the existing issues or elsewhere on the net.

**Comment by cilia** [comment]
> That's a known incompatibility with usepackage.  You should find the answer, i.e. correct way to use both packages together, in one of the existing issues or elsewhere on the net.

I found [this issue](https://github.com/politza/pdf-tools/issues/482) but the suggested config does not work. It may work in the past but things may have changed in pdf-tools and/or use-package since then as we're getting a different error message

**Comment by mike-alex** [comment]
Update pdf-tools from package manager: `M-x package-reinstall` RET `pdf-tools` RET.

**Comment by jchkoch** [comment]
> That system is not supported by the autobuild script. You need find out the required packages to compile pdf-tools under Opensuse and install them. You can orientate yourself by looking at the package-list for other linux-systems as listed in the autobuild script in the pdf-tools folder. Judging by the error-message, you need to install at least a c-compiler, i.e. gcc.

on the new release of opensuse leap 15.3, I have managed to get pdf-tools installed. I needed to install the following 4 package `libpng16-devel`, `zlib-devel`, `libpoppler-glib-devel`, and `libpoppler-qt5-devel`. Just wanted to post here my solution to get pdf-tools to work on opensuse (maybe it helps someone out).

**Comment by vedang** [comment]
@jchkoch : `pdf-tools` is now maintained at https://github.com/vedang/pdf-tools. If you can submit a PR there adding support for OpenSuse in the `autobuild` script, that would be great!
