### ISSUE TITLE
Annotation symbol blocks text

### ISSUE THREAD

**Issue by sati-bodhi** [politza/pdf-tools#523]
When I use `C-c C-a t` to annotate a `pdf`, I get a picture that blocks out part of the text right in the middle of the page, but nothing to indicate where the annotation has been placed on the page. 

A yellow label appears only when the mouse pointer happens to roll over that position, as shown in the picture below (mouse pointer moved away to operate screen capture). 

![圖片](https://user-images.githubusercontent.com/7592695/68487928-fa7f4100-027e-11ea-92f5-3b10326aa23a.png)

The ocr-ed Chinese text has its own issues as plain-text is jumbled up. So markup annotation is out of the question. 

![圖片](https://user-images.githubusercontent.com/7592695/68488256-a032b000-027f-11ea-8ad7-daee865d5fa7.png)

Is there a way to fix this?

**Comment by politza** [comment]
As far as I'm concerned, this is exactly how  it's supposed to be. If you click the annotation a buffer pops up where you are able to enter the annotations content.

**Comment by sati-bodhi** [comment]
The annotation is not visible and the visible icon blocks text. I have no issues with the annotation buffer.
