### ISSUE TITLE
What would be the correct `use-package` declaration?

### ISSUE THREAD

**Issue by joostkremers** [politza/pdf-tools#528]
I recently removed my `.elpa` directory and had `package.el` reinstall all my packages, which includes `pdf-tools`, since I installed it from MELPA. I also use `use-package` and it turned out that my particular `use-package` declaration for `pdf-tools` actually caused a problem.

Since I'm using a `use-package` declaration that is similar to John Wiegley's example [here](https://github.com/jwiegley/use-package#magic-handlers), I've come to wonder what the correct declaration would be, and whether it would be a good idea to add it to the README.

In [this](https://github.com/politza/pdf-tools/issues/482#issuecomment-472597902) Github issue, you suggest the following declaration:

``` emacs-lisp
(use-package pdf-loader
  :config (pdf-loader-install))
```

However, in my case, this doesn't work, because I also bind some keys in `pdf-view-mode-map` in my `use-package` declaration, and just loading `pdf-loader` doesn't seem to define this key map.

The background story:

After blowing away my `.elpa` directory and letting Emacs repopulate it, I ran into the problem that whenever I tried opening a pdf file, I got the following warning:

    `pdf-occur.elc` failed to define function pdf-occur-global-minor-mode

The warning turns up a few times in the issues reported on Github, but there was no solution that solved the issue for me. In particular, the suggestion to reinstall the package didn't work, because that was basically what triggered the error in the first place.

So I started digging into this, and I found that `pdf-occur.el` hadn't been compiled properly: the file `pdf-occur.elc` did not contain any byte code. This turned out to be caused by the fact that `pdf-occur.el` has `(require 'pdf-tools)`, combined with the fact my `use-package` config is for the package `pdf-tools` and has `:config (pdf-tools-install)` in it.

Because of the `require` statement in `pdf-occur.el`, compiling this file caused `pdf-tools.el` to be loaded. Because of the `:config` section in my `use-package` declaration, loading this file also caused the function `pdf-tools-install` to be called. Since I was installing the package in a fresh instance, meaning the server `epdfinfo` didn't exist, `pdf-tools-install` proceeded to compile `epdfinfo`.

That compilation went fine, but it somehow caused the compilation of `pdf-occur.el` to fail. The file `pdf-occur.elc` *is* created (so `pdf-occur.el` is not loaded instead), but it is empty.

I know it's the building of `epdfinfo` that causes the compilation of `pdf-occur.el` to fail, because if I answer `n` to the question whether I want to build `epdfinfo`, `pdf-occur.el` compiles fine. (John Wiegley's `use-package` example for `pdf-tools` passes `:no-query` to the call to `pdf-tools-install`, but I don't.)

So, to (try and) put it in a nut shell: if you have a `use-package` declaration for `pdf-tools` and the `:config` section calls `pdf-tools-install`, and if you then uninstall `pdf-tools`, restart Emacs and reinstall `pdf-tools`, you'll likely run into this problem.

**Comment by politza** [comment]
My package contains circular dependencies, which seem to be causing problems with use-package.

But, apart from that, I don't really use use-package. So can't really help. 

 You should try to remove pdf-tools and reinstall it with "emacs - Q".

**Comment by fvdbeek** [comment]
I use the following:
```
(use-package pdf-tools
  :ensure t
  :pin manual ;; don't reinstall when package updates
  :mode  ("\\.pdf\\'" . pdf-view-mode)
  :config
  (setq-default pdf-view-display-size 'fit-page)
  (setq pdf-annot-activate-created-annotations t)
  (pdf-tools-install :no-query)
  (require 'pdf-occur))
```

**Comment by joostkremers** [comment]
> My package contains circular dependencies, which seem to be causing problems with use-package. 

Well, in this particular case the problem seems to be that `pdf-occur.el` requires `pdf-tools`. The only symbol from `pdf-tools.el` that I can find is the variable `pdf-tools-auto-mode-alist-entry` from `pdf-tools`.

If that's all there is (of course I may be missing something), isn't it possible to replace `(require 'pdf-tools)` with a simple `(defvar pdf-tools-auto-mode-alist-entry)`? I mean, how big is the risk someone would try to invoke `pdf-occur` without `pdf-tools` loaded?

**Comment by politza** [comment]
I don't know, but there are commands in pdf-occur which work with dired and ibuffer buffer.

**Comment by publicimageltd** [comment]
I think I had the same problem. Everytime the deferred modules of pdf-tools were loaded, that is, everytime I view a pdf for the first time since startup, I got some missing symbol (i.e. `pdf-occur-minor-mode`, or `pdf-history-minor-mode`).  It seems that I have to require *all* modules of pdf-tools in the `:config` section of the `use-package` declaration. The following works:

```emacs-lisp
(use-package pdf-tools
 :config
  (require 'pdf-tools)
  (require 'pdf-view)
  (require 'pdf-misc)
  (require 'pdf-occur)
  (require 'pdf-util)
  (require 'pdf-annot)
  (require 'pdf-info)
  (require 'pdf-isearch)
  (require 'pdf-history)
  (require 'pdf-links)
  (pdf-tools-install :no-query))
```
But since this is very inflexible, I found the following solution:
```emacs-lisp
(use-package pdf-tools
  ;; To update pdf-tools, visit ~/build-repos/pdf-tools and follow the
  ;; instructions in the notes. Roughly, do make clean; make all. Do
  ;; not forget to copy the epdfinfo executable also into the lisp
  ;; subdirectory.
  :pin manual
  ;; point to the lisp directory of the local clone of the repository:
  :load-path "/home/jv/build-repos/pdf-tools/lisp"
  :magic ("%PDF" . pdf-view-mode)
  :config
  (let* ((files   (directory-files "/home/jv/build-repos/pdf-tools/lisp/" nil "\\.el"))
	 (names   (seq-map #'(lambda (s) (string-trim-right s "\\.el")) files))
	 (symbols (seq-map #'intern names)))
    (seq-do #'require symbols))
  (pdf-tools-install :no-query))
```
