### ISSUE TITLE
`Failed to render page` on OS X

### ISSUE THREAD

**Issue by svend** [politza/pdf-tools#53]
I get the following errors when attempting to view a PDF using pdf-tools on OS X.

```
14:41:06 close:/Users/ssorensen/src/pdf-tools/test/test.pdf
14:41:06 OK
1
.
14:41:06 pagesize:/Users/ssorensen/src/pdf-tools/test/test.pdf:1
14:41:06 OK
612.000000:792.000000
.
14:41:06 renderpage:/Users/ssorensen/src/pdf-tools/test/test.pdf:1:2535
14:41:06 ERR
Failed to render page 1
.
14:41:06 number-of-pages:/Users/ssorensen/src/pdf-tools/test/test.pdf
14:41:06 OK
6							
```

poppler_page_render is returning CAIRO_STATUS_NO_MEMORY.

* OS X Yosemite
* GNU Emacs 24.4.90.1
* poppler: stable 0.29.0 (bottled)

**Comment by politza** [comment]
Sounds exactly like this: https://github.com/politza/pdf-tools/issues/49

**Comment by svend** [comment]
You're right! Sorry I missed that issue.
