### ISSUE TITLE
Midnight-view  customize annotation color 

### ISSUE THREAD

**Issue by nc10** [politza/pdf-tools#533]
Hi,

I am not reporting a bug, but rather posting a question. I know that I can customize the background and foreground of the pdf-view-midnight-minor-mode via an statement like this:
(setq pdf-view-midnight-colors '("#cccccc" . "#2d2d2d"))

I am wondering if it is possible to also set the other colors (in midnight-view mode), e.g., those used in annotated text such as the one that is used by pdf-annot-add-text-annotation or the one that is used by pdf-annot-add-underline-markup-annotation. I searched about this on the web and also checked the code in pdf-view.el, but was not able to find any answer or clue. 

Many thanks,

**Comment by politza** [comment]
Midnight-mode enables is a form of post-processing of the images.  As
such it does not actually change any color of the PDF.

Since this is a minor-mode, you could install a hook which modifies
e.g. pdf-annot-default-annotation-properties.

**Comment by nc10** [comment]
Hi Politza,

Thanks for your prompt reply. My understanding is that Midnight-mode does not change the actual color (as you indicated) and simply applies a filter to it (when it renders the page). My question is about if the rendered color that is presented to the reader can be changed (similar to the way the background and foreground colors are changed in the rendered page). I am not after changing the actual color of the annotation but simply preserving that color when the midnight-mode is activated. 

Many thanks,

**Comment by politza** [comment]
No, that's not possible.
