### ISSUE TITLE
 error while loading shared libraries: libpoppler.so.91: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#536]
> File mode specification error: (error Error running ‘/home/torysa/epdfinfo’: /home/torysa/epdfinfo: error while loading shared libraries: libpoppler.so.91: cannot open shared object file: No such file or directory)

This occurs when attempting to view a pdf file (pdf-install works without complaint). I'm not sure what is specifying the .91 version; the machine with the error has .94 installed. How to I change what it's looking for?

Relevant: I share all my emacs code between two machines; the other machine has version 91 and works fine. But even a reinstall and searching my emacs config doesn't seem to specify version 91 anywhere; why is it looking for that specific version?

**Comment by politza** [comment]
The library version is baked into the executable at compile-time.  So you can't use the same exe on different machines if the library versions are different.

You should  `(setq pdf-info-epdfinfo-program "~/bin/epdfinfo")` or some other non-shared location and `(pdf-tools-install)` should build it there.
