### ISSUE TITLE
pdf-isearch-occur and case-sensitivity

### ISSUE THREAD

**Issue by podczeck** [politza/pdf-tools#538]
Hi,

I observe the following problem:

Calling pdf-isearch, with the first letter in the search string capitalized, gives case-sensitive isearch as with standard Emacs; however, calling pdf-isearch-occur (during isearch) gives results respecting case-sensitivity only for about the first 15 pages of a pfd-file.

Thanks,  

Konrad

**Comment by politza** [comment]
0159cb1ab36f75879151e5ea24a6918ef58e50a3 should fix it.  If not please reopen.

**Comment by podczeck** [comment]
Yes, this fixes the problem. Thanks,

Konrad
