### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by Alexander-Shukaev** [politza/pdf-tools#54]
Hello, my apologies, I don't want this to sound like a rant, but seriously, why would somebody decide to develop so useful extension for Emacs (which is cross-platform) and lock it for Unix? For instance

```
epdfinfo.c:19:17: fatal error: err.h: No such file or directory
 #include <err.h>
```

Why would one even use `err.h` explicitly in such an extension? There are tons of cross-platform well-designed libraries these days (even `libpoppler` is cross-platform). Would you find it challenging to clean up this platform-specific code so that we could finally build this extension on Windows? Maybe you need some help with it? Thanks for your efforts.

**Comment by politza** [comment]
> Hello, my apologies, I don't want this to sound like a rant, but

But it does.

> [...]  why would somebody decide to develop so useful extension for
> Emacs (which is cross-platform) and lock it for Unix?

I didn't lock anything, just spared me the additional work. Also,
originally I just wanted to implement Isearch and it grew from there.

So is it feasible for an ordinary user to install libpoppler on Windows ?
Last time I checked it didn't very much look that way.

**Comment by Haroogan** [comment]
Yes, `libpoppler` is available. See [MSYS2](http://sourceforge.net/projects/msys2/), on Windows we already have all the necessary infrastructure to build many packages natively. Installing `libpoppler` on Windows these days is as easy as issuing `pacman -S mingw-w64-x86_64-poppler`.

**Comment by politza** [comment]
Alexander Shukaev <notifications@github.com> writes:

> Yes, libpoppler is available.

Then why don't you figure out what needs to be changed, write a patch
and we work from there ?

**Comment by Haroogan** [comment]
This might take quite some time then. I'm currently writing my Master's thesis and I won't really have time for this until summer probably. What I could offer right now is testing/feedback and advice on which alternatives to use in order to get rid of platform-specific code. If you decide not to do anything about it, then please, don't close it, so that I remember to have it on my schedule.

**Comment by politza** [comment]
What a lame excuse. Well, see you in summer !

**Comment by oscarfv** [comment]
Some random notes about this topic:

Apart from the mentioned `err.h` issue, `epdinfo.c` also uses `getline` which is not available on Windows.

After creating a replacement for `err` and changing the code for using `fgets`, the project builds fine under MSYS2 (after installing the required packages autotools, automake, pkg-config and mingw-w64-i686-poppler).

It is necessary to tweak `pdf-info-epdfinfo-program` to use `epdinfo.exe`. That's not a big deal to do so by default on Windows.

But whenever I tried to open a pdf emacs hangs (until I press C-g). The problem consists on `epdinfo` using a colon for separating arguments, so I changed the code to use `#` as argument separator.

`epdinfo` still refused to work, so I tried from the command line. The problem consisted on `poppler_document_new_from_file` requiring an uri, which in turn is made from an absolure path (also required). It seems that the file name argument is corrupted before reaching `poppler_document_new_from_file`. This doesn't seem a big problem to debug.

However, I'm stumbled on the problem communicating emacs with epdinfo.

**Comment by oscarfv** [comment]
In case anyone is curious, I pushed my changes to the `windows` branch of my `pdf-tools` fork.

**Comment by politza** [comment]
Is there any error output ?

**Comment by oscarfv** [comment]
Nope. I added some `fprintfs` to `epdinfo.c` and it seems that `fgets` never returns when a command is sent from Emacs. It works when `pdf-info-check-epdfinfo` sends the `quit` command though. Either `epdinfo` is not receiving the commands from Emacs, or `fgets` fails to detect the end of line that terminates the command.

Otherwise `epdinfo` seems to correctly get the command when used from the MSYS2 shell (`echo command | epdinfo`).

It would not be the first case of a problematic Emacs<->tool communication problem on Windows.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> Nope. I added some fprintfs to epdinfo.c and it seems that fgets never
> returns when a command is sent from Emacs.

And what about the filename error ?

**Comment by politza** [comment]
I don't think that the field separator of the protocol (semicolon) has anything to do with this.

**Comment by oscarfv** [comment]
The field separator is a problem when Emacs sends the file name (with mandatory full path) to the pdf-tools server, for obvious reasons (C:/foo.pdf). However, I agree with you about it having nothing to do with the problem of the server not receiving  commands from Emacs or the file name corruption.

I'll look into this when I have some spare time and a Windows machine at hand (a rare combination of events.)

In any case, the main roadblock to use pdf-tools on Windows is the requirement of an available compiler and Posix tools and environment while installing. (Even some popular Linux distros (eg Ubuntu) do not install a compiler on the default setup, although it is quite easy to get it.) It is feasible to provide a MSYS2 package for pdf-tools, but that would limit the coverage to a small percentage of Emacs users on Windows. For the rest, someone will need to make and distribute a Windows-style installer.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> The field separator is a problem when Emacs sends the file name (with
> mandatory full path) to the pdf-tools server[...]

No, it'll be escaped before transmission.

> In any case, the main roadblock to use pdf-tools on Windows is the
> requirement of an available compiler and Posix tools and environment
> while installing. (Even some popular Linux distros (eg Ubuntu) do not
> install a compiler on the default setup, although it is quite easy to
> get it.) It is feasible to provide a MSYS2 package for pdf-tools, but
> that would limit the coverage to a small percentage of Emacs users on
> Windows. For the rest, someone will need to make and distribute a
> Windows-style installer.

Agree.

**Comment by oscarfv** [comment]
Well, there is another option: submit pdf-tools for inclusion on Emacs core. You might consider this possibility.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> Well, there is another option: submit pdf-tools for inclusion on Emacs
> core. You might consider this possibility.

That option is already on the table.

Still, people have to install the dependencies (poppler, glib, cairo).

**Comment by politza** [comment]
Getting cold outside.

**Comment by Alexander-Shukaev** [comment]
Yep, it does.  But lots of things changed as well.  For instance, at the time of posting the issue, I didn't know that I would have to type this answer with my 2-month old son lying next to me.  Furthermore, I've been working mostly on Linux lately, what gives this issue less priority.  I would like to do this, but I just don't have enough time at hand at the moment.  If floating of this issue annoys you, you could close it for the time being.  Anyway, the best thing to do would be direct integration into Emacs (like `doc-view`), and this would mean that this project *must* support all major Emacs platforms.  The good news is that finding assistance and contributers on Emacs mailing list for such a useful package as this one should be easy.

**P.S.** Yet another lame excuse, right? `;)`

**Comment by larslj** [comment]
In #191 I made some minimal changes to the code to build the server on Windows. Mostly I just added my own simple implementations of err() and getline(). It works well for me.

**Comment by nasseralkmim** [comment]
@larslj

Would you give more details on how to get it to work on Windows? I tried substitute your changes on my system but still can't make it to work.

**Comment by larslj** [comment]
Right now it's not possible to build it automatically from within Emacs. You need to manually build epdfinfo.exe with MSYS2 and copy the executable to the right location, together with a bunch of DLLs. But I can't help you if you don't describe your problem.

**Comment by justbur** [comment]
After struggling for a bit trying to get pdf-tools to work on my windows machine using msys2, I figured it out. I wrote up steps that will hopefully be helpful to someone. 

https://gist.github.com/justbur/afb5f605def2376eeffc643f7b7daae9

**Comment by politza** [comment]
As it seems there are two ways to build it on Windows using either msys or cygwin, so I'm closing this.
