### ISSUE TITLE
Is there any function to just highlight selection?

### ISSUE THREAD

**Issue by randomwangran** [politza/pdf-tools#540]
`pdf-annot-add-markup-annotation` is great for pdf-tools alone.

However, user might just want to use highlight function, i.e. user don't want to type comments.

The reason is that the user uses ``org-noter`'.

Not sure there is a function. I will try to write it if anyone has the same issue.

With the following image, I can say it more clearly:

![image](https://user-images.githubusercontent.com/8197831/74255602-16e8aa80-4cc0-11ea-860b-4c7e25d910dc.png)

User wants just A, but not B.

**Comment by andersjohansson** [comment]
Set `pdf-annot-activate-created-annotations` to nil.

I use and bind some custom functions for highlighting, underlining etc. Like this:
```
(defvar aj/pdf-hl-color "#DED1EE")
(defvar aj/pdf-ul-color "#633D91")

(defun aj/pdf-hl (edit) (interactive "P")
         (let ((pdf-annot-activate-created-annotations edit))
           (pdf-annot-add-markup-annotation (pdf-view-active-region t) 
            'highlight aj/pdf-hl-color)))
(defun aj/pdf-ul (edit) (interactive "P")
         (let ((pdf-annot-activate-created-annotations edit))
           (pdf-annot-add-markup-annotation (pdf-view-active-region t) 
            'underline aj/pdf-ul-color)))
```

Hope this helps.

**Comment by randomwangran** [comment]
Resolved: https://github.com/randomwangran/WRE/commit/572968ad465b7a029085dc5eb46aa124933bf0e2

Thanks for addtional info, it is helpful.

**Comment by politza** [comment]
Nothing forcing you to write a comment.  You can also deactivate the corresponding popup window.
