### ISSUE TITLE
Add a way to adjust highlight annotation height

### ISSUE THREAD

**Issue by cadadr** [politza/pdf-tools#541]
I'd like to be able to adjust highlight so that they are a little less tall such that they're not larger than the text on the line.  Currently, the highlights extend to the spacing between lines.

I tried my hand at modifying the relevant bits of server code but failed.   I could retry with some guidance and maybe come up with a PR.

Thanks a lot in advance!

**Comment by politza** [comment]
The highlighting is performed by the poppler function [poppler_page_render_selection](https://people.freedesktop.org/~ajohnson/docs/poppler-glib/PopplerPage.html#poppler-page-render-selection) in epdfinfo.c:3222 .

**Comment by cadadr** [comment]
I meant the highlights pdf-tools added, not those already in the document that pdf-tools only renders (it renders them faithfully).

I had found the functions `annotation_new` (which calls `poppler_annot_text_markup_new_highlight` which might be what adds the rounded edges and large borders), and `cmd_addannot`, but I don't understand how it really works. Can't find what is it that sets the shape or whether there are any options in the poppler functions that I can use.
