### ISSUE TITLE
click, then add annotation in location?

### ISSUE THREAD

**Issue by titaniumbones** [politza/pdf-tools#542]
I'm not sure if this is possible, but I would really like to be able to click on a location in a PDF, and immediately afterwards add a text annotation in that location. Right now I have to first call `pdf-annot-add-text-annotation` and then click. This is somehow counter-intuitive for me and slows me down when I'm commenting on student papers. In general clicking in pdf-tools is just a little bit slower and more painstaking than in some other interfaces, (e.. the proprietary commenting features in my University's grading interface), so the extra delay in pdf-tools tends to distract me a bit and that little bit of cognitive overload makes grading quite a bit slower.  

For instance, would it be possible to add some advice to the mouse left-click that saves the car of `pdf-util-read-image-position` as a variable, and then bind a key to a custom function that calls `pdf-annot-add-text-annotation` with the current value of that function? I don't understnad emacs mouse functions very well so if you are able to guide me here I'd really appreciate the help.

**Comment by titaniumbones** [comment]
Or maybe I could bind a one-stop function directly to <C-mouse-1>? Am not sure whether it's possible to read the mose-click event rom a function that's bound to the mouse click itself?

**Comment by titaniumbones** [comment]
ok, this seems to work, but I don't quite know why -- leaving this open for you in case you want to correct my lousy code for the next person, but feel free to close. Thank you!

```emacs-lisp
(defun mwp-pdf-view-mouse-add-annot (event)
  "Extend the currently active region with mouse event EVENT."
  (interactive "@e")
  (let ((posn (car (cdr event)))
        (buffer (current-buffer)))
    (unless (and (eq (window-buffer
                      (posn-window posn))
                     buffer)
                 (eq 'image (car-safe (posn-object posn))))
      (error "Invalid image position"))
    (select-window (posn-window posn))
    (pdf-annot-add-text-annotation posn)))
```

**Comment by politza** [comment]
Try right clicking.
