### ISSUE TITLE
remove boundary/outline/selection surrounding pdf in pdf-view-mode 

### ISSUE THREAD

**Issue by nhmacuk** [politza/pdf-tools#543]
Could there be a feautre added to remove/change the color of the bar and/or the outline surrounding the pdf in pdf-view?  
When clicking next to a document in pdf-view-mode, a (here yellow) bar is shown on the right of the document: 
![image](https://user-images.githubusercontent.com/44981227/74469196-76031680-4e9c-11ea-91b3-dabde6d4558a.png)
When clicking the pdf, the bar dissapears but an outline (here gray) appears around the pdf:
![image](https://user-images.githubusercontent.com/44981227/74469306-b19de080-4e9c-11ea-9b9d-299faea0aa39.png)
I haven't been able to find the option to remove it, or to find out if these features are part of pdf-tools or not, but it would be very pleasing to be able to control them (e.g. make same colour as background).

**Comment by politza** [comment]
This looks like the cursor which should be deactivated (`cursor-type` should be `nil`).  Check your configuration.

**Comment by nhmacuk** [comment]
Sadly, it doesn't seem to change the behavior. I tried changing it through easy-customization by setting it to "none" in the value menu, and ```(setq default-cursor-type 'nil)``` within my .init.

**Comment by politza** [comment]
Try with setq-local in the pdf buffer.

**Comment by nhmacuk** [comment]
Do I understand you correctly by:
![image](https://user-images.githubusercontent.com/44981227/74571990-b1761180-4f7e-11ea-8ff9-e62d07c6061d.png)
Evaluating (setq-local cursor-type 'nil) and (setq-local default-cursor-type 'nil) doesn't seem to change it so far.

**Comment by nhmacuk** [comment]
I tried to set the following hooks of pdf-view with ```(setq-local cursor-type nil)``` with no result:
Show Value Pdf View After Change Page Hook 
Show Value Pdf View Before Change Page Hook 
Show Value Pdf View Change Page Hook

**Comment by nhmacuk** [comment]
Do you have an alternative suggestion to solve my issue?
It seems it is not easy to change the cursor type in evil/spacemacs: https://github.com/syl20bnr/spacemacs/issues/1543

I tried also:
- setting in my ```(custom-set-variables```, cursor-type to nil  ``` '(cursor-type nil)``` using the easy customize interface.
-putting it into my .init file and to set the evil cursor to zero, and tried to do it locally wihtin a pdf buffer.

(just for info: my variable values for cursor-type and evil cursor-type and spacemacs cursor are:
"cursor-type is a variable defined in ‘C source code’.
Its value is ‘box’
Original value was t
Local in buffer ex2.pdf; global value is nil"

"evil-emacs-state-cursor is a variable defined in ‘evil-states.el’.
Its value is (nil box)"

"spacemacs-evil-cursors is a variable defined in ‘config.el’.
Its value is shown below.
Value:
(("normal" "DarkGoldenrod2" box)
 ("insert" "chartreuse3"
  (bar . 2))
 ("emacs" "SkyBlue2" box)
 ("hybrid" "SkyBlue2"
  (bar . 2))
 ("replace" "chocolate"
  (hbar . 2))
 ("evilified" "LightGoldenrod3" box)
 ("visual" "gray"
  (hbar . 2))
 ("motion" "plum3" box)
 ("lisp" "HotPink1" box)
 ("iedit" "firebrick1" box)
 ("iedit-insert" "firebrick1"
  (bar . 2)))"
)

**Comment by nhmacuk** [comment]
As it seems to be related to spacemacs/evil, I made a new issue to ask the help of the spacemacs community: https://github.com/syl20bnr/spacemacs/issues/13393. Thank you for your help so far. Shall I leave this issue open or close it?

**Comment by politza** [comment]
Please close it.  You may reopen it if necessary.

**Comment by nhmacuk** [comment]
Thanks for the help @politza
