### ISSUE TITLE
[feature request] save virtual pdf to actual pdf file

### ISSUE THREAD

**Issue by showgood** [politza/pdf-tools#547]
I recently discovered virtual pdf mode and found it really useful, however I couldn't figure out how to save the virtual pdf buffer into the actual pdf file so it can be viewed by any pdf reader.

Is this currently supported? If not, would it be possible to add?

Thanks!

**Comment by politza** [comment]
No. It could be implemented using an external tool, e.g. ghostscript.

**Comment by showgood** [comment]
thanks, could you elaborate a little bit by giving an example? That would be really helpful.
