### ISSUE TITLE
scroll-other-window doesn't work

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#55]
When reading the PDF below and writing above, found that `scroll-other-window` (`C-M-v`) will scroll down to the end of the page and then, rather than going to the next page, will just bounce to the top of the same page again.

**Comment by politza** [comment]
That's a matter of `scoll-other-window` not beeing configurable which function it should use to scroll the window, i.e. it always calls `window_scroll', a C function.  Similar problem occurs when the other window displays a `info` node.

**Comment by WorldsEndless** [comment]
I believe this should still be possible. My approach is as follows: 
Rebind `C-M-v` to a function that checks to see if `other-window-for-scrolling` is PDFView mode and then use the appropriate scroll function, or use the regular scroll-other-window. 

However, I can't find a way to get PDFView's mode; I've tried (derived-mode-p) but PDFView doesn't seem to derive, and there seems to be no function like (doc-view-mode-p) for PDFView mode. Do you have any suggestions on moving forward on this?

**Comment by politza** [comment]
"Tory S. Anderson" <notifications@github.com> writes:

> I believe this should still be possible. 

Sure, but it should not be fixed in pdf-tools.  Maybe you want to open
a (Emacs) feature request / bug-report.

> However, I can't find a way to get PDFView's mode; I've tried
> (derived-mode-p) but PDFView doesn't seem to derive [...]

That should be fixed sometime.  You can use `pdf-util-pdf-buffer-p' or
`pdf-util-pdf-window-p'.

**Comment by WorldsEndless** [comment]
That this should not be done in PDF-Tools and that the scroll-other-window functions need to be improved is true, but this functionality is simply too useful for me to pass up, so I'm sharing the code I wrote to achieve this (I spend a lot of my time studying PDFs and taking notes in an adjoining window), which also works for other-window scrolling in info mode and any other mode you care to specify. Hopefully it will be useful to others. 

http://www.toryanderson.com/files/pdf-other-window.el

**Comment by politza** [comment]
"Tory S. Anderson" <notifications@github.com> writes:

> That this should not be done in PDF-Tools and that the
> scroll-other-window functions need to be improved is true, but this
> functionality is simply too useful for me to pass up,[...]

Why don't you open a feature-request for Emacs ?

**Comment by WorldsEndless** [comment]
Where/how is feature-request for emacs done?

**Comment by politza** [comment]
"Tory S. Anderson" <notifications@github.com> writes:

> Where/how is feature-request for emacs done? 

M-x report-emacs-bug RET

**Comment by WorldsEndless** [comment]
Using the function I made I see some curious behavior that I can't understand. Scrolling down from the other window works as expected, however, scrolling up makes invisible changes UNLESS a) I switch to the buffer, which causes it to update and show me where it is now (after however many scroll-ups I've done), or b) a page-break has occurred, when it shows me the correct other-window regardless. This behavior doesn't seem to occur with scroll-down, which displays every time. Any idea why this would be? is there some difference in implementation of scroll up vs. scroll down?

**Comment by jagrg** [comment]
Here's a (temporary?) fix in case anyone needs it.

```elisp
(defun my/scroll-other-window ()
  (interactive)
  (let* ((wind (other-window-for-scrolling))
         (mode (with-selected-window wind major-mode)))
    (if (eq mode 'pdf-view-mode)
        (with-selected-window wind
	  (pdf-view-next-line-or-next-page 2))
      (scroll-other-window 2))))

(defun my/scroll-other-window-down ()
  (interactive)
  (let* ((wind (other-window-for-scrolling))
         (mode (with-selected-window wind major-mode)))
    (if (eq mode 'pdf-view-mode)
	(with-selected-window wind
	  (progn
	    (pdf-view-previous-line-or-previous-page 2)
	    (other-window 1)))
      (scroll-other-window-down 2))))
```

**Comment by politza** [comment]
https://gist.github.com/politza/3f46785742e6e12ba0d1a849f853d0b9#file-scroll-other-window-el

**Comment by holtzermann17** [comment]
I've found that the Gist posted by @politza works for my use case; I wanted to post this code with a couple other steps that I needed to polish off the integration, hoping this saves someone else some time:
```lisp
(require 'scroll-other-window)
(add-hook 'org-noter-notes-mode-hook #'sow-mode)
(setq org-noter--inhibit-location-change-handler t)
```
