### ISSUE TITLE
search from latex source  to  pdf viewer 

### ISSUE THREAD

**Issue by wdysun** [politza/pdf-tools#551]
I installed `pdf-tools` to mainly work latex documents. After some work with settings, everything works as expected except the functionality that allows to go from the tex source to the pdf.

From the documentation it is said that the command to go from the source to the pdf is `C-c C-g`. However, when I run it,  emacs says that the command is undefined. If check with `M-x describe-key`, in fact it says that `C-c C-g is undefined`. 

Now I think this may be due to AUCTeX loaded when I work with tex documents. The key to perform tex -> pdf search with AUCTeX + synctex is  `C-c C-v`, if I use it it somehow works but not as expected because it doesn't point to the exact position of the cursor.  On the other hand the search from pdf to tex source works as expected, it always points to the exact position in the tex source.

I'll try to be more specific:

suppose that I have a text line in tex file which results in many lines into the pdf, then suppose the cursor is placed in the middle of this long line and I do `C-c C-v`, in the pdf  it will point in a place in the pdf that correspond to the beginning of  text line into the tex file. 

I wonder whether this is just how it works, or rather there is some issues with my use of `pdf-tools`. Just in case I report below the parts of my `init.el` involving `pdf-tools` settings.

```emacs

;; pdf-tools: general settings 
;; -----------------------------------
;; load pdf-tools
(pdf-tools-install)

;; use pdf-tools to open pdf files
(setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)

;; default page width behavior
(setq-default pdf-view-display-size 'fit-page) 

;; pdf-tools  zooming to better rendering 
(setq pdf-view-resize-factor 1.1)


;; TeX Settings
;; ----------------
;; pdf / tex correlation
(setq TeX-source-correlate-method 'synctex)
(add-hook 'LaTeX-mode-hook 'TeX-source-correlate-mode)

;; revert pdf-view after compilation
(add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
```

**Comment by politza** [comment]
Try to execute the command directly via M-x. Maybe the doc outdated. I can't remember or check right now.

**Comment by wdysun** [comment]
What's the `M-x` command for `C-c C-g`?

**Comment by politza** [comment]
I just checked: C-c C-g is not bound anymore. C-c C-v (TeX-pdf-tools-sync-view) should work in auctex.  The plain command is pdf-sync-forward-search.  TeX-pdf-tools-sync-view does some setup in order to support regions.

**Comment by wdysun** [comment]
Thanks this, it  solved my issue. `M-x pdf-sync-forward-search` works like charm. The problem in  my installation is that `C-c C-v` doesn't bind automatically to `pdf-sync-forward-search`. I just remapped the keybind and it works. Great!
