### ISSUE TITLE
feature propasal: search through annotations (by its contents)

### ISSUE THREAD

**Issue by dalanicolai** [politza/pdf-tools#553]
Hi,

As I could not find a way to search for annotations by contents, I coded the solution printed below. Of course this might be interesting for more users so that I would like to propose (and discus about) its implementation. This solution uses Ivy but of course the same "main" function can be used with helm and also it can easily get tweaked for use without completion framework.

![ivy-annot-search](https://user-images.githubusercontent.com/18429791/77857867-77945e00-7200-11ea-993f-6ec807c50cf9.gif)

The function should get invoked from the pdf-view buffer
```
(defun search-annot ()
  (interactive)
  (let ((results '())
        (annots (pdf-info-getannots nil (current-buffer))))
    (while annots
      (let* ((annot (car annots))
            (id (alist-get 'id annot)))
      (add-to-list 'results (cons annot (pdf-annot-get
                             (pdf-annot-getannot id (current-buffer)) 'contents)))
      (setq annots (cdr annots))))
    (print results)))

(defun ivy-search-annot ()
  (interactive)
  (let ((results (search-annot)))
    (ivy-read "Search string: " (mapcar 'cdr results)
              :action (lambda (x)
                        (pdf-annot-show-annotation (car (rassoc x results)) t)))))


(spacemacs/set-leader-keys "aog" 'ivy-search-annot)
```
As I use spacemacs I added the keybinding definition (that probably should get specified to pdf-mode-map or something) so others can just copy paste this.

**Comment by oantolin** [comment]
An easy way to get search in annotations would be to add a column to the tabulated list produced by `pdf-annot-list-annotations` with the actual text of the annotations. Then the usual tabulated search filters could be used.

**Comment by politza** [comment]
... which is already possible, see pdf-annot-list-format.

**Comment by oantolin** [comment]
Fantastic! I didn't realize that. It's perfect! In my personal configuration I'll remove the label and date columns which I never use and give the contents a couple of tweets worth of space.

**Comment by dalanicolai** [comment]
> ... which is already possible, see pdf-annot-list-format.

Great, really nice! So now I know where to find it (and the many more features of the annot-mode).

However, there is a " BUG " which is that the search only searches in the visible part of the tablist. Therefore it won't find matches for parts of comments that do not fit in the tablist screen (just try to create a long enough comment and search for it).

It would be great if there were some filter options also, e.g. to filter on annotation type. Maybe there is already, but then again I could not find it ;)

**Comment by oantolin** [comment]
> It would be great if there were some filter options also, e.g. to filter on annotation type.

There is a type column, so you can filter on its value. Put the cursor on the type column and then press `/ = highlight` to narrow to highlights, etc. I recommend reading the commentary in tablist.el

**Comment by dalanicolai** [comment]
Thanks for the tip! Although there is not much information in the comments. And even after knowing this I can not find more information about tablist. Anyway, the features are really nice and PDF-tools really is a great package!

While I am here anyway, maybe I can just drop another very short question here...
I am using evil-mode and I would like to open the content editor in evil-insert-state. I put the following line in my .emacs file, but it does not work (although evil-insert-state is added to the hook variable)
`(add-hook 'pdf-annot-edit-contents-minor-mode-hook 'evil-insert-state)`. Any suggestions?

**Comment by dalanicolai** [comment]
I found out that the "correct" way to open the content editor in insert mode is to add `pdf-annot-edit-contents-minor-mode` to the `evil-insert-state-modes` list, which is a customizable variable

**Comment by dalanicolai** [comment]
> > ... which is already possible, see pdf-annot-list-format.
> 
> Great, really nice! And now I know where to find it (and the many more features of the annot-mode).
> 
> However, there is a " BUG " which is that the search only searches in the visible part of the tablist. Therefore it won't find matches for parts of comments that do not fit in the tablist screen (just try to create a long enough comment and search for it).
> 
> I would like to suggest that showing the annotation contents in the tablist should be the default. If someone does not add contents it will show empty anyway, and otherwise the person probably prefers to see (and possibly search) the contents in his annotations.
> 
> It would be great if there were some filter options also, e.g. to filter on annotation type. Maybe there is already, but then again I could not find it ;)
> 
> Maybe I should open different issues for these, but I just first mention them here to get your opinions.

Except for the bug reported in the quoted message, I guess this issue can be closed
