### ISSUE TITLE
in pdf-view-mode position of highlight annotation is off

### ISSUE THREAD

**Issue by MarkoSchuetz** [politza/pdf-tools#555]
I have at least one PDF file  where the position of the highlight annotation shifts as soon as the buffer for entering the annotation text opens.

I had not updated pdf-tools in a while, when I upgraded to pdf-tools-20200214.536 I started seeing this.

**Comment by oantolin** [comment]
It would be very useful to have a PDF for which this happens. Is there one you can share?

**Comment by MarkoSchuetz** [comment]
Unfortunately, so far I have seen it only with one PDF that I cookout share.

**Comment by dit7ya** [comment]
I have this same error in every PDF. Here's a screenshot. I can share the pdfs if you want.
![2020-04-18-192507_1920x1080_scrot](https://user-images.githubusercontent.com/14034137/79639580-5c3ac400-81aa-11ea-9c2e-aca093f75703.png)

In this example I tried to highlight the paragraph that begins with `The computation...`
