### ISSUE TITLE
rebind key to overwrite evil keybindings

### ISSUE THREAD

**Issue by Xunius** [politza/pdf-tools#558]
Hi politza,

I noticed after pressing `C-c C-a l`, in the list of annotations, I could not use the default SPACE key to follow an annotation. That key is doing a "move cursor right by one char", the evil-mode navigation function. How could I rebind that follow function to another key? I've tried this:

```
  (use-package pdf-tools
    :ensure t
    :defer t
    :init
    (pdf-loader-install)
    :config
    ;; turn off line number mode
    (global-display-line-numbers-mode -1)
    (define-key pdf-view-mode-map (kbd "h") 'pdf-annot-add-highlight-markup-annotation)
    (define-key pdf-view-mode-map (kbd "t") 'pdf-annot-add-text-annotation)
    (define-key pdf-view-mode-map (kbd "D") 'pdf-annot-delete)
    ;; this doesn't work:
    (define-key pdf-view-mode-map (kbd " ") 'pdf-annot-list-display-annotation-from-id)
    ;; neither this one:
    ;(define-key pdf-view-mode-map (kbd "g") 'pdf-annot-list-display-annotation-from-id)
  )
```

I also tried
```
    (define-key pdf-annot-list-mode-map (kbd "g") 'pdf-annot-list-display-annotation-from-id)
```
Launching emacs then gives this error:
```
Error (use-package): pdf-tools/:config: Symbol’s value as variable is void: pdf-annot-list-mode-map
```

I'm using evil-mode like this:
```
  (use-package evil
    :ensure t
    :init
    (setq evil-search-mode 'evil-search)
    :config
    (evil-mode t)
    )
```

Some other specs:
* OS: Linux Mint
* GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-09-17

Please help

**Comment by Trotsky1917** [comment]
Please try:

`(add-hook 'pdf-annot-list-mode-hook (define-key 'evil-normal-state-local-map " " pdf-annot-list-display-annotation-from-id))`
