### ISSUE TITLE
Multibyte character gets corrupted in isearch

### ISSUE THREAD

**Issue by shingo256** [politza/pdf-tools#559]
Hi,

When I enter Japanese character via input method during isearch, it's corrupted.  I found it's because `enable-multibyte-characters` is set to nil in pdf view buffer.  My temporal solution is:

<pre>
(add-hook 'pdf-view-mode-hook #'(lambda () (set-buffer-multibyte t)))
</pre>

It' working well so far but I don't know there would be any side effect.  Please check and consider to resolve it in a correct way.  Thank you for the great package anyway.

**Comment by keeneadt** [comment]
Hello. I have exactly the same issue when i use cyrillic symbols in minibuffer during isearch in **PdfView** mode.
```
Debugger entered--Lisp error: (wrong-type-argument characterp -1)
  unibyte-char-to-multibyte(-1)
  quail-update-translation(t)
  quail-self-insert-command()
  funcall-interactively(quail-self-insert-command)
  call-interactively(quail-self-insert-command)
  quail-start-translation(100)
  quail-input-method(100)
  isearch-with-input-method()
  funcall-interactively(isearch-with-input-method)
  call-interactively(isearch-with-input-method nil nil)
  command-execute(isearch-with-input-method)
  read-string("I-search [RU]: " "" junk-hist nil t)
  isearch-process-search-multibyte-characters(100 1)
  isearch-printing-char(100 1)
  funcall-interactively(isearch-printing-char 100 1)
  call-interactively(isearch-printing-char nil nil)
  command-execute(isearch-printing-char)
```
However i can easily use **pdf-occur** to search inside pdf with no problem, but in return i get emacs session bugged - i can't use any other input method except the one i use last time to search inside pdf file with **pdf-occur**. Changing system (not inside emacs) keyboard layout doesn't help in this case. Seems like that searching inside pdf is a bit buggy.

Emacs 26.3. Pdf-tools 0.90.
