### ISSUE TITLE
Addition to Documentation

### ISSUE THREAD

**Issue by rkrug** [politza/pdf-tools#56]
I just installed / updated pdf-tools on melpa and it worked fine. To set the PKG_CONFIG_PATH from emacs, I just did in the scratch buffer and it compiled and installed fine:

```
(Setenv "PKG_CONFIG_PATH"
        (concat
         "/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:"
         (getenv "PKG_CONFIG_PATH")
         )
        )
````

Maybe this cold be added to the README?

Just one remark: the lib part depends obviously on the version installed. But as there is a system version of lib, the by using home-brew installed version is not linked into the ```/usr/local/lib/pkgconfig``` path. Therefore it needs to be added explicitly and the b=version obviously can change.

Thanks,

Rainer

**Comment by politza** [comment]
So what exactly should be added to the docu ?

**Comment by rkrug** [comment]
That ```pdf-tools-install``` works under OS X (Yosemite at least) when the path is set from inside emacs. Executing 
````
(setenv "PKG_CONFIG_PATH"
        (concat
           "/usr/local/Cellar/zlib/1.2.8/lib/pkgconfig:/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig:"
         (getenv "PKG_CONFIG_PATH")
         )
        )
````
in the scratch buffer *before* executing ```pdf-tools-install``` and everything works.

**Comment by bradyt** [comment]
Adding `(setenv "PKG_CONFIG_PATH" "/opt/X11/lib/pkgconfig")` to my init file solved the following error on `M-x pdf-tools-install`. 

```
-*- mode: compilation; default-directory: "~/" -*-
Compilation started at Wed Sep 14 19:11:01

make V=0 -kC '/Users/iam/.emacs.d/elpa/pdf-tools-20160525.920/build'  melpa-build
cd server && ./configure -q
configure: error: Package requirements (poppler-glib >= 0.16.0) were not met:

Package 'xcb-shm', required by 'cairo', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables poppler_glib_CFLAGS
and poppler_glib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** [server/Makefile] Error 1
make: Target `melpa-build' not remade because of errors.

Compilation exited abnormally with code 2 at Wed Sep 14 19:11:02
```
