### ISSUE TITLE
render latex inside popup when hover over annotation

### ISSUE THREAD

**Issue by jstaursky** [politza/pdf-tools#560]
Is it possible to preview a latex fragment written in an annotation inside a popup window?
e.g.
![pdftools-question](https://user-images.githubusercontent.com/25406664/79130543-22665980-7d75-11ea-9f0c-d9ad5730cd23.png)

**Comment by politza** [comment]
The text is rendered as latex in the tool-tip, if it starts with a backslash or dollar.  See also `pdf-annot-print-annotation-functions`.

**Comment by jstaursky** [comment]
right, I do use the dollar sign in the above screenshot (see for e.g. towards the bottom of the tooltip it shows "$(n_1,n_2)$) I am just using latex snippets here and there. 
also I am using 
```emacs-lisp
    (setq pdf-annot-edit-contents-setup-function
          (lambda (_annot) (org-mode) (px-preview)))
```
which makes it actually an org tooltip, latex render happens when I try and edit the annotation, just not in the tooltip.

**Comment by jstaursky** [comment]
whoops realized my mistake. I'll followup when I have a solution.
