### ISSUE TITLE
Cannot enter sudo password

### ISSUE THREAD

**Issue by berhoel** [politza/pdf-tools#569]
When running "pdf-tools-install" I get stuck in the attempt to install the required packages. emacs asks for a password for sudo, but any key I press generates a "is undefined" error message. I only can kill emacs, not even Cg is working. 

Installing the required packages beforehand is not working either, because for Ubuntu 20.04 `libz-dev` is installed as `zlib1g-dev`.

```shell
> sudo apt install libz-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by politza** [comment]
Workaround:

cd /path/to/package/build/server && ./configure && make && cp epdfinfo ../../

**Comment by berhoel** [comment]
When installing 20200512.1524 from melpa, there is not configure in the server directory, but for reference

```shell
cd /path/to/package/build && make server/epdfinfo && cp server/epdfinfo ../
```

does work for me
