### ISSUE TITLE
problems running with poppler 0.29.0-1 

### ISSUE THREAD

**Issue by mandarm** [politza/pdf-tools#57]
I get the following error on Ubuntu 14.04.1 LTS x86_64 with
pdf-tools-20150219.2326 from melpa.

pdf-info-query: The epdfinfo server quit unexpectedly.
The epdfinfo server quit, restart it ? y
Error during redisplay: (eval (pdf-misc-size-indication)) signaled (error "Invalid image specification: nil") [2 times]

This started after I built and installed poppler-0.29.0 from source, and
built epdfinfo using this version. If I build epdfinfo with the system
libpoppler-glib8 (0.24.5), things work fine, but of course, highlighting,
squiggly, etc. are not supported.

Aside, I had to do the following to build the server:

export poppler_glib_CFLAGS="-I/usr/include/poppler/glib -I/usr/include/cairo"
export poppler_glib_LIBS="-L/usr/lib -lpoppler -lcairo -lcairo-gobject -lpoppler-glib -lpoppler-cpp -lgobject-2.0 -lglib-2.0"

Finally, thanks for a wonderful tool!

**Comment by politza** [comment]
> pdf-info-query: The epdfinfo server quit unexpectedly.

Most likely you are linking against 0.29, but running with 0.24.  Try to
execute `epdfinfo` directly in a terminal.  `ldconfig` or
`LD_LIBRARY_PATH` should help you.

> Aside, I had to do the following to build the server:

The used version depends on which one the configure script finds and may
be directly influenced by pointing `PKG_CONFIG_PATH` to right pkg
directory.


> export poppler_glib_CFLAGS="-I/usr/include/poppler/glib -
> I/usr/include/cairo"
> export poppler_glib_LIBS="-L/usr/lib -lpoppler -lcairo -lcairo-gobject
> -lpoppler-glib -lpoppler-cpp -lgobject-2.0 -lglib-2.0"

These look like flags for the system version (?).
