### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Gahamelas** [politza/pdf-tools#571]
Hi! When installing via Melpa, do I have to worry about installing the other packages mentioned below in the README, or I'm ready? It's also not clear what to add to my init.el (I'm a emacs newbie and woudl appreciate more user-friendly instructions).

**Comment by politza** [comment]
No.

**Comment by Gahamelas** [comment]
You mean, NO, that I don't need to install any packages?

**Comment by politza** [comment]
No, you don't have to worry about installing the other packages mentioned below in the README.

**Comment by Gahamelas** [comment]
(pdf-loader-install) gives me an error: 
`progn: Symbol’s function definition is void: pdf-loader-install`
Any ideas? Thanks.
