### ISSUE TITLE
Misplaced annotations

### ISSUE THREAD

**Issue by shamiv** [politza/pdf-tools#577]
In some PDF files annotations (highlight, underline) are positioned at considerable distance from the selected text. 

Possibly related to #555 ? (Although in my case the annotations are immediately wrongly positioned, not after the annotation buffer opens).

Some documents in which this happens:

[du Gay - 2004 - Self-service - Retail, shopping and personhood.pdf](https://github.com/politza/pdf-tools/files/4695243/du.Gay.-.2004.-.Self-service.-.Retail.shopping.and.personhood.pdf)
[Neuman_CC Fallacy.pdf](https://github.com/politza/pdf-tools/files/4661402/Neuman_CC.Fallacy.pdf)
[raven_et_al_2016_niche_construction.pdf](https://github.com/politza/pdf-tools/files/4661403/raven_et_al_2016_niche_construction.pdf)
[vandoren_etal_2016.pdf](https://github.com/politza/pdf-tools/files/4673570/vandoren_etal_2016.pdf)

![Screenshot from 2020-05-21 10-46-31](https://user-images.githubusercontent.com/26513701/82541200-5bea6b80-9b50-11ea-85e8-fa4a8d4889e7.png)

**Comment by shamiv** [comment]
If anyone else has this problem: for me, a work-around is to (re)print the pdf file as pdf in for instance Okular. Then the problem disappears.

**Comment by vnckppl** [comment]
I am experiencing the same issue on GNU Emacs 26.3 with pdf-tools version 20200427.2136 (via melpa).

**Comment by shamiv** [comment]
I found another work-around: the main solution to [this](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) post works as well. So on Linux, you run this script on your pdf:
`gs -o repaired.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress corrupted.pdf`

**Comment by vnckppl** [comment]
> I found another work-around: the main solution to [this](https://superuser.com/questions/278562/how-can-i-fix-repair-a-corrupted-pdf-file) post works as well. So on Linux, you run this script on your pdf:
> `gs -o repaired.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress corrupted.pdf`

This fixes the issue with misplaced highlighting, but can introduce font changes:

Header of a Journal Article before processing with Ghostscript:
<img width="167" alt="Screen Shot 2020-09-13 at 18 28 27" src="https://user-images.githubusercontent.com/15114746/93032490-1534eb80-f5ef-11ea-99f8-60e6b000972d.png">

The same header after processing with Ghostscript:
<img width="166" alt="Screen Shot 2020-09-13 at 18 28 37" src="https://user-images.githubusercontent.com/15114746/93032503-309ff680-f5ef-11ea-9ce5-e86ce2da5ae1.png">
