### ISSUE TITLE
Windows install instruction missing cask

### ISSUE THREAD

**Issue by notuntoward** [politza/pdf-tools#579]
The Windows 10 install instructions:

`https://github.com/politza/pdf-tools#compilation-and-installation-on-windows`

work up until this line: 

`make -s`

at which point I get this error:
```
Using Emacs 26.3
make: cask: No such file or directory
make: *** [Makefile:44: .cask/26.3] Error 127
```
Do I need to install cask (whatever that is) on Windows 10, or if not, do I have a path problem?

**Comment by politza** [comment]
If you don't want to install cask, install from melpa.

**Comment by notuntoward** [comment]
Thanks for the reply.  OK, that works for me.

I have to do this on several machines, so I want to make sure I get the melpa procedure right.  In the [Windows instructions](https://github.com/politza/pdf-tools#compilation-and-installation-on-windows), can I do a melpa install by doing only steps 1 and 2, followed by installing the melpa package and doing steps 7 and 8?

**Comment by Ypot** [comment]
Hi
Mine says:
`# make -s
make: emacs: No such file or directory
Using Emacs
make: emacs: No such file or directory
make: emacs: No such file or directory
make: emacs: No such file or directory
make: cask: No such file or directory
make: *** [Makefile:44: .cask/] Error 127
`
