### ISSUE TITLE
Sometimes beginning of page is duplicated below the current page

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#58]
When I'm writing a LaTeX document and view that using PDF tools, I frequently manage to have the beginning of the current page shown again below the current page.

![pdf-view](https://cloud.githubusercontent.com/assets/103854/6552320/edce71e0-c644-11e4-8fe7-e1bb0589d040.png)

If that happens, all I can do is to kill the buffer and open the file again.  Just switching to another page again shows this other page + its beginning again.

I think the cause of the problem is that I use `auto-revert-mode` with a quite low `auto-revert-interval` of 1 second in order to make the pdf buffer refresh when I re-compiled my document.  However, there's the possibility that auto-revert kicks in while the document is still compiling.  In that case, I get the error

```
Error: (error "epdfinfo: Error opening /path/to/file.pdf:PDF document is damaged")
```

some raw PDF code is displayed below the current page's image, and then eventually the buffer is refreshed with the page-and-its-beginning-again pdf image.

Probably, that's more of a generic auto-revert issue, i.e., files that are still in the process of being written should not be reverted (unless by `auto-revert-tail-mode`).

**Comment by tsdh** [comment]
OTOH, I think there's no good way auto-revert could know if a file is still being written to.  So maybe pdf tools could just test if the pdf is valid and do nothing in case it is not.  Then, a subsequent auto-revert will eventually trigger a refresh.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> When I'm writing a LaTeX document and view that using PDF tools, I
> frequently manage to have more than one page shown, i.e., it shows a
> page + the beginning of the next page as shown in the attached
> screenshot.

Do you know if this is a display issue, i.e. the overlays are messed up,
or is it a rendering one, i.e. epdfinfo creates theses double-paged
images ?

**Comment by tsdh** [comment]
There are two overlays in the buffer now. Both start at `(point-min)` and one extends until `(point-max)` (which is ~45.000) whereas the other extends only to 11.

BTW, I edited this issue: it's not the beginning of the next page which is shown, it is the beginning of the current page again.

And those are really two separate images: when I click the upper, completely visible one, I can see a blinking border.  So it seems like the same image (or two images showing the same) are displayed on top of each other but I can only see the beginning of the second one because scrolling triggers jumping to the next page.

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> There are two overlays in the buffer now. 

I can't reproduce two overlays, but I clearly see the PDF content appear
below the image while reverting with auto-revert-mode.

I have the following for some time in my init file:

    (defadvice TeX-LaTeX-sentinel (after after-run-latex-hook activate)
      "Run `after-run-latex-hook'."
      (with-current-buffer TeX-command-buffer
        (run-hooks 'after-run-latex-hook)))

In `after-run-latex-hook` I revert the PDF buffer. (I did this because
Doc-View in combination with imagemagick suffers from a similar issue
(imagemagick mmaps Doc-View's PNG files and triggers a SIGBUS if the file
is unavailable (or has shrunken ?) which will make Emacs abort.)

I wonder if it wouldn't be better to fix it like this in auctex, since
that's about the only common case where PDF files get modified on the
file-system side and it sidesteps the inherent race condition.  It may
also look better, since I don't see any intermediate text noise,
i.e. the PDF's data.

I think failing silently, as you've suggested, would invalidate the
purpose of auto-revert-mode, since in a lot of cases you wouldn't see
any LaTeX updates in the PDF buffer, only the ones from the previous
edit-cycle.  (And polling the file-system doesn't seem very attractive
either.)

**Comment by tsdh** [comment]
Indeed, the revert-after-LaTeX-is-done above seems to be the best solution here.  I'll add such a hook in AUCTeX.

**Comment by tsdh** [comment]
Ok, done.  AUCTeX commit http://git.savannah.gnu.org/cgit/auctex.git/commit/?id=a2a4777fbc2cec4c5ef7da74e17bf75b1dae4840 adds a new hook `TeX-after-TeX-LaTeX-command-finished-hook` which you can use to revert your PDF buffers after successful latex runs.  For example, I have:

```elisp
(defun th/pdf-view-revert-buffer-maybe (file)
  (when-let ((buf (find-buffer-visiting file)))
    (with-current-buffer buf
      (when (derived-mode-p 'pdf-view-mode)
        (pdf-view-revert-buffer nil t)))))

(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
          #'th/pdf-view-revert-buffer-maybe)
```

**Comment by sherter** [comment]
Thanks for adding the hook to AUCTeX and providing this code snippet. Could you please also provide the implementation of the `when-let` function/macro? Emacs keeps telling me
```
error in process sentinel: th/pdf-view-revert-buffer-maybe: Symbol's function definition is void: when-let
```
and (E)Lisp is still a bit of a mystery to me :smile:.  Thanks!

**Comment by tsdh** [comment]
@sherter Oh yes, `when-let` is a new macro in emacs 25 which hasn't been released yet. You can find its definition here.

http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/subr-x.el#n134

Well, that relies on some internal functions which are also new, but you can just replace the `when-let ` in my definition with `(let ((buf ...)) (when buf ...))`.

Sorry, I'm writing from my mobile so it's hard to just adapt the definition. I can do that tomorrow when I'm back at a computer.

**Comment by sherter** [comment]
Thanks, with your help I figured it out:
```lisp
(defun th/pdf-view-revert-buffer-maybe (file)
  (let ((buf (find-buffer-visiting file)))    
    (when buf
      (with-current-buffer buf
        (when (derived-mode-p 'pdf-view-mode)
          (pdf-view-revert-buffer nil t))))))

(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
          #'th/pdf-view-revert-buffer-maybe)
```

One day I will find time to finally learn Lisp... :smile:

**Comment by tsdh** [comment]
That's exactly right. May the parens be with you also in the future, my friend. ;-)

**Comment by politza** [comment]
@tsdh: Maybe you could add this function as a custom option for the hook
in AUCTeX, so people don't have to figure this out on their own ?

**Comment by tsdh** [comment]
@politza: Done.  AUCTeX 11.89 which will be released within the next few weeks will have the function `TeX-revert-document-buffer` which you can add to `TeX-after-TeX-LaTeX-command-finished-hook` if you are using `doc-view-mode` or `pdf-view-mode`.

**Comment by manuel-uberti** [comment]
@tsdh: AUCTeX 11.89 is out and I can confirm this works:
```
(add-hook 'TeX-after-TeX-LaTeX-command-finished-hook
              #'TeX-revert-document-buffer)
```
Thank you.

**Comment by tsdh** [comment]
You're welcome, Manuel!
