### ISSUE TITLE
Feature Request: a way to change highlight colors

### ISSUE THREAD

**Issue by notuntoward** [politza/pdf-tools#581]
Love the fact that I can now annotate pdfs in Emacs! 

But I have a feature request: in other pdf annotators, I've stuck with a color system for highlighting and underlines: green is for definitions, orange is for emphasis, blue is for important figure numbers, etc.

A color switcher UI might be a bit too much to ask, but would it be at least possible to add customizations for the highlighter and underliner colors?

**Comment by vnckppl** [comment]
You can add the following to your setup to set default colors for all different annotation styles:

```
  ;; Default annotation colors
  ;; Strike out
  (defun pdftools-strikeout-gray (oldfun loe)
    (apply oldfun loe '("gray")))
  (advice-add 'pdf-annot-add-strikeout-markup-annotation :around 
              #'pdftools-strikeout-gray)
  ;; Underline
  (defun pdftools-underline-purple (oldfun loe)
    (apply oldfun loe '("#8a1e8a")))
  (advice-add 'pdf-annot-add-underline-markup-annotation :around 
              #'pdftools-underline-purple)
  ;; Squiggly underline
  (defun pdftools-squiggly-red (oldfun loe)
    (apply oldfun loe '("#fe2500")))
  (advice-add 'pdf-annot-add-squiggly-markup-annotation :around 
              #'pdftools-squiggly-red)
 
  ;; Default color for text highlight. 
  ;; This will change the color of the Note.
  (setq pdf-annot-default-markup-annotation-properties
        '((color . "yellow")))

  ;; Default color for text.
  ;; This will change the color of the Note.
  (setq pdf-annot-default-text-annotation-properties
        '((color . "#90ee90")))
```

Some credit goes to [brittAnderson](https://emacs.stackexchange.com/questions/34959/how-to-set-the-colors-for-pdf-tools-annotations-individually).

**Comment by notuntoward** [comment]
Thanks much, that's a good start towards towards some kind of color switcher UI.

**Comment by dalanicolai** [comment]
You can customize `pdf-annot-default-annotation-properties`, `pdf-annot-default-markup-annotation-properties` and `pdf-annot-default-text-annotation-properties` via the customization menu.
