### ISSUE TITLE
Horizontal pdf-util-tooltip-arrow implemantation

### ISSUE THREAD

**Issue by kadircancetin** [politza/pdf-tools#582]
First of all, I am new in elisp so I could be wrong in many ways. 

I think there isn't any `pdf-util-tooltip-arrow` implementation which has show arrow with given horizontal parameter. The function use basicly `pdf-util-tooltip-in-window` and it has x parameter but `pdf-util-tooltip-arrow` has only `image-top` parameter. I think  `pdf-util-tooltip-arrow` adding an optional dx parameter and add the end of the function when it will call the pdf-util-tooltip-in-window.

It will be good for org-noter if there is a horizontal implementation of the arrow. 

Related issue:  https://github.com/weirdNox/org-noter/issues/96

ps: sorry about my poor english

**Comment by tim-hilt** [comment]
I also would love to have that feature! It would greatly improve org-noter (see the related issue above).

**Comment by vedang** [comment]
Copying my comment from #623 :

> Hey @ahmed-shariff ,
> 
> Thanks for submitting this PR. I read through the conversation on #582, weirdNox/org-noter#96 and weirdNox/org-noter#129.
> 
> I'll need some more time to test out the changes on my own end and apply them, I will probably tackle this next weekend, I'm posting this update to let you know that I'm looking into it and hope to unblock `org-noter` for this change soon.
