### ISSUE TITLE
Some PDF files are not correctly rendered

### ISSUE THREAD

**Issue by ElectroQuanta** [politza/pdf-tools#583]
I have some large PDF files (don't know if the cause is size), but they are not rendered correctly. 
![image](https://user-images.githubusercontent.com/29806215/82719936-c01f4380-9ca6-11ea-8403-77734aad32e7.png)
However, in Doc-view mode, it displays correctly.
![image](https://user-images.githubusercontent.com/29806215/82719948-dc22e500-9ca6-11ea-9927-26c68f0dd871.png)

I've reinstalled pdf-tools to the latest melpa version. Still did not help.
Even stranger is that I recall opening this same file and being correctly displayed in pdf-view mode.

Any help is appreciated.

**Comment by politza** [comment]
This looms like pdf-midnight-minor-mode is enabled.

**Comment by ElectroQuanta** [comment]
Yes, my eyes urged me to use it :)
If I disable it, I still get an undesired result.
![image](https://user-images.githubusercontent.com/29806215/82734004-d1506a80-9d0f-11ea-8c9b-0e03b564bf6e.png)

**Comment by politza** [comment]
See if it looks the same in Ocular or Evince.  Doc-view uses a different renderer than pdf-tools.

**Comment by ElectroQuanta** [comment]
I’m on a Mac, so I was not using evince.
As a matter of fact, I don’t know which renderer is being used (maybe mupdf?).

Nonetheless, I installed evince, and I still see the same output :(
Here is the link for the file, in case you want to check it.
https://www.st.com/resource/en/user_manual/dm00189702-description-of-stm32f7-hal-and-lowlayer-drivers-stmicroelectronics.pdf <https://www.st.com/resource/en/user_manual/dm00189702-description-of-stm32f7-hal-and-lowlayer-drivers-stmicroelectronics.pdf>

Thanks in advance :)

**Comment by ElectroQuanta** [comment]
An additional fact: when I opened evince from command line and then opened the pdf, it reports: ```some font thing failed```.
Maybe this is the culprit?
