### ISSUE TITLE
PDF Printing no longer works: pdf-misc-print-document: Symbol’s function definition is void: pdf-misc-print-program

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#590]
For the past year I've had success doing `C-c C-p` to print. In my config I have:

```elisp
(setq pdf-misc-print-program "/usr/bin/lp")
```

Some time recently, however, I receive the following error when I do `C-c C-p`:

> pdf-misc-print-document: Symbol’s function definition is void: pdf-misc-print-program

I'm guessing this had to do with an update to my pdf-tools version, but I don't see anything in any of the docs

**Comment by phil-s** [comment]
Commit 2ece5084c213def6ef6721f84867dae3fed77fd2 fixed a bunch of typos, and defined some compatibility aliases for the old names, but unfortunately some of the typos were left in.

If you replace all instances of `programm` with `program` in `pdf-misc.el`, with the exceptions of the following two (and then byte-compile and reload the library), I suspect you'll have a working version.  (Untested -- I simply noticed the typos while doing something else).

```lang-none
(define-obsolete-variable-alias 'pdf-misc-print-programm
(define-obsolete-variable-alias 'pdf-misc-print-programm-args
```

I think those are the only two lines which should still include the typo `programm`.

**Comment by WorldsEndless** [comment]
That did the trick. Can I help that come out in the next version?

**Comment by phil-s** [comment]
I don't know, sorry.  I *imagine* it will be included for the next release.  Assuming you made and have tested the same changes I've made in https://github.com/politza/pdf-tools/pull/591/files then you could always use the 'Review changes' button to confirm that you think it's good.

**Comment by vedang** [comment]
Hey @WorldsEndless , @phil-s,

I've merged this change into vedang/pdf-tools@500191c and vedang/pdf-tools@91630c2 as part of #658. Thank you for submitting this change! Please close this issue :)

**Comment by phil-s** [comment]
@vedang  Apparently it's not possible to create issues for your fork?  You'll want to fix that if you'll be maintaining the project?

**Comment by vedang** [comment]
Thanks for letting me know, I guess that's the default for forks @phil-s ! :D I've changed it now.
