### ISSUE TITLE
Does pdf-tools support  view night mode?

### ISSUE THREAD

**Issue by fu123456** [politza/pdf-tools#592]
My Emacs does into pdf-view-dark-minor-mode, then my pdf shows white texts and blue background. However, I want to use white texts and black background. So does it support this? Thx.

**Comment by phil-s** [comment]
`M-x pdf-view-midnight-minor-mode` ?

**Comment by fu123456** [comment]
It does not work. Yes, I use M-x pdf-view-midnight-minor-mode. But it shows white texts and blue background. Can you say about "render options" more details?

**Comment by fu123456** [comment]
Very thx. It does work well. It is amazing.

**Comment by fu123456** [comment]
Hi, I use "pdf-view-midnight-minor-mode", but I found that figures show inverted colors.
In fact, I want to keep the figure not change their color, while background is black and text is white.

**Comment by davdent** [comment]
Yes, that would be fantastic: if the embedded images could stay in their normal colours  with white text on black background.
