### ISSUE TITLE
error: Odd number of elements in hash table data

### ISSUE THREAD

**Issue by wuqui** [politza/pdf-tools#595]
Hello, I have been happily using `pdf-tools` for a while now, thanks for this great package! Unfortunately, it has stopped working today and despite numerous attempts I can't get it running again.

I'm using Doom Emacs and I can still open PDFs with `pdf-tools` and I can even add annotations and use the keyboard shortcuts to jump to the last or first page. However, whenever I want to jump from one page to the next one or previous one, I get the following error:

`Odd number of elements in hash table data`

I'm using the latest version, updated using the Doom Emacs package manager on macOS.

I have tried

- re-installing `pdf-tools` (several times)
- compiling it again
- updating `poppler`
- running it without my config

One thing I noticed during re-installing is that sometimes Doom Emacs asked me to re-build `epdf` on startup and even though it gave me some message like  "rebuild successful", Emacs froze and I could see another error message concerning some number of elements in a hash table. I couldn't reproduce this now to give you the exact messages, but could try to if that's of any help.

Hoping for your help! :)

**Comment by politza** [comment]
It's a doom error. Please take it up with them.

**Comment by chayward1** [comment]
Issue is with doom fix is posted in comments here
https://github.com/hlissner/doom-emacs/issues/3434

Cheers everyone
