### ISSUE TITLE
Unable to compile on Debian Wheezy x86_64

### ISSUE THREAD

**Issue by flexibeast** [politza/pdf-tools#6]
`./configure` produces (amongst other things):

```
Is writing annotations enabled ?      no   (requires poppler-glib >= 0.19.4)
```

because the Wheezy version of `poppler-glib` is 0.18.4-6. But then `make` fails with:

```
poppler-hack.cc:1:27: fatal error: poppler/Annot.h: No such file or directory
compilation terminated
```

**Comment by christopherwoo** [comment]
I have the same problem using the poppler repository. 
I compile it again by enable ENABLE_XPDF_HEADERS in CMakeLists.txt and it works.
