### ISSUE TITLE
highlighting: imprecise/incorrect regions

### ISSUE THREAD

**Issue by vnckppl** [politza/pdf-tools#600]
I am suggesting to reopen https://github.com/politza/pdf-tools/issues/122 because 'highlights showing up in incorrect regions' is still an issue that people are experiencing, as is evident from the comments that have been posted since this issue was closed.

_In short:_
When highlighting an area in a pdf file, the highlight shows up in a different position in the PDF. See the issue demonstrated in the enclosed .gif file. 
![highlight](https://user-images.githubusercontent.com/15114746/87879152-24f4d280-c9a6-11ea-9e9f-dad7a7ef3245.gif)

**Comment by mindbike** [comment]
I am having the same issue with Emacs-27.1 and Emacs-26.3 build on
Linux-Mint-20 (which is based on Ubuntu-20.04).

For those who want to check the problem can get the PDF file in the
gif image **vnckppl** posted above, by searching "DOI 10.3233/JAD-142079" 
(it is the id of the article).

Also here is a [link to iospress](https://content.iospress.com/articles/journal-of-alzheimers-disease/jad142079)  where you can download a sample at the moment.

The issue does not occur on all PDF files, only some are problematic.

And on Ubuntu-18.04 both Emacs-27.1 and 26.3 **works fine with no problems.**

This brings to mind, the issue might be related to the third party libraries the epdfinfo server is based on.

The libraries that PDF-tools depend and their version numbers on ubuntu-18.04 and 20.40 are
as follows:

- libpng-dev :  1.6.34-1ubuntu0.18.04.2 (ubuntu1-8.04) ,   1.6.37-2 (ubuntu-20.04)              
- zlib1g-dev :  1:1.2.11.dfsg-0ubuntu2 (ubuntu-18.04) ,  1:1.2.11.dfsg-2ubuntu1 (ubuntu-20.04)
- libpoppler-glib-dev:  0.62.0-2ubuntu2.10 (ubuntu-18.04) ,  0.86.1-0ubuntu1 (ubuntu-20.04)        
- libpoppler-private-dev:  0.62.0-2ubuntu2.10 (ubuntu-18.04) ,  0.86.1-0ubuntu1 (ubuntu-20.04)
