### ISSUE TITLE
Invalid function error with gccemacs

### ISSUE THREAD

**Issue by A6GibKm** [politza/pdf-tools#601]
This bug only affects emacs `native-comp` branch with the `--with-nativecomp` configure flag enabled.

When running pdf-tools I get the following error:
```
pdf-util-tooltip-arrow: Invalid function: pdf-view-current-overlay Invalid face reference: highlight-numbers-number
Invalid face reference: highlight-numbers-number [11 times]
Invalid face reference: highlight-quoted-symbol [22 times]
...
Invalid face reference: highlight-numbers-number [5 times]
Invalid face reference: highlight-quoted-symbol [2 times]
Invalid face reference: highlight-numbers-number [2 times]
```
I suspect it is because the face `highlight-numbers-number` defined in `highlight-numbers.el` (and `highlight-quoted-symbol` in `highlight-quoted.el`) are not loaded in time. I could not find a reference to them in the source of pdf-tools.

**Comment by A6GibKm** [comment]
I also get 

```
Error running timer ‘pdf-cache--prefetch-start’: (invalid-function pdf-view-current-page) [4 times]
```

**Comment by A6GibKm** [comment]
This might be related to the following issues:
```
$ emacs -Q -batch -L . -f batch-byte-compile *.el

In toplevel form:
pdf-annot.el:32:1: Error: Cannot open load file: No such file or directory, tablist

In pdf-links-browse-uri-default:
pdf-links.el:372:4: Warning: ‘org-open-link-from-string’ is an obsolete
    function (as of Org 9.3); use ‘org-link-open-from-string’ instead.

In end of data:
pdf-misc.el:288:1: Warning: the function ‘pdf-misc-print-program’ is not known
    to be defined.

In toplevel form:
pdf-occur.el:29:1: Error: Cannot open load file: No such file or directory, tablist

In pdf-view-registerv-make:
pdf-view.el:1601:4: Warning: ‘registerv-make’ is an obsolete function (as of
    27.1); Use your own type with methods on
    register-val-(insert|describe|jump-to)
```

**Comment by t-e-r-m** [comment]
Hey, I have a similar issue, although I don't see anything wrong with the navigation or display. Also using `native-comp`.

From the `*Messages*` buffer:

```lisp
Error during redisplay: (eval (propertize (let ((buffer-file-name (buffer-file-name (buffer-base-buffer)))) (or (when (and (not (file-remote-p buffer-file-name)) buffer-file-name) (if-let (project (doom-project-root buffer-file-name)) (let ((filename (or buffer-file-truename (file-truename buffer-file-name)))) (file-relative-name filename (concat project ".."))))) "%b")) 'face (cond ((buffer-modified-p) '(error bold mode-line-buffer-id)) ((+modeline-active) 'mode-line-buffer-id)) 'help-echo buffer-file-name)) signaled (wrong-type-argument stringp nil) [108 times]
Error running timer ‘pdf-cache--prefetch-start’: (invalid-function pdf-view-current-page) [5 times]
```

And this when debugging is true:

```lisp
Debugger entered--Lisp error: (invalid-function pdf-view-current-page)
  pdf-view-current-page()
  pdf-cache-prefetch-pages-function-default()
  pdf-cache--prefetch-start(#<buffer mydocument.pdf>)
  apply(pdf-cache--prefetch-start #<buffer mydocument.pdf>)
  timer-event-handler([t 0 0 500000 t pdf-cache--prefetch-start (#<buffer mydocument.pdf>) idle 0])
```

**Comment by A6GibKm** [comment]
The navigation and display issues might be related to the use of `TeX-source-correlate-mode`. Note that the arrow (which appears in the pdf-tools buffer) that correlates source and pdf is not being displayed on my machine using `TeX-view`, probably due to this issue.

**Comment by A6GibKm** [comment]
See #588.

**Comment by rdiaz02** [comment]
Same here: #588 solves these issues.

**Comment by beyondpie** [comment]
@rdiaz02 @A6GibKm 

How to use the #588 in Mac? I download that repo with the fixed codes, and compile the server using make. Then put the server under where pdf-tools package is installed for Emacs (when install pdf-tools in Emacs, I didn't compile the server).

But seems this does not work...

**Comment by rdiaz02** [comment]
@beyondpie I am not sure I can be of much help, since I do not have a Mac (I did this on Debian GNU/Linux). 

What I think did was actually:
- clone flatwhatson's repo (https://github.com/flatwhatson/pdf-tools/tree/fix-macros)
- compare that branch to this one (from github itself): https://github.com/politza/pdf-tools/compare/master...flatwhatson:fix-macros
-  record the files that differ
- copy those four files rom  flatwhatson's repo into the my `~/.emacs.d/elpa/pdf-tools-20200512.1524` directory
- (I might have removed the .elc files, but I don't remember)

I do not remember rebuilding the server. And I think the problem is not really in the server part, but on the other files.

**Comment by beyondpie** [comment]
@rdiaz02 
Thanks! I miss the correction logic. Now it works!
Songpeng
