### ISSUE TITLE
pdf-info-query: The epdfinfo server quit unexpectedly. Again...

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [politza/pdf-tools#609]
For information :
 
Setup : `emacs` 26.3 from Debian testing.

`pdf-tools` from MELPA, loaded via `(use-package...)`

Support libraries : 
```charpent@zen-book-flip:~$ dpkg -l "*poppler*"
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=att>
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom                          Version      Architecture Description
+++-============================-============-============-====================>
ii  gir1.2-poppler-0.18:amd64    0.85.0-2     amd64        GObject introspectio>
un  libpoppler-cpp0              <aucune>     <aucune>     (aucune description >
ii  libpoppler-cpp0v5:amd64      0.85.0-2     amd64        PDF rendering librar>
ii  libpoppler-dev:amd64         0.85.0-2     amd64        PDF rendering librar>
ii  libpoppler-glib-dev          0.85.0-2     amd64        PDF rendering librar>
un  libpoppler-glib-doc          <aucune>     <aucune>     (aucune description >
ii  libpoppler-glib8:amd64       0.85.0-2     amd64        PDF rendering librar>
ii  libpoppler-private-dev:amd64 0.85.0-2     amd64        PDF rendering librar>
ii  libpoppler-qt5-1:amd64       0.85.0-2     amd64        PDF rendering librar>
ii  libpoppler82:amd64           0.71.0-6     amd64        PDF rendering library
ii  libpoppler95:amd64           0.85.0-2     amd64        PDF rendering library
ii  poppler-data                 0.4.9-2      all          encoding data for th>
ii  poppler-utils                0.85.0-2     amd64        PDF utilities (based>
```

This worked two days ago. Now, every time I try to open a `.pdf`, I get :  
```
pdf-info-query: The epdfinfo server quit unexpectedly.Error during redisplay: (eval (pdf-misc-size-indication)) signaled (error "Invalid image specification: nil")
Error during redisplay: (eval (pdf-misc-size-indication)) signaled (error "Invalid image specification: nil")
```

in the `*Messages*` buffer.

I am at loss about what has changed...

A bit of Googling showed me that such problems already happened, but I have been unable to figure out what to do. I tried de/re-installing `pdf-tools`, (which involved de-reinstalling some other packages having it as a dependency), which, to my surprise, *worked* the first time.

BTW : I haven't been able to figure out how to force a recompilation of the `epdfinfo` server, much less to configure it to leave some log. This info might possibly be of some use the next time. Could it be added to the homepage ?

**Comment by PatriciaJH** [comment]
On the one hand, you can force a rebuild by finding the executable and renaming it (safer than deleting). Mine was located in ~/.emacs.d/elpa/pdf-tools-20190701.202/epdfinfo 
and I also deleted all the .elc files while I was at it.   Emacs will rebuild it the next time you open emacs, or (I believe) the next time a call is made to epdfinfo.  

On the other hand, I'm still getting the same error as you have reported.  Haven't yet tested with other pdfs; can't share the one I'm getting it on.  If I have time, I'll come back with results of further tests, and a pdf that provokes the problem.

**Comment by vedang** [comment]
You can change the value of `pdf-info-epdfinfo-program` before `M-x pdf-tools-install` to force a recompile. 

This repo is no longer maintained. Can you please update your setup to fetch from `vedang/pdf-tools` and then try again? If the problem persists, please open an issue against that repo so that I can track and fix  it. That is the official maintained repo now. 

Please close this issue as it helps me keep track of new issues on `politza/pdf-tools`

**Comment by EmmanuelCharpentier** [comment]
I tried to uninstall, then reinstall `pdf-tools` and `org-pdftools` (following `melpa`) ; still getting the same error. Reinstalling `pdf-tools` only results in no error.

I'll explore `org-pdftools` before closing this one...

**Comment by EmmanuelCharpentier** [comment]
Reinstalled `org-pdftools` afterwards also gave no errors. Ditto for `org-noter-pdftools` I still do not understand this (growing pains of `org 9.5` and  change of `org` archive ?), but closing this for sake of change of source...

Thank you !
