### ISSUE TITLE
how to install server dependents for Arch Linux?

### ISSUE THREAD

**Issue by stardiviner** [politza/pdf-tools#61]
just as the title.

**Comment by politza** [comment]
1. Figure out how to install libraries on your OS.
2. Read the README.
3. Install the libraries PDF Tools depends on.

**Comment by tsdh** [comment]
@stardiviner It would be very strange if libpng and poppler weren't installed already.  But maybe you are missing tools required by pdf-tools for building the server component.  Those should all be installed by pulling in the `base-devel` group, e.g., `pacman -S base-devel`.

**Comment by stardiviner** [comment]
@tsdh I already installed `base-devel`. And when try to install again. I got this error output:
```
sudo apt-get install gcc g++ make automake autoconf \
	libpng-dev libz-dev libpoppler-glib-dev
sudo: no tty present and no askpass program specified
Makefile:68: recipe for target 'install-server-deps' failed
make: *** [install-server-deps] Error 1
```

**Comment by stardiviner** [comment]
And I checked out `Makefile`, found it only have this section (just for Ubuntu apt package manager):

```
install-server-deps:
	sudo apt-get install gcc g++ make automake autoconf \
		libpng-dev libz-dev libpoppler-glib-dev
	-sudo apt-get install libpoppler-private-dev
	-sudo apt-get install gtklp
```

**Comment by csantosb** [comment]
Running arch here and install runs fine for me.  I get it from melpa.

Try to compile manually: cd to `pdf-tools` dir and run
 
    make V=0 -kC '/home/csantos/emacs-packages/elpa/pdf-tools-20150327.245/build'  melpa-build

In case of problem, post errors.

**Comment by tsdh** [comment]
@stardiviner sudo needs an askpass program to query the user for the password in order to install files.  One such program is `x11-ssh-askpass` which you can install from extra.

**Comment by politza** [comment]
I guess you figured it out.
