### ISSUE TITLE
pdf-annot-list-annotations — gives error

### ISSUE THREAD

**Issue by holtzermann17** [politza/pdf-tools#619]
I get this error message when trying to list annotations. I'm using `pdf-tools-20200512.1524` via MELPA

> ``helm-M-x-execute-command: Invalid function: (feval (filter) (pcase filter (`(not \, (and operand (guard (not (cdr operand))))) (not (feval (car operand)))) (`(and \, (and operands (guard (= 2 (length operands))))) (and (feval (nth 0 operands)) (feval (nth 1 operands)))) (`(or \, (and operands (guard (= 2 (length operands))))) (or (feval (nth 0 operands)) (feval (nth 1 operands)))) (`(,op \, (and operands (guard (= (length operands) 1)))) (let ((fn (assq op tablist-filter-unary-operator))) (unless fn (error "Undefined unary operator: %s" op)) (funcall fn id entry (car operands)))) (`(,op \, (and operands (guard (= (length operands) 2)))) (let ((fn (cdr (assq op tablist-filter-binary-operator)))) (unless fn (error "Undefined binary operator: %s" op)) (funcall fn id entry (car operands) (cadr operands)))) ((guard (stringp filter)) (let ((fn (cdr (assoc filter named-alist)))) (unless fn (error "Undefined named filter: %s" filter)) (if (functionp fn) (funcall fn id entry)) (feval (if (stringp fn) (tablist-filter-unparse fn) fn)))) (`nil t) (_ (error "Invalid filter: %s" filter))))``

**Comment by holtzermann17** [comment]
Maybe this was just transient... I have recompiled and the error no longer presents itself. Will leave this open for now in case others encounter the error and can comment further.

**Comment by adbjesus** [comment]
I am still getting this error. I've tried to recompile/reinstall but keep getting this error. However, this seems related to tablist and not pdf-tools, see https://github.com/politza/tablist/issues/23

**Comment by gusbrs** [comment]
Just passing by to say I'm also affected by this issue. Reinstalling/recompiling did not make it work, but removing the .elc files did (thanks @adbjesus  for the pointer).

**Comment by salehmu** [comment]
Same here. Worked by deleting `.elc` from the `~/.emacs.d/.local/straight/build-27.2/tablist/` directory

**Comment by vedang** [comment]
This repo is no longer maintained. Can you please update your setup to fetch from https://github.com/vedang/pdf-tools and then try again? IF you are using MELPA or NonGNU ELPA for package management, simply uninstall and reinstall the package.

If the problem persists, please open an issue against `vedang/pdf-tools` so that I can track and fix  it. That is the official maintained repo now.

Please close this issue as it helps me keep track of new issues on `politza/pdf-tools`.
