### ISSUE TITLE
Install on cygwin works after small changes in source code

### ISSUE THREAD

**Issue by ericdanan** [politza/pdf-tools#62]
I apologize if I am posting this message at the wrong place, because this is not really an "issue". I just want to report that I was able to install and use the package on cygwin (and cygwin emacs-w32) after I made two small changes in the source code.

The changes are basically as in pull request #44 which fixes compilation errors for OS X. I don't understand the code, just landed there because I was getting similar errors as in issue #38 , but I noticed one instance of `__APPLE__` in file epdfinfo.c and one in file epdfinfo.h that apparently fix the errors on OS X. I replaced `__APPLE__` with `__CYGWIN__` in these two files and everything worked.

So here is the complete procedure that worked for me (if it matters, my OS is windows 7 64 bit with cygwin 64 bit) :
1. Installed dependencies mentioned in the pdf-tools readme from cygwin (I didn't need to follow the OS X specific instructions)
2. Installed pdf-tools from emacs (MELPA)
3. Made the two changes described above
4. Added '(pdf-tools-install)' to my emacs init file, as explained in the readme
5. Restarted emacs and said yes to build the epdfinfo server

When I update the package, I just need to make the two changes again and it works as expected.

Hopefully this is useful to somebody (perhaps the author of issue #54 ). I suppose there is some syntax to say `__APPLE__ or __CYGWIN__` and perhaps you want to implement this in the code. I don't know it and I don't know how to make a pull request either, unfortunately, but if I can still help in some way please let me know.

Thank you for providing this package, I find it very useful.

**Comment by politza** [comment]
ericdanan <notifications@github.com> writes:

> [...]  I replaced _ _APPLE__ with __CYGWIN__ in these two files and
> everything worked.

I added __CYGWIN__ to the check.

**Comment by ericdanan** [comment]
I updated the package from MELPA and everything now works out of the box, no need to manually change the code any more. Thank you.

**Comment by politza** [comment]
Ok, so I guess I'm closing this then.

**Comment by ericdanan** [comment]
The problem is back after last commit 8f7e698. In file epdfinfo.c this commit replaces the line `#if ! (defined (__APPLE__) || defined (__CYGWIN__))` witth `#ifdef HAVE_ERROR_H`. If I understand correctly, `HAVE_ERROR_H` is defined in file configure.ac and under CYGWIN it receives value 1 whereas it should be 0 to avoid including error.h. If I manually delete the three lines `#ifdef ...  #endif` from epdfinfo.c then the package installs correctly (I didn't need to make the same change in file epdfinfo.h but perhaps it would have been better to do so as well...).

**Comment by ericdanan** [comment]
Last commit 8bf1b19 solved the issue, thanks.
