### ISSUE TITLE
Annotations are displayed at the wrong place

### ISSUE THREAD

**Issue by NightMachinery** [politza/pdf-tools#620]
https://files.lilf.ir/tmp/displaced%20annot.mp4

![image](https://user-images.githubusercontent.com/36224762/92719827-fe855f00-f378-11ea-98b9-821e42e72df4.png)

This happens on other files I have tested, too.

**Comment by mindbike** [comment]
We have also issue #600 open for a similar case.
 
> This happens on other files I have tested, too.

Can you please tell about your operating system and version. Also might be nice if you can provide the PDF file which you are having the problem to let others reproduce the case.

**Comment by NightMachinary** [comment]
[**@mindbike**](https://github.com/mindbike) commented on [Sep 11, 2020, 3:56 PM GMT+4:30](https://github.com/politza/pdf-tools/issues/620#issuecomment-691038379 "2020-09-11T11:26:48Z - Replied by Github Reply Comments"):
> We have also issue [#600](https://github.com/politza/pdf-tools/issues/600) open for a similar case.
> 
> > This happens on other files I have tested, too.
> 
> Can you please tell about your operating system and version. Also might be nice if you can provide the PDF file which you are having the problem to let others reproduce the case.

https://files.lilf.ir/tmp/C_C_Pugh%2C_Real_Mathematical_Analysis.pdf

In GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.0.0, NS appkit-1894.00 Version 10.15 (Build 19A583))

System Description:  Mac OS X 10.15
