### ISSUE TITLE
(pdf-tools-install) gives y/n question, but accepts only uppercase Y

### ISSUE THREAD

**Issue by ComedyTomedy** [politza/pdf-tools#621]
On install, the (y/n) prompt should accept a wider range of input: [Yy] and [Nn].

### Details:

Running (pdf-tools-install), I got a message that read something like "need to rebuild epdftool, do that now (y/n)"

Answering lowercase "y" quit the process, echoing I think only "QUIT" in the minibuffer.

♥

**Comment by phil-s** [comment]
As one would expect, this is just a call to the standard Emacs `y-or-n-p`:

    (y-or-n-p "Need to (re)build the epdfinfo program, do it now ?")

There's no reason why `pdf-tools` should do anything non-standard here, so your issue is actually with Emacs not with pdf-tools.

**Comment by phil-s** [comment]
I.e. I suggest you close this issue yourself, and `M-x report-emacs-bug` if you wish to suggest changes.

**Comment by ComedyTomedy** [comment]
Thanks! Sorry for not looking deeper, I was debugging and in a rush.

**Comment by phil-s** [comment]
Although (having just tested) given that `y-or-n-p` accepts both upper- and lower-case responses, and the case does not affect its return value, your issue is somewhat confusing.

Which version of Emacs are you using?

**Comment by ComedyTomedy** [comment]
27.1, hang on I'll test a little

**Comment by ComedyTomedy** [comment]
It's my config. I'm not entirely sure how. It waits for a newline except in the case of uppercase "Y" (!)

Thanks for your help, and sorry for wasting your time!
