### ISSUE TITLE
Export all annotations

### ISSUE THREAD

**Issue by pank** [politza/pdf-tools#63]
Hi,

`C-c C-a l` is great!  It would be handy if all annotations could be exported at once.  For example, this is useful for discussing change in email.

Thanks,

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> C-c C-a l is great! It would be handy if all annotations could be
> exported at once.

Try M-x pp-eval-expression (pdf-annot-getannots nil '(text)) RET .

**Comment by pank** [comment]
politza <notifications@github.com> writes:

> pank <notifications@github.com> writes:
>
>> C-c C-a l is great! It would be handy if all annotations could be
>> exported at once.
>
> Try M-x pp-eval-expression (pdf-annot-getannots nil '(text)) RET .

Great.  I got what I wanted with:

    (mapconcat (lambda (x) (alist-get 'contents x)) (pdf-annot-getannots nil nil) "\n\n\nNext note:\n")

Thanks.

-- 
The Kids call him Billy the Saint

**Comment by politza** [comment]
Can this be closed or do you think there should be a actual export command ?

**Comment by pank** [comment]
I think the current function is OK for people who know lisp. Probably a pointer or example in the manual/readme is enough.

**Comment by politza** [comment]
pank <notifications@github.com> writes:

> [...] Probably a pointer or example in the manual/readme is enough.

Starting some kind of manual would probably a good idea.
