### ISSUE TITLE
Cannot add markup annotation

### ISSUE THREAD

**Issue by egh** [politza/pdf-tools#637]
OS: debian testing
Emacs version 28.0.50, installed via [snap](https://snapcraft.io/emacs) edge (28.0.50-native-comp-be907b0)

Steps to reproduce:

1. Open `test.pdf` (https://github.com/politza/pdf-tools/blob/master/test/test.pdf)
2. Highlight some text
3. `C-c C-a h` (pdf-annot-add-highlight-markup-annotation)
4. Click on highlight to edit annotation
5. Type text.
6. `C-c C-c` (pdf-annot-edit-contents-commit)

Expected result: text is saved.

Actual result: error: `pdf-info-query: epdfinfo: No such annotation: annot-1-0`

**Comment by LorenRiccie** [comment]
same error here, emacs 27.1 / fedora 33

**Comment by chiraag-nataraj** [comment]
Hmm, seems to work for me on emacs 27.1 on Debian sid/experimental. I tried it with a random PDF on hand, but I'll try it with yours next and edit this comment with the result.
