### ISSUE TITLE
Feature Request: Printing PDFs

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#64]
After heavy use of PDF Tools I've come to the conclusion that it's by far the most feature-complete PDF viewer out there.  Except for one little thing: printing.  And by that I don't mean passing the PDF to `lpr`.  Instead it would be awesome if there was a print entry in the menus that would invoke the standard GTK system printer dialog from which I can easily set options like page range, printer, duplex, etc, i.e., that one: https://developer.gnome.org/gtk3/stable/GtkPrintUnixDialog.html

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> [...] Instead it would be awesome if there was a print entry in the
> menus that would invoke the standard GTK system printer dialog from
> which I can easily set options [...]

I can't find any command line front-ends for the GTK dialog, but there
are other tools, like xpp, which looks pretty good.

**Comment by tsdh** [comment]
politza <notifications@github.com> writes:

> I can't find any command line front-ends for the GTK dialog,

Me neither although I had expected that Freedesktop.org should have
given us something like that already, like xdg-open for opening files
with an appropriate application...

But you already have C code, so yet another micro utility might not be
the worst thing one can imagine.  And it has the benefit that GTK is
installed almost on every system.

> but there are other tools, like xpp, which looks pretty good.

XPP uses FLTK and I guess that's not installed on most systems.

Bye,
Tassilo

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> politza <notifications@github.com> writes:
>
>> I can't find any command line front-ends for the GTK dialog,
>
> But you already have C code, so yet another micro utility might not be
> the worst thing one can imagine.[...]

Still, someone has to write and maintain it. I'd rather prefer a
existing solution.

> XPP uses FLTK and I guess that's not installed on most systems.

Package-manager ? I'm sure there are similar tools on Mac/Windows.

**Comment by politza** [comment]
http://gtklp.sirtobi.com/

**Comment by tsdh** [comment]
Looks ok to me.

**Comment by politza** [comment]
Can I close this then ?

**Comment by tsdh** [comment]
Yes, I closed it.

As a reference, here's a python snipped I got from the GNOME desktop mailing list when I asked there if the printing dialog could be fired up from the command line.  The answer is, usually not but yes for documents Poppler can handle.

```python
#!/usr/bin/env python
import os
import sys
from gi.repository import GLib, Gtk, Poppler


class PrintingApp:
    def __init__(self, file_uri):
        self.operation = Gtk.PrintOperation()

        self.operation.connect('begin-print', self.begin_print, None)
        self.operation.connect('draw-page', self.draw_page, None)

        self.doc = Poppler.Document.new_from_file(file_uri)

    def begin_print(self, operation, print_ctx, print_data):
        operation.set_n_pages(self.doc.get_n_pages())

    def draw_page(self, operation, print_ctx, page_num, print_data):
        cr = print_ctx.get_cairo_context()
        page = self.doc.get_page(page_num)
        page.render(cr)

    def run(self, parent=None):
        result = self.operation.run(Gtk.PrintOperationAction.PRINT_DIALOG,
                                    parent)

        if result == Gtk.PrintOperationResult.ERROR:
            message = self.operation.get_error()

            dialog = Gtk.MessageDialog(parent,
                                       0,
                                       Gtk.MessageType.ERROR,
                                       Gtk.ButtonsType.CLOSE,
                                       message)

            dialog.run()
            dialog.destroy()

        Gtk.main_quit()


def main():
    if len(sys.argv) != 2:
        print( "%s FILE" % sys.argv[0])
        sys.exit(1)

    file_uri = GLib.filename_to_uri(os.path.abspath(sys.argv[1]))

    main_window = Gtk.OffscreenWindow()
    app = PrintingApp(file_uri)
    GLib.idle_add(app.run, main_window)
    Gtk.main()

if __name__ == '__main__':
    main()
```

**Comment by politza** [comment]
Tassilo Horn <notifications@github.com> writes:

> Yes, I closed it.
>
> As a reference, here's a python snipped I got from the GNOME desktop
> mailing list

I get these two errors, is this a version problem ?

TypeError: filename_to_uri() takes exactly 2 arguments (1 given)

TypeError: new_from_file() takes exactly 2 arguments (1 given)

But after adding a None arg each, it started.  When I press the Preview
button it get this:

TypeError: Couldn't find conversion for foreign struct 'cairo.Context'

Anyway, looks like this could be an alternative with some additional
work ...

**Comment by tsdh** [comment]
Yes, that could be a version error.  I've run it with Python 3.4.3.  And AFAIK, that script relies on GNOME3, so probably it'll just work for people running GNOME3 but not for others.

Anyway, the point is that I'm fine with a `pdf-view-print-command` option where one could just add a command for printing be it that script, XPP, gtklp, or something completely different.
