### ISSUE TITLE
Highlights and annotations not saved

### ISSUE THREAD

**Issue by faaip** [politza/pdf-tools#646]
When using this with doom emacs on macOS, my highlights and annotations are not saved. In Finder it says that the file has been modified, but the annotations and highlights aren't there when I reopen the file. By default pdf-tools opens the pdf in read-only, but I disable this and still it doesn't work. Any idea on why this might be? Thanks!

**Comment by workcomplete** [comment]
Having the same issue, this is new for me this week. I am using org-pdf-tools and thought it was be an issue with that package, but pdf-tools itself may be to common denominator.. #fuxialexander/org-pdftools#68

**Comment by workcomplete** [comment]
Cannot reproduce this now. Everything appears to be saving, but annotations are still missing from older documents.

**Comment by vedang** [comment]
Doom has now changed to point to my fork - vedang/pdf-tools - Please update your Doom and try again. As you've mentioned above, I believe this is not a bug. However, you don't need to call write in the pdf-buffer, simply selecting text and annotating it using `C-c C-a h` (or any other annotation function) should do the job.

**Comment by faaip** [comment]
@vedang . Tried updating doom, but still have this problem. Whenever I save the PDF buffer my annotations disappear. Do you have an idea for a solution?
