### ISSUE TITLE
[feature request]: pdf-multi-occur

### ISSUE THREAD

**Issue by wdkrnls** [politza/pdf-tools#65]
I've found that I tend to have dozens of related PDF's open at once, and have often wished to be able to search all of them at once. My workaround right now is to use the Python `stapler` utility to combine a bunch of the more related ones, and then search that. But that requires a lot more tedium than I'd wish was necessary. Given that `multi-occur` already exists for text, perhaps it wouldn't be so difficult to do with `pdf-tools`?

**Comment by politza** [comment]
Occur/Moccur don't help at all here, because searching in this functions is hard-coded to use `re-search-forward'.

**Comment by wdkrnls** [comment]
Sorry, I wasn't implying you could reuse the functionality in `multi-occur`. I just was advocating that `pdf-multi-occur` would be a very useful and powerful feature for an Emacs oriented pdf reader to have. I'd be very happy with `pdf-multi-occur`  showing the same table interface we have for `pdf-occur` but with an extra column showing the source buffer.

**Comment by politza** [comment]
wdkrnls <notifications@github.com> writes:

> Sorry, I wasn't implying [...]

I was merely stating a fact.

**Comment by politza** [comment]
cccf5e0e1172366e933546c2b7c47c30ea2bb984

You're wishes are my commands.

**Comment by wdkrnls** [comment]
This sounds great!  I just updated on MELPA (deleting first, restarting emacs, the installing) and tried to play with it. I like the ability to easily include or exclude PDFs from the search. However, I'm not exactly sure how to perform the search as there doesn't appear to be a pdf-multi-occur function yet. Also, I tried just using `pdf-occur` in a pdf and discovered I'm getting the error below:

```
Debugger entered--Lisp error: (invalid-function tablist-generate-sorter)
  tablist-generate-sorter(0 < string-to-number)
  pdf-occur-revert-buffer()
  pdf-occur-search((#<buffer Book.pdf>) "workflow" t)
  pdf-occur("workflow" t)
  call-interactively(pdf-occur nil nil)
  command-execute(pdf-occur)
```

Playing around in `IELM` I saw that this macro isn't expanding as I would naively expect. I would have assumed that the arguments to the macro which are functions would be inserted into the lambda. Maybe that is related? 

```
ELISP> (tablist-generate-sorter 0 '< 'string-to-number)
(lambda
  (e1 e2)
  (funcall compare-fn
           (funcall read-fn
                    (aref
                     (cadr e1)
                     column))
           (funcall read-fn
                    (aref
                     (cadr e2)
                     column))))

```

**Comment by politza** [comment]
wdkrnls <notifications@github.com> writes:

> [...] I just updated on MELPA (deleting first, restarting
> emacs, the installing) [...]

Are you sure you deleted all versions ?

> [...]  there doesn't appear to be a
> pdf-multi-occur function yet. 

It' called pdf-occur-multi due to naming conventions.  Though it's just
a wrapper for ibuffer. 

> Also, I tried just using pdf-occur in a pdf and discovered I'm getting
> the error below:
>
> Debugger entered--Lisp error: (invalid-function tablist-generate-sorter)
>   tablist-generate-sorter(0 < string-to-number)

This looks like a package.el problem: The compiler did not expand the
macro, because it was not defined, because a old version of tablist.el
was still loaded.  Try this:

1. Load tablist.el 
2. Byte compile pdf-occur.el
3. Load pdf-occur.elc 

>
> Playing around in IELM I saw that this macro isn't expanding as I
> would naively expect. [...]

You need to enable lexical-binding in the IELM buffer first.

**Comment by politza** [comment]
wdkrnls <notifications@github.com> writes:

> Playing around in IELM I saw that this macro isn't expanding

Never mind, this should have been a function in the first place.  So I
changed it.

**Comment by wdkrnls** [comment]
Just updated again and was more careful. The package manager had trouble uninstalling the tablist package, but deleting it manually and reinstalling worked. I saw that that capital O in the ibuffer view started the search.

Thanks for your great work!
