### ISSUE TITLE
Isearch not highlighting search hits

### ISSUE THREAD

**Issue by n14s** [politza/pdf-tools#654]
Neither isearch-forward nor pdf-occur are highlighting the occurences of the search term.
 
Isearch-forward, which I usually use, is only highlighting as the word is typed in. 
When I press enter and browse to the different occurences with n or N, the pdf focuses the area, but without highlighting the word. 

I'm using Doom Emacs 27.1 on Ubuntu.
I got no additional configurations for pdf-tools.

**Comment by michaelmyc** [comment]
Having the same issue.

**Comment by vedang** [comment]
Hello! I'm unable to reproduce this on my Emacs configuration (I use a personally crafted non-evil-based Emacs configuration on Ubuntu). Can you please update your setup to use the latest vedang/pdf-tools and let me know if you can still reproduce the problem?

**Comment by michaelmyc** [comment]
I think Doom Emacs has its built-in package management system. I ran `doom upgrade` so pdf-tools should be automatically upgraded to politza/pdf-tools. @vedang Are you aware of what functions/variables control the highlighting?

**Comment by michaelmyc** [comment]
@vedang Doom emacs just updated their pdf-tools to use your fork as upstream. Is it possible to implement a function similar to `evil-search` as @hlissner suggested in hlissner/doom-emacs#4750? I'd love to help, but I'm new to emacs and don't really know elisp :(

**Comment by vedang** [comment]
Thanks @michaelmyc . Honestly speaking, I do not know what you want to implement / improve with `evil-search` as I've never used Vim / Evil. I can confirm that currently `isearch` is working exactly as it should in vanilla Emacs. 

If you can help me out with examples of what is supposed to happen - screenshots, video of what is supposed to happen for example - I will add it to my list of enhancements and track it

**Comment by brabalan** [comment]
When using evil, one can initiate a search in normal mode using `/`, then start typing the search phrase, just like `isearch`. The difference is the following: to reach the next occurrence of the phrase, one type `C-s` again, whereas with evil one must first hit `RET` to validate the search phrase, then one can navigate between results using `n` and `N`. The results remain highlighted.

![evil-search](https://user-images.githubusercontent.com/1021637/110436181-35cc9280-80b4-11eb-88c2-2f1a02c8a742.gif)

**Comment by michaelmyc** [comment]
Yes. C-s works and it's as expected. The only catch is most evil users would expect "RET" would preserve the highlighting, and "n" to find next and "N" to find previous. Maybe a minor mode that the user can optionally turn on to allow vim-like keybindings to work for isearch. I can demonstrate with a normal document, but I'm not sure what tool I can use to show the keys I'm pressing. Any pointers?

**Comment by vedang** [comment]
Thanks for the Gif, I understand now. I'll add this to the list of
enhancements I'm tracking.
