### ISSUE TITLE
How to find a new maintainer?

### ISSUE THREAD

**Issue by sje30** [politza/pdf-tools#659]
@politza has done an amazing job on this package pdf-tools.  It is part of my daily Emacs setup, and probably  used by many others.  It would be a shame to see it accrue issues and PRs that cannot be shared.  I understand others have reached out to @politza but have not heard back.

This reddit thread summarises the state of play:

https://www.reddit.com/r/emacs/comments/ip17pu/looking_for_a_maintainer_for_pdftoolstablist/

Can we as a community agree how best to support this package if @politza no longer has the energy?  

**Some options (not exclusive)**

1. I'd be willing to ask on the gnu-emacs-devel mailing list for help on maintaining it; I doubt it would get into Emacs core, as much as I would like to see it,  because of external dependencies (and possibly copyleft assignments?)

2. Fork it to melpa/emacsorphanage 

3. Someone volunteer to fork it and maintain

For my part, I don't have time to maintain it, but I could do 2 if that met with everyone's approval.

Stephen

**Comment by antoine-levitt** [comment]
The best scenario would be to have @politza add someone as maintainer, but he appears to be unreachable. I'm not sure 1. is the best option, there's little point in moving things to emacs core.

If somebody here steps up as maintainer, is it possible to fork pdf-tools and make MELPA point to the fork? That would probably be the best option.

**Comment by sje30** [comment]
@purcell might be able to address the MELPA issue.

**Comment by vedang** [comment]
I'm willing to step up as a maintainer here, I can currently dedicate my weekends for this work. Caveats: 

1. I have not maintained heavily used open-source stuff earlier
2. I have not contributed to `pdf-tools` or `libpoppler` previously. I use `pdf-tools` mainly to read papers and capture notes (via `org-noter`). I don't have expertise in PDF land. I can learn though. 
3. I am a long-time Emacs user (14 years) and have written emacs-lisp for my own purposes, but have not written packages / serious emacs-lisp code before. I can learn though. 

Let me know if this works, and I will start from this weekend.

**Comment by antoine-levitt** [comment]
Has anyone tried to contact politza through something else than github and reddit? There is an Andreas Politz working in IT on LinkedIn and on facebook, but I'm not sure it's him.

**Comment by antoine-levitt** [comment]
Hm no it's probably not him, listed university doesn't match with the one in the pdf-tools docs, which someone says has used to try to contact him without success. So dead end it appears...

**Comment by sje30** [comment]
hi @vedang 

as no-one else seems keen to rush up, and no-one opposes a fork, why not give it a go and see how you get on?  If I can help out, time-willing, I will.  Perhaps the starting point would be to get some recent issues folded in, which at the least should start to generate some discussion with the submitters of those issues.  Other people who have then expressed interest can join in.

**Comment by vedang** [comment]
Sure, I'll get started by reviewing all the issues + PRs and applying the simpler patches. I'll spend some time familiarizing myself with the code as well. The fork is here, https://github.com/vedang/pdf-tools . I'll post some sort of updates from the next weekend onward

**Comment by sje30** [comment]
Great.

**Comment by purcell** [comment]
> listed university doesn't match with the one in the pdf-tools docs, which someone says has used to try to contact him without success.

Is that the high school email address in this commit? https://github.com/politza/pdf-tools/commit/cc29d4c9c2d81fcb1255f7172fd5b9b7851d656c.patch

**Comment by antoine-levitt** [comment]
Yes, only one I could find

**Comment by antoine-levitt** [comment]
I imagine they tried the one at the top of the lisp file, this one could be another one to test!

**Comment by sje30** [comment]
has anyone written to this new (Hochschule) email?  If not, I can.

**Comment by sje30** [comment]
oh no... both that new email that @purcell found and the one in the .el files bounced when I just tried to send a message.

**Comment by vedang** [comment]
Update for weekend 1:

I've reviewed all the PRs and have applied all the simpler patches. For the pending ones, I'll need to set up better testing environments and/or better understand the code changes.

I've merged in patches that close the following PRs and Issues: #539, #578, #591, #658, #590, #650, #649, #604, #660, #588, #626, #631, #589, #566, #628, #567. If the respective authors could close the PRs/Issues, that would be very helpful.

(Since I'm only looking at PRs right now, I'm sure a bunch more issues have been resolved in these patches as well)

I'll see how it goes over the next two weekends and if I feel like I can keep this up, I'll put in a request to point package managers to my fork.

Cheers,
Vedang

**Comment by sje30** [comment]
Thank you Vedang.  I have now switched over to your fork using this recipe:

```
(straight-use-package
 '(pdf-tools :type git
	     :host github :repo "vedang/pdf-tools"
	     ))

(pdf-tools-install)
```

Are you hoping to continue working on this fork?

**Comment by vedang** [comment]
Yes @sje30 : I'm continuing working on the fork. Currently, I'm only working on merging in patches / debugging new issues filed by users, but I soon hope to make time for some improvements I've identified and for addressing existing issues. It'll be slow going but I'm in it for the long run.

Thanks for switching over. Doom Emacs has moved over as well, and I'm hoping that slowly everyone else will.

**Comment by sje30** [comment]
Thank you for your continuing hard work!
