### ISSUE TITLE
[bug]: pdf's get stuck on the same page

### ISSUE THREAD

**Issue by wdkrnls** [politza/pdf-tools#66]
When viewing the same `PDF` in multiple windows (e.g. on different pages), sometimes the `PDF` gets stuck on a particular page. Killing the buffer and reopening the `PDF` resolves the issue.

**Comment by politza** [comment]
Please be more specific. What does getting stuck mean ? What is the
error message, if any.

**Comment by svend** [comment]
I see this when I run `pdf-view-fit-height-to-window`. Pressing `SPC` (`command pdf-view-scroll-up-or-next-page`) has no effect (same with `S-SPC`). `pdf-view-next-page` does advance to the next page.

If I run `pdf-view-fit-width-to-window`, `SPC` advances to the next page.

I don't get any error messages.

**Comment by politza** [comment]
Yes, it's a rounding issue.

**Comment by wdkrnls** [comment]
By "get stuck", I mean that the page number advances, but the page displayed does not.

**Comment by politza** [comment]
> By "get stuck", I mean that the page number advances, but the page displayed does not.

Do you advance by `n` or `SPC` ?

**Comment by wdkrnls** [comment]
`n`

**Comment by politza** [comment]
wdkrnls <notifications@github.com> writes:

> n

Next time, if this happens, try `SPC` or `DEL`.  The redisplay for the
`n` and `p` commands run on a timer, if Emacs thinks that there is still
input available -- this may not work a 100%.

**Comment by wdkrnls** [comment]
It happened to me again today. `SPC` and `DEL` moved the current page down/up repeatedly, but didn't change the page displayed.  As before, the page number reported in the information line incremented/decremented, but the page displayed didn't change.

**Comment by politza** [comment]
Does this still happen, or can this be closed ?

**Comment by narendraj9** [comment]
I am facing the issue right now. I have faced this multiple times but not sure what might be causing this.
