### ISSUE TITLE
Annotations: where are they saved?

### ISSUE THREAD

**Issue by AtomicNess123** [politza/pdf-tools#661]
Simple question. Where are annotations saved? Within the PDF or in an orgmode document somewhere?

**Comment by andersjohansson** [comment]
They are saved in the pdf, following the pdf standard. So if you open the annotated file in another pdf viewer you will see the annotations there.

**Comment by AtomicNess123** [comment]
Cosed too early: any possibility to export these annotations to ORG (org-noter, for instance)?

**Comment by andersjohansson** [comment]
A guide for exporting: https://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/
The formatting is off with the current rendering of that page, more readable here: https://web.archive.org/web/20200307114049/https://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/

**Comment by titaniumbones** [comment]
Ha, amazing people still read these old posts - I will look into the formatting issues when I have a chance, maybe st the end of the week.

On Feb. 22, 2021 6:51 a.m., Anders Johansson <notifications@github.com> wrote:
EXTERNAL EMAIL:

A guide for exporting: https://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/
The formatting is off with the current rendering of that page, more readable here: https://web.archive.org/web/20200307114049/https://matt.hackinghistory.ca/2015/11/11/note-taking-with-pdf-tools/
