### ISSUE TITLE
Is there a way to add text annotations that are displayed in the document as text?

### ISSUE THREAD

**Issue by simurgh9** [politza/pdf-tools#664]
For example, using Okular's review tool you can add annotations that are displayed as text in the document,

![text_annot](https://user-images.githubusercontent.com/43047754/111055729-83435980-843e-11eb-8396-4f9a8830c6ff.png)

The closest I have been able to do using pdf-tools is adding a small icon that then opens a buffer with the annotation,

![pdftools](https://user-images.githubusercontent.com/43047754/111055740-981fed00-843e-11eb-8fdc-49d765da1a7a.png)

Is there a way to achieve the Okular like annotations in pdf-tools? Could it be added?

**Comment by vedang** [comment]
When you add the text annotation using `pdf-tools`, (default `C-c C-a t`) as you have shown above, you'll be able to see the text on hover as well (vs on click which opens a new buffer and lets you edit the annotation as well). 

Further, you can also list all the annotations on demand using `C-c C-a l`. Isn't that sufficient for your usecase?

**Comment by simurgh9** [comment]
Adequate? Yeah maybe, sufficient? No, it is not. I prefer the small margin notes which then can be read from any pdf reader.

**Comment by vedang** [comment]
Okay, understood. I was thinking strictly within the context of
`pdf-tools`.

What you are asking for isn't currently possible. I'll add it to a list of
enhancements I'm tracking but it isn't very high priority at the moment.

If you can upload a test PDF here with the kind of annotations you are
describing, it'll be helpful for me to track the expected behaviour.

**Comment by simurgh9** [comment]
[Here](https://github.com/politza/pdf-tools/files/6145941/diophantus.pdf) is a page out of *Arithmetic* by Diophantus with Pierre de Fermat’s legendary margin annotation. Note that the margin annotation won't show in the browser, either actually open this in `pdf-tools` within Emacs or Atril Document Viewer. I also test viewed this with Mupdf and was able to see the margin annotation. Like I said before, I created this using Oklular's review tool's typwriter option.

We can already edit or modify such annotations with `pdf-tools` which makes me think that making them should not be that difficult.

**Comment by simurgh9** [comment]
Okay so what I am referring to is called a [FreeText](https://www.pdftron.com/api/PDFTronSDK/dotnetcore/pdftron.PDF.Annots.FreeText.html) annotation type. I was reading [pdf-annot.el](https://github.com/politza/pdf-tools/blob/master/lisp/pdf-annot.el). Maybe something like,

```lisp
(defcustom pdf-annot-default-annotation-properties
  `((t (label . ,user-full-name))
    (text (icon . "Note")
          (color . "#ff0000"))
    (freetext (???)) ;; I am not sure what to put here exactly.
    (highlight (color . "yellow"))
    (squiggly (color . "orange"))
    (strike-out(color . "red"))
    (underline (color . "blue")))
```

**Comment by titaniumbones** [comment]
This looks somewhat difficult to implement bu it would be great for me as well when I am marking student papers. I usually add a text comment to a highlight annotation, and htis works fine; but students often miss them and they can not look at all the comments in one glance, so they often don't quite understand what I'm saying. Would love to have something like this.  But I think drawing the box would be pretty tough.

**Comment by simurgh9** [comment]
@titaniumbones read my responses, it should not be anymore difficult than adding annotations of any other types.

**Comment by uti5** [comment]
This would be useful.  Hidden notes are very cumbersome.  This is the main reason I'm sticking with okular for now.

**Comment by titaniumbones** [comment]
@uti5  development on this repo has now moved to https://github.com/vedang/pdf-tools/ . I think it would be great to see this feature implemented, but I disagree with @simurgh9  that it is uncomplicated. pdf-tools would have to identify the available marginal space and calculate things like font-size to make the annotation fit in the appropriate region.  That is more complicated than simply adding `'free-text` to the list of writable annotations hard-coded into `pdf-info-creatable-annotation-types` in pdf-info.el.  As far as I know, there's also no way to e.g. use the mouse to select an area on the page and use it as a set of coordinates, which might be a way forward if writing a new function on the model of `pdf-annot-add-text-annotation`.  

In any case it makes sense to open this as an issue on @vedang's fork!

**Comment by vedang** [comment]
Yes, please open the issue on vedang/pdf-tools and link back to this issue,
if you haven't already.

I've stopped looking at issues / PRs on politza/pdf-tools due to lack of
time.

/Vedang

**Comment by simurgh9** [comment]
Am I expected to open a new issue on @vedang's fork? If one is already opened, could someone link it here?
