### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by foogee** [politza/pdf-tools#665]
I followed the instructions on the README for installation and configuration on windows. I have mingw64 installed. I downloaded everything from https://github.com/politza/pdf-tools. Using mingw64, I cd to the path where I saved pdf-tools-master, and I run "make -s." I get the following: 

```
$ make -s
Using Emacs 27.1
make: cask: No such file or directory
make: *** [Makefile:44: .cask/27.1] Error 127
```

When I try pdf-tools-install from emacs it asks whether I have msys2 installed and when I select yes it prompts me for the installation directory. I supply that info and then I get the following error: 

```
---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=c:/Users/[name]/Documents/.emacs.d/elpa/pdf-tools-20200512.1524/ && make -s
configure: error: cannot find necessary  poppler-private header (see README.org)
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Mon Mar 15 10:16:29
```

Even though I have poppler installed through mingw64. This seems related to [https://ask.csdn.net/questions/1704842](url), so I added the mingw64/bin directory to my path in hopes that that would resolve the issue, but it did not work. 

Any ideas?

**Comment by vedang** [comment]
Copying my comment from vedang/pdf-tools#3 :

> Please try installing cask as described here: https://github.com/cask/cask and then run make -s again in the pdf-tools directory. Let me know if that fixes the issue.
>
> Also, please clone https://github.com/vedang/pdf-tools for the latest changes.

**Comment by revrari** [comment]
I have the same problem. I have followed the steps you have provided to resolve the issue but they have not been successful. If I run make -s I get 

`make: *** [Makefile:24: pdf-tools-1.0.tar] Error 127`

**Comment by foogee** [comment]
revrari I suggest checking out the issue on the other page, at https://github.com/vedang/pdf-tools/issues/3

did you get mingw64 set up and running? Within mingw64, you have to make sure all necessary packages are installed, including those listed in the pdf-tools README and cask, and python, and you need your paths set up correct. I also installed emacs in mingw64 (though I don't use emacs through mingw64). have you tried those steps"?

**Comment by revrari** [comment]
I will check that out now. Just to say that in the past I have succeeded installing PDF-TOOLS in Windows. It is only recently that I have had a problem again.

**Comment by revrari** [comment]
I have succeeded in installing mingw64. I have installed all the required packages. I have installed cask and python. I am not sure which paths you mean except that in installing cask, I followed the instructions.

**Comment by revrari** [comment]
If I install through package.el the program succeeds in building. If I I try to do it manually through git, I get the above error.

**Comment by yanghaifeng516** [comment]
> revrari 我建议在另一个页面上查看这个问题，在[vedang#3](https://github.com/vedang/pdf-tools/issues/3)
> 
> 你设置并运行mingw64了吗？在 mingw64 中，您必须确保安装了所有必需的软件包，包括 pdf-tools README 和 cask 中列出的软件包，以及 python，并且您需要正确设置路径。我还在 mingw64 中安装了 emacs（虽然我没有通过 mingw64 使用 emacs）。你有没有试过这些步骤”？

Has your problem been solved? How to solve it?
