### ISSUE TITLE
Wrong documentation under Windows and Archlinux

### ISSUE THREAD

**Issue by BuddhiLW** [politza/pdf-tools#666]
Somehow the Archlinux install documentation is right under Windows.

**Comment by vedang** [comment]
I don't understand the question. Can you pleas explain a bit more? I'm neither an Archlinux user nor a Windows user.

**Comment by BuddhiLW** [comment]
Ok. No problem.

The default package manager of Archlinux is pacman, which use-instructions are below Windows's section.

**Comment by yanghaoxie** [comment]
The document is fine. `Pacman` is the package manager of [MSYS2](https://www.msys2.org/), too.

**Comment by BuddhiLW** [comment]
Oh, I see.

Alright then. Sorry for my ignorance!
