### ISSUE TITLE
Nagivation by text entities

### ISSUE THREAD

**Issue by roy-tancredi** [politza/pdf-tools#668]
Is there any option to navigate on page by text? Like in regular text mode.

**Comment by vedang** [comment]
Hello! I don't understand the question. Do you mean you want to search for a word and find it's occurrences? This is already supported in `pdf-tools`

**Comment by roy-tancredi** [comment]
> Hello! I don't understand the question. Do you mean you want to search for a word and find it's occurrences? This is already supported in `pdf-tools`

No, I meant navigation like in regular text by lines, words, chars, etc. That could enable using all evil-mode/avy capabilities.
