### ISSUE TITLE
Configure script not working

### ISSUE THREAD

**Issue by neuschwanstein** [politza/pdf-tools#67]
I have the almost exact same problem as [Issue 39](https://github.com/politza/pdf-tools/issues/39), that is the configure script is not working.

I'm working on Mac OS 10.3.3, and here's the ouput of `./configure`: 

    ...
    checking for ranlib... ranlib
    checking for ar... ar
    checking the archiver (ar) interface... ar
    ./configure: line 4730: syntax error near unexpected token `png,'
    ./configure: line 4730: `PKG_CHECK_MODULES(png, libpng)'

`pkg-config` looks correctly installed in `/opt/local/bin`.

I just grabbed the latest MELPA version, the directory indicates `pdf-tools-20150330.1331`.

**Comment by politza** [comment]
Thierry BM <notifications@github.com> writes:

> ./configure: line 4730: syntax error near unexpected token `png,'
> ./configure: line 4730: `PKG_CHECK_MODULES(png, libpng)'
>
> pkg-config looks correctly installed in /opt/local/bin.

I think the PKG_CHECK_MODULES macro should be expanded at this point.

Sorry, can't help with that.  If you find the right fix for your
OS/automake configuration (google configure+aclocal+PKG_CHECK_MODULES),
I am happy to include it.
