### ISSUE TITLE
Pdf occur context resize

### ISSUE THREAD

**Issue by Twix53791** [politza/pdf-tools#671]
Hello, 

Thanks very much for this amazing tools for emacs, very useful for me! I would like to improve the pdf occur mode, as I use it a lot, and I would appreciate to be able to resize the surrounding context displayed by the occur search, the number of lines displayed. It is something possible on the native emacs occur mode, even dynamically with this little but formidable tool : https://github.com/dgtized/occur-context-resize.el. 
I don't know coding enough to discover by myself in the pdf-occur.el what function could do that, so I ask here (maybe not the right place?) if someone could give me an insight about the way to do achieve this functionality. 

Thanks

**Comment by vedang** [comment]
Hello @Twix53791 ,

Unfortunately, this is non-trivial in `pdf-occur` due to the fact that the underlying text is returned by `poppler` and requires changes in the `epdfinfo` server (C) program. I will track this as a feature request and pick it up when time permits. 

Thanks,
Vedang

**Comment by vedang** [comment]
Can you please open this issue against `vedang/pdf-tools`? This is the maintained fork of `pdf-tools` and I can label / organize issues better against that repo.

**Comment by Twix53791** [comment]
Hi,

Thank you vedang for your answer and consideration. I expected it to be difficult, as I had since looked a bit at the code... I open the issue on the link you gave me.
