### ISSUE TITLE
(Minor) bug found in pdf-tools-20210511.1739.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [politza/pdf-tools#672]
After this morning's update to `pdf-tools-20210511.1739`, the first opening of a PDF file (created by `org-mode`, which uses `org-pdftools-20210118.1611`) game mi this :

> Error (use-package): pdf-tools/:config: Autoloading file /home/charpent/.emacs.d/elpa/pdf-tools-20210511.1739/pdf-occur.elc failed to define function pdf-occur-global-minor-mode

in a buffer called' `*Warnings*`. So far, `pdftools` seems functional (but I'll update this (minor) bug report if necessary).

HTH,

**Comment by vedang** [comment]
Thanks. `pdf-occur-global-minor-mode` does have a autoload cookie, so this should not be happening. I'll look into this on my end as well.
