### ISSUE TITLE
win10 can't open pdf file

### ISSUE THREAD

**Issue by robin2003** [politza/pdf-tools#677]
open pdf file after epdfinfo, but error message prompt as follow:

pdf-info-encrypted-p: epdfinfo: Error opening c:/tmp/docker_practice.pdf:The pathname    c:/tmp/docker_practice.pdf    is not an absolute path

can anyone know why?

**Comment by tongjie-chen** [comment]
Probably you compiled epdfinfo with a different environment than the Emacs runs. Maybe you can try to change the environment and compile again.

What environment of Emacs are you using in, Cygwin or native?

**Comment by robin2003** [comment]
> Probably you compiled epdfinfo with a different environment than the Emacs runs. Maybe you can try to change the environment and compile again.
> 
> What environment of Emacs are you using in, Cygwin or native?

my environment is Cygwin.
