### ISSUE TITLE
pdf-sync.el for orgmode

### ISSUE THREAD

**Issue by fab6** [politza/pdf-tools#678]
Hi,
I am preparing most of my documents with orgmode and like it a lot. Especially for beamer presentation it would be quite helpful to have a syncing to the actual pdf page.

Is there an option to use pdf-sync with orgmode files as well?
Or are there any plans to adjust this?

This would be really great!

Fab

**Comment by vedang** [comment]
Hello, there is no such option at the moment, and no plans in the immediate future for this support. If you file this issue against https://github.com/vedang/pdf-tools, I will tag it as a future feature request and track it

Thanks,
Vedang

**Comment by fab6** [comment]
ok, thank you very much for you quick reply! I understand...no problem.
Would it be much effort to do this based on the current tex-code? Or could this be used as a good base?
Fab

**Comment by vedang** [comment]
This is a high-effort feature, nothing in the current code base supports it :) Hence this will probably not be picked up in the near future. However, it would be good to track it and see how many other folks are interested in a similar feature

**Comment by fab6** [comment]
ok, thank you for your further information
