### ISSUE TITLE
Error when I-search on MacOS

### ISSUE THREAD

**Issue by Enrico68** [politza/pdf-tools#68]
When I try to search I got the following error

`````
Error while processing tq callback: Invalid image specification [2 times]
```````

**Comment by politza** [comment]
Enrico Pirani <notifications@github.com> writes:

> When I try to search I got the following error
>
> Error while processing tq callback: Invalid image specification [2 times]

How do you search ? Isearch ?

**Comment by Enrico68** [comment]
politza <notifications@github.com> writes:

> Enrico Pirani <notifications@github.com> writes:
>
>> When I try to search I got the following error
>>
>> Error while processing tq callback: Invalid image specification [2 times]
>
> How do you search ? Isearch ?

Yes I use I-search

>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/politza/pdf-tools/issues/68#issuecomment-88033921

-- 
Dr. Enrico Pirani
Medico Chirurgo
Specialista in Chirurgia Toracica
FMH Chirurgia Cardiaca 
Via Matteotti 7
35042 Este (Padova)

Cell:392-6224668
Tel: 0429-17660135

  Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute in
  questo messaggio sono riservate ed a uso esclusivo del destinatario.
  Qualora il messaggio Le fosse pervenuto per errore, La invitiamo ad
  eliminarlo senza copiarlo e a non inoltrarlo a terzi, dandocene gentilmente
  comunicazione. Grazie.

  Pursuant to Legislative Decree No. 196/2003, you are hereby informed that
  this message contains confidential information intended only for the use of
  the addressee. If you are not the addressee, and have received this message
  by mistake, please delete it and immediately notify us. You may not copy or

**Comment by politza** [comment]
Enrico Pirani <notifications@github.com> writes:

>>> Error while processing tq callback: Invalid image specification [2
>>> times]

Try to execute the epdfinfo programm in the shell, I think your
installation might be broken.  My guess is different link and runtime
library versions.

**Comment by Enrico68** [comment]
politza <notifications@github.com> writes:

> Enrico Pirani <notifications@github.com> writes:
>
>>>> Error while processing tq callback: Invalid image specification [2
>>>> times]
>
> Try to execute the epdfinfo programm in the shell, I think your
> installation might be broken.  My guess is different link and runtime
> library versions.
>
Yes now it works. Problem was that epdfinfo was not in the PATH. Simlink
to /usr/bin fix it. Thanks.

**Comment by politza** [comment]
Usually the program resides in the package directory and is not installed.

**Comment by Enrico68** [comment]
My mistake..

**Comment by Jehops** [comment]
I've only been running pdf-tools on FreeBSD 10.1 for a day but so it's running fantastically.  Thanks!   However, despite putting `(add-hook 'after-init-hook (lambda () (pdf-tools-install)))` in my *init.el* I see this error if I try to search.  I've noticed if I open a pdf file, then evaluate `(pdf-tools-install)` then search again, I'll get the error once or twice, but then searching will work after that.

If I execute `echo quit | ./epdfinfo` from the server directory where I built pdf-tools I see the output
    OK
    .
Am I missing something?

**Comment by Enrico68** [comment]
Joseph Mingrone <notifications@github.com> writes:



> I've only been running pdf-tools on FreeBSD 10.1 for a day but so it's running fantastically.  Thanks!   However, despite putting `(add-hook 'after-init-hook (lambda () (pdf-tools-install)))` in my *init.el* I see this error if I try to search.  I've noticed if I open a pdf file, then evaluate `(pdf-tools-install)` then search again, I'll get the error once or twice, but then searching will work after that.
>
> If I execute `echo quit | ./epdfinfo` from the server directory where I built pdf-tools I see the output
>     OK
>     .
> Am I missing something?

You should symlink epdinfo to /usr/bin/ or whatever directory you have
in your $PATH, I had the same problem on MacOS but I think it shuld be
the same...

**Comment by Jehops** [comment]
Thanks Enrico68.  This made no difference.
P.S. I removed my post and opened a new issue (#80).
https://github.com/politza/pdf-tools/issues/80
