### ISSUE TITLE
Circular dependency between `pdf-view.el` and `pdf-cache.el`

### ISSUE THREAD

**Issue by narendraj9** [politza/pdf-tools#680]
I have this in my configuration to avoid getting a constant error that `pdf-view-current-page` is not defined: 
```emacs lisp
  ;; There is a circular dependency between `pdf-view.el' and
  ;; `pdf-cache.el'. `pdf-view' requires `pdf-cache' and `pdf-cache'
  ;; uses a macro (`pdf-view-current-page') defined in
  ;; `pdf-view'. This wouldn't have been a problem if it wasn't a
  ;; macro because then it could be defined later (i.e. after
  ;; byte-compilation) and the call would work just fine. Once
  ;; `pdf-cache' compiled, Emacs lisp tries to execute it as a
  ;; function. That's why I have defined it here as a function instead
  ;; of a macro:
  (defun pdf-view-current-page (&optional window)
    (image-mode-window-get 'page window))
```

**Comment by vedang** [comment]
@narendraj9 : IIRC this is solved at `vedang/pdf-tools` which is the maintained fork of this project :) Can you please use that version and then create a ticket against `vedang/pdf-tools` if needed?

**Comment by narendraj9** [comment]
Hey @vedang , thanks for maintaining the project :) I will try it out and share if the issue still occurs for me. I looked at the code and couldn't easily find the fix.

**Comment by vedang** [comment]
I've abstracted a bunch of macros out into a new file - `pdf-macs.el` - so
I'm expecting that this problem is solved with that change as well

/vedang

**Comment by narendraj9** [comment]
Makes sense. thanks :+1: The problem is fixed for me. I am going to close this issue. :)
