### ISSUE TITLE
How can one make a selection persist

### ISSUE THREAD

**Issue by revrari** [politza/pdf-tools#682]
If I select text in a pdf viewed with pdf-tools so as to to add a markup annotation, once I choose an option like "highlight" or "squiggly" the selection is immediately removed. To copy the same text I then need to re-select the text. It would be nice to be able to have the selection persist so as to enable multiple actions.

**Comment by tongjie-chen** [comment]
An ugly way is to override pdf-view-deactivate-region function.

(defun pdf-view-deactivate-region ()
>   "Deactivate the region."
>   (interactive)
>   t)
>

I made my own function to copy and then highlight,

(defun capture-notes-as-highlighting()
>   (interactive)
>   (kill-new (replace-regexp-in-string "-\n" "" (car
> (pdf-view-active-region-text))))
>   (pdf-annot-add-highlight-markup-annotation (pdf-view-active-region t)
> "yellow")
>   )
>

**Comment by revrari** [comment]
Your function is just awesome. Thanks.
