### ISSUE TITLE
AUCTeX and pdf-tools: split windows configuration

### ISSUE THREAD

**Issue by vp1981** [politza/pdf-tools#688]
Hello.

I'm using pdf-tools with AUCTeX and configured it to use pdf-tools to view PDF generated by LaTeX.

I stumbled upon with very strange behavior. I have two hosts running Emacs on full screen in AwesomeWM. One host in connected to a FullHD monitor, while another one is connected to a 4k monitor. When I work with a LaTeX document in Emacs and want to view PDF file on the FullHD host, the Emacs frame is split into left and right windows. But on the 4k host with the same configuration the frame is split into top and bottom windows. I find this strange because there are plenty space horizontally.

Does anyone know what is responsible for window splitting/configuration? Does Emacs itself choose this configuration? Could I "advise" it to split windows "horizontally" (to left and right ones)?

P.S. The 4k monitor in question could be rotated so that horizontal and vertical dimensions swap, but I don't think it is relevant here since `xrandr` returns correct h/v values.

**Comment by tongjie-chen** [comment]
After a long trace, the end result is the split is done by function `split-window-sensibly` which is the name of variable set by `split-window-preferred-function`.

In the description of this variable, you may find useful here, 

> You can customize the options `split-height-threshold` and/or `split-width-threshold` in order to have `split-window-sensibly` prefer either vertical or horizontal splitting.

The trace is `find-file-other-window`, `switch-to-buffer-other-window`, `pop-to-buffer`, `display-buffer`, `window--try-to-split-window`.

**Comment by vp1981** [comment]
Thank you tongjie-chen. I asked on AUCTeX ML and Joost Kremers gave some information how to configure `split-window-sensibly`. I tried settings on the host with 4k monitor and work fine, but I need to check them on the host with FullHD monitor (will do that tomorrow).
