### ISSUE TITLE
Gentoo dev-util/pkgconfig no longer in repos

### ISSUE THREAD

**Issue by RJSent** [politza/pdf-tools#693]
`dev-util/pkgconfig` was [removed](https://www.mail-archive.com/gentoo-dev@lists.gentoo.org/msg93072.html) from the Gentoo repos in August 2021. An alternative implementation `dev-util/pkgconf` is [available](https://wiki.gentoo.org/wiki/Pkg-config#Available_implementations). I was able to build everything without issue using `dev-util/pkgconf`.

I suggest replacing `dev-util/pkgconfig` in `server/autobuild:os_gentoo()` with `dev-util/pkgconf` so that the correct package is installed if a user is missing it.

**Comment by borgorworgor** [comment]
#695

**Comment by borgorworgor** [comment]
#695

**Comment by vedang** [comment]
Please note that the maintained fork of `pdf-tools` is now at https://github.com/vedang/pdf-tools. This issue has been fixed on that fork. Please close this issue and open any new issues on the maintained fork. Thanks!
