### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by pati-ni** [politza/pdf-tools#697]
Experimental pgtk support has been merged in recent emacs versions. 

Is it possible to make pdf-tools run natively in Wayland environments instead of XWayland without a complete overhaul?

**Comment by vedang** [comment]
No idea about this as I have not played around with Wayland at all.

Can you please close this issue and re-open it against `vedang/pdf-tools`? This repo is no longer maintained, and that is the official maintained repo right now.

**Comment by pati-ni** [comment]
Thank you
