### ISSUE TITLE
Error while building the epdfinfo program

### ISSUE THREAD

**Issue by algor512** [politza/pdf-tools#700]
After responding `yes` to `Need to (re)build the epdfinfo program, do it now ? (y or n) y`, I got the following error:
```
---------------------------
 Configuring and compiling
---------------------------
autoreconf -i
configure.ac:15: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:78: installing './config.guess'
configure.ac:78: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'
./configure -q --bindir=/home/algor/.emacs.d/elpa/pdf-tools-20220125.1708 && make clean && make -s
./configure: 4757: Syntax error: word unexpected (expecting ")")
===========================
     Build failed.  ;o(
===========================
Note: maybe try the '-d' option.
```
Removing `~/.emacs.d/elpa/pdf-tools-20220125.1708/` and restarting emacs as in #374 did not help.

I use Void Linux and GNU Emacs 27.2.

**Comment by algor512** [comment]
`sudo ln -s /usr/share/aclocal/pkg.m4 /usr/share/aclocal-1.16/` also don't help (I took this from #330).
Maybe this is a Void Linux issue mainly.

**Comment by vedang** [comment]
Are you using the latest `pdf-tools` from MELPA? If so, you are using my Repo (vedang/pdf-tools). Can you please try again, and if the problem persists please open an issue against vedang/pdf-tools? It makes it easier for me to track all the open issues (as I have no control over closing issues in this repo)
