### ISSUE TITLE
Printing with filename that contains a space

### ISSUE THREAD

**Issue by jsilve24** [politza/pdf-tools#704]
I ran into a problem using the function `pdf-misc-print-document` with a file that has a space in the name. 

If I try to shell escape quote the file name when I pass it to `pdf-misc-print-document` then the line ` (cl-check-type filename (and string (satisfies file-readable-p)))` throws an error. In contrast, if I don't escape quote the file name then the shell call has spaces in the file name and lpr doesnt print the document. 

I think the function  `pdf-misc-print-document`  needs to be modified to escape spaces in file names after the line ` (cl-check-type filename (and string (satisfies file-readable-p)))`. I am just not sure how to do that. 

Thanks, 
Justin

**Comment by vedang** [comment]
Thank you for the report! 

Just to set expectations here: This is a low-priority issue for me at the moment, and it will take me an indeterminate amount of time to get to it. I have some time free in July when I'm planning to go through non-critical open issues and fix them.

**Comment by vedang** [comment]
Also, can you please reproduce this on https://github.com/vedang/pdf-tools and open an issue there? That is the maintained fork of this project and it's easier for me to manage issues which are raised there.

**Comment by tongjie-chen** [comment]
I don't have this printing problem in my `20200512.1524` version of `pdf-tools`.

If you really want to escape the filename, you can try to modify the line with args to
```emacs-lisp
(args (append pdf-misc-print-programm-args (list (shell-quote-argument filename)))))
```

After I modify this part, "lp" does not print with escaped name, which becomes an issue.
