### ISSUE TITLE
pdf-tools-20220426.2203's epdfinfo doesn't build anymore on Arch Linux (requires c++17, not c++11)

### ISSUE THREAD

**Issue by tsdh** [politza/pdf-tools#706]
I've used `pdf-tools` for years but recently the build of the `epdfinfo` program started failing on all my up-to-date Arch installs.  The output is:

```
-*- mode: compilation; default-directory: "~/.emacs.d/elpa/pdf-tools-20220426.2203/build/server/" -*-
Comint started at Mon May  9 06:54:24

/home/horn/.emacs.d/elpa/pdf-tools-20220426.2203/build/server/autobuild -i /home/horn/.emacs.d/elpa/pdf-tools-20220426.2203/
---------------------------
    Installing packages    
---------------------------
Skipping package installation (already installed)

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/home/horn/.emacs.d/elpa/pdf-tools-20220426.2203/ && make clean && make -s
configure: error: cannot find necessary  poppler-private header (see README.org)
===========================
     Build failed.  ;o(    
===========================
Note: maybe try the '-d' option.

Comint exited abnormally with code 1 at Mon May  9 06:54:25
```
Running the `make -sd` in `~/.emacs.d/elpa/pdf-tools-20220426.2203/build/server` doesn't output more information.
Running `./configure` indicates that it cannot find `Annot.h` which actually exists in `/usr/include/poppler/Annot.h`.
The [config.log](https://github.com/politza/pdf-tools/files/8648901/config.log).  It contains many errors such as:

```
configure:6358: checking for Annot.h
configure:6358: g++ -c -std=c++11 -g -O2 -I/usr/include/poppler  conftest.cpp >&5
In file included from /usr/include/poppler/Object.h:43,
                 from /usr/include/poppler/AnnotStampImageHelper.h:15,
                 from /usr/include/poppler/Annot.h:59,
                 from conftest.cpp:49:
/usr/include/poppler/goo/GooString.h:249:33: error: 'std::string_view' has not been declared
  249 |     static bool startsWith(std::string_view str, std::string_view prefix) { return str.size() >= prefix.size() && 0 == str.compare(0, prefix.size(), prefix); }
      |                                 ^~~~~~~~~~~
```

The reason is that `std::string_view` seems to be something new in the C++17 standard but we're building with `-std=c++11`.  When I change it to `CXXFLAGS = -std=c++17 -g -O2` in `Makefile` (which is auto-generated, of course, so it's not the right fix), the build succeeds.

I have the following poppler package versions installed:
```
extra/poppler 22.05.0-1 [installed]
    PDF rendering library based on xpdf 3.0
extra/poppler-data 0.4.11-1 [installed]
    Encoding data for the poppler PDF rendering library
extra/poppler-glib 22.05.0-1 [installed]
    Poppler glib bindings
```

**Comment by tongjie-chen** [comment]
To temporality use pdf-tools, you can get the last version shared object files where your pdf-tools was built on, including `libpoppler-cpp.so`, `libpoppler-glib.so` and `libpoppler.so` to LD_LIBRARY_PATH and recover those files built last time by epdf-info, it will not ask you to install again. That's how I am still using libpoppler.so.94.

**Comment by HarHarLinks** [comment]
I downgraded `poppler-{,glib,qt5}22.05.0-1` to `poppler-{,glib,qt5}22.03.0-1` to work around this issue for now.

**Comment by tsdh** [comment]
I've used `sed` to replace every `c++11` with `c++17` in `~/.emacs.d/elpa/pdf-tools-20220426.2203/build/server` and then it compiles also with new poppler versions.

**Comment by vedang** [comment]
This problem should be fixed in the latest commit I've just pushed to `vedang/pdf-tools` (MELPA repo of `pdf-tools`). Please refetch from MELPA (I think it takes a day for MELPA to update packages so try tomorrow / day-after) and check.

**Comment by sr-hm** [comment]
Hello. Just dropping in to say refetching from MELPA now fixes the problem (3 hours after submission).

**Comment by tsdh** [comment]
@vedang Thanks a lot!
I'm closing this issue then.  (It seems your `Closes:` comment in https://github.com/vedang/pdf-tools/commit/4460a4fd3122e6b53cab1b7d86d6e19022d81fb1 didn't do it.)
