### ISSUE TITLE
Adding images to pdfs

### ISSUE THREAD

**Issue by vikasrawal** [politza/pdf-tools#707]
I was unable to find out if pdf-tools would allow me to add an image to a pdf at a point? It would be useful if one could do some basic operations on the image -- for example, to resize/crop it -- while sticking it in the pdf.

I need to do this often and wonder if it is a common enough use-case to make a feature request if it is not already supported. I currently need to go out of emacs to do this, and it would be very nice if I could do it from within emacs.

Thanks.

**Comment by tongjie-chen** [comment]
I guess what you want is something similar to this, https://www.foxit.com/blog/how-to-add-image-annotations-to-pdfs. This may need to depend on [Emacs Image Manipulation Package](https://www.emacswiki.org/emacs/EmacsImageManipulation).

**Comment by vikasrawal** [comment]
>
> I guess what you want is something similar to this,
> https://www.foxit.com/blog/how-to-add-image-annotations-to-pdfs.
>

But that is for Foxit. There are many applications that do something
similar (gimp, xournal). The question is how to do it on emacs.


> This may need to depend on Emacs Image Manipulation Package
> <https://www.emacswiki.org/emacs/EmacsImageManipulation>.
>
>
Thanks. I didn't know about eimp.
