### ISSUE TITLE
Cannot install on Manjaro poppler-private header 

### ISSUE THREAD

**Issue by Accacio** [politza/pdf-tools#708]
Running (pdf-tools-install) yields the following message

configure: error: cannot find necessary  poppler-private header (see README.org)

uname -a gives
Linux home 5.15.41-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022 x86_64 GNU/Linux

I've already installed poppler and poppler-glib

Is there a package that have such private headers?

**Comment by vedang** [comment]
Hi @Accacio : 

The `poppler-private` library is no longer needed for `pdf-tools` and the configure error you have printed above has also been removed from the codebase. Can you delete your `pdf-tools`, re-install from the latest Melpa and try again? 

A release is pending to ensure that these changes propagate to Melpa Stable and to NonGnu Elpa, I have planned to do this in the first week of July when I have some time.

**Comment by xenomorph1096** [comment]
Can confirm, removing the package and reinstalling works for me.

**Comment by Accacio** [comment]
@vedang, thank you. Using the updated version in vendang/pdf-tools worked for me.
