### ISSUE TITLE
Cannot build the server

### ISSUE THREAD

**Issue by ReichKV** [politza/pdf-tools#71]
When iam trying to build the server i get following error:

cd ~/.emacs.d/elpa/pdf-tools-20150401.751/build/server

make  all-am

gcc -DHAVE_CONFIG_H -I.    -Wall -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/poppler/glib -I/usr/include/poppler -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16  -I/usr/include/poppler  -I/usr/include/libpng16  -g -O2 -MT epdfinfo-epdfinfo.o -MD -MP -MF .deps/epdfinfo-epdfinfo.Tpo -c -o epdfinfo-epdfinfo.o `test -f 'epdfinfo.c' || echo './'`epdfinfo.c
In file included from epdfinfo.c:39:0:
epdfinfo.h:142:11: error: ‘cmd_getoptions’ undeclared here (not in a function)
   {#name, cmd_ ## name, cmd_ ## name ## _spec,  \
           ^
epdfinfo.c:3218:5: note: in expansion of macro ‘DEC_CMD’
     DEC_CMD (getoptions),
     ^
epdfinfo.h:142:25: error: ‘cmd_getoptions_spec’ undeclared here (not in a function)
   {#name, cmd_ ## name, cmd_ ## name ## _spec,  \
                         ^
epdfinfo.c:3218:5: note: in expansion of macro ‘DEC_CMD’
     DEC_CMD (getoptions),
     ^
epdfinfo.h:142:11: error: ‘cmd_setoptions’ undeclared here (not in a function)
   {#name, cmd_ ## name, cmd_ ## name ## _spec,  \
           ^
epdfinfo.c:3219:5: note: in expansion of macro ‘DEC_CMD’
     DEC_CMD (setoptions),
     ^
epdfinfo.h:142:25: error: ‘cmd_setoptions_spec’ undeclared here (not in a function)
   {#name, cmd_ ## name, cmd_ ## name ## _spec,  \
                         ^
epdfinfo.c:3219:5: note: in expansion of macro ‘DEC_CMD’
     DEC_CMD (setoptions),
     ^
Makefile:507: recipe for target 'epdfinfo-epdfinfo.o' failed
make: *** [epdfinfo-epdfinfo.o] Error 1

**Comment by politza** [comment]
https://github.com/politza/pdf-tools/issues/69
