### ISSUE TITLE
FR: Double clicking on a word to highlight it

### ISSUE THREAD

**Issue by haji-ali** [politza/pdf-tools#712]
Would it be possible to make it so that double-clicking on a word in the pdf document selects that word? This is the default in most modern pdf viewers (and is what double-clicking on a word does in an Emacs buffer by default).

Of course I would much rather have a way to navigate and selected text in a pdf using the keyboard, but I understand that's a difficult problem to solve.

**Comment by vedang** [comment]
Hi @haji-ali ,

This repo is no longer maintained. Can you please close this request and open it on `vedang/pdf-tools`? It will help me track the request better.

Thanks
