### ISSUE TITLE
Symbol's function definition is void: pdf-occur-global-minor-mode

### ISSUE THREAD

**Issue by ReichKV** [politza/pdf-tools#72]
When i start emacs with new version of pdf-tools i get following warning:

Warning (initialization): An error occurred while loading `/home/RCV/.emacs.d/init.el':

Symbol's function definition is void: pdf-occur-global-minor-mode

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by politza** [comment]
It's a autoloaded function defined in `pdf-occur.el`. Your installation is broken.

**Comment by politza** [comment]
If this a recurring issue, reopen it.

**Comment by ReichKV** [comment]
Hey, i again get this error  and cannot solve the problem. (Last time i just reinstall the package. ) In my init file i have (require 'pdf-tools). If i have in the init file the line (pdf-tools-install) i get:

Warning (initialization): An error occurred while loading `/home/ReichKV/.emacs.d/init.el':

Symbol's function definition is void: pdf-occur-global-minor-mode

Without the line i successfully load the emacs, execute  (pdf-tools-install) in the scratch buffer and pdf-tools works fine.


Please, could you help me to solve the problem.

**Comment by deb0ch** [comment]
I am currently having the same issue.

When using pdf-tools I can view pdf files just fine but searching words seems broken with isearch and occur (will only search the binary without highlighting anything).

When running `pdf-tools-install` I get `progn: Symbol's function definition is void: pdf-occur-global-minor-mode`.

I suspect that it might be related.

What is broken in my installation is the question.

I installed from source (branch master, commit 87690b7) on Ubuntu 16.04 using

```shell
make install-server-deps
make -s
```

added the pdf-tools-0.70 to my load-path and just executed `(require 'pdf-tools)` in my init file.

**Comment by politza** [comment]
You have to install the package as written in the readme.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Thomas de Beauchêne <notifications@github.com> </div><div>Datum:28.05.2016  13:20  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,State change <state_change@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Symbol's function definition is void:
  pdf-occur-global-minor-mode (#72) </div><div>
</div>I am currently having the same issue.

When using pdf-tools I can view pdf files just fine but searching words seems broken with isearch and occur (will only search the binary without highlighting anything).

When running pdf-tools-install I get progn: Symbol's function definition is void: pdf-occur-global-minor-mode.

I suspect that it might be related.

What is broken in my installation is the question.

I installed from source (branch master, commit 87690b7) on Ubuntu 16.04 using

make install-server-deps
make -s
added the pdf-tools-0.70 to my load-path and just executed (require 'pdf-tools) in my init file.

**Comment by whirm** [comment]
@ReichKV try requiring `pdf-occur` before calling `pdf-tools-install`
