### ISSUE TITLE
Select text?

### ISSUE THREAD

**Issue by yitang** [politza/pdf-tools#73]
Hi, 

I know we can search text in pdf-tools, and wonder how do we select the text? 

-Yi

**Comment by politza** [comment]
Yi Tang <notifications@github.com> writes:

> I know we can search text in pdf-tools, and wonder how do we select
> the text? 

Select text per Isearch or select text with mouse ?

**Comment by politza** [comment]
I don't know what this is about.

**Comment by yitang** [comment]
Hi politza, sorry for getting back to you late, I was lazy during the holiday. 

@manuel-uberti uses `pdf-tools` almost every day, and wonder how to integrate the `voca-builder` package to his workflow.  Basiclly `voca-builder` is a handy learning tool and can show the meaning of a word in English as a pop-up menu.  It needs to know the word at the cursor or point, but it `pdf-tools` render PDF pages as images. 

The [quick fix](https://github.com/yitang/voca-builder/commit/628fcbd481338d62987eadd1c11319f5ae010a07) for `voca-builder` is to add an interactive function that requires an argument, but it loses an important feature which is to record the sentence containing the word as an example for the vocabulary, and should be studied later on.

`pdf-tools` is more advanced Emacs package, and I presume a lot people use it for reading, and I think it would be nice to have `voca-builder` to work with it, and help user to increase their understanding of the text, especially for whom English is not their first language. 

But currently I am not capable to figure out, so I wonder if you could provide few suggestions on the integration between `voca-builder` and `pdf-tools`.  The user is happy about the current solution, so please don't be bothered to reply if you are busy.

-Yi

**Comment by politza** [comment]
Yi Tang <notifications@github.com> writes:

> Hi politza, sorry for getting back to you late, I was lazy during the
> holiday. 

No problem.

> [...] But currently I am not capable to figure out, so I wonder if you could
> provide few suggestions on the integration between voca-builder and
> pdf-tools. [...]

I still don't understand what it is exactly that you want to do...

You can extract text by letting the user select a region with the mouse
and do something like this:

    (prog1 (pdf-view-active-region-text)
      (pdf-view-deactivate-region))

Or use the backend functions directly, i.e. pdf-info-gettext or
pdf-info-charlayout.

-ap

**Comment by manuel-uberti** [comment]
Thanks for this one. If I can do any tests to help getting through with this, feel free to ask.

**Comment by politza** [comment]
I can't loose the feeling that I'm supposed to do something here. Wish I knew what it is.

**Comment by yitang** [comment]
@politza @manuel-uberti 
Hi both, I am struggle to finish other two projects at this moment and will come back as soon as I got time. 

-Yi

**Comment by politza** [comment]
If you got any questions I'm able to answer, feel free to reopen this or a new one or drop me a mail.
