### ISSUE TITLE
`follow-mode` implementation [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [politza/pdf-tools#74]
It will be useful have something like a `follow-mode` implemented for viewing pdf files too. When that mode is enabled, we can view consecutive PDF pages in different windows.

A good use case would be to open a PDF file in a frame, enable the "pdf follow mode" and split the frame into two side-by-side windows. The user can then have two consecutive pages accessible at the same time.

In that case, though, it would also be useful to have an option to have the next and previous page commands to jump pages by 2. 

This feature requested originated from [this][1] emacs.stackexchange question.

[1]: http://emacs.stackexchange.com/q/5518/115

**Comment by politza** [comment]
https://gist.github.com/politza/a3339a4f3b3901fcce4c

I removed this some time ago, since it has some problems.  I am not going to pursue this at the moment, but maybe someone else wants to pick it up...

**Comment by Lindydancer** [comment]
One approach could be to extend `follow-mode` with a variable, say `follow-mode-align-window-function` that could be assigned by major modes like `doc-view`. When unbound, `follow-mode` could do it's normal "set window start" routine, when bound, the major mode could do whatever it wants.

Spontaneously, I think the function would be called with three arguments, the window to align, the window to align to, and a flag saying if the window should be aligned before or after the other function.

Maybe we would need some kind of function to tell whether the windows are aligned to start with (mainly for performance reasons).

    -- Anders Lindgren

Ps. I'm the author of follow-mode.

**Comment by politza** [comment]
How about multiple pages in one window.  Would that leave for anything to be desired regarding this topic ?

**Comment by kaushalmodi** [comment]
If you have 2 pages side by side in the same window, how will text selection using mouse work? What if I try to select a paragraph of text on page 1? If page 2 is on the side, will the text selection include corresponding lines from page 2 too?

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> If you have 2 pages side by side in the same window, how will text
> selection using mouse work?

Why is that important ? It'll be either limited to one page or act as if
both pages where a single one, I guess.

**Comment by kaushalmodi** [comment]
If two pages are displayed side by side in the same window, I am wondering if the text selection will respect the page boundaries.

Assume you have these two pdf pages side-by-side in a window:

```
| pg 1               | pg 2               |                                      
| abc                | ghi                |
| def                | jkl                |
```

Would I be able to select just the "abc def" text without "ghi" being part of the selection. 

As I am ignorant how the pdf page display rending works in an emacs window, I am wondering how emacs will respect that page boundary between pg 1 and pg 2 in the same window.

**Comment by politza** [comment]
Kaushal Modi <notifications@github.com> writes:

> As I am ignorant how the pdf page display rending works in an emacs
> window, I am wondering how emacs will respect that page boundary
> between pg 1 and pg 2 in the same window.

I'm a little bit baffled that you seem to think that the selection uses
regular Emacs commands.  To answer your question: It depends how it'll
be implemented.

**Comment by kaushalmodi** [comment]
Ignorance point proven..

**Comment by andersjohansson** [comment]
I just discovered pdf-tools and got totally blown away! Having some kind of double-page view would eliminate my need for any other pdf-viewer/editor (few linux-viewers are good at annotations, pdf-tools seems to be one of the best).
(BTW: @Lindydancer, cheers from Uppsala)

**Comment by andersjohansson** [comment]
What would be required to implement this? It is currently the one major feature that I miss in pdf-tools.
What more than the "display" functions (pdf-view.el:718-950) would need to be changed? I guess one way would be to add a minor-mode and checks in some of these functions to render and display two pages at the same time when active.
Then also some check to always (or configurable by local variable) display odd pages to the left and even to the right (for example when jumping to an even page, displaying that page + the previous page to the left, and not that page + next page to the right).

But I figure this doesn't account for all mechanisms. Selection and annotation would need to work on the correct image (do those functions assume only one image per window now?).
Would changes be needed in the server as well?

How complex a change would it be?

I suppose you don't want amateurs making half-baked solutions for this, @politza (and I know that pdf-tools is probably not your only priority in life), but I'm willing to try out some things (if elisp is what's needed, that is) if I could get a pointer to what a good (and general, where perhaps other display modes like 2×2 could be defined) solution would be.

**Comment by politza** [comment]
I think the best solution to this problem would be to display multiple pages per window, i.e. #27 .

**Comment by clubfed** [comment]
+1

If I understand correctly, this is a request to have two different windows, or buffers, view two different pages of a pdf. If I do for example `C-x 4 c` to clone the buffer, chaos ensues, and I have to close Emacs to regain sanity.
