### ISSUE TITLE
[CYGWIN] edpfinfo error: The pathname is not an absolute path.

### ISSUE THREAD

**Issue by stevem995** [politza/pdf-tools#75]
On windows 7 64bit using Emacs for windows and Cygwin64 as shell:

I used make to create the Emacs package under Cygwin64. It created
the jar fine. I then copied the package to my package tree.

However, when using the mode in Emacs it throws the
error shown below.

If I try to correct the string using backslash(in the event Emacs is
using the windows shell), I get hung up on replace string's
string-match which finds an RTL character in arch.

Externally, when I run epdfinfo on the command line(cygwin), given
that path, it just sits with no error. Moreover, running the command
on the command line(cmd) using a backslash produces the same.

Debugger entered--Lisp error: (error "epdfinfo: Error opening
c:/Users/Username/Downloads/doc.pdf:The pathname
'c:/Users/Username/Downloads/doc.pdf' is not an
absolute path")

Note: path in example is modified, but structure is the same.

**Comment by politza** [comment]
stevem995 <notifications@github.com> writes:

> Debugger entered--Lisp error: (error "epdfinfo: Error opening
> c:/Users/Username/Downloads/doc.pdf:The pathname
> 'c:/Users/Username/Downloads/doc.pdf' is not an
> absolute path")

g_filename_to_uri from glib throws this error.  Not much I can do about
it.

**Comment by politza** [comment]
I'm closing this because I think it's a problem with glib and/or Emacs's integration with Cygwin.
