### ISSUE TITLE
Feature request: Docview does .docx! Why not pdf-tools?

### ISSUE THREAD

**Issue by WorldsEndless** [politza/pdf-tools#76]
Imagine my surprise today when I accidentally told Emacs to open a .docx and, instead of giving me the archive listing as it (still) does with .odt, it converted the docx to a PDF and viewed it (in docview mode)! I'm not sure how long this has been possible, but as always I would rather use pdf-tools than doc-view. 

GNU Emacs 25.0.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.9) of 2015-03-23 on localhost.localdomain

**Comment by politza** [comment]
I guess that's feasible.

**Comment by tsdh** [comment]
@WorldsEndless doc-view can and will do the same with OpenDocument files if the `soffice` program is installed on the system.  That's part of LibreOffice and OpenOffice.org.

@politza I think you could simply reuse (i.e., call) the doc-view conversion functions for all kinds of documents which are no PDFs already but still can be displayed by doc-view after converting them to PDF.
