### ISSUE TITLE
Imenu index builder function

### ISSUE THREAD

**Issue by Kurvivor19** [politza/pdf-tools#78]
Pdf-tools interferes with imenu index builder function for python. In particular, after pdf-tools-install is run or (depending on configuration) a pdf document is opened, index builder function in python-mode is changed to one that fails to find any items suitable for index.

**Comment by politza** [comment]
Kurvivor19 <notifications@github.com> writes:

> Pdf-tools interferes with imenu index builder function for python.

I require semantic's parser which ends up putting a function on
python-mode-hook and maybe others.

**Comment by politza** [comment]
Should be fixed by this 8b2d27db210083246e4e619a393656f97c9c1682 .  

Please reopen if it didn't.

**Comment by Kurvivor19** [comment]
Thanks!
