### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by cazgp** [politza/pdf-tools#82]
Ubuntu 14.04, emacs24-lucid, libpoppler 0.24.5-2ubuntu4.2.

Tried installing this through `el-get` to begin with, but that stalls on `make install-sever-deps` with sudo issues. The command manually works fine. This same issue happens on tag v0.4, v0.5 and v0.6.

`make -s`:

Running autoreconf...
configure.ac:15: installing './ar-lib'
configure.ac:11: installing './compile'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './depcomp'

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? no (requires poppler-glib >= 0.26)

config.status: creating config.h
config.status: config.h is unchanged
epdfinfo.c: In function ‘annotation_print’:
epdfinfo.c:1452:10: warning: label ‘error’ defined but not used [-Wunused-label]
  theend: error:
          ^
epdfinfo-epdfinfo.o: In function `mktempfile':
/home/caz/.emacs.d/el-get/pdf-tools/server/epdfinfo.c:271: warning: the use of `tempnam' is dangerous, better use `mkstemp'

`make install-package`:

mkdir -p 'pdf-tools-0.60'
cp lisp/*.el README server/epdfinfo 'pdf-tools-0.60'
echo '(define-package "pdf-tools" "0.60" "Support library for PDF documents." (quote ((emacs "24.3"))) :keywords (quote ("files" "multimedia")))' > 'pdf-tools-0.60/pdf-tools-pkg.el'
tar cf 'pdf-tools-0.60.tar' 'pdf-tools-0.60'
emacs24-lucid -Q -L /home/caz/.emacs.d/el-get/pdf-tools/lisp --batch --eval \
                "(progn (package-initialize) \
                        (package-install-file \
                                \"pdf-tools-0.60.tar\"))"
Wrong type argument: stringp, nil
make: *** [install-package] Error 255

**Comment by politza** [comment]
Emacs version ?

Try to enable the debugger and install with `M-x package-install-file`.

**Comment by cazgp** [comment]
^emacs24-lucid

Is there anything else to do other than `emacs -Q` and `M-x package-install-file` which produces: `package-read-from-string: End of file during parsing`?

**Comment by politza** [comment]
cazgp <notifications@github.com> writes:

> ^emacs24-lucid

M-x emacs-version RET

**Comment by cazgp** [comment]
24.3.1

**Comment by politza** [comment]
> cp lisp/.el README server/epdfinfo 'pdf-tools-0.60'

There should be a * in `lisp/.el`. Verify that the directory pdf-tools-0.60 contains a bunch of lisp files.

> Is there anything else to do other than emacs -Q and M-x package-install-file which produces: package-read-from-string: End of file during parsing?

Open the tar file in Emacs and verify that it is indeed a tar archive.

Do the same as above, but enable the debugger beforehand and publish the back-trace.

**Comment by cazgp** [comment]
`ls pdf-tools`: epdfinfo*     pdf-cache.el  pdf-history.el 
pdf-isearch.el  pdf-misc.el   pdf-outline.el  pdf-tools.el pdf-util.el  
README      tablist-filter.el
pdf-annot.el  pdf-dev.el    pdf-info.el     pdf-links.el pdf-occur.el  
pdf-sync.el     pdf-tools-pkg.el  pdf-view.el tablist.el

`ls lisp`: pdf-annot.el  pdf-cache.el  pdf-dev.el  pdf-history.el 
pdf-info.el  pdf-isearch.el  pdf-links.el  pdf-misc.el pdf-occur.el  
pdf-outline.el  pdf-sync.el  pdf-tools.el pdf-util.el  pdf-view.el  
tablist.el  tablist-filter.el

Didn't open the tar in Emacs, but it's definitely a valid tar archive - 
untarring produced those files above.

Are there instructions you can point me to on how to enable the Emacs 
debugger? I'm quite new to Emacs and all I could find was the -Q flag.

**Comment by politza** [comment]
`M-x toggle-debug-on-error RET`

**Comment by cazgp** [comment]
Nothing happens when I do that... Messages shows:

     Debug on Error enabled globally
     package-read-from-string: End of file during parsing.

**Comment by cazgp** [comment]
Downloaded and built emacs-24.5 from source.

MELPA couldn't find a file, so that install-method failed.
el-get had issues with sudo / askpass, so that failed.

Manual install has worked.

Thank you, this is a very useful package :)
