### ISSUE TITLE
opening a large file (text book) takes forever to load

### ISSUE THREAD

**Issue by ThomasDuPlessis** [politza/pdf-tools#83]
I tested on a single page pdf and it opened up immediately. However I wanted to use this for reading my textbooks and it seems to jsut start eating up the CPU and take forever to load. In fact, I havent been able to eopn a large pdf like a textbook because after about a minute or two I just quit emacs.

**Comment by politza** [comment]
Thomas DuPlessis <notifications@github.com> writes:

> [...]  However I wanted to use this for reading my textbooks and it
> seems to jsut start eating up the CPU and take forever to load. [...]

I have no problem with this. Opening any kind of PDF document displays
it's page almost immediately.

**Comment by ThomasDuPlessis** [comment]
yea. I had the same problems using Docview when opening the same file. is there no possible error that could be causing this? Or perhaps if my compilation didn't work properly this could have resulted?

**Comment by politza** [comment]
Is this problem restricted to a single file, or any file of larger size ?

**Comment by ThomasDuPlessis** [comment]
So far, it seems anything over about 15 MB takes a long time.

**Comment by politza** [comment]
Thomas DuPlessis <notifications@github.com> writes:

> So far, it seems anything over about 15 MB takes a long time. 

The largest book I have is 85 MB, loading time is about a second.

Are you sure you're using pdf-view-mode and not doc-view-mode ?

**Comment by ThomasDuPlessis** [comment]
The modes changed since downloading pdf tools, and i have the (pdf-tools-install) in my .emacs. Is PDFView mode the correct mode it should be in?

**Comment by ThomasDuPlessis** [comment]
Here is a screen shot of all my active modes
![screenshot from 2015-04-28 12 44 00](https://cloud.githubusercontent.com/assets/5506107/7375096/55161782-eda4-11e4-9ed6-141392823ebf.png)

**Comment by politza** [comment]
Thomas DuPlessis <notifications@github.com> writes:

> Is PDFView mode the correct mode it should be in?

Yes.  My guess is, that it is some minor mode having trouble with large
files, e.g. global-linum-mode .

**Comment by ThomasDuPlessis** [comment]
In the profiler, it says helm is using up the most CPU usage and memory. Have you seen this before?

**Comment by politza** [comment]
Thomas DuPlessis <notifications@github.com> writes:

> In the profiler, it says helm is using up the most CPU usage and
> memory. Have you seen this before?

No, I don't use helm.

**Comment by ThomasDuPlessis** [comment]
Well getting rid of helm didn't help. I guess ill just have to limit emacs to just small pdfs.

**Comment by politza** [comment]
Thomas DuPlessis <notifications@github.com> writes:

> Well getting rid of helm didn't help. I guess ill just have to limit
> emacs to just small pdfs. 

You do that.

**Comment by ThomasDuPlessis** [comment]
I found the solution! I used fci-mode to highlight the 80th column. however disabling this make pdf tools run lightening fast.

**Comment by RobinTournemenne** [comment]
I know it is an old closed issue but I wanted to know if @ThomasDuPlessis  found an automatic way to disable fci-mode only for the pdf-view major mode?
Besides I would suggest to add in the readme of the repo that tabbar and fci minor modes add circa 4 seconds delay to any movement of the pdf or access to the minibuffer.

**Comment by ThomasDuPlessis** [comment]
If I remember correctly, I only enabled it for prog-mode.

**Comment by pierrebonbon** [comment]
@RobinTournemenne Maybe adding a hook to your `init.el` will do the trick, along these lines:

`(add-hook 'pdf-view-mode-hook (lambda() ( fci-mode -1)))`
