### ISSUE TITLE
 I-search and pdf-occur work with light but not with dark themes (similar to #68 #80)

### ISSUE THREAD

**Issue by ardpp** [politza/pdf-tools#84]
I'm running pdf-tools (the newest version from elpa) in Emacs 24.5.1 on Arch Linux. 

When I use a light theme (tested with tsdh-light, dichromacy or solarized-light) and invoke I-search or pdf-occur everything works as expected. With a dark theme (tested with tsdh-dark, solarized-dark, zenburn) I get the same error as #68 and #80 

`Error while processing tq callback: Invalid image specification`

If I immideately load a light theme then the error disappears again. Am I doing somthing wrong? 

Thanks, 
Andrej

**Comment by politza** [comment]
Please discuss [here] (https://github.com/politza/pdf-tools/issues/80).
