### ISSUE TITLE
Highlighting / Annotations

### ISSUE THREAD

**Issue by cazgp** [politza/pdf-tools#86]
Is highlighting a feature that's fully implemented? M-x pdf-add-underline-markup-annotation, for example, gives "The region is not active". Selecting text with the mouse doesn't seem to have any effect on this result - messages simply prints "Mark set". Is this a case of user error?

Thank you for such a great package - this + org-mode was definitely worth the switch to emacs!

**Comment by politza** [comment]
cazgp <notifications@github.com> writes:

> [...] Is this a case of user error?

Yes, you first select a region and then invoke the command.

**Comment by cazgp** [comment]
How do you select a region? It doesn't work with the mouse. I've tried every command in the list but always see "Mark set" in the mini-buffer followed by "The region is not active".

**Comment by politza** [comment]
cazgp <notifications@github.com> writes:

> How do you select a region?

You click somewhere, drag the mouse and the selected text becomes
highlighted.

**Comment by cazgp** [comment]
But I've said that doesn't work...

**Comment by politza** [comment]
Well, that's how it should work.

**Comment by cazgp** [comment]
OK... is there some way of debugging what's going on?

**Comment by politza** [comment]
For starters, check if `down-mouse-1` is bound to `pdf-view-mouse-set-region`.  Else start with `emacs -Q` and start from there.

**Comment by cazgp** [comment]
Cool, that got it. I'm using evil so it needs `evil-emacs-state` in the 
`pdf-view-mode-hook`. Thank you.
