### ISSUE TITLE
Misplaced highlighting in some PDFs

### ISSUE THREAD

**Issue by pablocouto** [politza/pdf-tools#87]
I have come across an issue with highlighting in some PDFs (such as http://journal.frontiersin.org/article/10.3389/fpsyg.2012.00096/pdf); namely, when I select and highlight a fragment of text, the highlight appears one line lower than it should. The annotation itself appears to be located in the right place, though, as can be seen in the capture below. (The properly highlighted text was marked with a different software.)

![screenshot from 2015-05-14 17-52-33](https://cloud.githubusercontent.com/assets/526124/7635597/35ebd462-fa62-11e4-87e7-7edbb0516323.png)

**Comment by politza** [comment]
It's most likely a bug in poppler.  It renders the same in my version of
evince.  Maybe you want to open a bug report with an annotated PDF
attached, here: http://bugs.freedesktop.org/ .

**Comment by pablocouto** [comment]
I’ll file a report there. Thanks.
