### ISSUE TITLE
Allow for rotation of displayed pages

### ISSUE THREAD

**Issue by tmalsburg** [politza/pdf-tools#89]
First of all, thank you for pdf-tools!

If a table or figure is too large it is common to present it in landscape format but I don't see how I can rotate the page.  Is there a way or is that feature missing?  In the latter case, I think it would be great to add rotation as a new feature.

**Comment by politza** [comment]
Sounds like a worthy addition, also easy to implement.

**Comment by politza** [comment]
Not so easy, as it turns out.

**Comment by LukeSwart** [comment]
This would be an awesome feature! :+1:

**Comment by chiraag-nataraj** [comment]
I've had the same problem. Until we can rotate within pdf-tools, I use `pdftk` to rotate the PDF and save it to another file.

**Comment by jabranham** [comment]
@politza Has there been any progress on this in the last twoish years? This seems like a very useful feature.

**Comment by schoettl** [comment]
Especially when reading paper scans where only some pages are in landscape format, it would be great to be able rotate single pages – only for displaying purpose!

I read at some places that pdf-tools renders pages as images (PNG). So it should be easy to rotate single pages (on Linux) with e.g. [imagemagick's](https://imagemagick.org/) `convert` command (`convert $file -rotate 90 rotated-$file`).

- The function could bind to `C-c C-r` or `C-c C-r x` where x is [n]orth, [s]outh, ..., [r]ight (clockwise), [l]eft (counter-clockwise). And the number of degrees as optional prefix argument :)

- [pdf-view-restore](https://github.com/007kevin/pdf-view-restore) which jumps to the last open page when opening a PDF file could maybe also restore the page orientation.
