### ISSUE TITLE
Is it possible to send PDF from Emacs to the server for rendering?

### ISSUE THREAD

**Issue by tmalsburg** [politza/pdf-tools#90]
If yes, ESS (R develepment environment in Emacs) could use pdf-tools to display dynamically generated plots without generating temporary files.

P.s: Sorry to abuse the issue tracker for this question.

**Comment by politza** [comment]
Titus von der Malsburg <notifications@github.com> writes:

> If yes, ESS (R develepment environment in Emacs) could use pdf-tools
> to display dynamically generated plots without generating temporary
> files. 

Like sending the PDF's data inline ? No.

**Comment by tmalsburg** [comment]
Yes, that's the idea.  The PDF would be generated by R but ideally never hit the disk.  Thanks for the response.

**Comment by politza** [comment]
If I remember correctly, the transfer via files was faster than sending it inline; so I did that.

**Comment by stardiviner** [comment]
@politza So it's not possible to render pdf inline with pdf-tools in Emacs ? Like Org-mode show an inline image.
