### ISSUE TITLE
Can't kill buffer when the filesystem is gone.

### ISSUE THREAD

**Issue by vanicat** [politza/pdf-tools#91]
I had open a pdf file on a usb stick. When I wanted to remove it, I just killed the pdfinfo server be able to dismount it. now, I cannot kill this buffer because the epfinfo server is dead, but it cannot restart it because the directory is not there. At least killing the buffer should work when the buffer is dead.

Thanks.

**Comment by politza** [comment]
Since the working directory is not used, it's probablly best to always use a safe directory, like root.

**Comment by politza** [comment]
This should be fixed now.
