### ISSUE TITLE
error when run pdf-annot-add-text-annotation

### ISSUE THREAD

**Issue by zhengjiezxxy** [politza/pdf-tools#92]
It err like: 
  Error running timer 'pdf-annot--prefetch-start' : (invalid-function pdf-view-current-page)

OS: Ubuntu 14.04
Emacs: emacs head
pdf file: engineering long last software

**Comment by politza** [comment]
zhengjiezxxy <notifications@github.com> writes:

> It err like: 
> Error running timer 'pdf-annot--prefetch-start' : (invalid-function
> pdf-view-current-page)

Looks like your installation is broken.  Please try this:

1. Uninstall pdf-tools,
2. Restart Emacs and
3. reinstall pdf-tools.

**Comment by zhengjiezxxy** [comment]
I reinstall pdf-tools, and it works, thanks!
