### ISSUE TITLE
Trigger automatic server compilation after upgrade from MELPA

### ISSUE THREAD

**Issue by manuel-uberti** [politza/pdf-tools#93]
Basically, would it be possible to trigger the server compilation right after an upgrade from MELPA?
Right now I have to restart Emacs every time.

I am using latest pdf-tools and Emacs 25.0.50.1 (```45c92dd```).

**Comment by kozross** [comment]
You can just ``eval-buffer`` your init file to get the compilation going. Restarting Emacs is almost *never* necessary.

**Comment by manuel-uberti** [comment]
Sure thing, but can't it be done automatically right after the upgrade?

**Comment by politza** [comment]
Manuel Uberti <notifications@github.com> writes:

> Sure thing, but can't it be done automatically right after the
> upgrade?

Actually, it should do that already.

**Comment by manuel-uberti** [comment]
I see, well it is not doing it at the moment on my setup.
This is the snippet about pdf-tools in my configuration:
```
(use-package pdf-tools ; Better PDF support
  :bind ("C-c M-g" . pdf-view-goto-page)
  :init (pdf-tools-install))
```
If you need me to do some tests, feel free to ask.

**Comment by politza** [comment]
Manuel Uberti <notifications@github.com> writes:

> I see, well it is not doing it at the moment on my setup.
> This is the snippet about pdf-tools in my configuration:
>
> (use-package pdf-tools ; Better PDF support
>   :bind ("C-c M-g" . pdf-view-goto-page)
>   :init (pdf-tools-install))
>

Does use-package check for updates and install them ?

**Comment by manuel-uberti** [comment]
No, that only ensures pdf-tools-install is run when I start Emacs. I update all my packages with [Paradox](https://github.com/Bruce-Connor/paradox), actually.
