### ISSUE TITLE
epdfinfo.log blocks other users

### ISSUE THREAD

**Issue by dxknight** [politza/pdf-tools#96]
Viewing a pdf puts a temporary file epdfinfo.log in /tmp.  This file is rw the current user, but only readable by group/all.  Exiting emacs does not delete this file.

Trying to use pdf-tools as another user fails with "Error running `/home/\<otheruser\>/.emacs.d/std/packages/elpa/pdf-tools-20150603.227/epdfinfo': "

Running echo -e "quit\n" | ./epdfinfo provides no output unless the current user has write rights to the temp file.

Deleting /tmp/epdfinfo.log cures the problem, until another user tries to view a pdf.

Suggestion: have a user specific log file epdfinfo-\<user\>.log in /tmp?

PS: pdf-tools is awesome, and makes reading pdfs in emacs a practical and preferable choice.  Thanks!

**Comment by politza** [comment]
dxknight <notifications@github.com> writes:

> Viewing a pdf puts a temporary file epdfinfo.log in /tmp.

Yes, that's basically a development residual, which should be changed to
use an argument as the log file.

**Comment by politza** [comment]
I simply dropped writing a log by default.  Usually it's of no interest, unless debugging.

**Comment by dxknight** [comment]
Thanks.
