### ISSUE TITLE
Changing styling of underline annotations

### ISSUE THREAD

**Issue by plantarum** [politza/pdf-tools#97]
Thank you for pdf-tools, this is a fantastic package!

Is it possible to style the underline annotation separately from the highlight annotation? I find the default yellow colour is hard to see as an underline, but fine for highlighting. Changing it to green in via pdf-annot-default-markup-annot-properties is a workable fix, but it would be nice to be able to increase the width of the underline, and set it to a different colour than the highlight.

This is a wishlist item, not a serious problem. 

Best,

Tyler

**Comment by politza** [comment]
Tyler <notifications@github.com> writes:

> Thank you for pdf-tools, this is a fantastic package!
>
> Is it possible to style the underline annotation separately from the
> highlight annotation? 

For the moment you could advice
pdf-annot-add-highlight-markup-annotation's arguments or interactive
spec and add a color property.

> [...] but it would be nice to be able to increase the width of the
> underline, [...]

As far as I can see, this is not possible with poppler-glib at the
moment.

**Comment by plantarum** [comment]
Ok, thanks!

**Comment by brabalan** [comment]
It would be great to also have an option to change the default color for strike-out annotations. How about a defcustom for the color of each markup annotation type?

**Comment by politza** [comment]
113
