### ISSUE TITLE
Feature request: trim margins or zoom to text width

### ISSUE THREAD

**Issue by plantarum** [politza/pdf-tools#99]
When reading pdfs with broad margins, it would be useful to be able to trim the margins, or zoom to the text width, rather than the page width. Is it possible to add this feature?

Thanks again,

Tyler

**Comment by ardpp** [comment]
Maybe `pdf-view-set-slice-from-bounding-box` is something you want.

**Comment by plantarum** [comment]
Perfect, that's exactly it. Thanks!
